import { Player } from '../../types';

export const AFC_EAST_PLAYERS: Player[] = [
  // ===================== BUFFALO BILLS (BUF) =====================
  {
    id: 'qb-allen',
    name: 'Josh Allen',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'QB',
    ovr: 95,
    salary: 43,
    starter: true,
    archetype: 'Gunslinger / Power Rusher',
    attributes: { passing: 95, rushing: 92, passBlocking: 0, runBlocking: 0, athleticism: 91, footballIQ: 91 },
    highlightStat: '99 Throw Power & Red Zone Trucking',
  },
  {
    id: 'qb-trubisky',
    name: 'Mitchell Trubisky',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'QB',
    ovr: 72,
    salary: 3,
    starter: false,
    archetype: 'Athletic Scrambler Backup',
    attributes: { passing: 74, rushing: 78, passBlocking: 0, runBlocking: 0, athleticism: 82, footballIQ: 73 },
    highlightStat: '82 Mobility & Zone-Read Option Execution',
  },
  {
    id: 'rb-cook',
    name: 'James Cook',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'RB',
    ovr: 85,
    salary: 2,
    archetype: 'One-Cut Speed Back',
    attributes: { passing: 0, rushing: 88, receiving: 84, passBlocking: 70, runBlocking: 0, athleticism: 91, footballIQ: 83 },
    highlightStat: '91 Outside Zone Burst & Angle Breaking',
  },
  {
    id: 'wr-shakir',
    name: 'Khalil Shakir',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'WR',
    ovr: 83,
    salary: 1,
    archetype: 'YAC Monster Slot',
    attributes: { passing: 0, rushing: 0, receiving: 85, passBlocking: 0, runBlocking: 65, athleticism: 89, footballIQ: 86 },
    highlightStat: '93 Catch Percentage & Slippery Tackle Shedding',
  },
  {
    id: 'wr-coleman-keon',
    name: 'Keon Coleman',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'WR',
    ovr: 78,
    salary: 2,
    archetype: 'Physical Red-Zone Boundary',
    attributes: { passing: 0, rushing: 0, receiving: 80, passBlocking: 0, runBlocking: 72, athleticism: 85, footballIQ: 78 },
    highlightStat: '92 High-Point Contested Jump Balls',
  },
  {
    id: 'wr-cooper-amari',
    name: 'Amari Cooper',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'WR',
    ovr: 85,
    salary: 20,
    archetype: 'Master Route Technician',
    attributes: { passing: 0, rushing: 0, receiving: 89, passBlocking: 0, runBlocking: 62, athleticism: 87, footballIQ: 93 },
    highlightStat: '95 Razor Route Breaks & Sideline Separation',
  },
  {
    id: 'te-kincaid',
    name: 'Dalton Kincaid',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'TE',
    ovr: 84,
    salary: 3,
    archetype: 'Middle Field Receiving TE',
    attributes: { passing: 0, rushing: 0, receiving: 87, passBlocking: 66, runBlocking: 72, athleticism: 85, footballIQ: 84 },
    highlightStat: '90 Soft Hands & Separation on Dig Routes',
  },
  {
    id: 'te-knox',
    name: 'Dawson Knox',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'TE',
    ovr: 81,
    salary: 13,
    archetype: 'Dual-Threat In-Line TE',
    attributes: { passing: 0, rushing: 0, receiving: 80, passBlocking: 75, runBlocking: 82, athleticism: 82, footballIQ: 82 },
    highlightStat: '85 In-Line Y-Seam & Goal-Line Blocking',
  },
  {
    id: 'ot-dawkins',
    name: 'Dion Dawkins',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'OT',
    ovr: 88,
    salary: 20,
    archetype: 'Blindside Enforcer',
    attributes: { passing: 0, rushing: 0, passBlocking: 90, runBlocking: 87, athleticism: 80, footballIQ: 89 },
    highlightStat: '91 Snatch-and-Trap vs Speed Rush',
  },
  {
    id: 'ot-brown-spencer',
    name: 'Spencer Brown',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'OT',
    ovr: 80,
    salary: 18,
    archetype: 'Power Edge Protector',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 84, athleticism: 84, footballIQ: 79 },
    highlightStat: '86 Downfield Screen Blocking Range',
  },
  {
    id: 'og-torrence',
    name: 'O\'Cyrus Torrence',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'OG',
    ovr: 80,
    salary: 1,
    archetype: 'Gap Power Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 86, athleticism: 75, footballIQ: 81 },
    highlightStat: '88 Anchor Strength vs Bull Rush',
  },
  {
    id: 'c-mcgovern-connor',
    name: 'Connor McGovern',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'C',
    ovr: 79,
    salary: 7,
    archetype: 'Agile Zone Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 80, athleticism: 79, footballIQ: 84 },
    highlightStat: '82 Pre-Snap Blitz Call Protection',
  },
  {
    id: 'edge-rousseau',
    name: 'Greg Rousseau',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'EDGE',
    ovr: 86,
    salary: 3,
    archetype: 'Long-Limbed Edge Setter',
    attributes: { passRush: 86, runDefense: 89, coverage: 60, athleticism: 84, footballIQ: 86 },
    highlightStat: '91 Run Contain & Arm Extension Length',
  },
  {
    id: 'edge-miller-von',
    name: 'Von Miller',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'EDGE',
    ovr: 83,
    salary: 20,
    archetype: 'Hall of Fame Speed Rusher',
    attributes: { passRush: 86, runDefense: 78, coverage: 65, athleticism: 82, footballIQ: 94 },
    highlightStat: '92 Ankle-Flex Dip on 3rd Down',
  },
  {
    id: 'dt-oliver',
    name: 'Ed Oliver',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'DT',
    ovr: 86,
    salary: 17,
    archetype: '3-Tech Penetrator',
    attributes: { passRush: 88, runDefense: 83, coverage: 50, athleticism: 87, footballIQ: 84 },
    highlightStat: '92 Quick-Twitch First Step in Gap',
  },
  {
    id: 'lb-milano',
    name: 'Matt Milano',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'LB',
    ovr: 88,
    salary: 14,
    archetype: 'Elite Coverage Specialist',
    attributes: { passRush: 76, runDefense: 86, coverage: 92, athleticism: 85, footballIQ: 93 },
    highlightStat: '94 RB/TE Matchup Lockdown in Space',
  },
  {
    id: 'lb-bernard',
    name: 'Terrel Bernard',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'LB',
    ovr: 82,
    salary: 1,
    archetype: 'Flow & Tackle Inside LB',
    attributes: { passRush: 78, runDefense: 82, coverage: 83, athleticism: 84, footballIQ: 85 },
    highlightStat: '86 Sideline-to-Sideline Scraping',
  },
  {
    id: 'cb-douglas-rasul',
    name: 'Rasul Douglas',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'CB',
    ovr: 85,
    salary: 7,
    archetype: 'Zone Baiter / Ballhawk',
    attributes: { passRush: 0, runDefense: 79, coverage: 87, athleticism: 84, footballIQ: 91 },
    highlightStat: '91 Cover 3 Cloud Route Jumping',
  },
  {
    id: 'cb-johnson-taron',
    name: 'Taron Johnson',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'CB',
    ovr: 87,
    salary: 10,
    archetype: 'All-Pro Nickel Corner',
    attributes: { passRush: 72, runDefense: 88, coverage: 89, athleticism: 88, footballIQ: 92 },
    highlightStat: '93 Slot Coverage & Perimeter Screen Blowups',
  },
  {
    id: 's-rapp',
    name: 'Taylor Rapp',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'S',
    ovr: 79,
    salary: 3,
    archetype: 'Box Safety Enforcer',
    attributes: { passRush: 68, runDefense: 84, coverage: 78, athleticism: 81, footballIQ: 83 },
    highlightStat: '86 Run Fit Physicality in C-Gap',
  },

  // ===================== MIAMI DOLPHINS (MIA) =====================
  {
    id: 'qb-tua',
    name: 'Tua Tagovailoa',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'QB',
    ovr: 86,
    salary: 53,
    starter: true,
    archetype: 'Anticipation Rhythm Passer',
    attributes: { passing: 91, rushing: 68, passBlocking: 0, runBlocking: 0, athleticism: 75, footballIQ: 93 },
    highlightStat: '95 Release Quickness & Middle-Field Anticipation',
  },
  {
    id: 'qb-thompson-skylar',
    name: 'Skylar Thompson',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'QB',
    ovr: 72,
    salary: 1,
    starter: false,
    archetype: 'Mobile Backup Signal Caller',
    attributes: { passing: 74, rushing: 78, passBlocking: 0, runBlocking: 0, athleticism: 81, footballIQ: 75 },
    highlightStat: '82 Rollout Delivery & Scramble Ability',
  },
  {
    id: 'rb-achane',
    name: 'De\'Von Achane',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'RB',
    ovr: 85,
    salary: 1,
    archetype: 'Track Speed Homerun Hitter',
    attributes: { passing: 0, rushing: 88, receiving: 86, passBlocking: 62, runBlocking: 0, athleticism: 96, footballIQ: 82 },
    highlightStat: '97 Acceleration & Angle-Eliminating Burst',
  },
  {
    id: 'rb-mostert',
    name: 'Raheem Mostert',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'RB',
    ovr: 84,
    salary: 4,
    archetype: 'One-Cut Slash & Score',
    attributes: { passing: 0, rushing: 85, receiving: 74, passBlocking: 70, runBlocking: 0, athleticism: 91, footballIQ: 84 },
    highlightStat: '92 Touchdown Efficiency & Speed',
  },
  {
    id: 'wr-hill',
    name: 'Tyreek Hill',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'WR',
    ovr: 98,
    salary: 30,
    archetype: 'Electrifying Deep Threat & Speed Phenom',
    attributes: { passing: 0, rushing: 82, receiving: 98, passBlocking: 0, runBlocking: 55, athleticism: 99, footballIQ: 94 },
    highlightStat: '99 Pure Top-End Speed & Unmatched Separation',
  },
  {
    id: 'wr-waddle',
    name: 'Jaylen Waddle',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'WR',
    ovr: 89,
    salary: 28,
    archetype: 'Explosive Route Runner',
    attributes: { passing: 0, rushing: 0, receiving: 91, passBlocking: 0, runBlocking: 58, athleticism: 96, footballIQ: 88 },
    highlightStat: '96 Acceleration on Crossing Routes',
  },
  {
    id: 'te-smith-jonnu',
    name: 'Jonnu Smith',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'TE',
    ovr: 83,
    salary: 4,
    archetype: 'YAC Weapon Tight End',
    attributes: { passing: 0, rushing: 0, receiving: 84, passBlocking: 68, runBlocking: 76, athleticism: 88, footballIQ: 81 },
    highlightStat: '90 Ball-Carrier Vision & Screen Execution',
  },
  {
    id: 'ot-armstead',
    name: 'Terron Armstead',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'OT',
    ovr: 90,
    salary: 13,
    archetype: 'Elite Dancing Bear Blindside',
    attributes: { passing: 0, rushing: 0, passBlocking: 93, runBlocking: 88, athleticism: 86, footballIQ: 92 },
    highlightStat: '94 Footwork Precision vs Speed Rush',
  },
  {
    id: 'ot-jackson-austin',
    name: 'Austin Jackson',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'OT',
    ovr: 80,
    salary: 12,
    archetype: 'Athletic Right Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 81, athleticism: 82, footballIQ: 79 },
    highlightStat: '82 Wide Zone Perimeter Seal',
  },
  {
    id: 'c-brewer',
    name: 'Aaron Brewer',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'C',
    ovr: 80,
    salary: 7,
    archetype: 'Elite Reach Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 77, runBlocking: 86, athleticism: 87, footballIQ: 82 },
    highlightStat: '91 Lateral Agility to the 2nd Level',
  },
  {
    id: 'edge-chubb',
    name: 'Bradley Chubb',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'EDGE',
    ovr: 88,
    salary: 22,
    archetype: 'Power-Speed Edge Destructor',
    attributes: { passRush: 90, runDefense: 85, coverage: 65, athleticism: 86, footballIQ: 87 },
    highlightStat: '92 Strip-Sack Force & Corner Turn',
  },
  {
    id: 'edge-phillips',
    name: 'Jaelan Phillips',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'EDGE',
    ovr: 86,
    salary: 3,
    archetype: 'Pure Explosive Bending Rusher',
    attributes: { passRush: 88, runDefense: 82, coverage: 68, athleticism: 90, footballIQ: 83 },
    highlightStat: '91 Quick Step & Inside Counter Spin',
  },
  {
    id: 'dt-sieler',
    name: 'Zach Sieler',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'DT',
    ovr: 86,
    salary: 10,
    archetype: 'Relentless High-Motor DT',
    attributes: { passRush: 85, runDefense: 89, coverage: 50, athleticism: 79, footballIQ: 88 },
    highlightStat: '90 Interior Penetration & Second-Effort Sacks',
  },
  {
    id: 'lb-brooks-jordyn',
    name: 'Jordyn Brooks',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'LB',
    ovr: 83,
    salary: 8,
    archetype: 'Tackling Machine Linebacker',
    attributes: { passRush: 75, runDefense: 87, coverage: 79, athleticism: 86, footballIQ: 84 },
    highlightStat: '89 Downhill Pursuit & Form Tackling',
  },
  {
    id: 'cb-ramsey',
    name: 'Jalen Ramsey',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'CB',
    ovr: 94,
    salary: 24,
    archetype: 'Hall of Fame Star Defender',
    attributes: { passRush: 74, runDefense: 88, coverage: 95, athleticism: 91, footballIQ: 97 },
    highlightStat: '96 Physical Press, Run Stop & Ball Trajectory Diagnosis',
  },
  {
    id: 's-holland',
    name: 'Jevon Holland',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'S',
    ovr: 89,
    salary: 2,
    archetype: 'Versatile Free Safety Playmaker',
    attributes: { passRush: 75, runDefense: 86, coverage: 91, athleticism: 90, footballIQ: 91 },
    highlightStat: '93 Centerfield Range & Disguised Safety Blitzing',
  },
  {
    id: 'og-wynn-isaiah',
    name: 'Isaiah Wynn',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'OG',
    ovr: 79,
    salary: 2,
    archetype: 'Pass-Protection Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 78, athleticism: 77, footballIQ: 81 },
    highlightStat: '84 Quick Set in Inside Pass Pro',
  },
  {
    id: 'og-jones-robert',
    name: 'Robert Jones',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'OG',
    ovr: 76,
    salary: 1,
    archetype: 'Physical Road Grader',
    attributes: { passing: 0, rushing: 0, passBlocking: 75, runBlocking: 80, athleticism: 76, footballIQ: 77 },
    highlightStat: '82 Goal Line Surge Blocking',
  },

  // ===================== NEW ENGLAND PATRIOTS (NE) =====================
  {
    id: 'qb-maye',
    name: 'Drake Maye',
    team: 'NE',
    teamCity: 'New England',
    position: 'QB',
    ovr: 82,
    salary: 9,
    starter: true,
    archetype: 'Prototypical Rocket Arm',
    attributes: { passing: 86, rushing: 82, passBlocking: 0, runBlocking: 0, athleticism: 88, footballIQ: 82 },
    highlightStat: '93 Arm Velocity & Off-Schedule Mobility',
  },
  {
    id: 'qb-brissett',
    name: 'Jacoby Brissett',
    team: 'NE',
    teamCity: 'New England',
    position: 'QB',
    ovr: 78,
    salary: 8,
    starter: false,
    archetype: 'Poised Veteran Field Commander',
    attributes: { passing: 81, rushing: 68, passBlocking: 0, runBlocking: 0, athleticism: 70, footballIQ: 86 },
    highlightStat: '87 Ball Security & Short-Yardage Sneak Specialist',
  },
  {
    id: 'qb-milton',
    name: 'Joe Milton III',
    team: 'NE',
    teamCity: 'New England',
    position: 'QB',
    ovr: 73,
    salary: 1,
    starter: false,
    archetype: 'Cannon-Arm Developmental QB',
    attributes: { passing: 77, rushing: 82, passBlocking: 0, runBlocking: 0, athleticism: 89, footballIQ: 72 },
    highlightStat: '99 Raw Throw Power & Deep Downfield Strength',
  },
  {
    id: 'rb-stevenson',
    name: 'Rhamondre Stevenson',
    team: 'NE',
    teamCity: 'New England',
    position: 'RB',
    ovr: 85,
    salary: 9,
    archetype: 'Violent Contact Balancer',
    attributes: { passing: 0, rushing: 88, receiving: 80, passBlocking: 81, runBlocking: 0, athleticism: 82, footballIQ: 86 },
    highlightStat: '91 Broken Tackles & Short-Yardage Conversion',
  },
  {
    id: 'wr-douglas-demario',
    name: 'DeMario Douglas',
    team: 'NE',
    teamCity: 'New England',
    position: 'WR',
    ovr: 80,
    salary: 1,
    archetype: 'Lightning Slot Spark',
    attributes: { passing: 0, rushing: 0, receiving: 82, passBlocking: 0, runBlocking: 50, athleticism: 91, footballIQ: 81 },
    highlightStat: '92 Whip-Route Separation in Under 2 Seconds',
  },
  {
    id: 'te-henry-hunter',
    name: 'Hunter Henry',
    team: 'NE',
    teamCity: 'New England',
    position: 'TE',
    ovr: 82,
    salary: 9,
    archetype: 'Red-Zone Security Blanket',
    attributes: { passing: 0, rushing: 0, receiving: 83, passBlocking: 74, runBlocking: 80, athleticism: 78, footballIQ: 87 },
    highlightStat: '88 Third-Down Chain Moving & End-Zone Targets',
  },
  {
    id: 'ot-onwenu',
    name: 'Mike Onwenu',
    team: 'NE',
    teamCity: 'New England',
    position: 'OT',
    ovr: 85,
    salary: 19,
    archetype: 'Immovable Wall Tackle/Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 86, runBlocking: 88, athleticism: 74, footballIQ: 88 },
    highlightStat: '93 Raw Core Power vs Elite Power Rushers',
  },
  {
    id: 'edge-white-keion',
    name: 'Keion White',
    team: 'NE',
    teamCity: 'New England',
    position: 'EDGE',
    ovr: 82,
    salary: 2,
    archetype: 'Heavy Bull-Rush Edge',
    attributes: { passRush: 84, runDefense: 86, coverage: 58, athleticism: 87, footballIQ: 80 },
    highlightStat: '89 Violent Hand Usage & Collapsing Edge',
  },
  {
    id: 'dt-barmore',
    name: 'Christian Barmore',
    team: 'NE',
    teamCity: 'New England',
    position: 'DT',
    ovr: 89,
    salary: 21,
    archetype: 'Elite Interior Pass Disruptor',
    attributes: { passRush: 92, runDefense: 87, coverage: 50, athleticism: 82, footballIQ: 88 },
    highlightStat: '93 Swim Move & Double-Team Busting',
  },
  {
    id: 'lb-tavai',
    name: 'Jahlani Tavai',
    team: 'NE',
    teamCity: 'New England',
    position: 'LB',
    ovr: 81,
    salary: 5,
    archetype: 'Physical Scheme-Versatile LB',
    attributes: { passRush: 76, runDefense: 84, coverage: 77, athleticism: 77, footballIQ: 86 },
    highlightStat: '85 Cross-Key Identification & Box Tackling',
  },
  {
    id: 'cb-gonzalez',
    name: 'Christian Gonzalez',
    team: 'NE',
    teamCity: 'New England',
    position: 'CB',
    ovr: 88,
    salary: 4,
    archetype: 'Silky Smooth Boundary Lockdown',
    attributes: { passRush: 0, runDefense: 78, coverage: 91, athleticism: 93, footballIQ: 88 },
    highlightStat: '94 Fluid Hip Flip & Boundary Erasure',
  },
  {
    id: 's-dugger',
    name: 'Kyle Dugger',
    team: 'NE',
    teamCity: 'New England',
    position: 'S',
    ovr: 87,
    salary: 14,
    archetype: 'Heavy Hitting Box/TE Eraser',
    attributes: { passRush: 76, runDefense: 90, coverage: 84, athleticism: 89, footballIQ: 89 },
    highlightStat: '93 Point-of-Impact Demolition & TE Brackets',
  },
  {
    id: 'wr-bourne-kendrick',
    name: 'Kendrick Bourne',
    team: 'NE',
    teamCity: 'New England',
    position: 'WR',
    ovr: 79,
    salary: 6,
    archetype: 'Reliable Possession Target',
    attributes: { passing: 0, rushing: 0, receiving: 81, passBlocking: 0, runBlocking: 62, athleticism: 84, footballIQ: 84 },
    highlightStat: '85 Contested Catch & Slant Separation',
  },
  {
    id: 'og-sow-sidy',
    name: 'Sidy Sow',
    team: 'NE',
    teamCity: 'New England',
    position: 'OG',
    ovr: 78,
    salary: 1,
    archetype: 'Mauling Power Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 77, runBlocking: 83, athleticism: 80, footballIQ: 78 },
    highlightStat: '85 Gap Power Drive Blocking',
  },
  {
    id: 'c-andrews-david',
    name: 'David Andrews',
    team: 'NE',
    teamCity: 'New England',
    position: 'C',
    ovr: 82,
    salary: 6,
    archetype: 'Veteran Anchor & Line Leader',
    attributes: { passing: 0, rushing: 0, passBlocking: 83, runBlocking: 82, athleticism: 74, footballIQ: 94 },
    highlightStat: '94 Blitz Call Leadership & Steady Snaps',
  },

  // ===================== NEW YORK JETS (NYJ) =====================
  {
    id: 'qb-rodgers',
    name: 'Aaron Rodgers',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'QB',
    ovr: 86,
    salary: 35,
    starter: true,
    archetype: 'Surgical Mastermind Passer',
    attributes: { passing: 91, rushing: 64, passBlocking: 0, runBlocking: 0, athleticism: 68, footballIQ: 99 },
    highlightStat: '99 Pre-Snap Audible & Free Play Touchdowns',
  },
  {
    id: 'qb-taylor-tyrod',
    name: 'Tyrod Taylor',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'QB',
    ovr: 74,
    salary: 6,
    starter: false,
    archetype: 'Veteran Scrambler / Safe Custodian',
    attributes: { passing: 76, rushing: 80, passBlocking: 0, runBlocking: 0, athleticism: 82, footballIQ: 87 },
    highlightStat: '88 Low Turnover Rate & Mobility',
  },
  {
    id: 'rb-hall-breece',
    name: 'Breece Hall',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'RB',
    ovr: 89,
    salary: 2,
    archetype: 'Generational Speed & Receiving RB',
    attributes: { passing: 0, rushing: 90, receiving: 89, passBlocking: 73, runBlocking: 0, athleticism: 94, footballIQ: 88 },
    highlightStat: '96 Breakaway Long-Speed & Wheel Route Mastery',
  },
  {
    id: 'rb-allen-braelon',
    name: 'Braelon Allen',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'RB',
    ovr: 79,
    salary: 1,
    archetype: 'Goliath Downhill Hammer',
    attributes: { passing: 0, rushing: 82, receiving: 74, passBlocking: 80, runBlocking: 0, athleticism: 82, footballIQ: 79 },
    highlightStat: '90 Goal-Line Trucking & Forward Lean',
  },
  {
    id: 'wr-adams-davante',
    name: 'Davante Adams',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'WR',
    ovr: 94,
    salary: 28,
    archetype: 'Master of the Line-of-Scrimmage Release',
    attributes: { passing: 0, rushing: 0, receiving: 96, passBlocking: 0, runBlocking: 62, athleticism: 88, footballIQ: 98 },
    highlightStat: '98 Hop-Step Release & Red-Zone Corner Fades',
  },
  {
    id: 'wr-wilson-garrett',
    name: 'Garrett Wilson',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'WR',
    ovr: 89,
    salary: 5,
    archetype: 'Acrobatic Separation Wizard',
    attributes: { passing: 0, rushing: 0, receiving: 92, passBlocking: 0, runBlocking: 60, athleticism: 93, footballIQ: 89 },
    highlightStat: '95 Contested Body Control & Sudden Cuts',
  },
  {
    id: 'te-conklin',
    name: 'Tyler Conklin',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'TE',
    ovr: 81,
    salary: 7,
    archetype: 'Reliable Possession In-Line',
    attributes: { passing: 0, rushing: 0, receiving: 82, passBlocking: 73, runBlocking: 79, athleticism: 78, footballIQ: 83 },
    highlightStat: '84 High-Percentage 3rd Down Catch Rate',
  },
  {
    id: 'ot-smith-tyron',
    name: 'Tyron Smith',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'OT',
    ovr: 90,
    salary: 7,
    archetype: 'Legendary Blindside Fortress',
    attributes: { passing: 0, rushing: 0, passBlocking: 95, runBlocking: 89, athleticism: 79, footballIQ: 96 },
    highlightStat: '96 Pass Protection Punch & Zero Pressure Rate',
  },
  {
    id: 'ot-moses',
    name: 'Morgan Moses',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'OT',
    ovr: 82,
    salary: 5,
    archetype: 'Veteran RT Anchor',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 85, athleticism: 75, footballIQ: 87 },
    highlightStat: '86 Gap Scheme Down-Block Torque',
  },
  {
    id: 'og-avt',
    name: 'Alijah Vera-Tucker',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'OG',
    ovr: 83,
    salary: 4,
    archetype: 'Versatile Athletic Puller',
    attributes: { passing: 0, rushing: 0, passBlocking: 84, runBlocking: 85, athleticism: 84, footballIQ: 86 },
    highlightStat: '88 Space Pulling on Counter & Sweep',
  },
  {
    id: 'c-tippmann',
    name: 'Joe Tippmann',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'C',
    ovr: 80,
    salary: 2,
    archetype: 'Tall Athletic Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 82, athleticism: 83, footballIQ: 81 },
    highlightStat: '85 Line-Call Command & Level-2 Mobility',
  },
  {
    id: 'edge-mcdonald',
    name: 'Will McDonald IV',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'EDGE',
    ovr: 84,
    salary: 4,
    archetype: 'Ghost Move Speed Rusher',
    attributes: { passRush: 89, runDefense: 74, coverage: 64, athleticism: 92, footballIQ: 81 },
    highlightStat: '94 Spin Move & Ankle-Flex Edge Bend',
  },
  {
    id: 'edge-reddick',
    name: 'Haason Reddick',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'EDGE',
    ovr: 87,
    salary: 14,
    archetype: 'Pure Double-Digit Sack Artist',
    attributes: { passRush: 91, runDefense: 76, coverage: 70, athleticism: 88, footballIQ: 88 },
    highlightStat: '93 Strip-Sack Club-Rip Velocity',
  },
  {
    id: 'dt-williams-quinnen',
    name: 'Quinnen Williams',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'DT',
    ovr: 94,
    salary: 24,
    archetype: 'Dominant 2-Gap Disruptor',
    attributes: { passRush: 94, runDefense: 96, coverage: 50, athleticism: 86, footballIQ: 95 },
    highlightStat: '97 Double-Team Eradication & Pocket Destruction',
  },
  {
    id: 'lb-williams-quincy',
    name: 'Quincy Williams',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'LB',
    ovr: 88,
    salary: 6,
    archetype: 'Human Missile Weakside LB',
    attributes: { passRush: 82, runDefense: 91, coverage: 87, athleticism: 91, footballIQ: 89 },
    highlightStat: '95 Bone-Crushing Open Field Tackles for Loss',
  },
  {
    id: 'lb-mosley',
    name: 'C.J. Mosley',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'LB',
    ovr: 88,
    salary: 8,
    archetype: 'Field General Mike LB',
    attributes: { passRush: 75, runDefense: 91, coverage: 86, athleticism: 77, footballIQ: 98 },
    highlightStat: '98 Pre-Snap Diagnostic Recognition',
  },
  {
    id: 'cb-gardner',
    name: 'Sauce Gardner',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'CB',
    ovr: 97,
    salary: 8,
    archetype: 'Generational Island Lock (Madden 97)',
    attributes: { passRush: 0, runDefense: 82, coverage: 98, athleticism: 94, footballIQ: 97 },
    highlightStat: '99 Length, Shadow Mirror & Lowest Target Rating Allowed',
  },
  {
    id: 'cb-reed',
    name: 'D.J. Reed',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'CB',
    ovr: 86,
    salary: 11,
    archetype: 'Tenacious Boundary Lockdown',
    attributes: { passRush: 0, runDefense: 80, coverage: 89, athleticism: 89, footballIQ: 90 },
    highlightStat: '91 Sticky Hand Placement in Press-Bail',
  },
  {
    id: 'cb-carter-michael',
    name: 'Michael Carter II',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'CB',
    ovr: 85,
    salary: 10,
    archetype: 'Premier Slot Technician',
    attributes: { passRush: 68, runDefense: 81, coverage: 88, athleticism: 89, footballIQ: 90 },
    highlightStat: '90 Change of Direction & Quick In-Breaking Route Denial',
  },
  {
    id: 's-adams-tony',
    name: 'Tony Adams',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'S',
    ovr: 81,
    salary: 1,
    archetype: 'Range Free Safety',
    attributes: { passRush: 64, runDefense: 80, coverage: 83, athleticism: 85, footballIQ: 83 },
    highlightStat: '85 Centerfield Break on Deep Ball',
  },
  {
    id: 's-clark-chuck',
    name: 'Chuck Clark',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'S',
    ovr: 80,
    salary: 2,
    archetype: 'Smart Box Safety',
    attributes: { passRush: 70, runDefense: 84, coverage: 80, athleticism: 78, footballIQ: 88 },
    highlightStat: '88 Downhill Run Fill & Communication',
  },
  // --- AFC East Kickers & Special Teams ---
  {
    id: 'k-bass-tyler',
    name: 'Tyler Bass',
    team: 'BUF',
    teamCity: 'Buffalo',
    position: 'K',
    ovr: 82,
    salary: 4,
    starter: true,
    archetype: 'Strong-Legged Cold Weather Kicker',
    attributes: { passing: 0, rushing: 0, kicking: 86, athleticism: 75, footballIQ: 84 },
    highlightStat: '58-Yard Career Long & Clutch Wind Management',
  },
  {
    id: 'k-sanders-jason',
    name: 'Jason Sanders',
    team: 'MIA',
    teamCity: 'Miami',
    position: 'K',
    ovr: 84,
    salary: 4,
    starter: true,
    archetype: 'Precision All-Weather Specialist',
    attributes: { passing: 0, rushing: 0, kicking: 88, athleticism: 76, footballIQ: 87 },
    highlightStat: '92% Inside 50 Yards & Pro Bowl Accuracy',
  },
  {
    id: 'k-slye-joey',
    name: 'Joey Slye',
    team: 'NE',
    teamCity: 'New England',
    position: 'K',
    ovr: 79,
    salary: 2,
    starter: true,
    archetype: 'Power Cannon Kickoff Master',
    attributes: { passing: 0, rushing: 0, kicking: 83, athleticism: 78, footballIQ: 80 },
    highlightStat: '63-Yard Leg Strength & Touchback Rate Leader',
  },
  {
    id: 'wr-polk-jalynn',
    name: "Ja'Lynn Polk",
    team: 'NE',
    teamCity: 'New England',
    position: 'WR',
    ovr: 77,
    salary: 2,
    starter: false,
    archetype: 'Contested Catch Boundary Target',
    attributes: { passing: 0, rushing: 0, receiving: 80, passBlocking: 0, runBlocking: 68, athleticism: 84, footballIQ: 82 },
    highlightStat: '90 Contested Catch Rate in Tight Windows',
  },
  {
    id: 'cb-jones-jonathan',
    name: 'Jonathan Jones',
    team: 'NE',
    teamCity: 'New England',
    position: 'CB',
    ovr: 83,
    salary: 9,
    starter: true,
    archetype: 'Speed Slot / Perimeter Veteran',
    attributes: { passRush: 0, runDefense: 78, coverage: 85, athleticism: 91, footballIQ: 89 },
    highlightStat: '4.33 Speed & Deep Post Mirroring',
  },
  {
    id: 'rb-gibson-antonio',
    name: 'Antonio Gibson',
    team: 'NE',
    teamCity: 'New England',
    position: 'RB',
    ovr: 79,
    salary: 4,
    starter: false,
    archetype: 'Receiving Third-Down Weapon',
    attributes: { passing: 0, rushing: 80, receiving: 83, passBlocking: 74, runBlocking: 0, athleticism: 88, footballIQ: 80 },
    highlightStat: '90 Pass-Catching Separation Out of the Backfield',
  },
  {
    id: 'k-zuerlein-greg',
    name: 'Greg Zuerlein',
    team: 'NYJ',
    teamCity: 'New York',
    position: 'K',
    ovr: 81,
    salary: 3,
    starter: true,
    archetype: 'Legatron 60-Yard Weapon',
    attributes: { passing: 0, rushing: 0, kicking: 85, athleticism: 74, footballIQ: 85 },
    highlightStat: '60-Yard Field Goal Range in MetLife Stadium',
  },
];
