import { Player } from '../../types';

export const AFC_NORTH_PLAYERS: Player[] = [
  // ===================== BALTIMORE RAVENS (BAL) =====================
  {
    id: 'qb-jackson',
    name: 'Lamar Jackson',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'QB',
    ovr: 98,
    salary: 52,
    starter: true,
    archetype: '2x MVP Generational Dual-Threat (Madden 98)',
    attributes: { passing: 94, rushing: 98, passBlocking: 0, runBlocking: 0, athleticism: 98, footballIQ: 95 },
    highlightStat: '98 Speed & Lethal Deep Post Accuracy',
  },
  {
    id: 'qb-johnson-josh',
    name: 'Josh Johnson',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'QB',
    ovr: 72,
    salary: 1,
    starter: false,
    archetype: 'Experienced Veteran Backup',
    attributes: { passing: 74, rushing: 74, passBlocking: 0, runBlocking: 0, athleticism: 77, footballIQ: 85 },
    highlightStat: '85 Steady Command of Option Packages',
  },
  {
    id: 'rb-henry',
    name: 'Derrick Henry',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'RB',
    ovr: 95,
    salary: 8,
    archetype: 'The King / Unstoppable Power Train',
    attributes: { passing: 0, rushing: 97, receiving: 74, passBlocking: 84, runBlocking: 0, athleticism: 89, footballIQ: 93 },
    highlightStat: '99 Stiff Arm & 4th Quarter Fourth-Gear Breakaway',
  },
  {
    id: 'rb-hill-justice',
    name: 'Justice Hill',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'RB',
    ovr: 78,
    salary: 3,
    archetype: 'Pass-Catching / Blitz Pickup',
    attributes: { passing: 0, rushing: 79, receiving: 83, passBlocking: 82, runBlocking: 0, athleticism: 91, footballIQ: 81 },
    highlightStat: '86 3rd Down Pass Protection Pickup',
  },
  {
    id: 'wr-flowers',
    name: 'Zay Flowers',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'WR',
    ovr: 85,
    salary: 3,
    archetype: 'Electric Joystick Receiver',
    attributes: { passing: 0, rushing: 78, receiving: 88, passBlocking: 0, runBlocking: 55, athleticism: 95, footballIQ: 85 },
    highlightStat: '96 Change-of-Direction & Stop-Start Burst',
  },
  {
    id: 'wr-bateman',
    name: 'Rashod Bateman',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'WR',
    ovr: 79,
    salary: 5,
    archetype: 'Crisp Boundary Route Runner',
    attributes: { passing: 0, rushing: 0, receiving: 82, passBlocking: 0, runBlocking: 62, athleticism: 87, footballIQ: 83 },
    highlightStat: '88 Separation on Comebacks and In-Breakers',
  },
  {
    id: 'wr-johnson-diontae',
    name: 'Diontae Johnson',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'WR',
    ovr: 83,
    salary: 4,
    archetype: 'Elite Separation & Route Technician',
    attributes: { passing: 0, rushing: 0, receiving: 86, passBlocking: 0, runBlocking: 58, athleticism: 89, footballIQ: 86 },
    highlightStat: '92 Sudden Break Separation on Slants',
  },
  {
    id: 'te-andrews',
    name: 'Mark Andrews',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'TE',
    ovr: 92,
    salary: 14,
    archetype: 'Elite Seam Weapon & Red Zone Target',
    attributes: { passing: 0, rushing: 0, receiving: 94, passBlocking: 76, runBlocking: 83, athleticism: 85, footballIQ: 94 },
    highlightStat: '95 Contested Catch & Middle Field Dominance',
  },
  {
    id: 'te-likely',
    name: 'Isaiah Likely',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'TE',
    ovr: 82,
    salary: 1,
    archetype: 'Dynamic Move TE / YAC Threat',
    attributes: { passing: 0, rushing: 0, receiving: 85, passBlocking: 68, runBlocking: 76, athleticism: 88, footballIQ: 82 },
    highlightStat: '90 Hurdle & Tightrope Sideline Catches',
  },
  {
    id: 'ot-stanley',
    name: 'Ronnie Stanley',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'OT',
    ovr: 85,
    salary: 20,
    archetype: 'Veteran Blindside Protector',
    attributes: { passing: 0, rushing: 0, passBlocking: 88, runBlocking: 84, athleticism: 78, footballIQ: 90 },
    highlightStat: '90 Pass Set Balance & Punch Timing',
  },
  {
    id: 'c-linderbaum',
    name: 'Tyler Linderbaum',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'C',
    ovr: 89,
    salary: 3,
    archetype: 'All-Pro Athletic Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 88, runBlocking: 94, athleticism: 89, footballIQ: 92 },
    highlightStat: '96 Second-Level Climb & Screen Pulling Speed',
  },
  {
    id: 'og-vorhees',
    name: 'Andrew Vorhees',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'OG',
    ovr: 78,
    salary: 1,
    archetype: 'Power Guard Anchor',
    attributes: { passing: 0, rushing: 0, passBlocking: 79, runBlocking: 84, athleticism: 77, footballIQ: 80 },
    highlightStat: '86 Bench Press Strength vs DTs',
  },
  {
    id: 'edge-van-noy',
    name: 'Kyle Van Noy',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'EDGE',
    ovr: 83,
    salary: 5,
    archetype: 'Savvy Vet Pass Rusher',
    attributes: { passRush: 86, runDefense: 82, coverage: 74, athleticism: 78, footballIQ: 94 },
    highlightStat: '91 Disguised Pressure & Strip-Sack Angles',
  },
  {
    id: 'edge-oweh',
    name: 'Odafe Oweh',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'EDGE',
    ovr: 82,
    salary: 3,
    archetype: 'Freakish Speed-Bender',
    attributes: { passRush: 85, runDefense: 81, coverage: 65, athleticism: 93, footballIQ: 80 },
    highlightStat: '93 10-Yard Split & Backfield Penetration',
  },
  {
    id: 'dt-madubuike',
    name: 'Justin Madubuike',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'DT',
    ovr: 91,
    salary: 24,
    archetype: 'All-Pro Interior Wrecking Ball',
    attributes: { passRush: 93, runDefense: 89, coverage: 50, athleticism: 85, footballIQ: 90 },
    highlightStat: '95 First-Step Club-Swim & Pocket Collapse',
  },
  {
    id: 'dt-pierce',
    name: 'Michael Pierce',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'DT',
    ovr: 84,
    salary: 7,
    archetype: '0-Tech Run Wall Anchor',
    attributes: { passRush: 75, runDefense: 94, coverage: 40, athleticism: 66, footballIQ: 88 },
    highlightStat: '97 Double-Team Absorption in A-Gap',
  },
  {
    id: 'lb-smith-roquan',
    name: 'Roquan Smith',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'LB',
    ovr: 96,
    salary: 20,
    archetype: 'Defensive Heart & Soul (Madden 96)',
    attributes: { passRush: 82, runDefense: 97, coverage: 93, athleticism: 89, footballIQ: 98 },
    highlightStat: '98 Instant Diagnostic Flow & Sideline Hits',
  },
  {
    id: 'cb-humphrey',
    name: 'Marlon Humphrey',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'CB',
    ovr: 91,
    salary: 19,
    archetype: 'Physical Press / Fruit Punch Creator',
    attributes: { passRush: 74, runDefense: 86, coverage: 92, athleticism: 89, footballIQ: 93 },
    highlightStat: '96 Fruit Punch Forced Fumbles & Press Disruption',
  },
  {
    id: 'cb-wiggins-nate',
    name: 'Nate Wiggins',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'CB',
    ovr: 78,
    salary: 3,
    archetype: '4.28 Blazing Trail Corner',
    attributes: { passRush: 0, runDefense: 70, coverage: 82, athleticism: 96, footballIQ: 77 },
    highlightStat: '97 Recovery Speed & Chasedown Punch-Outs',
  },
  {
    id: 's-hamilton',
    name: 'Kyle Hamilton',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'S',
    ovr: 94,
    salary: 4,
    archetype: 'Unicorn All-World Chess Piece',
    attributes: { passRush: 86, runDefense: 93, coverage: 95, athleticism: 91, footballIQ: 97 },
    highlightStat: '97 Slot Erasure, Sub-Linebacker Blitzes & Deep Range',
  },
  {
    id: 's-williams-marcus',
    name: 'Marcus Williams',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'S',
    ovr: 84,
    salary: 14,
    archetype: 'Deep Centerfield Range Safety',
    attributes: { passRush: 60, runDefense: 79, coverage: 88, athleticism: 87, footballIQ: 89 },
    highlightStat: '90 Over-the-Top Deep Ball Anticipation',
  },

  // ===================== CINCINNATI BENGALS (CIN) =====================
  {
    id: 'qb-burrow',
    name: 'Joe Burrow',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'QB',
    ovr: 95,
    salary: 55,
    starter: true,
    archetype: 'Surgical Pocket Assassin',
    attributes: { passing: 97, rushing: 74, passBlocking: 0, runBlocking: 0, athleticism: 78, footballIQ: 98 },
    highlightStat: '98 Short & Intermediate Pinpoint Ball Placement',
  },
  {
    id: 'qb-browning',
    name: 'Jake Browning',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'QB',
    ovr: 76,
    salary: 2,
    starter: false,
    archetype: 'Gritty Rhythm Backup',
    attributes: { passing: 79, rushing: 72, passBlocking: 0, runBlocking: 0, athleticism: 76, footballIQ: 83 },
    highlightStat: '86 Quick Read Decision-Making & Accuracy',
  },
  {
    id: 'rb-brown-chase',
    name: 'Chase Brown',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'RB',
    ovr: 81,
    salary: 1,
    archetype: 'Explosive Homerun Back',
    attributes: { passing: 0, rushing: 84, receiving: 80, passBlocking: 69, runBlocking: 0, athleticism: 93, footballIQ: 79 },
    highlightStat: '94 Acceleration & Perimeter Speed',
  },
  {
    id: 'rb-moss-zack',
    name: 'Zack Moss',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'RB',
    ovr: 78,
    salary: 4,
    archetype: 'Inside Zone Grinder',
    attributes: { passing: 0, rushing: 80, receiving: 74, passBlocking: 78, runBlocking: 0, athleticism: 79, footballIQ: 81 },
    highlightStat: '85 Contact Balance & Pass Pro Trust',
  },
  {
    id: 'wr-chase',
    name: 'Ja\'Marr Chase',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'WR',
    ovr: 95,
    salary: 9,
    archetype: 'Generational Alpha / YAC Tyrant',
    attributes: { passing: 0, rushing: 80, receiving: 97, passBlocking: 0, runBlocking: 68, athleticism: 96, footballIQ: 94 },
    highlightStat: '98 Broken Tackle Slants & 80-Yard TD Explosions',
  },
  {
    id: 'wr-higgins',
    name: 'Tee Higgins',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'WR',
    ovr: 87,
    salary: 21,
    archetype: 'Boundary High-Point Specialist',
    attributes: { passing: 0, rushing: 0, receiving: 90, passBlocking: 0, runBlocking: 70, athleticism: 85, footballIQ: 88 },
    highlightStat: '95 Catch Radius & Back-Shoulder Fade Prowess',
  },
  {
    id: 'wr-iosivas',
    name: 'Andrei Iosivas',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'WR',
    ovr: 77,
    salary: 1,
    archetype: 'Athletic Red-Zone Threat',
    attributes: { passing: 0, rushing: 0, receiving: 79, passBlocking: 0, runBlocking: 65, athleticism: 90, footballIQ: 78 },
    highlightStat: '88 Red-Zone Target Conversion & Touchdown Nose',
  },
  {
    id: 'te-gesicki',
    name: 'Mike Gesicki',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'TE',
    ovr: 80,
    salary: 3,
    archetype: 'Big Slot Weapon',
    attributes: { passing: 0, rushing: 0, receiving: 83, passBlocking: 60, runBlocking: 62, athleticism: 85, footballIQ: 81 },
    highlightStat: '88 Leaping Catch Radius in the Seam',
  },
  {
    id: 'ot-brown-orlando',
    name: 'Orlando Brown Jr.',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'OT',
    ovr: 83,
    salary: 16,
    archetype: 'Massive Length Anchor',
    attributes: { passing: 0, rushing: 0, passBlocking: 85, runBlocking: 83, athleticism: 68, footballIQ: 88 },
    highlightStat: '94 Reach Length & Impenetrable Width',
  },
  {
    id: 'ot-mims-amarius',
    name: 'Amarius Mims',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'OT',
    ovr: 77,
    salary: 3,
    archetype: 'Goliath Physical Specimen',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 81, athleticism: 84, footballIQ: 76 },
    highlightStat: '93 Wingspan & Raw Punch Force',
  },
  {
    id: 'c-karras',
    name: 'Ted Karras',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'C',
    ovr: 80,
    salary: 6,
    archetype: 'Vocal Leader Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 80, athleticism: 74, footballIQ: 89 },
    highlightStat: '88 Offensive Line Communication & Bull Anchor',
  },
  {
    id: 'og-cappa',
    name: 'Alex Cappa',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'OG',
    ovr: 80,
    salary: 9,
    archetype: 'Solid Veteran Right Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 83, runBlocking: 79, athleticism: 73, footballIQ: 87 },
    highlightStat: '85 Interior Pass Protection Stability',
  },
  {
    id: 'og-volson',
    name: 'Cordell Volson',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'OG',
    ovr: 76,
    salary: 1,
    archetype: 'Gritty Left Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 75, runBlocking: 80, athleticism: 75, footballIQ: 77 },
    highlightStat: '82 Inside Run Fit Push',
  },
  {
    id: 'edge-hendrickson',
    name: 'Trey Hendrickson',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'EDGE',
    ovr: 92,
    salary: 21,
    archetype: 'Relentless Dip-and-Rip Sack Leader',
    attributes: { passRush: 95, runDefense: 82, coverage: 60, athleticism: 86, footballIQ: 91 },
    highlightStat: '97 Pressure Rate & Signature Up-and-Under Counter',
  },
  {
    id: 'edge-hubbard',
    name: 'Sam Hubbard',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'EDGE',
    ovr: 80,
    salary: 10,
    archetype: 'Disciplined Edge Setter',
    attributes: { passRush: 78, runDefense: 86, coverage: 68, athleticism: 77, footballIQ: 88 },
    highlightStat: '89 Bootleg Contain & Fumble Return Awareness',
  },
  {
    id: 'dt-hill-bj',
    name: 'B.J. Hill',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'DT',
    ovr: 81,
    salary: 10,
    archetype: 'Trench Battler',
    attributes: { passRush: 81, runDefense: 84, coverage: 55, athleticism: 75, footballIQ: 85 },
    highlightStat: '85 Batted Passes at the Line & Run Stuffs',
  },
  {
    id: 'lb-wilson-logan',
    name: 'Logan Wilson',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'LB',
    ovr: 84,
    salary: 9,
    archetype: 'Ballhawking Zone LB',
    attributes: { passRush: 74, runDefense: 84, coverage: 88, athleticism: 83, footballIQ: 90 },
    highlightStat: '92 Interceptions in Underneath Hook Zones',
  },
  {
    id: 'lb-pratt',
    name: 'Germaine Pratt',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'LB',
    ovr: 82,
    salary: 7,
    archetype: 'Turnover Specialist LB',
    attributes: { passRush: 75, runDefense: 85, coverage: 82, athleticism: 82, footballIQ: 86 },
    highlightStat: '88 Punching Ball Loose on Group Tackles',
  },
  {
    id: 'cb-taylor-britt',
    name: 'Cam Taylor-Britt',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'CB',
    ovr: 82,
    salary: 1,
    archetype: 'Physical Downhill Corner',
    attributes: { passRush: 0, runDefense: 82, coverage: 84, athleticism: 91, footballIQ: 82 },
    highlightStat: '89 One-Handed Interceptions & Hard Tackles',
  },
  {
    id: 'cb-hilton',
    name: 'Mike Hilton',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'CB',
    ovr: 82,
    salary: 6,
    archetype: 'Blitzing Nickel Enforcer',
    attributes: { passRush: 84, runDefense: 87, coverage: 82, athleticism: 86, footballIQ: 93 },
    highlightStat: '94 Corner Blitz Timing & Perimeter Run Defense',
  },
  {
    id: 's-stone',
    name: 'Geno Stone',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'S',
    ovr: 83,
    salary: 7,
    archetype: 'Deep Ball-Theft Free Safety',
    attributes: { passRush: 60, runDefense: 77, coverage: 89, athleticism: 84, footballIQ: 92 },
    highlightStat: '93 Deep Post-Pattern Interceptions',
  },

  // ===================== CLEVELAND BROWNS (CLE) =====================
  {
    id: 'qb-watson',
    name: 'Deshaun Watson',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'QB',
    ovr: 79,
    salary: 20,
    starter: true,
    projectedStarter: true,
    archetype: 'Playmaker Passer',
    attributes: { passing: 82, rushing: 82, passBlocking: 0, runBlocking: 0, athleticism: 83, footballIQ: 81 },
    highlightStat: '88 Off-Schedule Throw Creation',
  },
  {
    id: 'qb-winston',
    name: 'Jameis Winston',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'QB',
    ovr: 75,
    salary: 4,
    starter: false,
    archetype: 'Fearless Gunslinger',
    attributes: { passing: 84, rushing: 68, passBlocking: 0, runBlocking: 0, athleticism: 72, footballIQ: 76 },
    highlightStat: '92 Deep Throw Power & Aggressive Shots',
  },
  {
    id: 'qb-dtr',
    name: 'Dorian Thompson-Robinson',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'QB',
    ovr: 72,
    salary: 1,
    starter: false,
    archetype: 'Scrambler / Dual-Threat',
    attributes: { passing: 73, rushing: 84, passBlocking: 0, runBlocking: 0, athleticism: 88, footballIQ: 73 },
    highlightStat: '88 Escape Agility on Rollouts',
  },
  {
    id: 'rb-chubb',
    name: 'Nick Chubb',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'RB',
    ovr: 94,
    salary: 12,
    archetype: 'Pure Running Perfection / Master of Contact',
    attributes: { passing: 0, rushing: 98, receiving: 74, passBlocking: 80, runBlocking: 0, athleticism: 91, footballIQ: 95 },
    highlightStat: '99 Broken Tackles, Vision & Yards After First Contact',
  },
  {
    id: 'rb-ford-jerome',
    name: 'Jerome Ford',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'RB',
    ovr: 79,
    salary: 1,
    archetype: 'Perimeter Speed Spark',
    attributes: { passing: 0, rushing: 81, receiving: 79, passBlocking: 68, runBlocking: 0, athleticism: 90, footballIQ: 78 },
    highlightStat: '91 Long Speed on Sweep Plays',
  },
  {
    id: 'wr-jeudy',
    name: 'Jerry Jeudy',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'WR',
    ovr: 81,
    salary: 17,
    archetype: 'Ankle-Breaking Route Technician',
    attributes: { passing: 0, rushing: 0, receiving: 85, passBlocking: 0, runBlocking: 55, athleticism: 89, footballIQ: 83 },
    highlightStat: '93 Route Running Separation at the Break Point',
  },
  {
    id: 'wr-tillman-cedric',
    name: 'Cedric Tillman',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'WR',
    ovr: 78,
    salary: 1,
    archetype: 'Physical Contested Catch Target',
    attributes: { passing: 0, rushing: 0, receiving: 80, passBlocking: 0, runBlocking: 68, athleticism: 84, footballIQ: 79 },
    highlightStat: '87 Over-the-Middle Tough Grabs',
  },
  {
    id: 'te-njoku',
    name: 'David Njoku',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'TE',
    ovr: 88,
    salary: 13,
    archetype: 'Athletic Freak / YAC Freight Train',
    attributes: { passing: 0, rushing: 0, receiving: 89, passBlocking: 76, runBlocking: 84, athleticism: 91, footballIQ: 86 },
    highlightStat: '94 Yards After Catch & Stiff-Arm Bulldozing',
  },
  {
    id: 'ot-conklin-jack',
    name: 'Jack Conklin',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'OT',
    ovr: 83,
    salary: 15,
    archetype: 'Veteran RT Power Blocker',
    attributes: { passing: 0, rushing: 0, passBlocking: 83, runBlocking: 88, athleticism: 74, footballIQ: 89 },
    highlightStat: '90 Drive Blocking Power & Edge Seal',
  },
  {
    id: 'ot-jones-dawand',
    name: 'Dawand Jones',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'OT',
    ovr: 80,
    salary: 1,
    archetype: 'Massive Human Mountain RT',
    attributes: { passing: 0, rushing: 0, passBlocking: 84, runBlocking: 81, athleticism: 68, footballIQ: 80 },
    highlightStat: '95 Reach Length & Pass Rush Stoning',
  },
  {
    id: 'og-bitonio',
    name: 'Joel Bitonio',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'OG',
    ovr: 89,
    salary: 16,
    archetype: 'All-Pro Guard Legend',
    attributes: { passing: 0, rushing: 0, passBlocking: 92, runBlocking: 90, athleticism: 82, footballIQ: 95 },
    highlightStat: '93 Pass Protection Balance & Pulling Craft',
  },
  {
    id: 'og-teller',
    name: 'Wyatt Teller',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'OG',
    ovr: 87,
    salary: 14,
    archetype: 'Pancake Mauler Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 95, athleticism: 79, footballIQ: 88 },
    highlightStat: '97 Pancake Block Impact on Pin-and-Pull Schemes',
  },
  {
    id: 'c-pocic',
    name: 'Ethan Pocic',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'C',
    ovr: 81,
    salary: 6,
    archetype: 'Zone Scheme Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 83, athleticism: 78, footballIQ: 86 },
    highlightStat: '86 Reach Blocks & Interior Combo Calls',
  },
  {
    id: 'edge-garrett',
    name: 'Myles Garrett',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'EDGE',
    ovr: 99,
    salary: 25,
    archetype: 'Reigning DPOY / Unblockable Titan (Madden 99 Club)',
    attributes: { passRush: 99, runDefense: 96, coverage: 65, athleticism: 96, footballIQ: 98 },
    highlightStat: '99 Pass Rush Move Arsenal & Pure Athletic Domination',
  },
  {
    id: 'edge-okoronkwo',
    name: 'Ogbo Okoronkwo',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'EDGE',
    ovr: 79,
    salary: 6,
    archetype: 'Explosive Speed Rusher',
    attributes: { passRush: 83, runDefense: 76, coverage: 60, athleticism: 84, footballIQ: 81 },
    highlightStat: '86 Quick Get-Off & Bend',
  },
  {
    id: 'dt-tomlinson-dalvin',
    name: 'Dalvin Tomlinson',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'DT',
    ovr: 82,
    salary: 14,
    archetype: 'Nose Tackle Space Eater',
    attributes: { passRush: 76, runDefense: 88, coverage: 40, athleticism: 70, footballIQ: 87 },
    highlightStat: '91 Double-Team Neutralization in Center',
  },
  {
    id: 'lb-jok',
    name: 'Jeremiah Owusu-Koramoah',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'LB',
    ovr: 88,
    salary: 13,
    archetype: 'Lightning Sideline Pursuer',
    attributes: { passRush: 84, runDefense: 89, coverage: 90, athleticism: 94, footballIQ: 91 },
    highlightStat: '96 Space Tackling & Backfield Missile TFLs',
  },
  {
    id: 'cb-ward-denzel',
    name: 'Denzel Ward',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'CB',
    ovr: 91,
    salary: 20,
    archetype: 'Premier Man-to-Man Shadow',
    attributes: { passRush: 0, runDefense: 75, coverage: 94, athleticism: 95, footballIQ: 92 },
    highlightStat: '96 Mirroring Footwork & PBU Reflexes',
  },
  {
    id: 'cb-emerson',
    name: 'Martin Emerson Jr.',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'CB',
    ovr: 83,
    salary: 1,
    archetype: 'Long Press-Cover Disruptor',
    attributes: { passRush: 0, runDefense: 80, coverage: 85, athleticism: 88, footballIQ: 84 },
    highlightStat: '90 Line of Scrimmage Boundary Jamming',
  },
  {
    id: 's-delpit',
    name: 'Grant Delpit',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'S',
    ovr: 84,
    salary: 12,
    archetype: 'Downhill Box Enforcer',
    attributes: { passRush: 78, runDefense: 88, coverage: 83, athleticism: 87, footballIQ: 86 },
    highlightStat: '90 Run Alley Fills & Blitz Pressure',
  },

  // ===================== PITTSBURGH STEELERS (PIT) =====================
  {
    id: 'qb-wilson-russell',
    name: 'Russell Wilson',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'QB',
    ovr: 81,
    salary: 1,
    starter: true,
    archetype: 'Moon Ball Pocket Commander',
    attributes: { passing: 84, rushing: 74, passBlocking: 0, runBlocking: 0, athleticism: 77, footballIQ: 91 },
    highlightStat: '92 Touchdown-to-Interception Ratio & Deep Moon Ball',
  },
  {
    id: 'qb-fields',
    name: 'Justin Fields',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'QB',
    ovr: 78,
    salary: 3,
    starter: false,
    archetype: 'Explosive 4.4 Scrambler',
    attributes: { passing: 78, rushing: 94, passBlocking: 0, runBlocking: 0, athleticism: 94, footballIQ: 76 },
    highlightStat: '96 Open-Field QB Scramble Breakaways',
  },
  {
    id: 'rb-harris-najee',
    name: 'Najee Harris',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'RB',
    ovr: 84,
    salary: 2,
    archetype: 'Relentless Bellcow Bruiser',
    attributes: { passing: 0, rushing: 86, receiving: 78, passBlocking: 83, runBlocking: 0, athleticism: 82, footballIQ: 86 },
    highlightStat: '92 Consecutive 1,000-Yard Tough Runs & Stiff Arms',
  },
  {
    id: 'rb-warren-jaylen',
    name: 'Jaylen Warren',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'RB',
    ovr: 83,
    salary: 1,
    archetype: 'Bowling Ball Contact Engine',
    attributes: { passing: 0, rushing: 85, receiving: 84, passBlocking: 86, runBlocking: 0, athleticism: 88, footballIQ: 84 },
    highlightStat: '93 Pass Protection Blitz Decapitations & Burst',
  },
  {
    id: 'wr-pickens',
    name: 'George Pickens',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'WR',
    ovr: 86,
    salary: 1,
    archetype: 'Circus Catch Machine / Boundary Freak',
    attributes: { passing: 0, rushing: 0, receiving: 90, passBlocking: 0, runBlocking: 78, athleticism: 91, footballIQ: 85 },
    highlightStat: '97 Absurd Contested Catch & Toe-Tap Artistry',
  },
  {
    id: 'wr-austin-calvin',
    name: 'Calvin Austin III',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'WR',
    ovr: 78,
    salary: 1,
    archetype: '4.32 Speed Slot Weapon',
    attributes: { passing: 0, rushing: 75, receiving: 80, passBlocking: 0, runBlocking: 52, athleticism: 95, footballIQ: 79 },
    highlightStat: '96 Deep Separation & Punt Return Speed',
  },
  {
    id: 'te-freiermuth',
    name: 'Pat Freiermuth',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'TE',
    ovr: 84,
    salary: 12,
    archetype: 'Muth Red-Zone Chain-Mover',
    attributes: { passing: 0, rushing: 0, receiving: 86, passBlocking: 74, runBlocking: 79, athleticism: 81, footballIQ: 88 },
    highlightStat: '90 Over-the-Middle 3rd Down Catch Radius',
  },
  {
    id: 'ot-jones-broderick',
    name: 'Broderick Jones',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'OT',
    ovr: 79,
    salary: 3,
    archetype: 'Athletic First-Round Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 79, runBlocking: 83, athleticism: 87, footballIQ: 78 },
    highlightStat: '88 Space Mobility on Pulls and Screens',
  },
  {
    id: 'ot-moore-dan',
    name: 'Dan Moore Jr.',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'OT',
    ovr: 78,
    salary: 3,
    archetype: 'Experienced Blindside Fighter',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 79, athleticism: 77, footballIQ: 81 },
    highlightStat: '82 Pass Set Battle vs EDGE Rushers',
  },
  {
    id: 'c-frazier-zach',
    name: 'Zach Frazier',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'C',
    ovr: 81,
    salary: 2,
    archetype: 'State Champion Wrestler Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 87, athleticism: 79, footballIQ: 84 },
    highlightStat: '90 Leverage Control & Run Finishing Drive',
  },
  {
    id: 'og-seumalo',
    name: 'Isaac Seumalo',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'OG',
    ovr: 83,
    salary: 8,
    archetype: 'Flawless Technique Interior Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 87, runBlocking: 84, athleticism: 76, footballIQ: 91 },
    highlightStat: '89 Zero-Sack Interior Pass Protection',
  },
  {
    id: 'edge-watt',
    name: 'T.J. Watt',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'EDGE',
    ovr: 97,
    salary: 28,
    archetype: 'Game-Wrecking Strip-Sack Force (Madden 97)',
    attributes: { passRush: 98, runDefense: 93, coverage: 78, athleticism: 90, footballIQ: 99 },
    highlightStat: '99 Game-Ending Strip-Sacks & Passing Lane Swats',
  },
  {
    id: 'edge-highsmith',
    name: 'Alex Highsmith',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'EDGE',
    ovr: 87,
    salary: 17,
    archetype: 'Elite Spin-Move Pressure Specialist',
    attributes: { passRush: 90, runDefense: 84, coverage: 72, athleticism: 86, footballIQ: 88 },
    highlightStat: '93 Deadly Inside Spin Move & Forced Fumbles',
  },
  {
    id: 'dt-heyward',
    name: 'Cameron Heyward',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'DT',
    ovr: 91,
    salary: 15,
    archetype: 'Ironhead Trench Destroyer',
    attributes: { passRush: 89, runDefense: 95, coverage: 50, athleticism: 77, footballIQ: 97 },
    highlightStat: '97 Bull Rush Power & Unmovable 5-Tech Anchor',
  },
  {
    id: 'dt-benton',
    name: 'Keeanu Benton',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'DT',
    ovr: 82,
    salary: 2,
    archetype: 'Club-Swim Interior Monster',
    attributes: { passRush: 84, runDefense: 85, coverage: 50, athleticism: 81, footballIQ: 82 },
    highlightStat: '88 Club-Swim Move & A-Gap Disruption',
  },
  {
    id: 'lb-queen',
    name: 'Patrick Queen',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'LB',
    ovr: 86,
    salary: 14,
    archetype: 'Three-Down Speed Linebacker',
    attributes: { passRush: 82, runDefense: 87, coverage: 86, athleticism: 91, footballIQ: 88 },
    highlightStat: '92 Sideline-to-Sideline Speed & Blitz Burst',
  },
  {
    id: 'cb-porter',
    name: 'Joey Porter Jr.',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'CB',
    ovr: 85,
    salary: 2,
    archetype: 'Long-Arm Press-Man Shadow',
    attributes: { passRush: 0, runDefense: 76, coverage: 89, athleticism: 90, footballIQ: 85 },
    highlightStat: '94 Physical Press at Line & Shadowing WR1s',
  },
  {
    id: 's-fitzpatrick',
    name: 'Minkah Fitzpatrick',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'S',
    ovr: 93,
    salary: 18,
    archetype: 'All-Pro Centerfield Ballhawk',
    attributes: { passRush: 65, runDefense: 87, coverage: 95, athleticism: 91, footballIQ: 97 },
    highlightStat: '97 Deep-Zone Anticipation & Pick-Six Returns',
  },
  {
    id: 's-elliott-deshon',
    name: 'DeShon Elliott',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'S',
    ovr: 83,
    salary: 3,
    archetype: 'Punishing Box Safety',
    attributes: { passRush: 74, runDefense: 88, coverage: 82, athleticism: 84, footballIQ: 86 },
    highlightStat: '90 Enforcer Hits in the Run Alley',
  },
  // --- AFC North Kickers & Special Teams ---
  {
    id: 'k-tucker-justin',
    name: 'Justin Tucker',
    team: 'BAL',
    teamCity: 'Baltimore',
    position: 'K',
    ovr: 93,
    salary: 6,
    starter: true,
    archetype: 'Greatest of All Time Clutch Kicker',
    attributes: { passing: 0, rushing: 0, kicking: 98, athleticism: 78, footballIQ: 99 },
    highlightStat: '66-Yard NFL Record Long & 98% Clutch Field Goal Execution',
  },
  {
    id: 'k-mcpherson-evan',
    name: 'Evan McPherson',
    team: 'CIN',
    teamCity: 'Cincinnati',
    position: 'K',
    ovr: 85,
    salary: 4,
    starter: true,
    archetype: 'Money Mac Playoff Assassin',
    attributes: { passing: 0, rushing: 0, kicking: 89, athleticism: 77, footballIQ: 88 },
    highlightStat: 'Perfect Postseason Walk-Off Game Winners',
  },
  {
    id: 'k-hopkins-dustin',
    name: 'Dustin Hopkins',
    team: 'CLE',
    teamCity: 'Cleveland',
    position: 'K',
    ovr: 83,
    salary: 3,
    starter: true,
    archetype: '50+ Yard Accuracy Specialist',
    attributes: { passing: 0, rushing: 0, kicking: 87, athleticism: 75, footballIQ: 85 },
    highlightStat: '8-for-8 from 50+ Yards in Single Season',
  },
  {
    id: 'k-boswell-chris',
    name: 'Chris Boswell',
    team: 'PIT',
    teamCity: 'Pittsburgh',
    position: 'K',
    ovr: 89,
    salary: 5,
    starter: true,
    archetype: 'Wizard of Boz Clutch Sniper',
    attributes: { passing: 0, rushing: 0, kicking: 93, athleticism: 76, footballIQ: 92 },
    highlightStat: '6-for-6 Single Game Mastery & Acrisure Wind Control',
  },
];
