import { Player } from '../../types';

export const AFC_SOUTH_PLAYERS: Player[] = [
  // ===================== HOUSTON TEXANS (HOU) =====================
  {
    id: 'qb-stroud',
    name: 'C.J. Stroud',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'QB',
    ovr: 89,
    salary: 9,
    starter: true,
    archetype: 'Poised Pocket Surgeon',
    attributes: { passing: 93, rushing: 75, passBlocking: 0, runBlocking: 0, athleticism: 83, footballIQ: 92 },
    highlightStat: '95 Deep Boundary Touch & Ice-in-Veins 2-Minute Drill',
  },
  {
    id: 'qb-mills',
    name: 'Davis Mills',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'QB',
    ovr: 74,
    salary: 2,
    starter: false,
    archetype: 'Pocket Passing Backup',
    attributes: { passing: 77, rushing: 60, passBlocking: 0, runBlocking: 0, athleticism: 66, footballIQ: 82 },
    highlightStat: '82 Intermediate Accuracy & Timing',
  },
  {
    id: 'rb-mixon',
    name: 'Joe Mixon',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'RB',
    ovr: 87,
    salary: 8,
    archetype: 'Complete Bellcow / Jump-Cut Specialist',
    attributes: { passing: 0, rushing: 89, receiving: 82, passBlocking: 80, runBlocking: 0, athleticism: 87, footballIQ: 88 },
    highlightStat: '92 Inside Zone Vision & Red-Zone Finishing',
  },
  {
    id: 'wr-collins',
    name: 'Nico Collins',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'WR',
    ovr: 92,
    salary: 24,
    archetype: 'Dominant X-Receiver Alpha',
    attributes: { passing: 0, rushing: 0, receiving: 94, passBlocking: 0, runBlocking: 75, athleticism: 92, footballIQ: 91 },
    highlightStat: '96 Yards Per Route Run & Physical Box-Outs',
  },
  {
    id: 'wr-diggs',
    name: 'Stefon Diggs',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'WR',
    ovr: 90,
    salary: 22,
    archetype: 'Master Route Craftsman',
    attributes: { passing: 0, rushing: 0, receiving: 93, passBlocking: 0, runBlocking: 60, athleticism: 88, footballIQ: 96 },
    highlightStat: '96 Sudden In-and-Out Route Break Snaps',
  },
  {
    id: 'wr-dell',
    name: 'Tank Dell',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'WR',
    ovr: 84,
    salary: 1,
    archetype: 'Uncoverable Space Explorer',
    attributes: { passing: 0, rushing: 0, receiving: 86, passBlocking: 0, runBlocking: 45, athleticism: 94, footballIQ: 85 },
    highlightStat: '95 Ankle-Breaker Double Moves & Deep Over Separation',
  },
  {
    id: 'te-schultz',
    name: 'Dalton Schultz',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'TE',
    ovr: 83,
    salary: 12,
    archetype: 'Chain-Moving Security Blanket',
    attributes: { passing: 0, rushing: 0, receiving: 85, passBlocking: 72, runBlocking: 76, athleticism: 79, footballIQ: 87 },
    highlightStat: '88 3rd Down Catch Radius & Zone Settlement',
  },
  {
    id: 'ot-tunsil',
    name: 'Laremy Tunsil',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'OT',
    ovr: 92,
    salary: 25,
    archetype: 'Premier Pass Protection Fortress',
    attributes: { passing: 0, rushing: 0, passBlocking: 97, runBlocking: 84, athleticism: 83, footballIQ: 94 },
    highlightStat: '98 Lowest Pressure Rate in NFL on True Pass Sets',
  },
  {
    id: 'og-mason',
    name: 'Shaq Mason',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'OG',
    ovr: 81,
    salary: 12,
    archetype: 'Stout Veteran Power Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 84, athleticism: 77, footballIQ: 89 },
    highlightStat: '87 Anchor vs Power Defensive Tackles',
  },
  {
    id: 'c-scruggs',
    name: 'Juice Scruggs',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'C',
    ovr: 77,
    salary: 1,
    archetype: 'Agile Center / Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 79, athleticism: 81, footballIQ: 79 },
    highlightStat: '82 Second-Level Reach Blocking',
  },
  {
    id: 'edge-anderson',
    name: 'Will Anderson Jr.',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'EDGE',
    ovr: 89,
    salary: 9,
    archetype: 'Relentless High-Motor Edge Smasher',
    attributes: { passRush: 91, runDefense: 93, coverage: 65, athleticism: 91, footballIQ: 90 },
    highlightStat: '95 Run TFLs & Relentless Closing Speed to QB',
  },
  {
    id: 'edge-hunter',
    name: 'Danielle Hunter',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'EDGE',
    ovr: 91,
    salary: 25,
    archetype: 'Long-Arm Speed-to-Power Terminator',
    attributes: { passRush: 93, runDefense: 87, coverage: 66, athleticism: 91, footballIQ: 91 },
    highlightStat: '96 Long-Arm Stab & Double-Digit Annual Sacks',
  },
  {
    id: 'dt-fatukasi',
    name: 'Foley Fatukasi',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'DT',
    ovr: 80,
    salary: 5,
    archetype: 'Run-Stuffer Nose Tackle',
    attributes: { passRush: 72, runDefense: 88, coverage: 35, athleticism: 68, footballIQ: 82 },
    highlightStat: '90 A-Gap Run Stoning',
  },
  {
    id: 'lb-al-shaair',
    name: 'Azeez Al-Shaair',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'LB',
    ovr: 84,
    salary: 11,
    archetype: 'Violent Demeco Enforcer',
    attributes: { passRush: 81, runDefense: 89, coverage: 81, athleticism: 87, footballIQ: 88 },
    highlightStat: '92 Gap Decapitations & Punishing Tackles',
  },
  {
    id: 'cb-stingley',
    name: 'Derek Stingley Jr.',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'CB',
    ovr: 91,
    salary: 9,
    archetype: 'All-Pro Island Lockdown / Ballhawk',
    attributes: { passRush: 0, runDefense: 78, coverage: 95, athleticism: 94, footballIQ: 92 },
    highlightStat: '97 Hip Fluidity & High-Point Interceptions',
  },
  {
    id: 'cb-lassiter',
    name: 'Kamari Lassiter',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'CB',
    ovr: 79,
    salary: 2,
    archetype: 'Gritty Boundary Press-Cover',
    attributes: { passRush: 0, runDefense: 83, coverage: 82, athleticism: 88, footballIQ: 82 },
    highlightStat: '87 Physical Perimeter Run Support & Tackling',
  },
  {
    id: 's-pitre',
    name: 'Jalen Pitre',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'S',
    ovr: 82,
    salary: 2,
    archetype: 'Hybrid Star/Slot Enforcer',
    attributes: { passRush: 78, runDefense: 86, coverage: 82, athleticism: 87, footballIQ: 84 },
    highlightStat: '89 Slot Blitzing & Disguised Robber Schemes',
  },
  {
    id: 's-bullock-calen',
    name: 'Calen Bullock',
    team: 'HOU',
    teamCity: 'Houston',
    position: 'S',
    ovr: 79,
    salary: 1,
    archetype: 'Centerfield Range Ballhawk',
    attributes: { passRush: 55, runDefense: 72, coverage: 87, athleticism: 91, footballIQ: 83 },
    highlightStat: '90 Over-the-Top Interception Range',
  },

  // ===================== INDIANAPOLIS COLTS (IND) =====================
  {
    id: 'qb-richardson',
    name: 'Anthony Richardson',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'QB',
    ovr: 82,
    salary: 8,
    starter: true,
    archetype: 'Physical Specimen / Dual-Threat Juggernaut',
    attributes: { passing: 83, rushing: 94, passBlocking: 0, runBlocking: 0, athleticism: 97, footballIQ: 78 },
    highlightStat: '99 Throw Power & 4.43 Speed at 245 lbs',
  },
  {
    id: 'qb-flacco',
    name: 'Joe Flacco',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'QB',
    ovr: 76,
    salary: 4,
    starter: false,
    archetype: 'Veteran Cannon-Arm Pocket Passer',
    attributes: { passing: 82, rushing: 55, passBlocking: 0, runBlocking: 0, athleticism: 58, footballIQ: 91 },
    highlightStat: '91 Deep Post Velocity & Veteran Pocket Poise',
  },
  {
    id: 'rb-taylor-jonathan',
    name: 'Jonathan Taylor',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'RB',
    ovr: 91,
    salary: 14,
    archetype: 'Generational Power & Breakaway Engine',
    attributes: { passing: 0, rushing: 94, receiving: 78, passBlocking: 80, runBlocking: 0, athleticism: 94, footballIQ: 92 },
    highlightStat: '96 Second-Gear Speed Burst & Between-Tackles Power',
  },
  {
    id: 'wr-pittman',
    name: 'Michael Pittman Jr.',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'WR',
    ovr: 86,
    salary: 23,
    archetype: 'Physical Possession Alpha',
    attributes: { passing: 0, rushing: 0, receiving: 89, passBlocking: 0, runBlocking: 76, athleticism: 84, footballIQ: 89 },
    highlightStat: '93 Contested Slants Through Contact',
  },
  {
    id: 'wr-downs',
    name: 'Josh Downs',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'WR',
    ovr: 82,
    salary: 1,
    archetype: 'Electric Slot Separator',
    attributes: { passing: 0, rushing: 0, receiving: 85, passBlocking: 0, runBlocking: 50, athleticism: 92, footballIQ: 84 },
    highlightStat: '94 Option-Route Separation in Slot',
  },
  {
    id: 'wr-pierce-alec',
    name: 'Alec Pierce',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'WR',
    ovr: 79,
    salary: 2,
    archetype: 'Deep Ball Boundary Burner',
    attributes: { passing: 0, rushing: 0, receiving: 80, passBlocking: 0, runBlocking: 65, athleticism: 92, footballIQ: 79 },
    highlightStat: '94 Yards Per Target & Go-Route Tracking',
  },
  {
    id: 'te-granson',
    name: 'Kylen Granson',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'TE',
    ovr: 78,
    salary: 1,
    archetype: 'Move Tight End / Receiver',
    attributes: { passing: 0, rushing: 0, receiving: 81, passBlocking: 65, runBlocking: 70, athleticism: 85, footballIQ: 81 },
    highlightStat: '84 Over-the-Middle Seam Routing',
  },
  {
    id: 'te-alie-cox',
    name: 'Mo Alie-Cox',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'TE',
    ovr: 77,
    salary: 3,
    archetype: 'Red-Zone In-Line Blocker',
    attributes: { passing: 0, rushing: 0, receiving: 78, passBlocking: 78, runBlocking: 84, athleticism: 75, footballIQ: 83 },
    highlightStat: '88 Goal-Line End-Zone Box-Outs',
  },
  {
    id: 'ot-raimann',
    name: 'Bernhard Raimann',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'OT',
    ovr: 83,
    salary: 1,
    archetype: 'Athletic Blindside Protector',
    attributes: { passing: 0, rushing: 0, passBlocking: 86, runBlocking: 83, athleticism: 85, footballIQ: 84 },
    highlightStat: '88 Reach Block Mobility & Smooth Set Footwork',
  },
  {
    id: 'ot-smith-braden',
    name: 'Braden Smith',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'OT',
    ovr: 83,
    salary: 17,
    archetype: 'Powerful Right Edge Anchor',
    attributes: { passing: 0, rushing: 0, passBlocking: 83, runBlocking: 87, athleticism: 77, footballIQ: 87 },
    highlightStat: '90 Gap Scheme Drive-Block Power',
  },
  {
    id: 'og-nelson',
    name: 'Quenton Nelson',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'OG',
    ovr: 91,
    salary: 20,
    archetype: 'All-Pro Guard Legend',
    attributes: { passing: 0, rushing: 0, passBlocking: 92, runBlocking: 94, athleticism: 83, footballIQ: 96 },
    highlightStat: '97 Pancake Finishing & Interior Blitz Eradication',
  },
  {
    id: 'c-kelly-ryan',
    name: 'Ryan Kelly',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'C',
    ovr: 83,
    salary: 12,
    archetype: 'Veteran Anchor Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 84, runBlocking: 83, athleticism: 78, footballIQ: 92 },
    highlightStat: '90 Defensive ID & Front Recognition',
  },
  {
    id: 'edge-latu',
    name: 'Laiatu Latu',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'EDGE',
    ovr: 79,
    salary: 4,
    archetype: 'Master Technician Pass Rusher',
    attributes: { passRush: 85, runDefense: 77, coverage: 65, athleticism: 85, footballIQ: 86 },
    highlightStat: '91 Chop-Dip-Rip Move Combination',
  },
  {
    id: 'edge-paye',
    name: 'Kwity Paye',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'EDGE',
    ovr: 81,
    salary: 3,
    archetype: 'Explosive Edge Setter',
    attributes: { passRush: 82, runDefense: 86, coverage: 60, athleticism: 88, footballIQ: 82 },
    highlightStat: '88 Speed-to-Power Bull Rush',
  },
  {
    id: 'dt-buckner',
    name: 'DeForest Buckner',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'DT',
    ovr: 90,
    salary: 22,
    archetype: '6-Foot-7 Interior Game-Wrecker',
    attributes: { passRush: 92, runDefense: 91, coverage: 55, athleticism: 84, footballIQ: 95 },
    highlightStat: '96 Arm-Over Swim & Block Shedding',
  },
  {
    id: 'dt-stewart-grover',
    name: 'Grover Stewart',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'DT',
    ovr: 84,
    salary: 13,
    archetype: '1-Tech Immovable Mountain',
    attributes: { passRush: 72, runDefense: 95, coverage: 40, athleticism: 67, footballIQ: 88 },
    highlightStat: '97 Double-Team Eradication in Run Defense',
  },
  {
    id: 'lb-franklin-zaire',
    name: 'Zaire Franklin',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'LB',
    ovr: 84,
    salary: 10,
    archetype: 'Tackle Machine Leader',
    attributes: { passRush: 76, runDefense: 90, coverage: 80, athleticism: 83, footballIQ: 91 },
    highlightStat: '94 150+ Tackles Per Season Consistent Production',
  },
  {
    id: 'cb-moore-kenny',
    name: 'Kenny Moore II',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'CB',
    ovr: 86,
    salary: 10,
    archetype: 'Pro Bowl Nickel Cornerback',
    attributes: { passRush: 79, runDefense: 87, coverage: 88, athleticism: 87, footballIQ: 93 },
    highlightStat: '93 Slot Blitz Sacks & One-Handed Picks',
  },
  {
    id: 's-blackmon',
    name: 'Julian Blackmon',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'S',
    ovr: 82,
    salary: 4,
    archetype: 'Versatile Strong/Free Safety',
    attributes: { passRush: 70, runDefense: 83, coverage: 85, athleticism: 86, footballIQ: 87 },
    highlightStat: '88 Turnover Creation on Overturned Balls',
  },

  // ===================== JACKSONVILLE JAGUARS (JAX) =====================
  {
    id: 'qb-lawrence',
    name: 'Trevor Lawrence',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'QB',
    ovr: 86,
    salary: 55,
    starter: true,
    archetype: 'Franchise Prototype Passer',
    attributes: { passing: 89, rushing: 82, passBlocking: 0, runBlocking: 0, athleticism: 86, footballIQ: 88 },
    highlightStat: '92 Pocket Mobility & Tight-Window Seam Throws',
  },
  {
    id: 'qb-jones-mac',
    name: 'Mac Jones',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'QB',
    ovr: 77,
    salary: 3,
    starter: false,
    archetype: 'Accurate System Operator Backup',
    attributes: { passing: 81, rushing: 66, passBlocking: 0, runBlocking: 0, athleticism: 70, footballIQ: 84 },
    highlightStat: '86 Quick Slant Timing & Ball Distribution',
  },
  {
    id: 'rb-etienne',
    name: 'Travis Etienne Jr.',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'RB',
    ovr: 87,
    salary: 3,
    archetype: 'Explosive Jump-Cut Weapon',
    attributes: { passing: 0, rushing: 89, receiving: 85, passBlocking: 73, runBlocking: 0, athleticism: 93, footballIQ: 86 },
    highlightStat: '95 Acceleration & Broken Tackles on Edge',
  },
  {
    id: 'rb-bigsby',
    name: 'Tank Bigsby',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'RB',
    ovr: 81,
    salary: 1,
    archetype: 'Violent North-South Runner',
    attributes: { passing: 0, rushing: 85, receiving: 70, passBlocking: 75, runBlocking: 0, athleticism: 87, footballIQ: 80 },
    highlightStat: '89 Yards After Contact Between the Tackles',
  },
  {
    id: 'wr-thomas-brian',
    name: 'Brian Thomas Jr.',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'WR',
    ovr: 84,
    salary: 3,
    archetype: '4.33 Deep-Shot Alpha',
    attributes: { passing: 0, rushing: 0, receiving: 87, passBlocking: 0, runBlocking: 62, athleticism: 95, footballIQ: 84 },
    highlightStat: '96 Vertical Separation & Stride Length',
  },
  {
    id: 'wr-kirk',
    name: 'Christian Kirk',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'WR',
    ovr: 83,
    salary: 18,
    archetype: 'Savvy Slot Separator',
    attributes: { passing: 0, rushing: 0, receiving: 86, passBlocking: 0, runBlocking: 55, athleticism: 89, footballIQ: 89 },
    highlightStat: '91 Intermediate Option Route Finding',
  },
  {
    id: 'te-engram',
    name: 'Evan Engram',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'TE',
    ovr: 87,
    salary: 14,
    archetype: '100-Catch Receiving Tight End',
    attributes: { passing: 0, rushing: 0, receiving: 91, passBlocking: 65, runBlocking: 71, athleticism: 91, footballIQ: 88 },
    highlightStat: '93 Short-Area Target Funnel & YAC',
  },
  {
    id: 'ot-robinson-cam',
    name: 'Cam Robinson',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'OT',
    ovr: 81,
    salary: 16,
    archetype: 'Physical Blindside Blocker',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 84, athleticism: 76, footballIQ: 85 },
    highlightStat: '87 Down-Block Punch & Anchor',
  },
  {
    id: 'ot-harrison-anton',
    name: 'Anton Harrison',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'OT',
    ovr: 80,
    salary: 2,
    archetype: 'Young Pass Protection RT',
    attributes: { passing: 0, rushing: 0, passBlocking: 83, runBlocking: 79, athleticism: 82, footballIQ: 81 },
    highlightStat: '86 Quick Pass Set vs Speed Rush',
  },
  {
    id: 'og-scherff',
    name: 'Brandon Scherff',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'OG',
    ovr: 82,
    salary: 15,
    archetype: 'All-Pro Veteran Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 84, runBlocking: 85, athleticism: 75, footballIQ: 92 },
    highlightStat: '89 Interior Punch & Pulling Balance',
  },
  {
    id: 'og-cleveland-ezra',
    name: 'Ezra Cleveland',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'OG',
    ovr: 79,
    salary: 7,
    archetype: 'Athletic Zone Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 81, athleticism: 84, footballIQ: 80 },
    highlightStat: '86 Zone Reach & Screen Blocking',
  },
  {
    id: 'c-morse',
    name: 'Mitch Morse',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'C',
    ovr: 82,
    salary: 5,
    archetype: 'Veteran Pass-Blocking Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 86, runBlocking: 79, athleticism: 77, footballIQ: 93 },
    highlightStat: '92 Blitz Pickup & Front Communication',
  },
  {
    id: 'edge-hines-allen',
    name: 'Josh Hines-Allen',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'EDGE',
    ovr: 91,
    salary: 28,
    archetype: 'Elite Speed-Power Edge Dominator',
    attributes: { passRush: 94, runDefense: 89, coverage: 71, athleticism: 91, footballIQ: 91 },
    highlightStat: '96 Ghost Move, Strip Sacks & Relentless Bend',
  },
  {
    id: 'edge-walker-travon',
    name: 'Travon Walker',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'EDGE',
    ovr: 83,
    salary: 9,
    archetype: 'Freak Bull-Rush Power Edge',
    attributes: { passRush: 84, runDefense: 89, coverage: 65, athleticism: 92, footballIQ: 81 },
    highlightStat: '93 Raw Core Power at Point of Attack',
  },
  {
    id: 'dt-armstead-arik',
    name: 'Arik Armstead',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'DT',
    ovr: 84,
    salary: 14,
    archetype: 'Long Interior/Edge Disruptor',
    attributes: { passRush: 86, runDefense: 87, coverage: 50, athleticism: 79, footballIQ: 89 },
    highlightStat: '90 Pocket Collapse on Passing Downs',
  },
  {
    id: 'dt-hamilton-davon',
    name: 'DaVon Hamilton',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'DT',
    ovr: 80,
    salary: 11,
    archetype: '0-Tech Run Plugger',
    attributes: { passRush: 73, runDefense: 89, coverage: 35, athleticism: 68, footballIQ: 82 },
    highlightStat: '92 Double-Team Anchor in Run Fits',
  },
  {
    id: 'lb-oluokun',
    name: 'Foyesade Oluokun',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'LB',
    ovr: 87,
    salary: 11,
    archetype: 'NFL Leading Tackler Machine',
    attributes: { passRush: 79, runDefense: 92, coverage: 86, athleticism: 87, footballIQ: 94 },
    highlightStat: '96 Diagnostic Speed & 170+ Annual Tackles',
  },
  {
    id: 'cb-campbell-tyson',
    name: 'Tyson Campbell',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'CB',
    ovr: 86,
    salary: 19,
    archetype: 'Speed Press-Man Lockdown',
    attributes: { passRush: 0, runDefense: 80, coverage: 89, athleticism: 94, footballIQ: 86 },
    highlightStat: '93 Hip Fluidity on Boundary Go-Routes',
  },
  {
    id: 's-cisco',
    name: 'Andre Cisco',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'S',
    ovr: 82,
    salary: 1,
    archetype: 'Deep Ballhawk Free Safety',
    attributes: { passRush: 60, runDefense: 79, coverage: 86, athleticism: 89, footballIQ: 84 },
    highlightStat: '90 Break-on-Ball Speed & Range',
  },

  // ===================== TENNESSEE TITANS (TEN) =====================
  {
    id: 'qb-levis',
    name: 'Will Levis',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'QB',
    ovr: 78,
    salary: 3,
    starter: true,
    archetype: 'Howitzer Arm Gunslinger',
    attributes: { passing: 83, rushing: 80, passBlocking: 0, runBlocking: 0, athleticism: 85, footballIQ: 76 },
    highlightStat: '96 Throw Power & Downfield Deep Shots',
  },
  {
    id: 'qb-rudolph-mason',
    name: 'Mason Rudolph',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'QB',
    ovr: 75,
    salary: 3,
    starter: false,
    archetype: 'Steady Veteran Pocket Backup',
    attributes: { passing: 78, rushing: 60, passBlocking: 0, runBlocking: 0, athleticism: 65, footballIQ: 83 },
    highlightStat: '84 Quick Out Delivery & Poised Pocket Presence',
  },
  {
    id: 'rb-pollard',
    name: 'Tony Pollard',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'RB',
    ovr: 85,
    salary: 7,
    archetype: 'Slashing Explosive Back',
    attributes: { passing: 0, rushing: 87, receiving: 83, passBlocking: 73, runBlocking: 0, athleticism: 91, footballIQ: 85 },
    highlightStat: '92 Acceleration on Stretch Plays & Screen Passes',
  },
  {
    id: 'rb-spears',
    name: 'Tyjae Spears',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'RB',
    ovr: 81,
    salary: 1,
    archetype: 'Shifty 3rd Down Weapon',
    attributes: { passing: 0, rushing: 82, receiving: 84, passBlocking: 70, runBlocking: 0, athleticism: 92, footballIQ: 80 },
    highlightStat: '93 Lateral Agility in Open Space',
  },
  {
    id: 'wr-ridley',
    name: 'Calvin Ridley',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'WR',
    ovr: 85,
    salary: 23,
    archetype: 'Elite Route Separator',
    attributes: { passing: 0, rushing: 0, receiving: 88, passBlocking: 0, runBlocking: 55, athleticism: 91, footballIQ: 89 },
    highlightStat: '94 Stop-and-Go Double Moves & Corner Routes',
  },
  {
    id: 'wr-westbrook-ikhine',
    name: 'Nick Westbrook-Ikhine',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'WR',
    ovr: 78,
    salary: 2,
    archetype: 'Big-Bodied Red Zone Target',
    attributes: { passing: 0, rushing: 0, receiving: 79, passBlocking: 0, runBlocking: 72, athleticism: 83, footballIQ: 82 },
    highlightStat: '88 End-Zone Touchdown Efficiency',
  },
  {
    id: 'wr-boyd-tyler',
    name: 'Tyler Boyd',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'WR',
    ovr: 80,
    salary: 4,
    archetype: 'Veteran Slot Anchor',
    attributes: { passing: 0, rushing: 0, receiving: 83, passBlocking: 0, runBlocking: 58, athleticism: 80, footballIQ: 88 },
    highlightStat: '89 3rd Down Middle Conversion Snag',
  },
  {
    id: 'te-okonkwo',
    name: 'Chigoziem Okonkwo',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'TE',
    ovr: 80,
    salary: 1,
    archetype: 'H-Back / Speed YAC Weapon',
    attributes: { passing: 0, rushing: 0, receiving: 82, passBlocking: 64, runBlocking: 72, athleticism: 90, footballIQ: 80 },
    highlightStat: '91 Speed After the Catch on Flats & Drags',
  },
  {
    id: 'ot-latham',
    name: 'JC Latham',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'OT',
    ovr: 79,
    salary: 6,
    archetype: 'Goliath Power Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 85, athleticism: 79, footballIQ: 78 },
    highlightStat: '92 Anchor Power vs Power Edge Rushers',
  },
  {
    id: 'og-skoronski',
    name: 'Peter Skoronski',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'OG',
    ovr: 81,
    salary: 4,
    archetype: 'Technical Master Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 85, runBlocking: 82, athleticism: 81, footballIQ: 87 },
    highlightStat: '88 Hand Placement & Strike Precision',
  },
  {
    id: 'c-cushenberry',
    name: 'Lloyd Cushenberry III',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'C',
    ovr: 83,
    salary: 12,
    archetype: 'Pass Pro Brick Wall Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 88, runBlocking: 80, athleticism: 77, footballIQ: 88 },
    highlightStat: '91 A-Gap Pass Protection Anchor',
  },
  {
    id: 'edge-landry',
    name: 'Harold Landry III',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'EDGE',
    ovr: 84,
    salary: 17,
    archetype: 'Bending Speed Rusher',
    attributes: { passRush: 87, runDefense: 82, coverage: 70, athleticism: 87, footballIQ: 86 },
    highlightStat: '90 Outside Edge Bend & QB Strip Sacks',
  },
  {
    id: 'dt-simmons-jeffery',
    name: 'Jeffery Simmons',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'DT',
    ovr: 92,
    salary: 23,
    archetype: 'All-Pro Interior Destroyer',
    attributes: { passRush: 93, runDefense: 95, coverage: 50, athleticism: 85, footballIQ: 93 },
    highlightStat: '97 Bull Rush Shockwave & 2-Gap Dominance',
  },
  {
    id: 'dt-sweat-tvondre',
    name: 'T\'Vondre Sweat',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'DT',
    ovr: 80,
    salary: 2,
    archetype: '366-Pound Black Hole Nose',
    attributes: { passRush: 73, runDefense: 94, coverage: 35, athleticism: 65, footballIQ: 80 },
    highlightStat: '98 Center Displacement & Run Wall Collapse',
  },
  {
    id: 'lb-murray-kenneth',
    name: 'Kenneth Murray Jr.',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'LB',
    ovr: 80,
    salary: 8,
    archetype: 'Downhill Speed Thumper',
    attributes: { passRush: 78, runDefense: 84, coverage: 78, athleticism: 88, footballIQ: 81 },
    highlightStat: '87 B-Gap Blitz Explosion',
  },
  {
    id: 'lb-jones-ernest',
    name: 'Ernest Jones IV',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'LB',
    ovr: 83,
    salary: 3,
    archetype: 'Physical Inside Run Stopper',
    attributes: { passRush: 80, runDefense: 88, coverage: 80, athleticism: 83, footballIQ: 86 },
    highlightStat: '91 Between-the-Tackles Run Stops',
  },
  {
    id: 'cb-sneed',
    name: 'L\'Jarius Sneed',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'CB',
    ovr: 91,
    salary: 19,
    archetype: 'Physical Press / WR1 Eraser',
    attributes: { passRush: 82, runDefense: 88, coverage: 93, athleticism: 91, footballIQ: 94 },
    highlightStat: '96 Line-of-Scrimmage Press & Punch-Out Turnovers',
  },
  {
    id: 'cb-mccreary',
    name: 'Roger McCreary',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'CB',
    ovr: 81,
    salary: 2,
    archetype: 'Feisty Slot In-Phase Corner',
    attributes: { passRush: 70, runDefense: 82, coverage: 84, athleticism: 87, footballIQ: 85 },
    highlightStat: '88 Quick Trigger on Slot Bubbles & Digs',
  },
  {
    id: 's-hooker-amani',
    name: 'Amani Hooker',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'S',
    ovr: 84,
    salary: 10,
    archetype: 'Robber / Coverage Safety',
    attributes: { passRush: 65, runDefense: 83, coverage: 87, athleticism: 86, footballIQ: 89 },
    highlightStat: '89 In-Breaking Pass Defenses & Tackling',
  },
  // --- AFC South Kickers & Special Teams ---
  {
    id: 'k-fairbairn-kaimi',
    name: "Ka'imi Fairbairn",
    team: 'HOU',
    teamCity: 'Houston',
    position: 'K',
    ovr: 86,
    salary: 4,
    starter: true,
    archetype: 'Long-Distance Bomb Specialist',
    attributes: { passing: 0, rushing: 0, kicking: 90, athleticism: 75, footballIQ: 88 },
    highlightStat: 'Multiple 50+ Yard FGs in a Single Game NFL Leader',
  },
  {
    id: 'k-gay-matt',
    name: 'Matt Gay',
    team: 'IND',
    teamCity: 'Indianapolis',
    position: 'K',
    ovr: 82,
    salary: 4,
    starter: true,
    archetype: 'High-Elevation Power Kicker',
    attributes: { passing: 0, rushing: 0, kicking: 86, athleticism: 74, footballIQ: 84 },
    highlightStat: 'Four 50+ Yarders in One Game NFL History Maker',
  },
  {
    id: 'k-little-cam',
    name: 'Cam Little',
    team: 'JAX',
    teamCity: 'Jacksonville',
    position: 'K',
    ovr: 80,
    salary: 2,
    starter: true,
    archetype: 'Clutch Young Specialist',
    attributes: { passing: 0, rushing: 0, kicking: 84, athleticism: 77, footballIQ: 82 },
    highlightStat: '90% Kickoff Touchbacks & Smooth Flight Arc',
  },
  {
    id: 'k-folk-nick',
    name: 'Nick Folk',
    team: 'TEN',
    teamCity: 'Tennessee',
    position: 'K',
    ovr: 82,
    salary: 2,
    starter: true,
    archetype: 'Old-School Automatic Inside 40',
    attributes: { passing: 0, rushing: 0, kicking: 86, athleticism: 70, footballIQ: 96 },
    highlightStat: '70+ Consecutive FGs Made Inside 40 Yards',
  },
];
