import { Player } from '../../types';

export const AFC_WEST_PLAYERS: Player[] = [
  // ===================== DENVER BRONCOS (DEN) =====================
  {
    id: 'qb-nix',
    name: 'Bo Nix',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'QB',
    ovr: 81,
    salary: 4,
    starter: true,
    archetype: 'Quick-Processing Rhythm Passer',
    attributes: { passing: 85, rushing: 82, passBlocking: 0, runBlocking: 0, athleticism: 85, footballIQ: 86 },
    highlightStat: '90 Short Throw Accuracy & Scramble First Downs',
  },
  {
    id: 'qb-stidham',
    name: 'Jarrett Stidham',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'QB',
    ovr: 72,
    salary: 5,
    starter: false,
    archetype: 'Pocket Passing Backup',
    attributes: { passing: 75, rushing: 68, passBlocking: 0, runBlocking: 0, athleticism: 74, footballIQ: 79 },
    highlightStat: '82 Intermediate Play-Action Throws',
  },
  {
    id: 'rb-williams-javonte',
    name: 'Javonte Williams',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'RB',
    ovr: 80,
    salary: 2,
    archetype: 'Tackle-Breaking Power Back',
    attributes: { passing: 0, rushing: 84, receiving: 74, passBlocking: 79, runBlocking: 0, athleticism: 82, footballIQ: 83 },
    highlightStat: '89 Broken Tackle Rate & Contact Balance',
  },
  {
    id: 'wr-sutton',
    name: 'Courtland Sutton',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'WR',
    ovr: 84,
    salary: 15,
    archetype: 'Toe-Tap Boundary Contested Master',
    attributes: { passing: 0, rushing: 0, receiving: 88, passBlocking: 0, runBlocking: 72, athleticism: 84, footballIQ: 87 },
    highlightStat: '95 End-Zone Corner Fade & Toe-Drag Catches',
  },
  {
    id: 'te-trautman',
    name: 'Adam Trautman',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'TE',
    ovr: 77,
    salary: 3,
    archetype: 'In-Line Blocking Tight End',
    attributes: { passing: 0, rushing: 0, receiving: 76, passBlocking: 78, runBlocking: 84, athleticism: 75, footballIQ: 82 },
    highlightStat: '86 Point of Attack Run Sealing',
  },
  {
    id: 'ot-bolles',
    name: 'Garett Bolles',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'OT',
    ovr: 83,
    salary: 17,
    archetype: 'Athletic Blindside Protector',
    attributes: { passing: 0, rushing: 0, passBlocking: 86, runBlocking: 82, athleticism: 82, footballIQ: 85 },
    highlightStat: '88 Kick-Slide Set vs Speed Rush',
  },
  {
    id: 'og-meinerz',
    name: 'Quinn Meinerz',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'OG',
    ovr: 87,
    salary: 18,
    archetype: 'The Belly / Violent Pulling Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 86, runBlocking: 93, athleticism: 85, footballIQ: 89 },
    highlightStat: '96 Space Pulling Pancake Blocks & Core Torque',
  },
  {
    id: 'og-powers-ben',
    name: 'Ben Powers',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'OG',
    ovr: 81,
    salary: 13,
    archetype: 'Power Scheme Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 84, runBlocking: 81, athleticism: 76, footballIQ: 86 },
    highlightStat: '87 Pass Protection Anchor vs Power Tackles',
  },
  {
    id: 'c-wattenberg',
    name: 'Luke Wattenberg',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'C',
    ovr: 78,
    salary: 1,
    archetype: 'Zoneway Mobile Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 79, runBlocking: 80, athleticism: 80, footballIQ: 82 },
    highlightStat: '84 Reach Blocks & Snap Timing',
  },
  {
    id: 'edge-bonitto',
    name: 'Nik Bonitto',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'EDGE',
    ovr: 83,
    salary: 1,
    archetype: 'Lightning Speed-Bender',
    attributes: { passRush: 87, runDefense: 74, coverage: 65, athleticism: 91, footballIQ: 82 },
    highlightStat: '92 First-Step Get-Off & Sack Conversion',
  },
  {
    id: 'edge-cooper-jonathon',
    name: 'Jonathon Cooper',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'EDGE',
    ovr: 82,
    salary: 13,
    archetype: 'Relentless High-Motor Rusher',
    attributes: { passRush: 84, runDefense: 85, coverage: 68, athleticism: 83, footballIQ: 85 },
    highlightStat: '88 Second-Effort Pursuit Sacks & Edge Setting',
  },
  {
    id: 'dt-allen-zach',
    name: 'Zach Allen',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'DT',
    ovr: 86,
    salary: 15,
    archetype: 'High-Pressure 3-Tech Disruptor',
    attributes: { passRush: 89, runDefense: 87, coverage: 55, athleticism: 82, footballIQ: 89 },
    highlightStat: '92 Interior QB Pressures & Batting Passes',
  },
  {
    id: 'dt-jones-dj',
    name: 'D.J. Jones',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'DT',
    ovr: 82,
    salary: 10,
    archetype: 'Low-Pad 0-Tech Run Wall',
    attributes: { passRush: 74, runDefense: 89, coverage: 35, athleticism: 73, footballIQ: 84 },
    highlightStat: '91 Gap Stacking & Run Fitting',
  },
  {
    id: 'lb-singleton',
    name: 'Alex Singleton',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'LB',
    ovr: 82,
    salary: 6,
    archetype: 'Downhill Flow Tackler',
    attributes: { passRush: 74, runDefense: 89, coverage: 78, athleticism: 81, footballIQ: 87 },
    highlightStat: '91 Double-Digit Tackles Per Game Engine',
  },
  {
    id: 'cb-surtain',
    name: 'Patrick Surtain II',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'CB',
    ovr: 97,
    salary: 24,
    archetype: 'Defensive MVP Candidate / Pure Shadow (Madden 97)',
    attributes: { passRush: 0, runDefense: 84, coverage: 99, athleticism: 95, footballIQ: 98 },
    highlightStat: '99 Pure Route Mirroring, Press Disruption & Zero TD Allowed',
  },
  {
    id: 'cb-moss-riley',
    name: 'Riley Moss',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'CB',
    ovr: 80,
    salary: 1,
    archetype: 'Speed Boundary Corner',
    attributes: { passRush: 0, runDefense: 79, coverage: 82, athleticism: 91, footballIQ: 83 },
    highlightStat: '87 Break on the Football & Open Field Tackling',
  },
  {
    id: 's-jones-brandon',
    name: 'Brandon Jones',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'S',
    ovr: 81,
    salary: 6,
    archetype: 'Downhill Blitzing Safety',
    attributes: { passRush: 82, runDefense: 84, coverage: 81, athleticism: 88, footballIQ: 84 },
    highlightStat: '88 Safety Blitz Timing & Interceptions',
  },

  // ===================== KANSAS CITY CHIEFS (KC) =====================
  {
    id: 'qb-mahomes',
    name: 'Patrick Mahomes',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'QB',
    ovr: 99,
    salary: 45,
    starter: true,
    archetype: '3x Super Bowl Champion / Magic Maker (Madden 99 Club)',
    attributes: { passing: 99, rushing: 88, passBlocking: 0, runBlocking: 0, athleticism: 90, footballIQ: 99 },
    highlightStat: '99 Throw on the Run, No-Look Touchdowns & Clutch Factor',
  },
  {
    id: 'qb-wentz',
    name: 'Carson Wentz',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'QB',
    ovr: 75,
    salary: 2,
    starter: false,
    archetype: 'Big-Arm Experienced Backup',
    attributes: { passing: 78, rushing: 74, passBlocking: 0, runBlocking: 0, athleticism: 77, footballIQ: 78 },
    highlightStat: '88 Downfield Throw Velocity',
  },
  {
    id: 'rb-pacheco',
    name: 'Isiah Pacheco',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'RB',
    ovr: 86,
    salary: 1,
    archetype: 'Angry Ground-Punishing Runner',
    attributes: { passing: 0, rushing: 90, receiving: 78, passBlocking: 82, runBlocking: 0, athleticism: 93, footballIQ: 85 },
    highlightStat: '96 Pure Running Ferocity, 4.37 Speed & Stiff Arm',
  },
  {
    id: 'rb-hunt-kareem',
    name: 'Kareem Hunt',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'RB',
    ovr: 80,
    salary: 1,
    archetype: 'Short-Yardage Clutch Bruiser',
    attributes: { passing: 0, rushing: 83, receiving: 78, passBlocking: 84, runBlocking: 0, athleticism: 80, footballIQ: 86 },
    highlightStat: '89 3rd-and-1 & Goal-Line Conversion Consistency',
  },
  {
    id: 'wr-rice-rashee',
    name: 'Rashee Rice',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'WR',
    ovr: 86,
    salary: 1,
    archetype: 'YAC Monster / Slant Specialist',
    attributes: { passing: 0, rushing: 0, receiving: 89, passBlocking: 0, runBlocking: 68, athleticism: 90, footballIQ: 87 },
    highlightStat: '94 Yards After Catch on Shallow Crossing Routes',
  },
  {
    id: 'wr-worthy',
    name: 'Xavier Worthy',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'WR',
    ovr: 80,
    salary: 3,
    archetype: '4.21 Historic NFL Combine Speed',
    attributes: { passing: 0, rushing: 78, receiving: 82, passBlocking: 0, runBlocking: 45, athleticism: 99, footballIQ: 80 },
    highlightStat: '99 Speed & Jet Sweep / Deep Post Separation',
  },
  {
    id: 'wr-hopkins',
    name: 'DeAndre Hopkins',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'WR',
    ovr: 86,
    salary: 4,
    archetype: 'Legendary Hands & Catch Radius',
    attributes: { passing: 0, rushing: 0, receiving: 90, passBlocking: 0, runBlocking: 70, athleticism: 81, footballIQ: 96 },
    highlightStat: '98 Contested Catch & Sideline Boundary Taps',
  },
  {
    id: 'te-kelce',
    name: 'Travis Kelce',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'TE',
    ovr: 96,
    salary: 17,
    archetype: 'Hall of Fame Receiving TE & Playoff Legend',
    attributes: { passing: 0, rushing: 0, receiving: 97, passBlocking: 76, runBlocking: 82, athleticism: 86, footballIQ: 99 },
    highlightStat: '99 Zone Coverage Diagnosis & Unstoppable Playoff Chemistry',
  },
  {
    id: 'ot-taylor-jawaan',
    name: 'Jawaan Taylor',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'OT',
    ovr: 81,
    salary: 20,
    archetype: 'Quick-Kick Pass Set RT',
    attributes: { passing: 0, rushing: 0, passBlocking: 86, runBlocking: 78, athleticism: 83, footballIQ: 84 },
    highlightStat: '92 First-Move Get-Off in Pass Protection',
  },
  {
    id: 'ot-suamataia',
    name: 'Kingsley Suamataia',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'OT',
    ovr: 77,
    salary: 2,
    archetype: 'Athletic Power Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 82, athleticism: 85, footballIQ: 76 },
    highlightStat: '88 Space Screen Mobility & Strike',
  },
  {
    id: 'og-thuney',
    name: 'Joe Thuney',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'OG',
    ovr: 92,
    salary: 16,
    archetype: 'Flawless Pass Protection Wall',
    attributes: { passing: 0, rushing: 0, passBlocking: 96, runBlocking: 90, athleticism: 80, footballIQ: 97 },
    highlightStat: '97 Pass Protection Technique & Zero Allowed Sacks',
  },
  {
    id: 'og-smith-trey',
    name: 'Trey Smith',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'OG',
    ovr: 86,
    salary: 1,
    archetype: 'Dominant Road-Grader Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 85, runBlocking: 92, athleticism: 81, footballIQ: 86 },
    highlightStat: '95 Pancake Blocks & Violent Strike Force',
  },
  {
    id: 'c-humphrey',
    name: 'Creed Humphrey',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'C',
    ovr: 94,
    salary: 18,
    archetype: 'Best Center in Football (Madden 94)',
    attributes: { passing: 0, rushing: 0, passBlocking: 95, runBlocking: 96, athleticism: 86, footballIQ: 97 },
    highlightStat: '98 Anchor Strength & Zero A-Gap Penetration Allowed',
  },
  {
    id: 'edge-karlaftis',
    name: 'George Karlaftis',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'EDGE',
    ovr: 84,
    salary: 3,
    archetype: 'Furious Motor Power Rusher',
    attributes: { passRush: 86, runDefense: 85, coverage: 60, athleticism: 84, footballIQ: 86 },
    highlightStat: '90 Bull Rush Pressure & Playoff Sacks',
  },
  {
    id: 'dt-jones',
    name: 'Chris Jones',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'DT',
    ovr: 97,
    salary: 32,
    archetype: 'Super Bowl Closer / Interior God (Madden 97)',
    attributes: { passRush: 98, runDefense: 94, coverage: 55, athleticism: 88, footballIQ: 98 },
    highlightStat: '99 4th Quarter Strip-Sack Clutch Domination',
  },
  {
    id: 'lb-bolton',
    name: 'Nick Bolton',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'LB',
    ovr: 86,
    salary: 1,
    archetype: 'Spagnuolo Defensive Quarterback',
    attributes: { passRush: 79, runDefense: 93, coverage: 82, athleticism: 81, footballIQ: 95 },
    highlightStat: '96 Goal-Line TFLs & Defensive Play-Calling',
  },
  {
    id: 'cb-mcduffie',
    name: 'Trent McDuffie',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'CB',
    ovr: 91,
    salary: 3,
    archetype: 'All-Pro Slot / Perimeter Weapon',
    attributes: { passRush: 86, runDefense: 90, coverage: 93, athleticism: 93, footballIQ: 96 },
    highlightStat: '97 Blitz Strip-Sacks & Blanket Man Coverage',
  },
  {
    id: 's-reid-justin',
    name: 'Justin Reid',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'S',
    ovr: 83,
    salary: 11,
    archetype: 'Physical Leader / Swiss-Army Safety',
    attributes: { passRush: 75, runDefense: 86, coverage: 83, athleticism: 87, footballIQ: 90 },
    highlightStat: '89 Open Field Tackling & Safety Blitz Disguises',
  },

  // ===================== LAS VEGAS RAIDERS (LV) =====================
  {
    id: 'qb-minshew',
    name: 'Gardner Minshew II',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'QB',
    ovr: 76,
    salary: 12,
    starter: true,
    archetype: 'Scrappy Gunslinger Scrambler',
    attributes: { passing: 80, rushing: 76, passBlocking: 0, runBlocking: 0, athleticism: 78, footballIQ: 83 },
    highlightStat: '87 Off-Schedule Creation & Moxy',
  },
  {
    id: 'qb-oconnell',
    name: 'Aidan O\'Connell',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'QB',
    ovr: 75,
    salary: 2,
    starter: false,
    archetype: 'Pocket Distributor Backup',
    attributes: { passing: 79, rushing: 58, passBlocking: 0, runBlocking: 0, athleticism: 62, footballIQ: 81 },
    highlightStat: '83 Quick Ball Out Release & Intermediate Touch',
  },
  {
    id: 'rb-mattison',
    name: 'Alexander Mattison',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'RB',
    ovr: 79,
    salary: 2,
    archetype: 'One-Cut Physical Back',
    attributes: { passing: 0, rushing: 82, receiving: 78, passBlocking: 76, runBlocking: 0, athleticism: 82, footballIQ: 81 },
    highlightStat: '86 Red-Zone Receiving & Jump Cuts',
  },
  {
    id: 'wr-meyers',
    name: 'Jakobi Meyers',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'WR',
    ovr: 83,
    salary: 11,
    archetype: 'Surgical Possession Receiver',
    attributes: { passing: 70, rushing: 0, receiving: 86, passBlocking: 0, runBlocking: 65, athleticism: 84, footballIQ: 91 },
    highlightStat: '91 3rd Down Separation & Trick Play Passing',
  },
  {
    id: 'wr-tucker-tre',
    name: 'Tre Tucker',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'WR',
    ovr: 77,
    salary: 1,
    archetype: '4.40 Field Stretcher',
    attributes: { passing: 0, rushing: 70, receiving: 78, passBlocking: 0, runBlocking: 52, athleticism: 93, footballIQ: 78 },
    highlightStat: '92 Deep Post-Pattern Acceleration',
  },
  {
    id: 'te-bowers',
    name: 'Brock Bowers',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'TE',
    ovr: 88,
    salary: 4,
    archetype: 'Rookie Record-Breaking Weapon',
    attributes: { passing: 0, rushing: 75, receiving: 92, passBlocking: 72, runBlocking: 80, athleticism: 91, footballIQ: 90 },
    highlightStat: '96 Yards After Catch & Matchup Nightmare in Slot',
  },
  {
    id: 'ot-miller-kolton',
    name: 'Kolton Miller',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'OT',
    ovr: 86,
    salary: 18,
    archetype: 'Elite Athletic Left Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 90, runBlocking: 84, athleticism: 86, footballIQ: 89 },
    highlightStat: '91 Pass Protection Anchor & Recovery Range',
  },
  {
    id: 'ot-glaze-dj',
    name: 'DJ Glaze',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'OT',
    ovr: 76,
    salary: 1,
    archetype: 'Rookie RT Anchor',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 77, athleticism: 78, footballIQ: 78 },
    highlightStat: '82 Pass Set Balance vs Speed Rushers',
  },
  {
    id: 'og-parham-dylan',
    name: 'Dylan Parham',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'OG',
    ovr: 80,
    salary: 1,
    archetype: 'Athletic Interior Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 82, athleticism: 83, footballIQ: 83 },
    highlightStat: '86 Pulling Speed & Trap Blocks',
  },
  {
    id: 'og-powers-johnson',
    name: 'Jackson Powers-Johnson',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'OG',
    ovr: 77,
    salary: 2,
    archetype: 'Mauler Inside Puller',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 85, athleticism: 80, footballIQ: 80 },
    highlightStat: '89 Violent Finish on Gap Pulls',
  },
  {
    id: 'c-james-andre',
    name: 'Andre James',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'C',
    ovr: 80,
    salary: 8,
    archetype: 'Solid Starting Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 81, athleticism: 77, footballIQ: 86 },
    highlightStat: '85 A-Gap Blitz Identification',
  },
  {
    id: 'edge-crosby',
    name: 'Maxx Crosby',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'EDGE',
    ovr: 97,
    salary: 23,
    archetype: 'The Condor / Infinite Energy Nightmare (Madden 97)',
    attributes: { passRush: 98, runDefense: 99, coverage: 70, athleticism: 93, footballIQ: 98 },
    highlightStat: '99 100% Snap Count Stamina, TFLs & Relentless Pressure',
  },
  {
    id: 'dt-wilkins',
    name: 'Christian Wilkins',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'DT',
    ovr: 90,
    salary: 27,
    archetype: 'First-Step Disruptive 3-Tech',
    attributes: { passRush: 91, runDefense: 93, coverage: 55, athleticism: 84, footballIQ: 92 },
    highlightStat: '95 Run Penetration & Interior Pressure',
  },
  {
    id: 'lb-spillane',
    name: 'Robert Spillane',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'LB',
    ovr: 84,
    salary: 4,
    archetype: 'Old-School Box Thumper',
    attributes: { passRush: 78, runDefense: 91, coverage: 80, athleticism: 78, footballIQ: 89 },
    highlightStat: '94 Goal-Line Stand Tackling & Interceptions',
  },
  {
    id: 'cb-hobbs',
    name: 'Nate Hobbs',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'CB',
    ovr: 82,
    salary: 1,
    archetype: 'Physical Nickel Corner',
    attributes: { passRush: 76, runDefense: 85, coverage: 83, athleticism: 88, footballIQ: 86 },
    highlightStat: '89 Slot Run Support & Physical Coverage',
  },
  {
    id: 's-moehrig',
    name: 'Tre\'von Moehrig',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'S',
    ovr: 83,
    salary: 1,
    archetype: 'Two-High Split Safety',
    attributes: { passRush: 68, runDefense: 82, coverage: 86, athleticism: 87, footballIQ: 85 },
    highlightStat: '88 Break on Deep Passes & Versatile Alignment',
  },

  // ===================== LOS ANGELES CHARGERS (LAC) =====================
  {
    id: 'qb-herbert',
    name: 'Justin Herbert',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'QB',
    ovr: 90,
    salary: 52,
    starter: true,
    archetype: 'Laser-Arm Rocket Launcher',
    attributes: { passing: 94, rushing: 82, passBlocking: 0, runBlocking: 0, athleticism: 88, footballIQ: 92 },
    highlightStat: '98 Throw Power & Laser 4th-and-Long Conversions',
  },
  {
    id: 'qb-stick',
    name: 'Easton Stick',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'QB',
    ovr: 70,
    salary: 2,
    starter: false,
    archetype: 'Athletic Scrambler Backup',
    attributes: { passing: 72, rushing: 78, passBlocking: 0, runBlocking: 0, athleticism: 81, footballIQ: 73 },
    highlightStat: '80 Mobility Outside the Pocket',
  },
  {
    id: 'rb-dobbins',
    name: 'J.K. Dobbins',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'RB',
    ovr: 83,
    salary: 1,
    archetype: 'Explosive Cutback Runner',
    attributes: { passing: 0, rushing: 87, receiving: 76, passBlocking: 74, runBlocking: 0, athleticism: 89, footballIQ: 86 },
    highlightStat: '93 Vision on Zone Cutbacks & High YPC',
  },
  {
    id: 'wr-mcconkey',
    name: 'Ladd McConkey',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'WR',
    ovr: 83,
    salary: 2,
    archetype: 'Elite Separation Slot / Z',
    attributes: { passing: 0, rushing: 0, receiving: 87, passBlocking: 0, runBlocking: 58, athleticism: 92, footballIQ: 88 },
    highlightStat: '95 Whip & Out-Route Instant Separation',
  },
  {
    id: 'wr-palmer',
    name: 'Joshua Palmer',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'WR',
    ovr: 79,
    salary: 1,
    archetype: 'Reliable Possession Target',
    attributes: { passing: 0, rushing: 0, receiving: 81, passBlocking: 0, runBlocking: 65, athleticism: 83, footballIQ: 83 },
    highlightStat: '86 3rd Down Chain Moving Contested Catch',
  },
  {
    id: 'te-dissly',
    name: 'Will Dissly',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'TE',
    ovr: 79,
    salary: 4,
    archetype: 'In-Line Blocking Master & Short Target',
    attributes: { passing: 0, rushing: 0, receiving: 78, passBlocking: 80, runBlocking: 88, athleticism: 75, footballIQ: 85 },
    highlightStat: '90 C-Gap Edge Sealing in Harbaugh Scheme',
  },
  {
    id: 'ot-slater',
    name: 'Rashawn Slater',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'OT',
    ovr: 89,
    salary: 4,
    archetype: 'Technically Perfect Blindside Wall',
    attributes: { passing: 0, rushing: 0, passBlocking: 94, runBlocking: 88, athleticism: 89, footballIQ: 93 },
    highlightStat: '95 Mirroring Speed Rush & Recovery Balance',
  },
  {
    id: 'ot-alt',
    name: 'Joe Alt',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'OT',
    ovr: 84,
    salary: 8,
    archetype: '6-Foot-8 Rookie Anchor Prodigy',
    attributes: { passing: 0, rushing: 0, passBlocking: 88, runBlocking: 86, athleticism: 88, footballIQ: 87 },
    highlightStat: '94 Wingspan, Core Anchor & Erasing Pro Bowl Edge Rushers',
  },
  {
    id: 'og-johnson-zion',
    name: 'Zion Johnson',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'OG',
    ovr: 80,
    salary: 3,
    archetype: 'Stout Anchor Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 82, athleticism: 81, footballIQ: 82 },
    highlightStat: '85 Interior Double Team Lifting',
  },
  {
    id: 'og-pipkins',
    name: 'Trey Pipkins III',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'OG',
    ovr: 78,
    salary: 7,
    archetype: 'Power Guard / Tackle Hybrid',
    attributes: { passing: 0, rushing: 0, passBlocking: 79, runBlocking: 80, athleticism: 78, footballIQ: 81 },
    highlightStat: '83 Inside Pass Protection Anchor',
  },
  {
    id: 'c-bozeman',
    name: 'Bradley Bozeman',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'C',
    ovr: 78,
    salary: 1,
    archetype: 'Physical Downhill Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 83, athleticism: 72, footballIQ: 84 },
    highlightStat: '86 A-Gap Power Scheme Drive',
  },
  {
    id: 'edge-bosa-joey',
    name: 'Joey Bosa',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'EDGE',
    ovr: 90,
    salary: 27,
    archetype: 'Master Hand Fighter / Edge Rusher',
    attributes: { passRush: 93, runDefense: 89, coverage: 65, athleticism: 86, footballIQ: 94 },
    highlightStat: '96 Hand Swipe Technique & Quick Sacks',
  },
  {
    id: 'edge-mack',
    name: 'Khalil Mack',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'EDGE',
    ovr: 92,
    salary: 23,
    archetype: 'Legendary Bull Rusher & Edge Setter',
    attributes: { passRush: 94, runDefense: 96, coverage: 68, athleticism: 85, footballIQ: 96 },
    highlightStat: '98 One-Arm Long-Arm Bull Rush Destruction',
  },
  {
    id: 'edge-tuipulotu',
    name: 'Tuli Tuipulotu',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'EDGE',
    ovr: 82,
    salary: 1,
    archetype: 'Heavy Hand Edge / 5-Tech Disruptor',
    attributes: { passRush: 84, runDefense: 86, coverage: 60, athleticism: 83, footballIQ: 83 },
    highlightStat: '88 Inside Stunts & Pocket Compression',
  },
  {
    id: 'dt-ford-poona',
    name: 'Poona Ford',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'DT',
    ovr: 82,
    salary: 1,
    archetype: 'Low-Pad-Level 1-Tech Disruptor',
    attributes: { passRush: 80, runDefense: 89, coverage: 40, athleticism: 75, footballIQ: 86 },
    highlightStat: '92 A-Gap Penetration & Run Stuffs',
  },
  {
    id: 'lb-henley',
    name: 'Daiyan Henley',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'LB',
    ovr: 82,
    salary: 1,
    archetype: 'Fast-Flow Coverage LB',
    attributes: { passRush: 76, runDefense: 84, coverage: 85, athleticism: 90, footballIQ: 84 },
    highlightStat: '91 Sideline Pursuit Speed & Pass Coverage',
  },
  {
    id: 'cb-fulton',
    name: 'Kristian Fulton',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'CB',
    ovr: 80,
    salary: 3,
    archetype: 'Press-Man Boundary Corner',
    attributes: { passRush: 0, runDefense: 76, coverage: 83, athleticism: 88, footballIQ: 82 },
    highlightStat: '86 In-Phase Trailing on Out-Breaking Routes',
  },
  {
    id: 's-james-derwin',
    name: 'Derwin James Jr.',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'S',
    ovr: 92,
    salary: 19,
    archetype: 'Defensive Enforcer / TE Eradicator',
    attributes: { passRush: 86, runDefense: 93, coverage: 91, athleticism: 91, footballIQ: 95 },
    highlightStat: '96 Matchup Flexibility, Box Hits & Blitz Pressure',
  },
  {
    id: 's-gilman',
    name: 'Alohi Gilman',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'S',
    ovr: 83,
    salary: 6,
    archetype: 'Instinctive Deep Safety',
    attributes: { passRush: 65, runDefense: 81, coverage: 86, athleticism: 85, footballIQ: 89 },
    highlightStat: '90 Forced Fumbles & Anticipation in Deep Half',
  },
  // --- AFC West Kickers & Special Teams ---
  {
    id: 'k-lutz-wil',
    name: 'Wil Lutz',
    team: 'DEN',
    teamCity: 'Denver',
    position: 'K',
    ovr: 82,
    salary: 3,
    starter: true,
    archetype: 'High-Altitude Mile High Weapon',
    attributes: { passing: 0, rushing: 0, kicking: 86, athleticism: 75, footballIQ: 86 },
    highlightStat: 'Mile High Altitude Distance & Game-Winning Clutch FGs',
  },
  {
    id: 'k-butker-harrison',
    name: 'Harrison Butker',
    team: 'KC',
    teamCity: 'Kansas City',
    position: 'K',
    ovr: 91,
    salary: 6,
    starter: true,
    archetype: 'Super Bowl Ice-in-the-Veins Assassin',
    attributes: { passing: 0, rushing: 0, kicking: 96, athleticism: 78, footballIQ: 96 },
    highlightStat: 'Super Bowl Record 57-Yard FG & Automatic in Playoffs',
  },
  {
    id: 'k-carlson-daniel',
    name: 'Daniel Carlson',
    team: 'LV',
    teamCity: 'Las Vegas',
    position: 'K',
    ovr: 87,
    salary: 4,
    starter: true,
    archetype: 'Dome Precision Machine',
    attributes: { passing: 0, rushing: 0, kicking: 91, athleticism: 76, footballIQ: 91 },
    highlightStat: '93% Accuracy in Allegiant Stadium & 50+ Yard Consistency',
  },
  {
    id: 'k-dicker-cameron',
    name: 'Cameron Dicker',
    team: 'LAC',
    teamCity: 'Los Angeles',
    position: 'K',
    ovr: 88,
    salary: 4,
    starter: true,
    archetype: 'Dicker the Kicker Laser Specialist',
    attributes: { passing: 0, rushing: 0, kicking: 92, athleticism: 77, footballIQ: 92 },
    highlightStat: '94.5% Career Field Goal Accuracy (Top 2 NFL All-Time)',
  },
];
