import React,{useEffect,useMemo,useRef,useState} from 'react';
import {LockKeyhole} from 'lucide-react';
import {useBallKnower} from './BallKnowerContext';
import {PLAYERS_DATABASE} from './players';
import type {League,Player} from './types';
import {fetchFantasyCommunications,FantasyDmMessage,FantasyDmThread,markFantasyDmRead,markTradeThreadRead,openFantasyDm,removeTradingBlockEntry,sendFantasyDm,sendTradeThreadMessage,setTradingBlockEntry,setWatchedFantasyPlayer,TradeMessage,TradeOffer,TradeThreadRead,TradingBlockEntry} from './fantasySeasonCloud';

type CommunicationState={dmThreads:FantasyDmThread[];dmMessages:FantasyDmMessage[];tradeMessages:TradeMessage[];tradeThreadReads:TradeThreadRead[];tradingBlock:TradingBlockEntry[];watchedPlayerIds:string[]};

export const FantasyLeagueCommunications=({league,trades}:{league:League;trades:TradeOffer[]})=>{
  const {currentUser,showToast}=useBallKnower();const me=league.members.find(member=>member.userId===currentUser?.id&&!member.isAi);
  const leagueTrades=useMemo(()=>trades.filter(trade=>trade.leagueId===league.id),[trades,league.id]);const leagueIdRef=useRef(league.id);
  const [view,setView]=useState<'dm'|'block'|'trade'>('dm');const [data,setData]=useState<CommunicationState>({dmThreads:[],dmMessages:[],tradeMessages:[],tradeThreadReads:[],tradingBlock:[],watchedPlayerIds:[]});const [active,setActive]=useState('');const [target,setTarget]=useState('');const [body,setBody]=useState('');const [tradeId,setTradeId]=useState(leagueTrades[0]?.id||'');const [tradeBody,setTradeBody]=useState('');const [loadError,setLoadError]=useState('');
  const refresh=async()=>{const requestedLeagueId=league.id;try{const next=await fetchFantasyCommunications(requestedLeagueId);if(leagueIdRef.current!==requestedLeagueId)return;setData(next);setLoadError('');}catch(error){if(leagueIdRef.current===requestedLeagueId)setLoadError(error instanceof Error?error.message:'League communications could not be loaded.');}};useEffect(()=>{leagueIdRef.current=league.id;setTradeId('');setActive('');setData({dmThreads:[],dmMessages:[],tradeMessages:[],tradeThreadReads:[],tradingBlock:[],watchedPlayerIds:[]});},[league.id]);useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),15000);return()=>window.clearInterval(timer);},[league.id]);
  useEffect(()=>{if(!tradeId&&leagueTrades[0]?.id)setTradeId(leagueTrades[0].id);},[tradeId,leagueTrades]);
  useEffect(()=>{if(view==='trade'&&tradeId)void markTradeThreadRead(tradeId).then(refresh).catch(error=>setLoadError(error instanceof Error?error.message:'Trade thread could not be marked read.'));},[view,tradeId]);
  const thread=data.dmThreads.find(item=>item.id===active);const messages=data.dmMessages.filter(item=>item.threadId===active);const unread=useMemo(()=>data.dmThreads.filter(item=>data.dmMessages.some(message=>message.threadId===item.id&&message.senderAuthId!==currentUser?.id&&Date.parse(message.createdAt)>Date.parse((item.participantA===currentUser?.id?item.lastReadAAt:item.lastReadBAt)||'1970-01-01'))).length,[data,currentUser?.id]);const unreadTrades=leagueTrades.filter(trade=>data.tradeMessages.some(message=>message.tradeId===trade.id&&message.senderAuthId!==currentUser?.id&&Date.parse(message.createdAt)>Date.parse(data.tradeThreadReads.find(read=>read.tradeId===trade.id)?.lastReadAt||'1970-01-01'))).length;
  const run=async(work:()=>Promise<unknown>,message:string)=>{try{await work();showToast(message);await refresh();}catch(error){showToast(error instanceof Error?error.message:'Communication update failed.');}};
  return <div className="mt-4 space-y-3 border-t border-white/10 pt-4"><div className="grid grid-cols-3 gap-1 rounded-xl bg-black/35 p-1">{(['dm','block','trade'] as const).map(item=><button key={item} onClick={()=>setView(item)} className={`min-h-11 rounded-lg text-[9px] font-black uppercase ${view===item?'bg-[#D4AF37] text-black':'text-zinc-400'}`}>{item==='dm'?`DMs${unread?` (${unread})`:''}`:item==='block'?'Trading Block':'Trade Threads'}</button>)}</div>{loadError&&<div role="alert" className="rounded-xl border border-red-400/20 bg-red-400/[.06] p-3 text-[10px] font-bold text-red-200">{loadError}</div>}
    {view==='dm'&&<div className="space-y-2"><div className="flex gap-2"><select aria-label="Manager to message" value={target} onChange={event=>setTarget(event.target.value)} className="min-h-11 min-w-0 flex-1 rounded-xl bg-black/40 px-3 text-xs"><option value="">Choose manager…</option>{league.members.filter(member=>!member.isAi&&member.id!==me?.id).map(member=><option key={member.id} value={member.id}>{member.userName}</option>)}</select><button disabled={!target} onClick={()=>void run(async()=>{const id=await openFantasyDm(league.id,target);setActive(id);await markFantasyDmRead(id);},'Private thread ready.')} className="rounded-xl bg-white px-3 text-[9px] font-black uppercase text-black disabled:opacity-35">Open</button></div><div className="grid gap-1 sm:grid-cols-2">{data.dmThreads.map(item=>{const other=item.participantA===currentUser?.id?item.participantB:item.participantA;return <button key={item.id} onClick={()=>{setActive(item.id);void markFantasyDmRead(item.id).then(refresh).catch(error=>setLoadError(error instanceof Error?error.message:'Private thread could not be marked read.'));}} className={`min-h-11 rounded-xl px-3 text-left text-xs font-black ${active===item.id?'bg-[#D4AF37] text-black':'bg-black/30'}`}><LockKeyhole className="mr-2 inline h-3 w-3"/>{league.members.find(member=>member.userId===other)?.userName||'Manager'}</button>})}</div>{thread&&<><div className="max-h-56 space-y-1 overflow-y-auto rounded-xl border border-white/10 p-2">{messages.map(item=><div key={item.id} className={`rounded-lg p-2 text-xs ${item.senderAuthId===currentUser?.id?'ml-8 bg-[#D4AF37] text-black':'mr-8 bg-black/40'}`}>{item.body}</div>)}</div><div className="flex gap-2"><input value={body} onChange={event=>setBody(event.target.value)} placeholder="Private message…" className="min-h-11 min-w-0 flex-1 rounded-xl bg-black/40 px-3 text-xs"/><button disabled={!body.trim()} onClick={()=>void run(async()=>{await sendFantasyDm(thread.id,body);setBody('');},'DM sent.')} className="rounded-xl bg-[#D4AF37] px-4 text-xs font-black text-black">Send</button></div></>}</div>}
    {view==='block'&&<div className="space-y-2">{data.tradingBlock.map(entry=><BlockEntry key={`${entry.memberId}:${entry.playerId}`} league={league} entry={entry} mine={entry.memberId===me?.id} watched={data.watchedPlayerIds.includes(entry.playerId)} run={run}/>)}{me&&<details className="rounded-xl border border-white/10 p-3"><summary className="flex min-h-11 cursor-pointer items-center text-[9px] font-black uppercase text-zinc-400">List one of my players</summary><div className="mt-2 space-y-1">{(me.roster||[]).map(player=><BlockAdder key={player.id} player={player} disabled={data.tradingBlock.some(entry=>entry.memberId===me.id&&entry.playerId===player.id)} onAdd={(status,needs)=>run(()=>setTradingBlockEntry(league.id,me.id,player.id,status,needs),'Trading Block updated.')}/>)}</div></details>}</div>}
    {view==='trade'&&<div className="space-y-2"><div className="text-[9px] font-black uppercase text-zinc-500">{unreadTrades?`${unreadTrades} unread trade thread${unreadTrades===1?'':'s'}`:'All trade threads read'}</div><select aria-label="Trade message thread" value={tradeId} onChange={event=>setTradeId(event.target.value)} className="min-h-11 w-full rounded-xl bg-black/40 px-3 text-xs"><option value="">Choose a trade…</option>{leagueTrades.map(trade=>{const isUnread=data.tradeMessages.some(message=>message.tradeId===trade.id&&message.senderAuthId!==currentUser?.id&&Date.parse(message.createdAt)>Date.parse(data.tradeThreadReads.find(read=>read.tradeId===trade.id)?.lastReadAt||'1970-01-01'));return <option key={trade.id} value={trade.id}>{isUnread?'● ':''}{trade.offeredPlayerIds.length} for {trade.requestedPlayerIds.length} · {trade.status}</option>})}</select>{tradeId&&<><div className="max-h-56 space-y-1 overflow-y-auto rounded-xl border border-white/10 p-2">{data.tradeMessages.filter(item=>item.tradeId===tradeId).map(item=><div key={item.id} className={`rounded-lg p-2 text-xs ${item.senderAuthId===currentUser?.id?'ml-8 bg-[#D4AF37] text-black':'mr-8 bg-black/40'}`}>{item.body}</div>)}</div><div className="flex gap-2"><input value={tradeBody} onChange={event=>setTradeBody(event.target.value)} placeholder="Message about this trade…" className="min-h-11 min-w-0 flex-1 rounded-xl bg-black/40 px-3 text-xs"/><button disabled={!tradeBody.trim()} onClick={()=>void run(async()=>{await sendTradeThreadMessage(tradeId,tradeBody);await markTradeThreadRead(tradeId);setTradeBody('');},'Trade message sent.')} className="rounded-xl bg-[#D4AF37] px-3 text-[9px] font-black uppercase text-black">Send</button></div></>}</div>}
  </div>;
};

const BlockEntry=({league,entry,mine,watched,run}:{league:League;entry:TradingBlockEntry;mine:boolean;watched:boolean;run:(work:()=>Promise<unknown>,message:string)=>Promise<void>})=>{const owner=league.members.find(member=>member.id===entry.memberId);const player=owner?.roster?.find(item=>item.id===entry.playerId)||PLAYERS_DATABASE.find(item=>item.id===entry.playerId);return <div className="flex min-h-12 items-center gap-2 rounded-xl bg-black/30 p-3"><div className="min-w-0 flex-1"><div className="truncate text-xs font-black">{player?.position} {player?.name}</div><div className="text-[9px] font-black uppercase text-[#D4AF37]">{owner?.userName} · {entry.status.replace('_',' ')}{entry.lookingFor.length?` · wants ${entry.lookingFor.join('/')}`:''}</div></div><button onClick={()=>void (mine?run(()=>removeTradingBlockEntry(league.id,entry.memberId,entry.playerId),'Removed.'):run(()=>setWatchedFantasyPlayer(league.id,entry.playerId,!watched),watched?'Watch removed.':'Player watched.'))} className="min-h-10 rounded-lg border border-white/10 px-3 text-[9px] font-black uppercase">{mine?'Remove':watched?'Watching':'Watch'}</button></div>;};
const BlockAdder=({player,disabled,onAdd}:{player:Player;disabled:boolean;onAdd:(status:TradingBlockEntry['status'],needs:string[])=>Promise<void>})=>{const [status,setStatus]=useState<TradingBlockEntry['status']>('available');const [need,setNeed]=useState('RB');return <div className="grid gap-1 rounded-lg bg-black/25 p-2 sm:grid-cols-[1fr_110px_80px_60px]"><span className="truncate text-xs"><b>{player.position}</b> {player.name}</span><select value={status} disabled={disabled} onChange={event=>setStatus(event.target.value as TradingBlockEntry['status'])} className="min-h-10 bg-[#111] text-[9px]"><option value="available">Available</option><option value="looking_for">Looking For</option><option value="untouchable">Untouchable</option></select><select value={need} disabled={disabled||status!=='looking_for'} onChange={event=>setNeed(event.target.value)} className="min-h-10 bg-[#111] text-[9px]">{['QB','RB','WR','TE','K','DST'].map(item=><option key={item}>{item}</option>)}</select><button disabled={disabled} onClick={()=>void onAdd(status,status==='looking_for'?[need]:[])} className="min-h-10 rounded bg-[#D4AF37] text-[9px] font-black text-black">Add</button></div>;};
