import React,{useEffect,useMemo,useState} from 'react';
import {Activity,ArrowRightLeft,Bandage,BarChart3,ChevronRight,Clock,Crown,History,MessageCircle,Shield,Trophy,User,Users} from 'lucide-react';
import {League} from './types';
import {PLAYERS_DATABASE} from './players';
import {useBallKnower} from './BallKnowerContext';
import {buildPlayoffBracket,buildWeeklySnapshot,fetchSeasonOperations,getLeagueFreeAgents,ownerSeasonProfile,postLeagueMessage,proposeTrade,resolveTrade,submitWaiverClaim,TradeOffer,WaiverClaim,LeagueTransaction,LeagueInjury,LeagueMessage} from './fantasySeasonCloud';

type View='weekly'|'playoffs'|'teams'|'trades'|'waivers'|'injuries'|'chat'|'legacy';
const views:{id:View;label:string;icon:React.ReactNode}[]=[
  {id:'weekly',label:'Season',icon:<Activity className="h-4 w-4"/>},{id:'playoffs',label:'Playoffs',icon:<Trophy className="h-4 w-4"/>},{id:'teams',label:'Teams',icon:<Users className="h-4 w-4"/>},{id:'trades',label:'Trades',icon:<ArrowRightLeft className="h-4 w-4"/>},{id:'waivers',label:'Waivers',icon:<BarChart3 className="h-4 w-4"/>},{id:'injuries',label:'Injuries',icon:<Bandage className="h-4 w-4"/>},{id:'chat',label:'Chat',icon:<MessageCircle className="h-4 w-4"/>},{id:'legacy',label:'Legacy',icon:<History className="h-4 w-4"/>},
];

export const FantasySeasonHub:React.FC<{league:League}>=({league})=>{
  const {currentUser,showToast}=useBallKnower();
  const me=league.members.find(m=>m.userId===currentUser?.id);
  const isCommissioner=currentUser?.id===league.commissionerId;
  const [view,setView]=useState<View>('weekly');
  const [trades,setTrades]=useState<TradeOffer[]>([]); const [claims,setClaims]=useState<WaiverClaim[]>([]); const [transactions,setTransactions]=useState<LeagueTransaction[]>([]); const [injuries,setInjuries]=useState<LeagueInjury[]>([]); const [messages,setMessages]=useState<LeagueMessage[]>([]);
  const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [pendingAction,setPendingAction]=useState(false);
  const [teamId,setTeamId]=useState(me?.id||league.members[0]?.id||''); const [tradeTarget,setTradeTarget]=useState(''); const [offerPlayer,setOfferPlayer]=useState(''); const [requestPlayer,setRequestPlayer]=useState('');

  const refresh=async(isCurrent:()=>boolean=()=>true)=>{if(isCurrent()){setLoading(true);setError('');}try{const data=await fetchSeasonOperations(league.id);if(!isCurrent())return;setTrades([...data.trades]);setClaims([...data.claims]);setTransactions([...data.transactions]);setInjuries([...data.injuries]);setMessages([...data.messages]);}catch(e:any){if(isCurrent())setError(e?.message||'Could not load league operations.');}finally{if(isCurrent())setLoading(false);}};
  useEffect(()=>{let active=true;void refresh(()=>active);return()=>{active=false;};},[league.id]);

  const weeks=useMemo(()=>buildWeeklySnapshot(league),[league.seasonResult]); const bracket=useMemo(()=>buildPlayoffBracket(league),[league.seasonResult,league.settings?.playoffTeams]);
  const selected=ownerSeasonProfile(league,teamId); const freeAgents=useMemo(()=>getLeagueFreeAgents(league,PLAYERS_DATABASE).slice(0,80),[league.members]);
  const target=league.members.find(m=>m.id===tradeTarget); const myRoster=me?.roster||[]; const targetRoster=target?.roster||[];
  const memberName=(id:string)=>league.members.find(m=>m.id===id||m.userId===id)?.userName||'Owner';

  const run=async(fn:()=>Promise<void>)=>{if(pendingAction)return;setPendingAction(true);try{await fn();await refresh();}catch(e:any){showToast(e?.message||'League operation failed.');}finally{setPendingAction(false);}};
  const sendMessage=()=>run(async()=>{await postLeagueMessage(league.id,currentUser?.name||'Ball Knower',message,isCommissioner&&message.startsWith('!')?'announcement':'chat');setMessage('');});
  const sendTrade=()=>run(async()=>{if(!me)throw new Error('League membership not found.');if(!tradeTarget)throw new Error('Choose an owner.');if(requestPlayer&&!targetRoster.some(player=>player.id===requestPlayer))throw new Error('Choose a player from the selected owner.');await proposeTrade(league,me.id,tradeTarget,offerPlayer?[offerPlayer]:[],requestPlayer?[requestPlayer]:[]);setOfferPlayer('');setRequestPlayer('');showToast('Trade offer sent.');});
  const claimPlayer=(playerId:string)=>run(async()=>{if(!me)throw new Error('League membership not found.');await submitWaiverClaim(league.id,me.id,playerId,undefined,claims.filter(c=>c.memberId===me.id&&c.status==='pending').length+1);showToast('Waiver claim submitted.');});

  return <section className="space-y-4">
    <div className="flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-[#0b0e12] p-2 no-scrollbar">{views.map(v=><button key={v.id} onClick={()=>setView(v.id)} className={`flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-4 text-[10px] font-black uppercase tracking-wider ${view===v.id?'bg-white text-black':'text-zinc-400 hover:bg-white/5'}`}>{v.icon}{v.label}</button>)}</div>
    {error&&<div className="rounded-xl border border-red-500/25 bg-red-500/5 p-3 text-xs font-bold text-red-300">{error} <button onClick={()=>void refresh()} className="ml-2 underline">Retry</button></div>}
    {loading&&<div className="text-xs font-black uppercase tracking-widest text-zinc-600">Syncing league operations…</div>}

    {view==='weekly'&&<div className="space-y-4"><Header title="Weekly Season Hub" sub="Every matchup, score, power shift and playoff push"/><div className="grid gap-3 md:grid-cols-3"><Stat label="Weeks" value={`${weeks.length}/${league.settings?.seasonGames||17}`}/><Stat label="Teams" value={String(league.members.length)}/><Stat label="Transactions" value={String(transactions.length)}/></div>{weeks.length?weeks.map(w=><div key={w.week} className="rounded-2xl border border-white/10 bg-[#101318] p-4"><div className="mb-3 text-xs font-black uppercase text-[#D4AF37]">Week {w.week}</div><div className="grid gap-2 md:grid-cols-2">{w.games.map(g=><div key={g.id} className="rounded-xl bg-black/35 p-3 text-xs"><div className="flex items-center justify-between"><span className="font-black">{memberName(g.awayMemberId)}</span><span>{g.awayScore}</span></div><div className="mt-1 flex items-center justify-between"><span className="font-black">{memberName(g.homeMemberId)}</span><span>{g.homeScore}</span></div><div className="mt-2 text-[10px] text-zinc-500">{g.keyMatchupFactor}</div></div>)}</div></div>):<Empty text="The weekly schedule appears after the season simulation runs."/>}</div>}

    {view==='playoffs'&&<div className="space-y-4"><Header title="Playoff Bracket" sub="Seeding, matchup paths and the road to the Ball Knower championship"/>{bracket.seeds.length?<><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{bracket.seeds.map((s,i)=><div key={s.memberId} className="rounded-2xl border border-white/10 bg-[#101318] p-4"><div className="text-[9px] font-black uppercase text-[#D4AF37]">Seed #{i+1}</div><div className="mt-1 font-black uppercase">{s.memberName}</div><div className="mt-1 text-xs text-zinc-500">{s.wins}-{s.losses}-{s.ties}</div></div>)}</div><div className="grid gap-3 md:grid-cols-2">{bracket.round1.map((m,i)=><div key={i} className="rounded-2xl border border-[#D4AF37]/20 bg-[#D4AF37]/5 p-4"><div className="text-[9px] font-black uppercase text-zinc-500">Opening Round</div><div className="mt-3 flex items-center justify-between font-black"><span>#{m.home.rank} {m.home.memberName}</span><span>VS</span><span>#{m.away.rank} {m.away.memberName}</span></div></div>)}</div></>:<Empty text="Playoff seeding appears when season standings are available."/>}</div>}

    {view==='teams'&&<div className="space-y-4"><Header title="Franchise Team Pages" sub="Roster, cap, ratings, schedule, record and owner history in one place"/><select value={teamId} onChange={e=>setTeamId(e.target.value)} className="min-h-11 w-full rounded-xl border border-white/10 bg-[#101318] px-3 text-sm font-bold">{league.members.map(m=><option key={m.id} value={m.id}>{m.userName}</option>)}</select>{selected.member&&<><div className="grid gap-3 sm:grid-cols-4"><Stat label="Record" value={selected.standing?`${selected.standing.wins}-${selected.standing.losses}-${selected.standing.ties}`:'—'}/><Stat label="Team OVR" value={String(selected.standing?.teamRating||selected.member.teamRatings?.overall||'—')}/><Stat label="Cap Spent" value={`$${selected.spent.toFixed(1)}M`}/><Stat label="Cap Room" value={`$${selected.capRoom.toFixed(1)}M`}/></div><div className="rounded-2xl border border-white/10 bg-[#101318] p-4"><div className="mb-3 text-xs font-black uppercase">Roster</div><div className="grid gap-2 sm:grid-cols-2">{selected.roster.map(p=><div key={p.id} className="flex items-center justify-between rounded-xl bg-black/30 p-3"><div><div className="text-xs font-black uppercase">{p.name}</div><div className="text-[10px] text-zinc-500">{p.position} · {p.team}</div></div><div className="text-right"><div className="text-sm font-black text-[#D4AF37]">{p.ovr}</div><div className="text-[9px] text-zinc-600">${p.salary}M</div></div></div>)}</div></div></>}</div>}

    {view==='trades'&&<div className="space-y-4"><Header title="Trade Center" sub="Owner-to-owner offers with a visible league paper trail"/>{me&&<div className="grid gap-2 rounded-2xl border border-white/10 bg-[#101318] p-4 md:grid-cols-4"><select value={tradeTarget} onChange={e=>{setTradeTarget(e.target.value);setRequestPlayer('');}} className="min-h-11 rounded-xl bg-black/40 px-2 text-xs"><option value="">Trade partner</option>{league.members.filter(m=>m.id!==me.id).map(m=><option value={m.id} key={m.id}>{m.userName}</option>)}</select><select value={offerPlayer} onChange={e=>setOfferPlayer(e.target.value)} className="min-h-11 rounded-xl bg-black/40 px-2 text-xs"><option value="">Your player</option>{myRoster.map(p=><option value={p.id} key={p.id}>{p.name} ({p.ovr})</option>)}</select><select value={requestPlayer} onChange={e=>setRequestPlayer(e.target.value)} className="min-h-11 rounded-xl bg-black/40 px-2 text-xs"><option value="">Their player</option>{targetRoster.map(p=><option value={p.id} key={p.id}>{p.name} ({p.ovr})</option>)}</select><button disabled={pendingAction} onClick={sendTrade} className="rounded-xl bg-[#D4AF37] text-xs font-black uppercase text-black disabled:opacity-40">Send Offer</button></div>}<div className="space-y-2">{trades.length?trades.map(t=><div key={t.id} className="rounded-2xl border border-white/10 bg-[#101318] p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-xs font-black uppercase">{memberName(t.proposerMemberId)} → {memberName(t.recipientMemberId)}</div><div className="mt-1 text-[10px] text-zinc-500">Offer {t.offeredPlayerIds.length} · Request {t.requestedPlayerIds.length} · {t.status.toUpperCase()}</div></div>{t.status==='pending'&&me?.id===t.recipientMemberId&&<div className="flex gap-2"><button disabled={pendingAction} onClick={()=>run(()=>resolveTrade(t.id,'accepted'))} className="rounded-lg bg-emerald-500/15 px-3 py-2 text-[10px] font-black text-emerald-400 disabled:opacity-40">ACCEPT</button><button disabled={pendingAction} onClick={()=>run(()=>resolveTrade(t.id,'rejected'))} className="rounded-lg bg-red-500/10 px-3 py-2 text-[10px] font-black text-red-400 disabled:opacity-40">REJECT</button></div>}</div></div>):<Empty text="No trade offers yet."/>}</div></div>}

    {view==='waivers'&&<div className="space-y-4"><Header title="Waivers & Free Agency" sub="Claim the best unrostered players before somebody else does"/><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{freeAgents.slice(0,30).map(p=><div key={p.id} className="flex items-center justify-between rounded-2xl border border-white/10 bg-[#101318] p-3"><div><div className="text-xs font-black uppercase">{p.name}</div><div className="text-[10px] text-zinc-500">{p.position} · {p.team} · ${p.salary}M</div></div><div className="flex items-center gap-2"><span className="font-black text-[#D4AF37]">{p.ovr}</span><button disabled={pendingAction} onClick={()=>claimPlayer(p.id)} className="rounded-lg bg-white px-2 py-1 text-[9px] font-black text-black disabled:opacity-40">CLAIM</button></div></div>)}</div><div><div className="mb-2 text-xs font-black uppercase">Your Claims</div>{claims.filter(c=>c.memberId===me?.id).map(c=><div key={c.id} className="rounded-xl bg-[#101318] p-3 text-xs">#{c.priority} · {PLAYERS_DATABASE.find(p=>p.id===c.playerId)?.name||c.playerId} · {c.status}</div>)}</div></div>}

    {view==='injuries'&&<div className="space-y-4"><Header title="Injury Report & IR" sub="Availability now matters to the weekly season story"/>{injuries.length?injuries.map(i=><div key={i.id} className="flex items-center justify-between rounded-2xl border border-white/10 bg-[#101318] p-4"><div><div className="text-xs font-black uppercase">{i.playerName}</div><div className="mt-1 text-[10px] text-zinc-500">{memberName(i.memberId)} · {i.injuryType}</div></div><div className="text-right"><div className="text-[10px] font-black uppercase text-red-400">{i.status}</div><div className="text-[9px] text-zinc-600">{i.weeksRemaining} week(s)</div></div></div>):<Empty text="No active injuries in this league."/>}</div>}

    {view==='chat'&&<div className="space-y-4"><Header title="League Chat & Receipts" sub="Talk ball, post commissioner announcements and save the receipts"/><div className="flex gap-2"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void sendMessage();}} placeholder={isCommissioner?'Message league — prefix ! for announcement':'Talk your talk…'} className="min-h-12 flex-1 rounded-xl border border-white/10 bg-[#101318] px-3 text-sm"/><button disabled={pendingAction} onClick={sendMessage} className="rounded-xl bg-[#D4AF37] px-5 text-xs font-black uppercase text-black disabled:opacity-40">Send</button></div><div className="space-y-2">{messages.length?messages.map(m=><div key={m.id} className={`rounded-2xl border p-4 ${m.kind==='announcement'?'border-[#D4AF37]/30 bg-[#D4AF37]/5':'border-white/10 bg-[#101318]'}`}><div className="flex items-center justify-between"><div className="text-xs font-black uppercase">{m.memberName}</div><div className="text-[9px] uppercase text-zinc-600">{m.kind}</div></div><p className="mt-2 text-sm text-zinc-300">{m.body}</p></div>):<Empty text="No messages yet. Somebody has to start the trash talk."/>}</div></div>}

    {view==='legacy'&&<div className="space-y-4"><Header title="Trophy Room & League History" sub="Championships, records and receipts that carry across seasons"/>{league.seasonResult?.standings?.length?<div className="grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-[#D4AF37]/30 bg-[#D4AF37]/5 p-5"><Crown className="h-7 w-7 text-[#D4AF37]"/><div className="mt-3 text-[9px] font-black uppercase text-zinc-500">Current Champion</div><div className="mt-1 text-xl font-black uppercase">{league.seasonResult.standings[0].memberName}</div></div><Stat label="Best Record" value={`${league.seasonResult.standings[0].wins}-${league.seasonResult.standings[0].losses}`}/><Stat label="League Seasons" value={String(Math.max(1,transactions.filter(t=>t.transactionType==='season_archive').length+1))}/></div>:<Empty text="The Trophy Room comes alive after the first completed season."/>}<div className="rounded-2xl border border-white/10 bg-[#101318] p-4"><div className="mb-3 text-xs font-black uppercase">Transaction History</div>{transactions.length?transactions.slice(0,30).map(t=><div key={t.id} className="border-b border-white/5 py-2 text-xs text-zinc-400">{t.summary}</div>):<div className="text-xs text-zinc-600">No recorded transactions yet.</div>}</div></div>}
  </section>;
};

const Header=({title,sub}:{title:string;sub:string})=><div><h2 className="font-display text-xl font-black uppercase tracking-tight">{title}</h2><p className="mt-1 text-xs font-semibold text-zinc-500">{sub}</p></div>;
const Stat=({label,value}:{label:string;value:string})=><div className="rounded-2xl border border-white/10 bg-[#101318] p-4"><div className="text-[9px] font-black uppercase tracking-wider text-zinc-600">{label}</div><div className="mt-1 text-lg font-black uppercase">{value}</div></div>;
const Empty=({text}:{text:string})=><div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-xs font-semibold text-zinc-600">{text}</div>;