import React,{useState} from 'react';
import {Bug, ExternalLink, Loader2, Mail, Rocket, ShieldCheck, Trash2, X} from 'lucide-react';
import {ModalPortal} from './ModalPortal';
import {useBallKnower} from './BallKnowerContext';
import {deleteBallKnowerAccount} from './supabase';

export type LaunchPanel='beta'|'privacy'|'terms'|'support';

const CONTACT='BallKnowerOfficial@gmail.com';

export function LaunchCenter({panel,onClose}:{panel:LaunchPanel|null;onClose:()=>void}){
  const {currentUser,logout,showToast}=useBallKnower();
  const [confirmDelete,setConfirmDelete]=useState(false);
  const [deleting,setDeleting]=useState(false);
  const [deleteError,setDeleteError]=useState<string|null>(null);
  if(!panel)return null;
  const reportBug=`mailto:${CONTACT}?subject=${encodeURIComponent('[BALL KNOWER BETA] Bug report')}&body=${encodeURIComponent('What screen were you on?\n\nWhat did you tap?\n\nWhat happened?\n\nDevice/browser: ')}`;
  const deleteAccount=async()=>{
    if(deleting)return;
    if(!confirmDelete){setConfirmDelete(true);setDeleteError(null);return;}
    setDeleting(true);setDeleteError(null);
    try{
      await deleteBallKnowerAccount();
      logout();
      showToast('Your Ball Knower account and personal data were deleted.');
      onClose();
    }catch(error:any){
      setDeleteError(error?.message||'Your account could not be deleted.');
    }finally{setDeleting(false)}
  };
  return <ModalPortal><div role="dialog" aria-modal="true" aria-label="Ball Knower launch information" className="fixed inset-0 z-[9999] overflow-y-auto overscroll-contain bg-black/85 px-4 pb-[max(1rem,env(safe-area-inset-bottom))] pt-[max(1rem,env(safe-area-inset-top))] backdrop-blur-md [-webkit-overflow-scrolling:touch]"><div className="mx-auto my-auto w-full max-w-2xl rounded-3xl border border-white/10 bg-[#0d1117] p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.22em] text-[var(--bk-team-accent)]">Ball Knower Public Beta</div><h2 className="mt-1 text-3xl font-black uppercase">{panel==='privacy'?'Privacy':panel==='terms'?'Terms of Use':panel==='support'?'Support':'Welcome to the beta'}</h2></div><button onClick={onClose} aria-label="Close" className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-white/10 bg-white/5"><X className="h-5 w-5"/></button></div>
  {panel==='beta'&&<div className="mt-5 space-y-4 text-sm font-semibold leading-6 text-zinc-300"><p>Ball Knower is open for real users while we finish live NFL data connections and polish remaining screens.</p><div className="grid gap-2 sm:grid-cols-3"><Info icon={<Rocket/>} title="Play now" text="Fantasy, Picks, Trivia and Solo are available during beta."/><Info icon={<Bug/>} title="Expect fixes" text="You may still find a bug. Report it and include what you tapped."/><Info icon={<ShieldCheck/>} title="No affiliation" text="Ball Knower is independent and is not endorsed by the NFL or its teams."/></div><p className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-4 text-xs text-amber-100">NFL data and projections may be delayed, incomplete or corrected. Confirm important information independently.</p></div>}
  {panel==='privacy'&&<div className="mt-5 space-y-4 text-sm leading-6 text-zinc-300"><p><b className="text-white">What we collect:</b> account identifiers, profile details you provide, league activity, gameplay progress, basic analytics, approximate country/region/city, and technical error information. Location analytics use a daily rotating anonymous identifier; Ball Knower does not store your raw IP address.</p><p><b className="text-white">Why:</b> to run accounts, leagues, scoring, saved progress, security, support and product improvement.</p><p><b className="text-white">Who receives it:</b> service providers needed to operate Ball Knower, including hosting, authentication, database, analytics and email providers. We do not sell personal information.</p><p><b className="text-white">Your choices:</b> you may request access or correction by emailing us. Signed-in users can permanently delete their Ball Knower account and associated personal data directly below.</p><p className="text-xs text-zinc-500">Effective September 3, 2026 · Contact: {CONTACT}</p><div className="rounded-2xl border border-red-400/20 bg-red-400/5 p-4"><div className="text-xs font-black uppercase tracking-wider text-red-200">Delete account</div><p className="mt-2 text-xs leading-5 text-zinc-400">This permanently deletes your account, profile photo and user-linked Ball Knower data. If you commission a league with other human members, commissioner control transfers to the oldest remaining human member. A league with no other human member is deleted.</p>{currentUser&&<p className="mt-2 break-all text-[10px] font-bold text-zinc-500">Current profile: {currentUser.email}</p>}{confirmDelete&&<p className="mt-3 rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-xs font-bold text-red-100">This cannot be undone. Tap “Permanently delete account” to confirm.</p>}{deleteError&&<p role="alert" className="mt-3 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-xs font-bold text-red-200">{deleteError}</p>}<div className="mt-3 flex flex-col gap-2 sm:flex-row">{confirmDelete&&<button type="button" disabled={deleting} onClick={()=>{setConfirmDelete(false);setDeleteError(null)}} className="min-h-12 flex-1 rounded-xl border border-white/10 px-4 text-xs font-black uppercase disabled:opacity-50">Cancel</button>}<button type="button" disabled={deleting} onClick={()=>void deleteAccount()} className="flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl border border-red-400/30 bg-red-500/15 px-4 text-xs font-black uppercase text-red-100 disabled:cursor-wait disabled:opacity-60">{deleting?<Loader2 className="h-4 w-4 animate-spin"/>:<Trash2 className="h-4 w-4"/>}{deleting?'Deleting…':confirmDelete?'Permanently delete account':'Delete my account'}</button></div></div></div>}
  {panel==='terms'&&<div className="mt-5 space-y-4 text-sm leading-6 text-zinc-300"><p>By using Ball Knower, you agree to use it lawfully, keep your account secure and avoid cheating, harassment, abuse, scraping or disrupting the service.</p><p>Ball Knower is provided during beta “as is.” Features, data, ratings and availability may change. We do not guarantee uninterrupted service or perfectly accurate sports data.</p><p>Ball Knower does not currently operate a sportsbook or process real-money wagers. Picks and simulations are for entertainment. Users are responsible for following local laws.</p><p>Ball Knower is an independent product and is not sponsored, endorsed or administered by the NFL, its clubs or their players. All third-party names and marks belong to their respective owners.</p><p className="text-xs text-zinc-500">Effective August 24, 2026 · Contact: {CONTACT}</p></div>}
  {panel==='support'&&<div className="mt-5 space-y-3"><p className="text-sm font-semibold leading-6 text-zinc-300">Tell us what screen you were on, what you tapped and what happened. A screenshot helps.</p><a href={reportBug} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[var(--bk-team-accent)] px-4 text-xs font-black uppercase text-black"><Bug className="h-4 w-4"/>Report a beta bug</a><a href={`mailto:${CONTACT}`} className="flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/10 px-4 text-xs font-black uppercase"><Mail className="h-4 w-4"/>Email support</a><a href="https://ballknower.com/support.html" target="_blank" rel="noreferrer" className="flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/10 px-4 text-xs font-black uppercase"><ExternalLink className="h-4 w-4"/>Support website</a></div>}
  </div></div></ModalPortal>;
}

const Info=({icon,title,text}:{icon:React.ReactNode;title:string;text:string})=><div className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="text-[var(--bk-team-accent)] [&>svg]:h-5 [&>svg]:w-5">{icon}</div><div className="mt-3 text-xs font-black uppercase text-white">{title}</div><p className="mt-1 text-xs leading-5 text-zinc-500">{text}</p></div>;

export function LaunchFooter({onOpen,onOpenPartners}:{onOpen:(panel:LaunchPanel)=>void;onOpenPartners:()=>void}){
  return <footer className="relative z-[3] mx-auto w-full max-w-5xl px-4 pb-[calc(5rem+env(safe-area-inset-bottom))] pt-5 md:pb-[max(1.25rem,env(safe-area-inset-bottom))]"><div className="flex flex-col gap-3 border-t border-white/10 pt-4 text-[9px] font-black uppercase tracking-wider text-zinc-600 sm:flex-row sm:items-center sm:justify-between"><div>© 2026 Ball Knower · Public Beta</div><div className="flex flex-wrap gap-x-4 gap-y-2"><button onClick={()=>onOpen('beta')} className="text-[var(--bk-team-accent)]">Beta info</button><button onClick={onOpenPartners}>Partners</button><button onClick={()=>onOpen('privacy')}>Privacy</button><button onClick={()=>onOpen('terms')}>Terms</button><button onClick={()=>onOpen('support')}>Support</button></div></div><p className="mt-3 max-w-3xl text-[9px] font-semibold leading-4 text-zinc-700">Independent football entertainment platform. Not affiliated with or endorsed by the NFL, its clubs or their players. Third-party names and marks belong to their owners.</p></footer>;
}
