import React from 'react';
import {Bug, ExternalLink, Mail, Rocket, ShieldCheck, Trash2, X} from 'lucide-react';
import {ModalPortal} from './ModalPortal';

export type LaunchPanel='beta'|'privacy'|'terms'|'support';

const CONTACT='BallKnowerOfficial@gmail.com';

export function LaunchCenter({panel,onClose}:{panel:LaunchPanel|null;onClose:()=>void}){
  if(!panel)return null;
  const requestDeletion=`mailto:${CONTACT}?subject=${encodeURIComponent('Ball Knower account deletion request')}&body=${encodeURIComponent('Please delete my Ball Knower account and associated personal data.\n\nAccount email: ')}`;
  const reportBug=`mailto:${CONTACT}?subject=${encodeURIComponent('[BALL KNOWER BETA] Bug report')}&body=${encodeURIComponent('What screen were you on?\n\nWhat did you tap?\n\nWhat happened?\n\nDevice/browser: ')}`;
  return <ModalPortal><div role="dialog" aria-modal="true" aria-label="Ball Knower launch information" className="fixed inset-0 z-[9999] overflow-y-auto overscroll-contain bg-black/85 px-4 pb-[max(1rem,env(safe-area-inset-bottom))] pt-[max(1rem,env(safe-area-inset-top))] backdrop-blur-md [-webkit-overflow-scrolling:touch]"><div className="mx-auto my-auto w-full max-w-2xl rounded-3xl border border-white/10 bg-[#0d1117] p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.22em] text-[var(--bk-team-accent)]">Ball Knower Public Beta</div><h2 className="mt-1 text-3xl font-black uppercase">{panel==='privacy'?'Privacy':panel==='terms'?'Terms of Use':panel==='support'?'Support':'Welcome to the beta'}</h2></div><button onClick={onClose} aria-label="Close" className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-white/10 bg-white/5"><X className="h-5 w-5"/></button></div>
  {panel==='beta'&&<div className="mt-5 space-y-4 text-sm font-semibold leading-6 text-zinc-300"><p>Ball Knower is open for real users while we finish live NFL data connections and polish remaining screens.</p><div className="grid gap-2 sm:grid-cols-3"><Info icon={<Rocket/>} title="Play now" text="Fantasy, Picks, Trivia and Solo are available during beta."/><Info icon={<Bug/>} title="Expect fixes" text="You may still find a bug. Report it and include what you tapped."/><Info icon={<ShieldCheck/>} title="No affiliation" text="Ball Knower is independent and is not endorsed by the NFL or its teams."/></div><p className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-4 text-xs text-amber-100">NFL data and projections may be delayed, incomplete or corrected. Confirm important information independently.</p></div>}
  {panel==='privacy'&&<div className="mt-5 space-y-4 text-sm leading-6 text-zinc-300"><p><b className="text-white">What we collect:</b> account identifiers, profile details you provide, league activity, gameplay progress, basic analytics and technical error information.</p><p><b className="text-white">Why:</b> to run accounts, leagues, scoring, saved progress, security, support and product improvement.</p><p><b className="text-white">Who receives it:</b> service providers needed to operate Ball Knower, including hosting, authentication, database, analytics and email providers. We do not sell personal information.</p><p><b className="text-white">Your choices:</b> you may request access, correction or deletion by emailing us. Avoid putting private information in public league names or messages.</p><p className="text-xs text-zinc-500">Effective August 24, 2026 · Contact: {CONTACT}</p><a href={requestDeletion} className="flex min-h-12 items-center justify-center gap-2 rounded-xl border border-red-400/25 bg-red-400/10 px-4 text-xs font-black uppercase text-red-200"><Trash2 className="h-4 w-4"/>Request account deletion</a></div>}
  {panel==='terms'&&<div className="mt-5 space-y-4 text-sm leading-6 text-zinc-300"><p>By using Ball Knower, you agree to use it lawfully, keep your account secure and avoid cheating, harassment, abuse, scraping or disrupting the service.</p><p>Ball Knower is provided during beta “as is.” Features, data, ratings and availability may change. We do not guarantee uninterrupted service or perfectly accurate sports data.</p><p>Ball Knower does not currently operate a sportsbook or process real-money wagers. Picks and simulations are for entertainment. Users are responsible for following local laws.</p><p>Ball Knower is an independent product and is not sponsored, endorsed or administered by the NFL, its clubs or their players. All third-party names and marks belong to their respective owners.</p><p className="text-xs text-zinc-500">Effective August 24, 2026 · Contact: {CONTACT}</p></div>}
  {panel==='support'&&<div className="mt-5 space-y-3"><p className="text-sm font-semibold leading-6 text-zinc-300">Tell us what screen you were on, what you tapped and what happened. A screenshot helps.</p><a href={reportBug} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[var(--bk-team-accent)] px-4 text-xs font-black uppercase text-black"><Bug className="h-4 w-4"/>Report a beta bug</a><a href={`mailto:${CONTACT}`} className="flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/10 px-4 text-xs font-black uppercase"><Mail className="h-4 w-4"/>Email support</a><a href="https://ballknower.com" target="_blank" rel="noreferrer" className="flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/10 px-4 text-xs font-black uppercase"><ExternalLink className="h-4 w-4"/>BallKnower.com</a></div>}
  </div></div></ModalPortal>;
}

const Info=({icon,title,text}:{icon:React.ReactNode;title:string;text:string})=><div className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="text-[var(--bk-team-accent)] [&>svg]:h-5 [&>svg]:w-5">{icon}</div><div className="mt-3 text-xs font-black uppercase text-white">{title}</div><p className="mt-1 text-xs leading-5 text-zinc-500">{text}</p></div>;

export function LaunchFooter({onOpen}:{onOpen:(panel:LaunchPanel)=>void}){
  return <footer className="relative z-[3] mx-auto w-full max-w-5xl px-4 pb-[max(1.25rem,env(safe-area-inset-bottom))] pt-5"><div className="flex flex-col gap-3 border-t border-white/10 pt-4 text-[9px] font-black uppercase tracking-wider text-zinc-600 sm:flex-row sm:items-center sm:justify-between"><div>© 2026 Ball Knower · Public Beta</div><div className="flex flex-wrap gap-x-4 gap-y-2"><button onClick={()=>onOpen('beta')} className="text-[var(--bk-team-accent)]">Beta info</button><button onClick={()=>onOpen('privacy')}>Privacy</button><button onClick={()=>onOpen('terms')}>Terms</button><button onClick={()=>onOpen('support')}>Support</button></div></div><p className="mt-3 max-w-3xl text-[9px] font-semibold leading-4 text-zinc-700">Independent football entertainment platform. Not affiliated with or endorsed by the NFL, its clubs or their players. Third-party names and marks belong to their owners.</p></footer>;
}
