import React,{useEffect,useMemo,useState} from 'react';
import {Crown,Lock,Package,Shirt,ShoppingBag,Sparkles,Star,Trophy} from 'lucide-react';
import {equipLockerItem,fetchLockerExperience,formatStorePrice,LockerState,PassProgress,StoreItem} from './lockerCloud';
import {useBallKnower} from './BallKnowerContext';

type Tab='locker'|'store'|'pass'|'collections'|'plus';
const lockerSlots:Record<string,keyof LockerState>={profile_frame:'equippedProfileFrame',nameplate:'equippedNameplate',league_theme:'equippedLeagueTheme',trivia_effect:'equippedTriviaEffect',my_player_cosmetic:'equippedMyPlayerCosmetic'};
const getLockerSlot=(item:StoreItem)=>lockerSlots[String(item.metadata.slot||'')];

export const LockerHub:React.FC=()=>{
 const {showToast}=useBallKnower(); const [tab,setTab]=useState<Tab>('locker'); const [catalog,setCatalog]=useState<StoreItem[]>([]); const [owned,setOwned]=useState<Set<string>>(new Set()); const [locker,setLocker]=useState<LockerState>({}); const [pass,setPass]=useState<PassProgress|null>(null); const [error,setError]=useState('');
 const refresh=async()=>{try{const d=await fetchLockerExperience();setCatalog([...d.catalog]);setOwned(new Set(d.entitlements.map(e=>e.sku)));setLocker(d.locker);setPass(d.pass);setError('');}catch(e:any){setError(e?.message||'Locker could not sync.');}};
 useEffect(()=>{void refresh()},[]);
 const tabs:[Tab,string][]=[['locker','Locker'],['store','Store'],['pass','Season Pass'],['collections','Collections'],['plus','BK+']];
 const equip=async(item:StoreItem)=>{const slot=getLockerSlot(item);if(!slot){showToast('This collectible is owned but is not an equippable Locker item.');return;}try{await equipLockerItem(slot,item.sku);showToast(`${item.title} equipped.`);await refresh();}catch(e:any){showToast(e?.message||'Could not equip item.');}};
 const ownedItems=useMemo(()=>catalog.filter(x=>owned.has(x.sku)),[catalog,owned]);
 return <div className="mx-auto max-w-7xl space-y-5 px-3 py-5 sm:px-6 sm:py-8">
  <section className="rounded-[2rem] border border-[#D4AF37]/25 bg-[radial-gradient(circle_at_82%_18%,rgba(212,175,55,.18),transparent_30%),#0a0d12] p-5 sm:p-8"><div className="text-[10px] font-black uppercase tracking-[.28em] text-[#D4AF37]">Profile / Locker</div><h1 className="mt-2 font-display text-4xl font-black uppercase sm:text-6xl">Own the look. Never buy wins.</h1><p className="mt-3 max-w-3xl text-sm font-semibold text-zinc-400">Cosmetics, collectibles, seasonal rewards and Ball Knower+ live here. Paid items never increase roster ratings, sim odds or competitive power.</p></section>
  <div className="flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-[#0d1015] p-2 no-scrollbar">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`min-h-11 shrink-0 rounded-xl px-4 text-[10px] font-black uppercase tracking-wider ${tab===id?'bg-[#D4AF37] text-black':'text-zinc-400'}`}>{label}</button>)}</div>
  {error&&<div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-red-500/20 bg-red-500/5 p-3 text-xs font-bold text-red-300"><span>{error}</span><button onClick={()=>void refresh()} className="inline-flex min-h-11 items-center justify-center rounded-lg border border-red-400/30 px-4 text-[10px] font-black uppercase tracking-wider text-red-200">Retry</button></div>}
  {tab==='locker'&&<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Stat label="Owned" value={String(owned.size)}/><Stat label="Pass Level" value={String(pass?.level||1)}/><Stat label="Season XP" value={String(pass?.xp||0)}/></div><div className="rounded-[1.5rem] border border-white/10 bg-[#101318] p-5"><div className="text-xs font-black uppercase">Your Equipped Identity</div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(locker).map(([k,v])=><div key={k} className="rounded-xl bg-black/30 p-3"><div className="text-[9px] font-black uppercase text-zinc-600">{k.replace('equipped','').replace(/([A-Z])/g,' $1')}</div><div className="mt-1 text-xs font-black">{v||'Default'}</div></div>)}</div></div><ItemGrid items={ownedItems} owned={owned} onEquip={equip}/></div>}
  {tab==='store'&&<><div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 text-xs font-semibold text-amber-200"><Lock className="mr-2 inline h-4 w-4"/>Checkout is intentionally disabled until trusted billing is connected. The catalog and entitlement system are ready, but the browser cannot grant purchases to itself.</div><ItemGrid items={catalog.filter(x=>!['season_pass','subscription','collectible'].includes(x.category))} owned={owned} onEquip={equip}/></>}
  {tab==='pass'&&<div className="rounded-[2rem] border border-[#D4AF37]/25 bg-[#101318] p-5 sm:p-7"><div className="flex items-start justify-between"><div><div className="text-[10px] font-black uppercase text-[#D4AF37]">2026 Season</div><div className="mt-2 font-display text-3xl font-black uppercase">Ball Knower Season Pass</div><p className="mt-2 text-sm text-zinc-400">Earn XP from trivia, leagues, predictions, trades and daily challenges. Free rewards stay free; premium adds cosmetics and collectibles only.</p></div><Trophy className="h-8 w-8 text-[#D4AF37]"/></div><div className="mt-6 h-3 overflow-hidden rounded-full bg-black/50"><div className="h-full bg-[#D4AF37]" style={{width:`${Math.min(100,((pass?.xp||0)%1000)/10)}%`}}/></div><div className="mt-2 text-[10px] font-black uppercase text-zinc-500">Level {pass?.level||1} · {pass?.xp||0} XP</div><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-5">{[1,2,3,4,5].map(n=><div key={n} className="rounded-xl border border-white/10 bg-black/25 p-3 text-center"><div className="text-[9px] font-black text-zinc-600">LV {n}</div><Sparkles className="mx-auto mt-2 h-5 w-5 text-[#D4AF37]"/><div className="mt-2 text-[9px] font-bold text-zinc-400">Cosmetic</div></div>)}</div></div>}
  {tab==='collections'&&<ItemGrid items={catalog.filter(x=>x.category==='collectible')} owned={owned} onEquip={equip}/>} 
  {tab==='plus'&&<div className="rounded-[2rem] border border-[#D4AF37]/30 bg-[linear-gradient(135deg,rgba(212,175,55,.13),transparent_50%),#101318] p-6 sm:p-8"><Crown className="h-8 w-8 text-[#D4AF37]"/><div className="mt-4 font-display text-4xl font-black uppercase">Ball Knower+</div><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-400">Advanced trade analysis, deeper historical analytics, enhanced owner-profile tools, premium cosmetic drops and an ad-free experience if ads are introduced later. No pay-to-win boosts.</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{['Advanced trade breakdowns','Deeper league & owner history','Premium cosmetic drops','Enhanced profile customization'].map(x=><div key={x} className="rounded-xl border border-white/10 bg-black/25 p-3 text-xs font-black"><Star className="mr-2 inline h-4 w-4 text-[#D4AF37]"/>{x}</div>)}</div></div>}
 </div>;
};

const ItemGrid=({items,owned,onEquip}:{items:StoreItem[];owned:Set<string>;onEquip:(x:StoreItem)=>void})=><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map(i=>{const equippable=Boolean(getLockerSlot(i));return <div key={i.sku} className="rounded-[1.5rem] border border-white/10 bg-[#101318] p-5"><div className="flex items-center justify-between"><CategoryIcon category={i.category}/><span className="text-[9px] font-black uppercase text-[#D4AF37]">{i.rarity}</span></div><div className="mt-4 text-lg font-black uppercase">{i.title}</div><div className="mt-2 min-h-10 text-xs leading-5 text-zinc-500">{i.description}</div><div className="mt-4 flex items-center justify-between gap-3"><span className="font-black">{formatStorePrice(i)}</span>{owned.has(i.sku)?equippable?<button onClick={()=>onEquip(i)} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-lg bg-white px-3 py-2 text-[9px] font-black uppercase text-black">Equip</button>:<span className="rounded-lg border border-white/10 px-3 py-2 text-[9px] font-black uppercase text-zinc-500">Owned</span>:<span className="rounded-lg border border-white/10 px-3 py-2 text-[9px] font-black uppercase text-zinc-600">{i.priceCents==null?'Included':'Billing Required'}</span>}</div></div>})}</div>;
const CategoryIcon=({category}:{category:string})=>category==='collectible'?<Package className="h-5 w-5 text-[#D4AF37]"/>:category.includes('cosmetic')?<Shirt className="h-5 w-5 text-[#D4AF37]"/>:category==='subscription'?<Crown className="h-5 w-5 text-[#D4AF37]"/>:<ShoppingBag className="h-5 w-5 text-[#D4AF37]"/>;
const Stat=({label,value}:{label:string;value:string})=><div className="rounded-2xl border border-white/10 bg-[#101318] p-4"><div className="text-[9px] font-black uppercase text-zinc-600">{label}</div><div className="mt-1 text-2xl font-black text-[#D4AF37]">{value}</div></div>;
