import { Madden27RosterEntry } from './madden27CurrentRoster';

export const MADDEN_27_ROSTER_CHUNK_6: Madden27RosterEntry[] = [
  { eaId: 22002, name: 'Adam Prentice', team: 'DEN', overallRating: 68, position: 'FB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1016.png?im=FaceCrop,padding=0.7' },
  { eaId: 15194, name: 'Ahmed Hassanein', team: 'DET', overallRating: 68, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10580.png?im=FaceCrop,padding=0.7' },
  { eaId: 1804, name: 'Alex Harkey', team: 'LAC', overallRating: 68, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11144.png?im=FaceCrop,padding=0.7' },
  { eaId: 20526, name: 'Andrew Beck', team: 'NYJ', overallRating: 68, position: 'FB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/89.png?im=FaceCrop,padding=0.7' },
  { eaId: 16339, name: 'Anez Cooper', team: 'NYJ', overallRating: 68, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11228.png?im=FaceCrop,padding=0.7' },
  { eaId: 15186, name: 'Antwaun Powell-Ryland', team: 'CIN', overallRating: 68, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10695.png?im=FaceCrop,padding=0.7' },
  { eaId: 15087, name: 'Arian Smith', team: 'NYJ', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10734.png?im=FaceCrop,padding=0.7' },
  { eaId: 13588, name: 'Austin Schlottmann', team: 'TEN', overallRating: 68, position: 'C', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9909.png?im=FaceCrop,padding=0.7' },
  { eaId: 21132, name: 'Benito Jones', team: 'LV', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/406.png?im=FaceCrop,padding=0.7' },
  { eaId: 21562, name: 'Brevin Jordan', team: 'HOU', overallRating: 68, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1379.png?im=FaceCrop,padding=0.7' },
  { eaId: 16277, name: 'Brian Parker II', team: 'CIN', overallRating: 68, position: 'LG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11099.png?im=FaceCrop,padding=0.7' },
  { eaId: 1391, name: 'British Brooks', team: 'HOU', overallRating: 68, position: 'FB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10879.png?im=FaceCrop,padding=0.7' },
  { eaId: 4724, name: 'Brycen Tremayne', team: 'CAR', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11071.png?im=FaceCrop,padding=0.7' },
  { eaId: 16161, name: 'Carson Beck', team: 'ARI', overallRating: 68, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11136.png?im=FaceCrop,padding=0.7' },
  { eaId: 17543, name: 'Carson Wentz', team: 'MIN', overallRating: 68, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/8258.png?im=FaceCrop,padding=0.7' },
  { eaId: 22096, name: 'Charlie Kolar', team: 'LAC', overallRating: 68, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1802.png?im=FaceCrop,padding=0.7' },
  { eaId: 23350, name: 'Chris Brooks', team: 'GB', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10369.png?im=FaceCrop,padding=0.7' },
  { eaId: 15271, name: 'Chris Paul Jr', team: 'SEA', overallRating: 68, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10688.png?im=FaceCrop,padding=0.7' },
  { eaId: 16323, name: 'CJ Daniels', team: 'LAR', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11271.png?im=FaceCrop,padding=0.7' },
  { eaId: 20531, name: 'Cody Ford', team: 'CIN', overallRating: 68, position: 'LT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9459.png?im=FaceCrop,padding=0.7' },
  { eaId: 22177, name: 'Cory Durden', team: 'NE', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10385.png?im=FaceCrop,padding=0.7' },
  { eaId: 1860, name: 'Dalton Johnson', team: 'LV', overallRating: 68, position: 'SS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11263.png?im=FaceCrop,padding=0.7' },
  { eaId: 23085, name: 'Daniel Scott', team: 'IND', overallRating: 68, position: 'FS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2385.png?im=FaceCrop,padding=0.7' },
  { eaId: 22087, name: 'Danny Gray', team: 'PHI', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1741.png?im=FaceCrop,padding=0.7' },
  { eaId: 22114, name: 'Darian Kinnard', team: 'GB', overallRating: 68, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1799.png?im=FaceCrop,padding=0.7' },
  { eaId: 4727, name: 'Darius Cooper', team: 'PHI', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11088.png?im=FaceCrop,padding=0.7' },
  { eaId: 1732, name: 'David Quessenberry', team: 'LAR', overallRating: 68, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/6030.png?im=FaceCrop,padding=0.7' },
  { eaId: 22855, name: 'Dawand Jones', team: 'CLE', overallRating: 68, position: 'LT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2248.png?im=FaceCrop,padding=0.7' },
  { eaId: 16163, name: 'Dillon Bell', team: 'MIN', overallRating: 68, position: 'WR', avatarUrl: 'null' },
  { eaId: 15040, name: 'Donovan Edwards', team: 'MIA', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10541.png?im=FaceCrop,padding=0.7' },
  { eaId: 15065, name: 'Dont\'e Thornton Jr', team: 'LV', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10754.png?im=FaceCrop,padding=0.7' },
  { eaId: 14995, name: 'Donte Kent', team: 'PIT', overallRating: 68, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10928.png?im=FaceCrop,padding=0.7' },
  { eaId: 16211, name: 'Drew Allar', team: 'PIT', overallRating: 68, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11303.png?im=FaceCrop,padding=0.7' },
  { eaId: 20395, name: 'Drew Sample', team: 'CIN', overallRating: 68, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9617.png?im=FaceCrop,padding=0.7' },
  { eaId: 16216, name: 'Drew Shelton', team: 'DAL', overallRating: 68, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11175.png?im=FaceCrop,padding=0.7' },
  { eaId: 1122, name: 'Dylan Laube', team: 'LV', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10151.png?im=FaceCrop,padding=0.7' },
  { eaId: 4663, name: 'Efton Chism III', team: 'NE', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11072.png?im=FaceCrop,padding=0.7' },
  { eaId: 21795, name: 'Elijah Hicks', team: 'CHI', overallRating: 68, position: 'FS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2528.png?im=FaceCrop,padding=0.7' },
  { eaId: 22779, name: 'Elijah Higgins', team: 'ARI', overallRating: 68, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2209.png?im=FaceCrop,padding=0.7' },
  { eaId: 1126, name: 'Elijah Klein', team: 'TB', overallRating: 68, position: 'C', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10929.png?im=FaceCrop,padding=0.7' },
  { eaId: 4739, name: 'Elijah Ponder', team: 'NE', overallRating: 68, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11073.png?im=FaceCrop,padding=0.7' },
  { eaId: 16352, name: 'Emmett Johnson', team: 'KC', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11153.png?im=FaceCrop,padding=0.7' },
  { eaId: 16406, name: 'Enrique Cruz Jr.', team: 'SF', overallRating: 68, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11204.png?im=FaceCrop,padding=0.7' },
  { eaId: 14690, name: 'Erick All Jr', team: 'CIN', overallRating: 68, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9997.png?im=FaceCrop,padding=0.7' },
  { eaId: 15193, name: 'Fadil Diggs', team: 'NO', overallRating: 68, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10534.png?im=FaceCrop,padding=0.7' },
  { eaId: 16281, name: 'Hezekiah Masses', team: 'LV', overallRating: 68, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11264.png?im=FaceCrop,padding=0.7' },
  { eaId: 10171, name: 'Jackie Marshall', team: 'TEN', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11325.png?im=FaceCrop,padding=0.7' },
  { eaId: 15104, name: 'Jackson Hawes', team: 'BUF', overallRating: 68, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10581.png?im=FaceCrop,padding=0.7' },
  { eaId: 10640, name: 'Jackson Slater', team: 'TEN', overallRating: 68, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10733.png?im=FaceCrop,padding=0.7' },
  { eaId: 20329, name: 'Jake Browning', team: 'TB', overallRating: 68, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9399.png?im=FaceCrop,padding=0.7' },
  { eaId: 23107, name: 'Jake Moody', team: 'WAS', overallRating: 68, position: 'K', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2318.png?im=FaceCrop,padding=0.7' },
  { eaId: 22783, name: 'Jalen Cropper', team: 'NO', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/6053.png?im=FaceCrop,padding=0.7' },
  { eaId: 15152, name: 'Jalen Travis', team: 'IND', overallRating: 68, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10758.png?im=FaceCrop,padding=0.7' },
  { eaId: 13239, name: 'Jalyn Holmes', team: 'TEN', overallRating: 68, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/8927.png?im=FaceCrop,padding=0.7' },
  { eaId: 16189, name: 'Jam Miller', team: 'NE', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11256.png?im=FaceCrop,padding=0.7' },
  { eaId: 20988, name: 'James Lynch', team: 'CHI', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/437.png?im=FaceCrop,padding=0.7' },
  { eaId: 23045, name: 'Jammie Robinson', team: 'ATL', overallRating: 68, position: 'SS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2372.png?im=FaceCrop,padding=0.7' },
  { eaId: 15348, name: 'Jaylen Reed', team: 'HOU', overallRating: 68, position: 'FS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10702.png?im=FaceCrop,padding=0.7' },
  { eaId: 22090, name: 'Jeremy Ruckert', team: 'NYJ', overallRating: 68, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1932.png?im=FaceCrop,padding=0.7' },
  { eaId: 22188, name: 'Jesse Luketa', team: 'NE', overallRating: 68, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1818.png?im=FaceCrop,padding=0.7' },
  { eaId: 14671, name: 'Jha\'Quan Jackson', team: 'HOU', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10116.png?im=FaceCrop,padding=0.7' },
  { eaId: 13038, name: 'Johnny Mundt', team: 'PHI', overallRating: 68, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9248.png?im=FaceCrop,padding=0.7' },
  { eaId: 14658, name: 'Johnny Wilson', team: 'PHI', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10301.png?im=FaceCrop,padding=0.7' },
  { eaId: 23123, name: 'Jon Gaines II', team: 'ARI', overallRating: 68, position: 'LG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2148.png?im=FaceCrop,padding=0.7' },
  { eaId: 15167, name: 'Jonah Savaiinaea', team: 'MIA', overallRating: 68, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10722.png?im=FaceCrop,padding=0.7' },
  { eaId: 21996, name: 'Jonah Williams', team: 'ARI', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9678.png?im=FaceCrop,padding=0.7' },
  { eaId: 10199, name: 'Jordan van den Berg', team: 'CHI', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11340.png?im=FaceCrop,padding=0.7' },
  { eaId: 23280, name: 'Jordon Riley', team: 'GB', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10958.png?im=FaceCrop,padding=0.7' },
  { eaId: 1448, name: 'Josh Butler', team: 'DAL', overallRating: 68, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10881.png?im=FaceCrop,padding=0.7' },
  { eaId: 16245, name: 'Josh Cameron', team: 'JAX', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11219.png?im=FaceCrop,padding=0.7' },
  { eaId: 15016, name: 'Josh Williams', team: 'TB', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11483.png?im=FaceCrop,padding=0.7' },
  { eaId: 16274, name: 'Justin Joly', team: 'DEN', overallRating: 68, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11115.png?im=FaceCrop,padding=0.7' },
  { eaId: 4765, name: 'Kaden Davis', team: 'CHI', overallRating: 68, position: 'WR', avatarUrl: 'null' },
  { eaId: 10177, name: 'Kaden Wetjen', team: 'PIT', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11311.png?im=FaceCrop,padding=0.7' },
  { eaId: 10194, name: 'Karon Prunty', team: 'NE', overallRating: 68, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11348.png?im=FaceCrop,padding=0.7' },
  { eaId: 16233, name: 'Keith Abney II', team: 'DET', overallRating: 68, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11234.png?im=FaceCrop,padding=0.7' },
  { eaId: 10185, name: 'Keyshawn James-Newby', team: 'PHI', overallRating: 68, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11192.png?im=FaceCrop,padding=0.7' },
  { eaId: 1071, name: 'Kiran Amegadjie', team: 'CHI', overallRating: 68, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9999.png?im=FaceCrop,padding=0.7' },
  { eaId: 16151, name: 'Korie Black', team: 'NYG', overallRating: 68, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10875.png?im=FaceCrop,padding=0.7' },
  { eaId: 1171, name: 'KT Leveston', team: 'CLE', overallRating: 68, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10157.png?im=FaceCrop,padding=0.7' },
  { eaId: 20422, name: 'L.J. Collier', team: 'ARI', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9418.png?im=FaceCrop,padding=0.7' },
  { eaId: 21951, name: 'LaCale London', team: 'ATL', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/970.png?im=FaceCrop,padding=0.7' },
  { eaId: 17555, name: 'Laquon Treadwell', team: 'IND', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/8238.png?im=FaceCrop,padding=0.7' },
  { eaId: 16252, name: 'Logan Taylor', team: 'LAC', overallRating: 68, position: 'LG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11148.png?im=FaceCrop,padding=0.7' },
  { eaId: 13911, name: 'Malik Turner', team: 'SF', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/164.png?im=FaceCrop,padding=0.7' },
  { eaId: 22298, name: 'Matt Henningsen', team: 'DEN', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2527.png?im=FaceCrop,padding=0.7' },
  { eaId: 16166, name: 'Micah Morris', team: 'PHI', overallRating: 68, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11194.png?im=FaceCrop,padding=0.7' },
  { eaId: 22976, name: 'Mike Morris', team: 'SEA', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2320.png?im=FaceCrop,padding=0.7' },
  { eaId: 21264, name: 'Myles Bryant', team: 'CLE', overallRating: 68, position: 'SS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/196.png?im=FaceCrop,padding=0.7' },
  { eaId: 1142, name: 'Myles Harden', team: 'CLE', overallRating: 68, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10098.png?im=FaceCrop,padding=0.7' },
  { eaId: 14921, name: 'Nathaniel Watson', team: 'CLE', overallRating: 68, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10287.png?im=FaceCrop,padding=0.7' },
  { eaId: 22996, name: 'Noah Sewell', team: 'CHI', overallRating: 68, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2390.png?im=FaceCrop,padding=0.7' },
  { eaId: 22172, name: 'Otito Ogbonnia', team: 'DAL', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1866.png?im=FaceCrop,padding=0.7' },
  { eaId: 15042, name: 'Phil Mafah', team: 'DAL', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10642.png?im=FaceCrop,padding=0.7' },
  { eaId: 22061, name: 'Pierre Strong Jr', team: 'GB', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1961.png?im=FaceCrop,padding=0.7' },
  { eaId: 1096, name: 'Qwan\'tez Stiggers', team: 'NYJ', overallRating: 68, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10468.png?im=FaceCrop,padding=0.7' },
  { eaId: 10239, name: 'Raylen Sharpe', team: 'IND', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11380.png?im=FaceCrop,padding=0.7' },
  { eaId: 21702, name: 'Robert Rochell', team: 'CAR', overallRating: 68, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1327.png?im=FaceCrop,padding=0.7' },
  { eaId: 16144, name: 'Ruben Hyppolite II', team: 'CHI', overallRating: 68, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10915.png?im=FaceCrop,padding=0.7' },
  { eaId: 22291, name: 'Russ Yeast', team: 'CIN', overallRating: 68, position: 'FS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2673.png?im=FaceCrop,padding=0.7' },
  { eaId: 20930, name: 'Salvon Ahmed', team: 'CHI', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/70.png?im=FaceCrop,padding=0.7' },
  { eaId: 21401, name: 'Sam Franklin Jr', team: 'BUF', overallRating: 68, position: 'FS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1431.png?im=FaceCrop,padding=0.7' },
  { eaId: 16313, name: 'Sam Hecht', team: 'CAR', overallRating: 68, position: 'C', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11247.png?im=FaceCrop,padding=0.7' },
  { eaId: 22661, name: 'Sam Okuayinonu', team: 'SF', overallRating: 68, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/4797.png?im=FaceCrop,padding=0.7' },
  { eaId: 22498, name: 'Sam Roberts', team: 'NYG', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2614.png?im=FaceCrop,padding=0.7' },
  { eaId: 23268, name: 'Scott Matlock', team: 'LAC', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/4689.png?im=FaceCrop,padding=0.7' },
  { eaId: 14999, name: 'Sione Vaki', team: 'DET', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10277.png?im=FaceCrop,padding=0.7' },
  { eaId: 15017, name: 'Tahj Washington', team: 'MIA', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10286.png?im=FaceCrop,padding=0.7' },
  { eaId: 13731, name: 'Tanner Hudson', team: 'CIN', overallRating: 68, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9807.png?im=FaceCrop,padding=0.7' },
  { eaId: 20867, name: 'Tom Kennedy', team: 'DET', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/410.png?im=FaceCrop,padding=0.7' },
  { eaId: 15223, name: 'Tonka Hemingway', team: 'LV', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10583.png?im=FaceCrop,padding=0.7' },
  { eaId: 20640, name: 'Travis Homer', team: 'PIT', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9507.png?im=FaceCrop,padding=0.7' },
  { eaId: 13467, name: 'Tremon Smith', team: 'HOU', overallRating: 68, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9353.png?im=FaceCrop,padding=0.7' },
  { eaId: 16155, name: 'Trikweze Bridges', team: 'DAL', overallRating: 68, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10877.png?im=FaceCrop,padding=0.7' },
  { eaId: 20838, name: 'Troy Reeder', team: 'DET', overallRating: 68, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1506.png?im=FaceCrop,padding=0.7' },
  { eaId: 20978, name: 'Trystan Colon', team: 'JAX', overallRating: 68, position: 'LG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/222.png?im=FaceCrop,padding=0.7' },
  { eaId: 22325, name: 'Tyler Goodson', team: 'ATL', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1736.png?im=FaceCrop,padding=0.7' },
  { eaId: 21029, name: 'Tyler Huntley', team: 'BAL', overallRating: 68, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/904.png?im=FaceCrop,padding=0.7' },
  { eaId: 22962, name: 'Tyler Lacy', team: 'DET', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2281.png?im=FaceCrop,padding=0.7' },
  { eaId: 22089, name: 'Velus Jones Jr', team: 'SEA', overallRating: 68, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1791.png?im=FaceCrop,padding=0.7' },
  { eaId: 15217, name: 'Vernon Broughton', team: 'NO', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10502.png?im=FaceCrop,padding=0.7' },
  { eaId: 16271, name: 'Wade Woodaz', team: 'HOU', overallRating: 68, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11319.png?im=FaceCrop,padding=0.7' },
  { eaId: 22687, name: 'Will Levis', team: 'TEN', overallRating: 68, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/7889.png?im=FaceCrop,padding=0.7' },
  { eaId: 14774, name: 'Will Sheppard', team: 'GB', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11381.png?im=FaceCrop,padding=0.7' },
  { eaId: 23311, name: 'Xavier Smith', team: 'LAR', overallRating: 68, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/4976.png?im=FaceCrop,padding=0.7' },
  { eaId: 15225, name: 'Yahya Black', team: 'PIT', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10492.png?im=FaceCrop,padding=0.7' },
  { eaId: 22925, name: 'Zacch Pickens', team: 'NYG', overallRating: 68, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2356.png?im=FaceCrop,padding=0.7' },
  { eaId: 21162, name: 'A.J. Green III', team: 'MIA', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/304.png?im=FaceCrop,padding=0.7' },
  { eaId: 15213, name: 'Aeneas Peebles', team: 'BAL', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10690.png?im=FaceCrop,padding=0.7' },
  { eaId: 22716, name: 'Aidan O\'Connell', team: 'LV', overallRating: 67, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2606.png?im=FaceCrop,padding=0.7' },
  { eaId: 20950, name: 'Albert Okwuegbunam', team: 'LV', overallRating: 67, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/490.png?im=FaceCrop,padding=0.7' },
  { eaId: 22875, name: 'Alex Forsyth', team: 'DEN', overallRating: 67, position: 'C', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2144.png?im=FaceCrop,padding=0.7' },
  { eaId: 20448, name: 'Amani Oruwariye', team: 'BAL', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9594.png?im=FaceCrop,padding=0.7' },
  { eaId: 1809, name: 'Andre Fuller', team: 'SEA', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11298.png?im=FaceCrop,padding=0.7' },
  { eaId: 20672, name: 'Andre James', team: 'TEN', overallRating: 67, position: 'C', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9521.png?im=FaceCrop,padding=0.7' },
  { eaId: 10197, name: 'Anterio Thompson', team: 'ATL', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11343.png?im=FaceCrop,padding=0.7' },
  { eaId: 16350, name: 'Anthony Smith', team: 'DAL', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11176.png?im=FaceCrop,padding=0.7' },
  { eaId: 15090, name: 'Beaux Collins', team: 'NYG', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10522.png?im=FaceCrop,padding=0.7' },
  { eaId: 23007, name: 'Ben VanSumeren', team: 'BUF', overallRating: 67, position: 'FB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10470.png?im=FaceCrop,padding=0.7' },
  { eaId: 14884, name: 'Braiden McGregor', team: 'NYJ', overallRating: 67, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10172.png?im=FaceCrop,padding=0.7' },
  { eaId: 13425, name: 'Brandon Parker', team: 'SF', overallRating: 67, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9014.png?im=FaceCrop,padding=0.7' },
  { eaId: 16265, name: 'Cade Klubnik', team: 'NYJ', overallRating: 67, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11230.png?im=FaceCrop,padding=0.7' },
  { eaId: 14680, name: 'Cade Stover', team: 'HOU', overallRating: 67, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10256.png?im=FaceCrop,padding=0.7' },
  { eaId: 21192, name: 'Calvin Throckmorton', team: 'DEN', overallRating: 67, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/617.png?im=FaceCrop,padding=0.7' },
  { eaId: 10652, name: 'Carson Vinson', team: 'BAL', overallRating: 67, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10764.png?im=FaceCrop,padding=0.7' },
  { eaId: 16316, name: 'Carver Willis', team: 'SF', overallRating: 67, position: 'LG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11210.png?im=FaceCrop,padding=0.7' },
  { eaId: 4662, name: 'Chandler Brayboy', team: 'JAX', overallRating: 67, position: 'WR', avatarUrl: 'null' },
  { eaId: 16256, name: 'Chase Roberts', team: 'LV', overallRating: 67, position: 'WR', avatarUrl: 'null' },
  { eaId: 1251, name: 'Chris Roland-Wallace', team: 'KC', overallRating: 67, position: 'FS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10960.png?im=FaceCrop,padding=0.7' },
  { eaId: 14740, name: 'Christian Jones', team: 'ARI', overallRating: 67, position: 'LT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10131.png?im=FaceCrop,padding=0.7' },
  { eaId: 13099, name: 'Chukwuma Okorafor', team: 'NYJ', overallRating: 67, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9011.png?im=FaceCrop,padding=0.7' },
  { eaId: 20366, name: 'Chuma Edoga', team: 'JAX', overallRating: 67, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9446.png?im=FaceCrop,padding=0.7' },
  { eaId: 1345, name: 'Cody Schrader', team: 'DEN', overallRating: 67, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10243.png?im=FaceCrop,padding=0.7' },
  { eaId: 5000, name: 'Cole Payton', team: 'PHI', overallRating: 67, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11195.png?im=FaceCrop,padding=0.7' },
  { eaId: 15158, name: 'Connor Colby', team: 'SF', overallRating: 67, position: 'LG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10520.png?im=FaceCrop,padding=0.7' },
  { eaId: 15018, name: 'Cornelius Johnson', team: 'BAL', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10127.png?im=FaceCrop,padding=0.7' },
  { eaId: 22306, name: 'D.J. Davidson', team: 'WAS', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1326.png?im=FaceCrop,padding=0.7' },
  { eaId: 22518, name: 'D\'Anthony Bell', team: 'SEA', overallRating: 67, position: 'FS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2818.png?im=FaceCrop,padding=0.7' },
  { eaId: 16416, name: 'Dametrious Crownover', team: 'NE', overallRating: 67, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11252.png?im=FaceCrop,padding=0.7' },
  { eaId: 22500, name: 'Daniel Hardy', team: 'CHI', overallRating: 67, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2522.png?im=FaceCrop,padding=0.7' },
  { eaId: 15344, name: 'Dante Trader Jr', team: 'MIA', overallRating: 67, position: 'SS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10756.png?im=FaceCrop,padding=0.7' },
  { eaId: 22840, name: 'Davis Allen', team: 'LAR', overallRating: 67, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/852.png?im=FaceCrop,padding=0.7' },
  { eaId: 22491, name: 'Deane Leonard', team: 'LAC', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2574.png?im=FaceCrop,padding=0.7' },
  { eaId: 20922, name: 'DeeJay Dallas', team: 'JAX', overallRating: 67, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/227.png?im=FaceCrop,padding=0.7' },
  { eaId: 16143, name: 'Dillon Gabriel', team: 'CLE', overallRating: 67, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10557.png?im=FaceCrop,padding=0.7' },
  { eaId: 16222, name: 'DJ Campbell', team: 'MIA', overallRating: 67, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11178.png?im=FaceCrop,padding=0.7' },
  { eaId: 23282, name: 'DJ Ivey', team: 'CIN', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/4447.png?im=FaceCrop,padding=0.7' },
  { eaId: 16210, name: 'Domani Jackson', team: 'GB', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11242.png?im=FaceCrop,padding=0.7' },
  { eaId: 15060, name: 'Dominic Lovett', team: 'DET', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10640.png?im=FaceCrop,padding=0.7' },
  { eaId: 22961, name: 'Dylan Horton', team: 'HOU', overallRating: 67, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2212.png?im=FaceCrop,padding=0.7' },
  { eaId: 15218, name: 'Elijah Simmons', team: 'TB', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10727.png?im=FaceCrop,padding=0.7' },
  { eaId: 16199, name: 'Emmanuel Henderson Jr.', team: 'SEA', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11299.png?im=FaceCrop,padding=0.7' },
  { eaId: 22736, name: 'Eric Gray', team: 'NYG', overallRating: 67, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2175.png?im=FaceCrop,padding=0.7' },
  { eaId: 12711, name: 'Eric Saubert', team: 'SEA', overallRating: 67, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/8717.png?im=FaceCrop,padding=0.7' },
  { eaId: 1348, name: 'Ethan Bonner', team: 'MIA', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10876.png?im=FaceCrop,padding=0.7' },
  { eaId: 16391, name: 'Ethan Onianwa', team: 'ATL', overallRating: 67, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11200.png?im=FaceCrop,padding=0.7' },
  { eaId: 10181, name: 'Evan Beerntsen', team: 'BAL', overallRating: 67, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11276.png?im=FaceCrop,padding=0.7' },
  { eaId: 10198, name: 'Gabe Rubio', team: 'PIT', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11350.png?im=FaceCrop,padding=0.7' },
  { eaId: 9718, name: 'George Holani', team: 'SEA', overallRating: 67, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10108.png?im=FaceCrop,padding=0.7' },
  { eaId: 1084, name: 'Giovanni Manu', team: 'DET', overallRating: 67, position: 'LT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10414.png?im=FaceCrop,padding=0.7' },
  { eaId: 21605, name: 'Ihmir Smith-Marsette', team: 'ARI', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1244.png?im=FaceCrop,padding=0.7' },
  { eaId: 14669, name: 'Isaiah Williams', team: 'NYJ', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10298.png?im=FaceCrop,padding=0.7' },
  { eaId: 1882, name: 'J.C. Davis', team: 'NYG', overallRating: 67, position: 'LT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11211.png?im=FaceCrop,padding=0.7' },
  { eaId: 15253, name: 'Jack Kiser', team: 'JAX', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10626.png?im=FaceCrop,padding=0.7' },
  { eaId: 16324, name: 'Jaden Dugger', team: 'SF', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11205.png?im=FaceCrop,padding=0.7' },
  { eaId: 23118, name: 'Jalen Brooks', team: 'ARI', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1794.png?im=FaceCrop,padding=0.7' },
  { eaId: 15133, name: 'Jalen Rivers', team: 'CIN', overallRating: 67, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10708.png?im=FaceCrop,padding=0.7' },
  { eaId: 16403, name: 'Jalon Kilgore', team: 'BUF', overallRating: 67, position: 'SS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11108.png?im=FaceCrop,padding=0.7' },
  { eaId: 14959, name: 'James Williams Sr', team: 'TEN', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10299.png?im=FaceCrop,padding=0.7' },
  { eaId: 1326, name: 'Jamie Sheriff', team: 'SEA', overallRating: 67, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10963.png?im=FaceCrop,padding=0.7' },
  { eaId: 1398, name: 'Jamree Kromah', team: 'CHI', overallRating: 67, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10930.png?im=FaceCrop,padding=0.7' },
  { eaId: 21579, name: 'Jaret Patterson', team: 'LAC', overallRating: 67, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1009.png?im=FaceCrop,padding=0.7' },
  { eaId: 1125, name: 'Jarrett Kingston', team: 'HOU', overallRating: 67, position: 'LG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10143.png?im=FaceCrop,padding=0.7' },
  { eaId: 23119, name: 'Jason Brownlee', team: 'KC', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1892.png?im=FaceCrop,padding=0.7' },
  { eaId: 14717, name: 'Javon Foster', team: 'CIN', overallRating: 67, position: 'LT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10076.png?im=FaceCrop,padding=0.7' },
  { eaId: 16259, name: 'Jaydn Ott', team: 'KC', overallRating: 67, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11372.png?im=FaceCrop,padding=0.7' },
  { eaId: 14912, name: 'Jaylan Ford', team: 'NO', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10075.png?im=FaceCrop,padding=0.7' },
  { eaId: 10183, name: 'Jeff Caldwell', team: 'KC', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11427.png?im=FaceCrop,padding=0.7' },
  { eaId: 15250, name: 'Jeffrey Bassa', team: 'KC', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10487.png?im=FaceCrop,padding=0.7' },
  { eaId: 22351, name: 'Jelani Woods', team: 'NYJ', overallRating: 67, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2050.png?im=FaceCrop,padding=0.7' },
  { eaId: 14903, name: 'Jeremiah Trotter Jr', team: 'PHI', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10271.png?im=FaceCrop,padding=0.7' },
  { eaId: 14772, name: 'Jimmy Horn Jr', team: 'CAR', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10592.png?im=FaceCrop,padding=0.7' },
  { eaId: 15208, name: 'JJ Pegues', team: 'LV', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10691.png?im=FaceCrop,padding=0.7' },
  { eaId: 21276, name: 'Joe Bachie', team: 'DET', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/81.png?im=FaceCrop,padding=0.7' },
  { eaId: 4678, name: 'Johnathan Edwards', team: 'IND', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11083.png?im=FaceCrop,padding=0.7' },
  { eaId: 14916, name: 'Jordan Magee', team: 'WAS', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10413.png?im=FaceCrop,padding=0.7' },
  { eaId: 13037, name: 'Josh Tupou', team: 'NYG', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9302.png?im=FaceCrop,padding=0.7' },
  { eaId: 1223, name: 'Josh Wallace', team: 'LAR', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10283.png?im=FaceCrop,padding=0.7' },
  { eaId: 22618, name: 'Julius Chestnut', team: 'TEN', overallRating: 67, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/3003.png?im=FaceCrop,padding=0.7' },
  { eaId: 22864, name: 'Justin Dedich', team: 'LAR', overallRating: 67, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10890.png?im=FaceCrop,padding=0.7' },
  { eaId: 16200, name: 'Justin Jefferson', team: 'CLE', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11125.png?im=FaceCrop,padding=0.7' },
  { eaId: 20732, name: 'Justin Skule', team: 'TB', overallRating: 67, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/157.png?im=FaceCrop,padding=0.7' },
  { eaId: 22453, name: 'Kalia Davis', team: 'CLE', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1334.png?im=FaceCrop,padding=0.7' },
  { eaId: 14961, name: 'Kamal Hadden', team: 'GB', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10093.png?im=FaceCrop,padding=0.7' },
  { eaId: 21729, name: 'Kene Nwangwu', team: 'NYJ', overallRating: 67, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1180.png?im=FaceCrop,padding=0.7' },
  { eaId: 22046, name: 'Kenny Pickett', team: 'CAR', overallRating: 67, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1889.png?im=FaceCrop,padding=0.7' },
  { eaId: 21283, name: 'Khalid Kareem', team: 'NYG', overallRating: 67, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/709.png?im=FaceCrop,padding=0.7' },
  { eaId: 14967, name: 'Kitan Oladapo', team: 'GB', overallRating: 67, position: 'SS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10201.png?im=FaceCrop,padding=0.7' },
  { eaId: 22178, name: 'LaBryan Ray', team: 'CAR', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1910.png?im=FaceCrop,padding=0.7' },
  { eaId: 21124, name: 'Larrell Murchison', team: 'LAR', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/695.png?im=FaceCrop,padding=0.7' },
  { eaId: 16250, name: 'Lewis Bond', team: 'HOU', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11312.png?im=FaceCrop,padding=0.7' },
  { eaId: 14888, name: 'Marcus Harris', team: 'KC', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10101.png?im=FaceCrop,padding=0.7' },
  { eaId: 15165, name: 'Marcus Mbow', team: 'NYG', overallRating: 67, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10652.png?im=FaceCrop,padding=0.7' },
  { eaId: 21116, name: 'Matt Peart', team: 'DEN', overallRating: 67, position: 'LT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/510.png?im=FaceCrop,padding=0.7' },
  { eaId: 22169, name: 'Matthew Butler', team: 'MIA', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1231.png?im=FaceCrop,padding=0.7' },
  { eaId: 16156, name: 'Micah Robinson', team: 'TEN', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10997.png?im=FaceCrop,padding=0.7' },
  { eaId: 10206, name: 'Michael Dansby', team: 'SEA', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11349.png?im=FaceCrop,padding=0.7' },
  { eaId: 17756, name: 'Miles Killebrew', team: 'TB', overallRating: 67, position: 'SS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/8096.png?im=FaceCrop,padding=0.7' },
  { eaId: 16412, name: 'Namdi Obiazor', team: 'NE', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11258.png?im=FaceCrop,padding=0.7' },
  { eaId: 16353, name: 'Nate Boerkircher', team: 'JAX', overallRating: 67, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11218.png?im=FaceCrop,padding=0.7' },
  { eaId: 4722, name: 'Nate Carter', team: 'ATL', overallRating: 67, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11075.png?im=FaceCrop,padding=0.7' },
  { eaId: 21975, name: 'Nick Leverett', team: 'DAL', overallRating: 67, position: 'C', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1107.png?im=FaceCrop,padding=0.7' },
  { eaId: 15062, name: 'Nick Nash', team: 'WAS', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10675.png?im=FaceCrop,padding=0.7' },
  { eaId: 22798, name: 'Nikko Remigio', team: 'KC', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10955.png?im=FaceCrop,padding=0.7' },
  { eaId: 20479, name: 'Olisaemeka Udoh', team: 'ARI', overallRating: 67, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9660.png?im=FaceCrop,padding=0.7' },
  { eaId: 16164, name: 'Oscar Delp', team: 'NO', overallRating: 67, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11289.png?im=FaceCrop,padding=0.7' },
  { eaId: 22999, name: 'Owen Pappoe', team: 'ARI', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2347.png?im=FaceCrop,padding=0.7' },
  { eaId: 1834, name: 'Parker Brailsford', team: 'CLE', overallRating: 67, position: 'C', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11121.png?im=FaceCrop,padding=0.7' },
  { eaId: 10166, name: 'Quintayvious Hutchins', team: 'NE', overallRating: 67, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11253.png?im=FaceCrop,padding=0.7' },
  { eaId: 21928, name: 'Quinton Bohanna', team: 'JAX', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1598.png?im=FaceCrop,padding=0.7' },
  { eaId: 16175, name: 'Rayshaun Benny', team: 'BAL', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11277.png?im=FaceCrop,padding=0.7' },
  { eaId: 15086, name: 'Ricky White III', team: 'SEA', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10778.png?im=FaceCrop,padding=0.7' },
  { eaId: 14795, name: 'Riley Leonard', team: 'IND', overallRating: 67, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10634.png?im=FaceCrop,padding=0.7' },
  { eaId: 13848, name: 'Robert Tonyan', team: 'PIT', overallRating: 67, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9943.png?im=FaceCrop,padding=0.7' },
  { eaId: 20970, name: 'Saahdiq Charles', team: 'CAR', overallRating: 67, position: 'LG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/209.png?im=FaceCrop,padding=0.7' },
  { eaId: 1328, name: 'Shemar Bartholomew', team: 'GB', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10869.png?im=FaceCrop,padding=0.7' },
  { eaId: 21742, name: 'Simi Fehoko', team: 'ARI', overallRating: 67, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1130.png?im=FaceCrop,padding=0.7' },
  { eaId: 22891, name: 'Spencer Anderson', team: 'PIT', overallRating: 67, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2757.png?im=FaceCrop,padding=0.7' },
  { eaId: 10837, name: 'Teddy Bridgewater', team: 'DET', overallRating: 67, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/6359.png?im=FaceCrop,padding=0.7' },
  { eaId: 4711, name: 'Theo Benedet', team: 'CHI', overallRating: 67, position: 'LT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11061.png?im=FaceCrop,padding=0.7' },
  { eaId: 15220, name: 'Tim Smith', team: 'IND', overallRating: 67, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10737.png?im=FaceCrop,padding=0.7' },
  { eaId: 21679, name: 'Tony Fields II', team: 'CHI', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1094.png?im=FaceCrop,padding=0.7' },
  { eaId: 1872, name: 'Toriano Pride Jr.', team: 'BUF', overallRating: 67, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11110.png?im=FaceCrop,padding=0.7' },
  { eaId: 15243, name: 'Tyrion Ingram-Dawkins', team: 'MIN', overallRating: 67, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10601.png?im=FaceCrop,padding=0.7' },
  { eaId: 1395, name: 'Winston Reid', team: 'CLE', overallRating: 67, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10954.png?im=FaceCrop,padding=0.7' },
  { eaId: 22436, name: 'Alec Anderson', team: 'BUF', overallRating: 66, position: 'LG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10361.png?im=FaceCrop,padding=0.7' },
  { eaId: 22944, name: 'Ali Gaye', team: 'HOU', overallRating: 66, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2167.png?im=FaceCrop,padding=0.7' },
  { eaId: 23070, name: 'Anthony Johnson Jr', team: 'CHI', overallRating: 66, position: 'FS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2238.png?im=FaceCrop,padding=0.7' },
  { eaId: 1851, name: 'Ar\'maj Reed-Adams', team: 'BUF', overallRating: 66, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11111.png?im=FaceCrop,padding=0.7' },
  { eaId: 4742, name: 'Austin Ajiake', team: 'IND', overallRating: 66, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11412.png?im=FaceCrop,padding=0.7' },
  { eaId: 16239, name: 'Bobby Jamison-Travis', team: 'NYG', overallRating: 66, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11214.png?im=FaceCrop,padding=0.7' },
  { eaId: 22640, name: 'Brenden Schooler', team: 'NE', overallRating: 66, position: 'SS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/4924.png?im=FaceCrop,padding=0.7' },
  { eaId: 22978, name: 'Brenton Cox', team: 'GB', overallRating: 66, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2068.png?im=FaceCrop,padding=0.7' },
  { eaId: 16146, name: 'Bryce Cabeldue', team: 'SEA', overallRating: 66, position: 'LG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10882.png?im=FaceCrop,padding=0.7' },
  { eaId: 10196, name: 'C.J. Williams', team: 'JAX', overallRating: 66, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11224.png?im=FaceCrop,padding=0.7' },
  { eaId: 21255, name: 'Cam Gill', team: 'CAR', overallRating: 66, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/873.png?im=FaceCrop,padding=0.7' },
  { eaId: 21898, name: 'Cameron Goode', team: 'MIA', overallRating: 66, position: 'EDGE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/3237.png?im=FaceCrop,padding=0.7' },
  { eaId: 15166, name: 'Cameron Williams', team: 'PHI', overallRating: 66, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10779.png?im=FaceCrop,padding=0.7' },
  { eaId: 22204, name: 'Channing Tindall', team: 'ATL', overallRating: 66, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1986.png?im=FaceCrop,padding=0.7' },
  { eaId: 22215, name: 'Chase Lucas', team: 'TB', overallRating: 66, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1817.png?im=FaceCrop,padding=0.7' },
  { eaId: 22223, name: 'Christian Braswell', team: 'JAX', overallRating: 66, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2879.png?im=FaceCrop,padding=0.7' },
  { eaId: 23277, name: 'Colton Dowell', team: 'SF', overallRating: 66, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/3095.png?im=FaceCrop,padding=0.7' },
  { eaId: 22249, name: 'Connor Heyward', team: 'LV', overallRating: 66, position: 'TE', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1764.png?im=FaceCrop,padding=0.7' },
  { eaId: 1137, name: 'Daijahn Anthony', team: 'CIN', overallRating: 66, position: 'FS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10000.png?im=FaceCrop,padding=0.7' },
  { eaId: 22280, name: 'Dallis Flowers', team: 'CHI', overallRating: 66, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/3169.png?im=FaceCrop,padding=0.7' },
  { eaId: 16148, name: 'Dan Jackson', team: 'DET', overallRating: 66, position: 'SS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10860.png?im=FaceCrop,padding=0.7' },
  { eaId: 21353, name: 'Daniel Thomas', team: 'CLE', overallRating: 66, position: 'SS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/613.png?im=FaceCrop,padding=0.7' },
  { eaId: 21337, name: 'Danny Pinter', team: 'BAL', overallRating: 66, position: 'C', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/531.png?im=FaceCrop,padding=0.7' },
  { eaId: 22377, name: 'Dareke Young', team: 'LV', overallRating: 66, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/2668.png?im=FaceCrop,padding=0.7' },
  { eaId: 21487, name: 'Darren Hall', team: 'ATL', overallRating: 66, position: 'FS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/1217.png?im=FaceCrop,padding=0.7' },
  { eaId: 16326, name: 'David Blay Jr.', team: 'NE', overallRating: 66, position: 'DT', avatarUrl: 'null' },
  { eaId: 21556, name: 'Davis Mills', team: 'HOU', overallRating: 66, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/969.png?im=FaceCrop,padding=0.7' },
  { eaId: 16392, name: 'Dean Connors', team: 'LAR', overallRating: 66, position: 'RB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11461.png?im=FaceCrop,padding=0.7' },
  { eaId: 1355, name: 'Demontrey Jacobs', team: 'ARI', overallRating: 66, position: 'RT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10919.png?im=FaceCrop,padding=0.7' },
  { eaId: 15169, name: 'Drew Kendall', team: 'PHI', overallRating: 66, position: 'RG', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10622.png?im=FaceCrop,padding=0.7' },
  { eaId: 20328, name: 'Drew Lock', team: 'SEA', overallRating: 66, position: 'QB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/9553.png?im=FaceCrop,padding=0.7' },
  { eaId: 14983, name: 'Dwight McGlothern', team: 'MIN', overallRating: 66, position: 'CB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10171.png?im=FaceCrop,padding=0.7' },
  { eaId: 4774, name: 'Dylan Drummond', team: 'ATL', overallRating: 66, position: 'WR', avatarUrl: 'null' },
  { eaId: 14911, name: 'Edefuan Ulofoshio', team: 'CLE', overallRating: 66, position: 'LB', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10276.png?im=FaceCrop,padding=0.7' },
  { eaId: 4654, name: 'Eli Pancol', team: 'IND', overallRating: 66, position: 'WR', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/11048.png?im=FaceCrop,padding=0.7' },
  { eaId: 14882, name: 'Eric Watts', team: 'NYJ', overallRating: 66, position: 'DT', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/10288.png?im=FaceCrop,padding=0.7' },
  { eaId: 23269, name: 'Erick Hallett II', team: 'TEN', overallRating: 66, position: 'SS', avatarUrl: 'https://ratings-images-prod.pulse.ea.com/madden-nfl-27/portraits/3258.png?im=FaceCrop,padding=0.7' },
];
