import { Player } from '../../types';

export const NFC_EAST_PLAYERS: Player[] = [
  // ===================== DALLAS COWBOYS (DAL) =====================
  {
    id: 'qb-prescott',
    name: 'Dak Prescott',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'QB',
    ovr: 90,
    salary: 60,
    starter: true,
    archetype: 'Pre-Snap Commander / Precise Pocket Passer',
    attributes: { passing: 93, rushing: 72, passBlocking: 0, runBlocking: 0, athleticism: 76, footballIQ: 95 },
    highlightStat: '95 Intermediate Boundary Accuracy & MVP Runner-Up Season',
  },
  {
    id: 'qb-rush',
    name: 'Cooper Rush',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'QB',
    ovr: 74,
    salary: 3,
    starter: false,
    archetype: 'Smart System Backup',
    attributes: { passing: 77, rushing: 60, passBlocking: 0, runBlocking: 0, athleticism: 66, footballIQ: 84 },
    highlightStat: '84 Quick Processing on Slants',
  },
  {
    id: 'qb-lance',
    name: 'Trey Lance',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'QB',
    ovr: 72,
    salary: 5,
    starter: false,
    archetype: 'Dual-Threat Developmental QB',
    attributes: { passing: 72, rushing: 86, passBlocking: 0, runBlocking: 0, athleticism: 89, footballIQ: 72 },
    highlightStat: '88 Designed Rollout Speed',
  },
  {
    id: 'rb-dowdle',
    name: 'Rico Dowdle',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'RB',
    ovr: 79,
    salary: 1,
    archetype: 'Physical Slashing Runner',
    attributes: { passing: 0, rushing: 82, receiving: 76, passBlocking: 74, runBlocking: 0, athleticism: 85, footballIQ: 80 },
    highlightStat: '86 Inside Zone Cutbacks & High Motor',
  },
  {
    id: 'wr-lamb',
    name: 'CeeDee Lamb',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'WR',
    ovr: 96,
    salary: 34,
    archetype: 'Dominant All-Field Alpha (Madden 96)',
    attributes: { passing: 0, rushing: 78, receiving: 98, passBlocking: 0, runBlocking: 66, athleticism: 93, footballIQ: 96 },
    highlightStat: '98 Slot & Boundary Domination, YAC & 135-Catch Production',
  },
  {
    id: 'wr-cooks',
    name: 'Brandin Cooks',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'WR',
    ovr: 81,
    salary: 19,
    archetype: 'Deep Ball Specialist',
    attributes: { passing: 0, rushing: 0, receiving: 83, passBlocking: 0, runBlocking: 50, athleticism: 91, footballIQ: 87 },
    highlightStat: '92 Deep Post Stride & Tracking',
  },
  {
    id: 'te-ferguson-jake',
    name: 'Jake Ferguson',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'TE',
    ovr: 85,
    salary: 1,
    archetype: 'Violent YAC & Seam Target',
    attributes: { passing: 0, rushing: 0, receiving: 87, passBlocking: 73, runBlocking: 80, athleticism: 84, footballIQ: 86 },
    highlightStat: '92 Broken Tackles & Hurdling Defenders',
  },
  {
    id: 'ot-guyton',
    name: 'Tyler Guyton',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'OT',
    ovr: 78,
    salary: 3,
    archetype: 'Freakish Athletic Left Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 79, athleticism: 90, footballIQ: 77 },
    highlightStat: '92 Lateral Kick-Slide Foot Speed',
  },
  {
    id: 'ot-steele-terence',
    name: 'Terence Steele',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'OT',
    ovr: 79,
    salary: 14,
    archetype: 'Power Run Blocking RT',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 85, athleticism: 77, footballIQ: 81 },
    highlightStat: '88 Down-Block Power on Zone Runs',
  },
  {
    id: 'og-smith-tyler',
    name: 'Tyler Smith',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'OG',
    ovr: 89,
    salary: 3,
    archetype: 'Mauling All-Pro Young Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 89, runBlocking: 94, athleticism: 85, footballIQ: 88 },
    highlightStat: '96 Raw Core Power & Violent Pancake Drives',
  },
  {
    id: 'og-martin-zack',
    name: 'Zack Martin',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'OG',
    ovr: 96,
    salary: 18,
    archetype: 'Hall of Fame Perfection (Madden 96)',
    attributes: { passing: 0, rushing: 0, passBlocking: 97, runBlocking: 97, athleticism: 80, footballIQ: 99 },
    highlightStat: '99 Pass Protection Set & Flawless Hand Placement',
  },
  {
    id: 'c-beebe-cooper',
    name: 'Cooper Beebe',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'C',
    ovr: 78,
    salary: 1,
    archetype: 'Mauler Interior Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 79, runBlocking: 84, athleticism: 76, footballIQ: 80 },
    highlightStat: '86 A-Gap Push & Strong Anchor',
  },
  {
    id: 'edge-parsons',
    name: 'Micah Parsons',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'EDGE',
    ovr: 98,
    salary: 4,
    archetype: 'Unstoppable Predator / Pass Rush Freak (Madden 98)',
    attributes: { passRush: 99, runDefense: 92, coverage: 82, athleticism: 98, footballIQ: 97 },
    highlightStat: '99 Fastest Get-Off in NFL, Ghost Bend & Pressure Rate',
  },
  {
    id: 'edge-lawrence-demarcus',
    name: 'DeMarcus Lawrence',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'EDGE',
    ovr: 88,
    salary: 13,
    archetype: 'Elite Run Stopping Edge Setter',
    attributes: { passRush: 86, runDefense: 96, coverage: 65, athleticism: 82, footballIQ: 94 },
    highlightStat: '97 Setting the Edge & Penetrating TFLs',
  },
  {
    id: 'dt-odighizuwa',
    name: 'Osa Odighizuwa',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'DT',
    ovr: 83,
    salary: 1,
    archetype: 'Quick-Twitch 3-Tech Disruptor',
    attributes: { passRush: 86, runDefense: 83, coverage: 50, athleticism: 84, footballIQ: 84 },
    highlightStat: '89 First-Step Inside Penetration',
  },
  {
    id: 'lb-overshown',
    name: 'DeMarvion Overshown',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'LB',
    ovr: 82,
    salary: 1,
    archetype: 'Human Missile Weakside LB',
    attributes: { passRush: 80, runDefense: 85, coverage: 85, athleticism: 93, footballIQ: 82 },
    highlightStat: '94 Sideline-to-Sideline Pursuit Speed',
  },
  {
    id: 'cb-diggs-trevon',
    name: 'Trevon Diggs',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'CB',
    ovr: 89,
    salary: 19,
    archetype: 'Elite WR-Turned-Ballhawk Corner',
    attributes: { passRush: 0, runDefense: 74, coverage: 91, athleticism: 92, footballIQ: 92 },
    highlightStat: '98 Ball Skills, Interception Theft & Return TD Ability',
  },
  {
    id: 'cb-bland',
    name: 'DaRon Bland',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'CB',
    ovr: 88,
    salary: 1,
    archetype: 'NFL Single-Season Pick-6 Record Holder',
    attributes: { passRush: 0, runDefense: 78, coverage: 90, athleticism: 91, footballIQ: 93 },
    highlightStat: '99 Pick-Six Instincts & Break-on-Ball Trajectory',
  },
  {
    id: 's-hooker-malik',
    name: 'Malik Hooker',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'S',
    ovr: 83,
    salary: 7,
    archetype: 'Centerfield Range Safety',
    attributes: { passRush: 60, runDefense: 79, coverage: 87, athleticism: 87, footballIQ: 89 },
    highlightStat: '90 Over-the-Top Deep Ball Erasure',
  },

  // ===================== NEW YORK GIANTS (NYG) =====================
  {
    id: 'qb-jones-daniel',
    name: 'Daniel Jones',
    team: 'NYG',
    teamCity: 'New York',
    position: 'QB',
    ovr: 78,
    salary: 36,
    starter: true,
    archetype: 'Athletic Dual-Threat Pocket Passer',
    attributes: { passing: 80, rushing: 88, passBlocking: 0, runBlocking: 0, athleticism: 89, footballIQ: 81 },
    highlightStat: '90 Designed Scrambles & Read Option Execution',
  },
  {
    id: 'qb-devito',
    name: 'Tommy DeVito',
    team: 'NYG',
    teamCity: 'New York',
    position: 'QB',
    ovr: 71,
    salary: 1,
    starter: false,
    archetype: 'Scrappy Pocket Backup',
    attributes: { passing: 74, rushing: 74, passBlocking: 0, runBlocking: 0, athleticism: 76, footballIQ: 77 },
    highlightStat: '81 Quick Pass Release Under Blitz',
  },
  {
    id: 'qb-lock',
    name: 'Drew Lock',
    team: 'NYG',
    teamCity: 'New York',
    position: 'QB',
    ovr: 73,
    salary: 5,
    starter: false,
    archetype: 'Big-Arm Gunslinger Backup',
    attributes: { passing: 76, rushing: 75, passBlocking: 0, runBlocking: 0, athleticism: 80, footballIQ: 76 },
    highlightStat: '86 Deep Ball Velocity',
  },
  {
    id: 'rb-singletary',
    name: 'Devin Singletary',
    team: 'NYG',
    teamCity: 'New York',
    position: 'RB',
    ovr: 80,
    salary: 5,
    archetype: 'Patient Shifty Runner',
    attributes: { passing: 0, rushing: 83, receiving: 78, passBlocking: 75, runBlocking: 0, athleticism: 84, footballIQ: 84 },
    highlightStat: '88 Zone Read Decisiveness & Low Pad Level',
  },
  {
    id: 'rb-tracy',
    name: 'Tyrone Tracy Jr.',
    team: 'NYG',
    teamCity: 'New York',
    position: 'RB',
    ovr: 78,
    salary: 1,
    archetype: 'WR-Convert Explosive Back',
    attributes: { passing: 0, rushing: 81, receiving: 84, passBlocking: 70, runBlocking: 0, athleticism: 89, footballIQ: 79 },
    highlightStat: '91 Route Running Out of Backfield & Open Field Cuts',
  },
  {
    id: 'wr-nabers',
    name: 'Malik Nabers',
    team: 'NYG',
    teamCity: 'New York',
    position: 'WR',
    ovr: 88,
    salary: 7,
    archetype: 'Explosive Alpha Rookie Dominator',
    attributes: { passing: 0, rushing: 80, receiving: 92, passBlocking: 0, runBlocking: 62, athleticism: 96, footballIQ: 89 },
    highlightStat: '97 Acceleration, Sudden Route Breaks & Target Magnet',
  },
  {
    id: 'wr-slayton',
    name: 'Darius Slayton',
    team: 'NYG',
    teamCity: 'New York',
    position: 'WR',
    ovr: 79,
    salary: 6,
    archetype: 'Deep Boundary Threat',
    attributes: { passing: 0, rushing: 0, receiving: 81, passBlocking: 0, runBlocking: 55, athleticism: 91, footballIQ: 81 },
    highlightStat: '91 Vertical Speed on Go and Post Routes',
  },
  {
    id: 'te-johnson-theo',
    name: 'Theo Johnson',
    team: 'NYG',
    teamCity: 'New York',
    position: 'TE',
    ovr: 78,
    salary: 1,
    archetype: 'Athletic Seam Threat TE',
    attributes: { passing: 0, rushing: 0, receiving: 79, passBlocking: 73, runBlocking: 80, athleticism: 91, footballIQ: 78 },
    highlightStat: '90 Seam Stretch Speed & Red Zone Catch',
  },
  {
    id: 'ot-thomas',
    name: 'Andrew Thomas',
    team: 'NYG',
    teamCity: 'New York',
    position: 'OT',
    ovr: 91,
    salary: 23,
    archetype: 'Elite Blindside Fortress',
    attributes: { passing: 0, rushing: 0, passBlocking: 95, runBlocking: 92, athleticism: 84, footballIQ: 93 },
    highlightStat: '96 Pass Protection Anchor & Complete Edge Lockdown',
  },
  {
    id: 'ot-eluemunor',
    name: 'Jermaine Eluemunor',
    team: 'NYG',
    teamCity: 'New York',
    position: 'OT',
    ovr: 80,
    salary: 7,
    archetype: 'Versatile Starting RT',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 81, athleticism: 77, footballIQ: 84 },
    highlightStat: '85 Pass Set Quickness on Right Edge',
  },
  {
    id: 'og-runyan',
    name: 'Jon Runyan Jr.',
    team: 'NYG',
    teamCity: 'New York',
    position: 'OG',
    ovr: 78,
    salary: 10,
    archetype: 'Pass Pro Inside Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 77, athleticism: 77, footballIQ: 82 },
    highlightStat: '84 Stunt Pickup & Pass Protection Balance',
  },
  {
    id: 'og-van-roten',
    name: 'Greg Van Roten',
    team: 'NYG',
    teamCity: 'New York',
    position: 'OG',
    ovr: 77,
    salary: 3,
    archetype: 'Veteran Interior Stabilizer',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 78, athleticism: 73, footballIQ: 85 },
    highlightStat: '83 Interior Stunt Communication',
  },
  {
    id: 'c-schmitz',
    name: 'John Michael Schmitz Jr.',
    team: 'NYG',
    teamCity: 'New York',
    position: 'C',
    ovr: 78,
    salary: 2,
    archetype: 'Physical Young Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 81, athleticism: 78, footballIQ: 81 },
    highlightStat: '84 Combo Block Climbing',
  },
  {
    id: 'edge-burns',
    name: 'Brian Burns',
    team: 'NYG',
    teamCity: 'New York',
    position: 'EDGE',
    ovr: 89,
    salary: 28,
    archetype: 'Speed & Bend Edge Assassin',
    attributes: { passRush: 92, runDefense: 84, coverage: 74, athleticism: 94, footballIQ: 89 },
    highlightStat: '95 Corner Bend, Ghost Move & Strip Sacks',
  },
  {
    id: 'edge-thibodeaux',
    name: 'Kayvon Thibodeaux',
    team: 'NYG',
    teamCity: 'New York',
    position: 'EDGE',
    ovr: 84,
    salary: 7,
    archetype: 'Explosive Speed-to-Power Edge',
    attributes: { passRush: 87, runDefense: 83, coverage: 65, athleticism: 90, footballIQ: 83 },
    highlightStat: '92 Long-Arm Stab & Double-Digit Sacks',
  },
  {
    id: 'dt-lawrence-dexter',
    name: 'Dexter Lawrence II',
    team: 'NYG',
    teamCity: 'New York',
    position: 'DT',
    ovr: 96,
    salary: 22,
    archetype: 'Unstoppable 340-Pound Nose / Pass Rusher (Madden 96)',
    attributes: { passRush: 97, runDefense: 98, coverage: 40, athleticism: 83, footballIQ: 96 },
    highlightStat: '99 A-Gap Demolition, Center Destruction & Pressure Rate',
  },
  {
    id: 'lb-okereke',
    name: 'Bobby Okereke',
    team: 'NYG',
    teamCity: 'New York',
    position: 'LB',
    ovr: 86,
    salary: 10,
    archetype: 'Every-Down Field General LB',
    attributes: { passRush: 78, runDefense: 89, coverage: 87, athleticism: 86, footballIQ: 92 },
    highlightStat: '93 Tackle Volume & Zone Pass Disruptions',
  },
  {
    id: 'cb-banks-deonte',
    name: 'Deonte Banks',
    team: 'NYG',
    teamCity: 'New York',
    position: 'CB',
    ovr: 80,
    salary: 3,
    archetype: 'Physical 4.35 Press Corner',
    attributes: { passRush: 0, runDefense: 79, coverage: 82, athleticism: 94, footballIQ: 81 },
    highlightStat: '93 Recovery Speed & Press Jam at Scrimmage',
  },
  {
    id: 's-nubin',
    name: 'Tyler Nubin',
    team: 'NYG',
    teamCity: 'New York',
    position: 'S',
    ovr: 78,
    salary: 2,
    archetype: 'Ballhawking Centerfield Safety',
    attributes: { passRush: 60, runDefense: 79, coverage: 84, athleticism: 85, footballIQ: 84 },
    highlightStat: '88 Interception Range & Deep Half Positioning',
  },

  // ===================== PHILADELPHIA EAGLES (PHI) =====================
  {
    id: 'qb-hurts',
    name: 'Jalen Hurts',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'QB',
    ovr: 91,
    salary: 51,
    starter: true,
    archetype: 'Tush Push King / Clutch Dual-Threat',
    attributes: { passing: 89, rushing: 92, passBlocking: 0, runBlocking: 0, athleticism: 90, footballIQ: 93 },
    highlightStat: '99 1-Yard Goal Line Power & Deep Ball Touch',
  },
  {
    id: 'qb-pickett',
    name: 'Kenny Pickett',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'QB',
    ovr: 73,
    salary: 2,
    starter: false,
    archetype: 'Accurate Intermediate Backup',
    attributes: { passing: 75, rushing: 76, passBlocking: 0, runBlocking: 0, athleticism: 80, footballIQ: 78 },
    highlightStat: '82 Rollout Touch Passing',
  },
  {
    id: 'rb-barkley',
    name: 'Saquon Barkley',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'RB',
    ovr: 95,
    salary: 12,
    archetype: 'Superhuman Athlete / Backward Hurdle Legend',
    attributes: { passing: 0, rushing: 96, receiving: 90, passBlocking: 82, runBlocking: 0, athleticism: 97, footballIQ: 93 },
    highlightStat: '99 Spin Move, Backward Hurdle & 70-Yard Breakaways',
  },
  {
    id: 'wr-brown-aj',
    name: 'A.J. Brown',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'WR',
    ovr: 95,
    salary: 32,
    archetype: 'Immovable YAC Behemoth Alpha',
    attributes: { passing: 0, rushing: 75, receiving: 97, passBlocking: 0, runBlocking: 75, athleticism: 93, footballIQ: 94 },
    highlightStat: '99 Slant Route Bullying & Broken Tackle Touchdowns',
  },
  {
    id: 'wr-smith-devonta',
    name: 'DeVonta Smith',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'WR',
    ovr: 89,
    salary: 25,
    archetype: 'The Slim Reaper / Flawless Route Technician',
    attributes: { passing: 0, rushing: 0, receiving: 93, passBlocking: 0, runBlocking: 62, athleticism: 92, footballIQ: 95 },
    highlightStat: '97 Toe-Tap Sideline Acrobatic Catches',
  },
  {
    id: 'wr-dotson-jahan',
    name: 'Jahan Dotson',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'WR',
    ovr: 79,
    salary: 3,
    archetype: 'Speed Slot / In-Between Weapon',
    attributes: { passing: 0, rushing: 0, receiving: 82, passBlocking: 0, runBlocking: 55, athleticism: 91, footballIQ: 81 },
    highlightStat: '88 Deep Post & Cross Route Tracking',
  },
  {
    id: 'te-goedert',
    name: 'Dallas Goedert',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'TE',
    ovr: 88,
    salary: 14,
    archetype: 'Complete In-Line & YAC Monster',
    attributes: { passing: 0, rushing: 0, receiving: 89, passBlocking: 80, runBlocking: 88, athleticism: 85, footballIQ: 91 },
    highlightStat: '94 Screen Route YAC & Dominant In-Line Blocking',
  },
  {
    id: 'ot-mailata',
    name: 'Jordan Mailata',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'OT',
    ovr: 92,
    salary: 22,
    archetype: 'Rugby Giant Blindside Wall',
    attributes: { passing: 0, rushing: 0, passBlocking: 94, runBlocking: 96, athleticism: 86, footballIQ: 91 },
    highlightStat: '98 Overwhelming Size, Strike Power & Downfield Screener',
  },
  {
    id: 'ot-johnson-lane',
    name: 'Lane Johnson',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'OT',
    ovr: 96,
    salary: 16,
    archetype: 'Greatest Right Tackle in Football (Madden 96)',
    attributes: { passing: 0, rushing: 0, passBlocking: 98, runBlocking: 96, athleticism: 89, footballIQ: 98 },
    highlightStat: '99 Zero Sacks Allowed Streak & Historic Set Quickness',
  },
  {
    id: 'og-dickerson',
    name: 'Landon Dickerson',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'OG',
    ovr: 89,
    salary: 21,
    archetype: 'Road-Grader Guard Titan',
    attributes: { passing: 0, rushing: 0, passBlocking: 89, runBlocking: 95, athleticism: 80, footballIQ: 90 },
    highlightStat: '97 Tush Push Push Force & Inside Gap Clearing',
  },
  {
    id: 'og-becton',
    name: 'Mekhi Becton',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'OG',
    ovr: 82,
    salary: 3,
    archetype: 'Giant Mountain Right Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 83, runBlocking: 88, athleticism: 78, footballIQ: 80 },
    highlightStat: '93 Raw Core Displacement in Gap Scheme',
  },
  {
    id: 'c-jurgens',
    name: 'Cam Jurgens',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'C',
    ovr: 84,
    salary: 2,
    archetype: 'Athletic Kelce Successor Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 85, runBlocking: 88, athleticism: 89, footballIQ: 88 },
    highlightStat: '92 Second Level Reach & Screen Pulling Speed',
  },
  {
    id: 'edge-sweat-josh',
    name: 'Josh Sweat',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'EDGE',
    ovr: 85,
    salary: 10,
    archetype: 'Long-Arm Dip Rusher',
    attributes: { passRush: 88, runDefense: 84, coverage: 62, athleticism: 88, footballIQ: 86 },
    highlightStat: '92 Long-Arm Bull Rush on 3rd Down',
  },
  {
    id: 'edge-smith-nolan',
    name: 'Nolan Smith',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'EDGE',
    ovr: 79,
    salary: 3,
    archetype: '4.39 Speed Rusher',
    attributes: { passRush: 82, runDefense: 80, coverage: 70, athleticism: 96, footballIQ: 79 },
    highlightStat: '95 Edge Closing Burst to the Quarterback',
  },
  {
    id: 'dt-carter',
    name: 'Jalen Carter',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'DT',
    ovr: 90,
    salary: 5,
    archetype: 'Unstoppable Interior Game-Wrecker',
    attributes: { passRush: 94, runDefense: 92, coverage: 50, athleticism: 90, footballIQ: 89 },
    highlightStat: '97 Swim-Rip Speed & Dissecting Double Teams',
  },
  {
    id: 'dt-davis-jordan',
    name: 'Jordan Davis',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'DT',
    ovr: 83,
    salary: 4,
    archetype: '340-Pound Run Eradicator',
    attributes: { passRush: 75, runDefense: 95, coverage: 40, athleticism: 82, footballIQ: 85 },
    highlightStat: '98 0-Tech Double Team Absorption',
  },
  {
    id: 'lb-baun',
    name: 'Zack Baun',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'LB',
    ovr: 86,
    salary: 2,
    archetype: 'Breakout All-Field Defensive Weapon',
    attributes: { passRush: 86, runDefense: 89, coverage: 86, athleticism: 88, footballIQ: 91 },
    highlightStat: '94 Strip-Sacks, TFLs & Over-the-Middle Coverage',
  },
  {
    id: 'cb-mitchell-quinyon',
    name: 'Quinyon Mitchell',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'CB',
    ovr: 84,
    salary: 4,
    archetype: '4.33 Lockdown Rookie Island',
    attributes: { passRush: 0, runDefense: 81, coverage: 89, athleticism: 96, footballIQ: 87 },
    highlightStat: '95 Zero Deep Passes Allowed & High-Point Breakups',
  },
  {
    id: 'cb-dejean-cooper',
    name: 'Cooper DeJean',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'CB',
    ovr: 83,
    salary: 2,
    archetype: 'Electrifying Nickel / Return Sensation',
    attributes: { passRush: 76, runDefense: 88, coverage: 87, athleticism: 94, footballIQ: 90 },
    highlightStat: '94 Slot Tackling for Loss & Punt Return Threat',
  },
  {
    id: 'cb-slay',
    name: 'Darius Slay Jr.',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'CB',
    ovr: 86,
    salary: 14,
    archetype: 'Big Play Slay / Master of Cover 3',
    attributes: { passRush: 0, runDefense: 75, coverage: 89, athleticism: 88, footballIQ: 94 },
    highlightStat: '92 Route Anticipation & Deep Sideline Eradication',
  },
  {
    id: 's-blankenship',
    name: 'Reed Blankenship',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'S',
    ovr: 83,
    salary: 4,
    archetype: 'Instinctive Alley Fill & Ballhawk',
    attributes: { passRush: 65, runDefense: 87, coverage: 85, athleticism: 85, footballIQ: 90 },
    highlightStat: '91 Red-Zone Interceptions & Sure Tackling',
  },

  // ===================== WASHINGTON COMMANDERS (WAS) =====================
  {
    id: 'qb-daniels',
    name: 'Jayden Daniels',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'QB',
    ovr: 88,
    salary: 9,
    starter: true,
    archetype: 'Offensive Rookie of the Year / Hail Mary Magician',
    attributes: { passing: 91, rushing: 95, passBlocking: 0, runBlocking: 0, athleticism: 96, footballIQ: 92 },
    highlightStat: '97 Deep Ball Accuracy, 4.4 Speed & Game-Winning Hail Marys',
  },
  {
    id: 'qb-mariota',
    name: 'Marcus Mariota',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'QB',
    ovr: 74,
    salary: 6,
    starter: false,
    archetype: 'Athletic Option Backup',
    attributes: { passing: 74, rushing: 86, passBlocking: 0, runBlocking: 0, athleticism: 88, footballIQ: 81 },
    highlightStat: '89 Read-Option Run Execution',
  },
  {
    id: 'rb-robinson-brian',
    name: 'Brian Robinson Jr.',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'RB',
    ovr: 84,
    salary: 1,
    archetype: 'Downhill Power Punisher',
    attributes: { passing: 0, rushing: 87, receiving: 78, passBlocking: 82, runBlocking: 0, athleticism: 83, footballIQ: 86 },
    highlightStat: '92 Yards After Contact & Goal-Line Conversion',
  },
  {
    id: 'rb-ekeler',
    name: 'Austin Ekeler',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'RB',
    ovr: 82,
    salary: 4,
    archetype: 'PPR Receiving Machine',
    attributes: { passing: 0, rushing: 80, receiving: 89, passBlocking: 76, runBlocking: 0, athleticism: 87, footballIQ: 88 },
    highlightStat: '93 Route Running out of Backfield & Kick Return Burst',
  },
  {
    id: 'wr-mclaurin',
    name: 'Terry McLaurin',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'WR',
    ovr: 91,
    salary: 23,
    archetype: 'Scary Terry / Uncontested Deep Track Master',
    attributes: { passing: 0, rushing: 0, receiving: 94, passBlocking: 0, runBlocking: 70, athleticism: 93, footballIQ: 94 },
    highlightStat: '97 Contested Deep Catches & 4.35 Speed',
  },
  {
    id: 'te-ertz',
    name: 'Zach Ertz',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'TE',
    ovr: 82,
    salary: 3,
    archetype: 'Veteran 3rd Down Chain-Mover',
    attributes: { passing: 0, rushing: 0, receiving: 85, passBlocking: 68, runBlocking: 74, athleticism: 75, footballIQ: 94 },
    highlightStat: '92 High-Percentage 3rd Down Catch Radius',
  },
  {
    id: 'ot-lucas-cornelius',
    name: 'Cornelius Lucas',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'OT',
    ovr: 79,
    salary: 4,
    archetype: 'Veteran Edge Protector',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 78, athleticism: 74, footballIQ: 85 },
    highlightStat: '85 Wingspan & Recovery vs Speed Rushers',
  },
  {
    id: 'ot-coleman-brandon',
    name: 'Brandon Coleman',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'OT',
    ovr: 77,
    salary: 2,
    archetype: 'Athletic Rookie Blindside OT',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 80, athleticism: 88, footballIQ: 76 },
    highlightStat: '89 Lateral Recovery & Mobility',
  },
  {
    id: 'og-cosmi',
    name: 'Sam Cosmi',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'OG',
    ovr: 86,
    salary: 18,
    archetype: 'Elite Pulling Power Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 87, runBlocking: 91, athleticism: 86, footballIQ: 89 },
    highlightStat: '94 Second-Level Screen & Gap Blocking',
  },
  {
    id: 'og-allegretti',
    name: 'Nick Allegretti',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'OG',
    ovr: 78,
    salary: 5,
    archetype: 'Tough Interior Battler',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 80, athleticism: 74, footballIQ: 85 },
    highlightStat: '84 Stunt Awareness & Interior Grit',
  },
  {
    id: 'c-biadasz',
    name: 'Tyler Biadasz',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'C',
    ovr: 80,
    salary: 10,
    archetype: 'Anchor Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 81, athleticism: 78, footballIQ: 86 },
    highlightStat: '86 Line Identification & Shotgun Snap Accuracy',
  },
  {
    id: 'edge-fowler',
    name: 'Dante Fowler Jr.',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'EDGE',
    ovr: 81,
    salary: 3,
    archetype: 'Quinn-Scheme Speed Rusher',
    attributes: { passRush: 85, runDefense: 76, coverage: 65, athleticism: 87, footballIQ: 82 },
    highlightStat: '89 Strip Sacks & First-Step Burst',
  },
  {
    id: 'dt-allen-jonathan',
    name: 'Jonathan Allen',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'DT',
    ovr: 88,
    salary: 18,
    archetype: 'Interior Power Wrecker',
    attributes: { passRush: 90, runDefense: 90, coverage: 50, athleticism: 81, footballIQ: 92 },
    highlightStat: '94 Club-Rip & Pocket Compression',
  },
  {
    id: 'dt-payne',
    name: 'Daron Payne',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'DT',
    ovr: 86,
    salary: 22,
    archetype: 'Heavy 1-Tech Penetrator',
    attributes: { passRush: 87, runDefense: 89, coverage: 48, athleticism: 83, footballIQ: 88 },
    highlightStat: '91 Bull Rush Power in A-Gap',
  },
  {
    id: 'lb-wagner',
    name: 'Bobby Wagner',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'LB',
    ovr: 90,
    salary: 6,
    archetype: 'Hall of Fame Field General (Madden 90)',
    attributes: { passRush: 78, runDefense: 96, coverage: 85, athleticism: 78, footballIQ: 99 },
    highlightStat: '99 Play Recognition, Sure Tackling & Leadership',
  },
  {
    id: 'lb-luvu',
    name: 'Frankie Luvu',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'LB',
    ovr: 87,
    salary: 11,
    archetype: 'Relentless Chaos & Blitz Specialist',
    attributes: { passRush: 89, runDefense: 91, coverage: 82, athleticism: 90, footballIQ: 90 },
    highlightStat: '95 Blitz Pressure, Forced Fumbles & TFLs',
  },
  {
    id: 'cb-sainristil',
    name: 'Mike Sainristil',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'CB',
    ovr: 80,
    salary: 2,
    archetype: 'Instinctive Slot Turnover Hawk',
    attributes: { passRush: 75, runDefense: 82, coverage: 83, athleticism: 90, footballIQ: 89 },
    highlightStat: '91 Clutch PBU & Slot Trailing',
  },
  {
    id: 'cb-lattimore',
    name: 'Marshon Lattimore',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'CB',
    ovr: 89,
    salary: 16,
    archetype: 'Pro Bowl Lock Boundary Island',
    attributes: { passRush: 0, runDefense: 79, coverage: 92, athleticism: 91, footballIQ: 93 },
    highlightStat: '94 Physical Press Against Elite WR1s',
  },
  {
    id: 's-chinn',
    name: 'Jeremy Chinn',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'S',
    ovr: 81,
    salary: 4,
    archetype: 'Hybrid Safety/Linebacker Enforcer',
    attributes: { passRush: 78, runDefense: 86, coverage: 80, athleticism: 92, footballIQ: 82 },
    highlightStat: '90 Downhill Hits in the C-Gap',
  },
  // --- NFC East Kickers & Special Teams ---
  {
    id: 'k-aubrey-brandon',
    name: 'Brandon Aubrey',
    team: 'DAL',
    teamCity: 'Dallas',
    position: 'K',
    ovr: 92,
    salary: 4,
    starter: true,
    archetype: '65+ Yard Infinite Range Weapon',
    attributes: { passing: 0, rushing: 0, kicking: 98, athleticism: 85, footballIQ: 93 },
    highlightStat: '65-Yard & 66-Yard NFL Bombs with Effortless Precision',
  },
  {
    id: 'k-gano-graham',
    name: 'Graham Gano',
    team: 'NYG',
    teamCity: 'New York',
    position: 'K',
    ovr: 80,
    salary: 3,
    starter: true,
    archetype: 'Veteran Clutch Placekicker',
    attributes: { passing: 0, rushing: 0, kicking: 84, athleticism: 73, footballIQ: 91 },
    highlightStat: '63-Yard Career Long & Cold Weather Veteran',
  },
  {
    id: 'k-elliott-jake',
    name: 'Jake Elliott',
    team: 'PHI',
    teamCity: 'Philadelphia',
    position: 'K',
    ovr: 89,
    salary: 6,
    starter: true,
    archetype: 'Super Bowl Ice-Cold Clutch Champion',
    attributes: { passing: 0, rushing: 0, kicking: 94, athleticism: 82, footballIQ: 96 },
    highlightStat: '61-Yard Miracle Walk-Off & 94% Postseason Field Goal Accuracy',
  },
  {
    id: 'k-seibert-austin',
    name: 'Austin Seibert',
    team: 'WAS',
    teamCity: 'Washington',
    position: 'K',
    ovr: 83,
    salary: 2,
    starter: true,
    archetype: 'Clutch High-Percentage Scorer',
    attributes: { passing: 0, rushing: 0, kicking: 87, athleticism: 74, footballIQ: 85 },
    highlightStat: '7-for-7 Single-Game Franchise Record Performance',
  },
];
