import { Player } from '../../types';

export const NFC_NORTH_PLAYERS: Player[] = [
  // ===================== CHICAGO BEARS (CHI) =====================
  {
    id: 'qb-williams-caleb',
    name: 'Caleb Williams',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'QB',
    ovr: 80,
    salary: 10,
    starter: true,
    archetype: 'Off-Platform Playmaker Prodigy',
    attributes: { passing: 84, rushing: 84, passBlocking: 0, runBlocking: 0, athleticism: 89, footballIQ: 81 },
    highlightStat: '94 Off-Schedule Arm Angles & Arm Strength',
  },
  {
    id: 'qb-bagent',
    name: 'Tyson Bagent',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'QB',
    ovr: 72,
    salary: 1,
    starter: false,
    archetype: 'Quick-Release High-IQ Backup',
    attributes: { passing: 74, rushing: 75, passBlocking: 0, runBlocking: 0, athleticism: 77, footballIQ: 81 },
    highlightStat: '82 Rhythm Processing & Quick Throw',
  },
  {
    id: 'rb-swift',
    name: 'D\'Andre Swift',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'RB',
    ovr: 84,
    salary: 8,
    archetype: 'Perimeter Shifty Slash & Catch',
    attributes: { passing: 0, rushing: 86, receiving: 85, passBlocking: 72, runBlocking: 0, athleticism: 92, footballIQ: 84 },
    highlightStat: '93 Cutback Acceleration & Angle Breaking',
  },
  {
    id: 'wr-moore',
    name: 'DJ Moore',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'WR',
    ovr: 89,
    salary: 27,
    archetype: 'RB-Built YAC Freight Train',
    attributes: { passing: 0, rushing: 75, receiving: 91, passBlocking: 0, runBlocking: 70, athleticism: 93, footballIQ: 91 },
    highlightStat: '96 Contact Balance on Slants & Screens',
  },
  {
    id: 'wr-allen-keenan',
    name: 'Keenan Allen',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'WR',
    ovr: 88,
    salary: 23,
    archetype: 'Master of Separation / 3rd Down King',
    attributes: { passing: 0, rushing: 0, receiving: 93, passBlocking: 0, runBlocking: 55, athleticism: 81, footballIQ: 98 },
    highlightStat: '98 Unstoppable Option Routes & Hands',
  },
  {
    id: 'wr-odunze',
    name: 'Rome Odunze',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'WR',
    ovr: 82,
    salary: 6,
    archetype: 'Elite Contested Ball Boundary Weapon',
    attributes: { passing: 0, rushing: 0, receiving: 85, passBlocking: 0, runBlocking: 66, athleticism: 92, footballIQ: 83 },
    highlightStat: '94 High-Point Catch Radius & Body Positioning',
  },
  {
    id: 'te-kmet',
    name: 'Cole Kmet',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'TE',
    ovr: 83,
    salary: 12,
    archetype: 'Red-Zone In-Line Security',
    attributes: { passing: 0, rushing: 0, receiving: 84, passBlocking: 76, runBlocking: 83, athleticism: 80, footballIQ: 87 },
    highlightStat: '89 Seam Catches & End-Zone Targets',
  },
  {
    id: 'ot-jones-braxton',
    name: 'Braxton Jones',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'OT',
    ovr: 81,
    salary: 1,
    archetype: 'Athletic Zone Left Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 84, athleticism: 85, footballIQ: 81 },
    highlightStat: '86 Outside Zone Reach Prowess',
  },
  {
    id: 'ot-wright-darnell',
    name: 'Darnell Wright',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'OT',
    ovr: 83,
    salary: 5,
    archetype: 'Power-Anchored Right Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 84, runBlocking: 86, athleticism: 85, footballIQ: 82 },
    highlightStat: '90 Anchor vs Elite Power Edge Rushers',
  },
  {
    id: 'og-jenkins-teven',
    name: 'Teven Jenkins',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'OG',
    ovr: 83,
    salary: 2,
    archetype: 'Violent Interior Road-Grader',
    attributes: { passing: 0, rushing: 0, passBlocking: 84, runBlocking: 88, athleticism: 81, footballIQ: 82 },
    highlightStat: '92 Finish-Through-the-Whistle Pancake Blocks',
  },
  {
    id: 'og-pryor-matt',
    name: 'Matt Pryor',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'OG',
    ovr: 77,
    salary: 1,
    archetype: 'Massive Power Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 80, athleticism: 70, footballIQ: 79 },
    highlightStat: '84 Point-of-Attack Size Displacement',
  },
  {
    id: 'c-shelton-coleman',
    name: 'Coleman Shelton',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'C',
    ovr: 78,
    salary: 3,
    archetype: 'Mobile Zone Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 79, runBlocking: 81, athleticism: 80, footballIQ: 83 },
    highlightStat: '85 Outside Reach Blocking on Stretch Plays',
  },
  {
    id: 'edge-sweat-montez',
    name: 'Montez Sweat',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'EDGE',
    ovr: 89,
    salary: 24,
    archetype: 'Long-Limbed 4.41 Speed-Power Freak',
    attributes: { passRush: 91, runDefense: 90, coverage: 65, athleticism: 94, footballIQ: 89 },
    highlightStat: '96 Long-Arm Push & Relentless Edge Penetration',
  },
  {
    id: 'dt-dexter',
    name: 'Gervon Dexter Sr.',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'DT',
    ovr: 81,
    salary: 2,
    archetype: 'Towering 3-Tech Pocket Pusher',
    attributes: { passRush: 84, runDefense: 82, coverage: 45, athleticism: 84, footballIQ: 81 },
    highlightStat: '88 Interior QB Pressure & Batting Passes',
  },
  {
    id: 'dt-billings',
    name: 'Andrew Billings',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'DT',
    ovr: 82,
    salary: 4,
    archetype: '325-Pound Run Brick Wall',
    attributes: { passRush: 74, runDefense: 93, coverage: 35, athleticism: 68, footballIQ: 84 },
    highlightStat: '95 Run Stuffs in A-Gap',
  },
  {
    id: 'lb-edwards',
    name: 'T.J. Edwards',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'LB',
    ovr: 87,
    salary: 6,
    archetype: 'Instinctive Flow & Tackle Master',
    attributes: { passRush: 76, runDefense: 93, coverage: 88, athleticism: 82, footballIQ: 95 },
    highlightStat: '96 Tackle Volume & Hook-Zone Interceptions',
  },
  {
    id: 'lb-edmunds',
    name: 'Tremaine Edmunds',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'LB',
    ovr: 84,
    salary: 18,
    archetype: '6-Foot-5 Giant Middle Zone Eraser',
    attributes: { passRush: 75, runDefense: 85, coverage: 89, athleticism: 91, footballIQ: 89 },
    highlightStat: '94 Passing Lane Swats & Tampa-2 Middle Deep Range',
  },
  {
    id: 'cb-johnson-jaylon',
    name: 'Jaylon Johnson',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'CB',
    ovr: 93,
    salary: 19,
    archetype: 'All-Pro Sticky Lockdown Island',
    attributes: { passRush: 0, runDefense: 83, coverage: 96, athleticism: 91, footballIQ: 96 },
    highlightStat: '98 Passer Rating Against Under 40.0 & Route Eradication',
  },
  {
    id: 'cb-gordon-kyler',
    name: 'Kyler Gordon',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'CB',
    ovr: 83,
    salary: 1,
    archetype: 'Acrobatic Spider Nickel',
    attributes: { passRush: 78, runDefense: 86, coverage: 86, athleticism: 92, footballIQ: 87 },
    highlightStat: '93 Slot Blitz TFLs & Flying Interceptions',
  },
  {
    id: 's-byard',
    name: 'Kevin Byard III',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'S',
    ovr: 85,
    salary: 7,
    archetype: 'Savvy Ballhawk Free Safety',
    attributes: { passRush: 62, runDefense: 81, coverage: 89, athleticism: 83, footballIQ: 95 },
    highlightStat: '93 Deep Centerfield Interception Reading',
  },
  {
    id: 's-brisker',
    name: 'Jaquan Brisker',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'S',
    ovr: 84,
    salary: 1,
    archetype: 'Hard-Hitting Enforcer Strong Safety',
    attributes: { passRush: 82, runDefense: 89, coverage: 82, athleticism: 89, footballIQ: 86 },
    highlightStat: '94 Downhill Decapitations & Disguised Edge Blitzes',
  },

  // ===================== DETROIT LIONS (DET) =====================
  {
    id: 'qb-goff',
    name: 'Jared Goff',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'QB',
    ovr: 88,
    salary: 53,
    starter: true,
    archetype: 'Deadly Play-Action Pocket Surgeon',
    attributes: { passing: 93, rushing: 60, passBlocking: 0, runBlocking: 0, athleticism: 66, footballIQ: 94 },
    highlightStat: '96 Clean Pocket Completion % & Middle-Field Velocity',
  },
  {
    id: 'qb-hooker',
    name: 'Hendon Hooker',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'QB',
    ovr: 72,
    salary: 1,
    starter: false,
    archetype: 'Strong-Armed Dual-Threat Backup',
    attributes: { passing: 75, rushing: 79, passBlocking: 0, runBlocking: 0, athleticism: 83, footballIQ: 75 },
    highlightStat: '85 Deep Ball Trajectory',
  },
  {
    id: 'rb-gibbs',
    name: 'Jahmyr Gibbs',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'RB',
    ovr: 89,
    salary: 4,
    archetype: 'Sonic Speed / Angle Breaker',
    attributes: { passing: 0, rushing: 92, receiving: 90, passBlocking: 70, runBlocking: 0, athleticism: 96, footballIQ: 88 },
    highlightStat: '98 0-to-60 Acceleration & Untouchable Home Runs',
  },
  {
    id: 'rb-montgomery',
    name: 'David Montgomery',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'RB',
    ovr: 87,
    salary: 6,
    archetype: 'Unstoppable Contact Balancer',
    attributes: { passing: 0, rushing: 91, receiving: 80, passBlocking: 84, runBlocking: 0, athleticism: 84, footballIQ: 91 },
    highlightStat: '97 Broken Tackles & Touchdown Inevitability',
  },
  {
    id: 'wr-arsb',
    name: 'Amon-Ra St. Brown',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'WR',
    ovr: 95,
    salary: 30,
    archetype: 'The Sun God / Iron Toughness Alpha (Madden 95)',
    attributes: { passing: 0, rushing: 78, receiving: 97, passBlocking: 0, runBlocking: 82, athleticism: 91, footballIQ: 98 },
    highlightStat: '99 3rd Down Conversions, Hands & Run Blocking Ferocity',
  },
  {
    id: 'wr-williams-jameson',
    name: 'Jameson Williams',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'WR',
    ovr: 82,
    salary: 4,
    archetype: 'Rocket-Fuel Deep Threat',
    attributes: { passing: 0, rushing: 75, receiving: 83, passBlocking: 0, runBlocking: 55, athleticism: 98, footballIQ: 80 },
    highlightStat: '98 Pure Speed & 70-Yard Touchdowns',
  },
  {
    id: 'te-laporta',
    name: 'Sam LaPorta',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'TE',
    ovr: 89,
    salary: 2,
    archetype: 'All-Pro Receiving Machine',
    attributes: { passing: 0, rushing: 0, receiving: 92, passBlocking: 76, runBlocking: 84, athleticism: 88, footballIQ: 92 },
    highlightStat: '95 Seam Catches, Touchdown Nose & YAC',
  },
  {
    id: 'ot-sewell',
    name: 'Penei Sewell',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'OT',
    ovr: 96,
    salary: 28,
    archetype: 'Generational Offensive Weapon (Madden 96)',
    attributes: { passing: 0, rushing: 0, passBlocking: 96, runBlocking: 99, athleticism: 92, footballIQ: 97 },
    highlightStat: '99 Space Blocking, Pancake Annihilations & Zero Pressure Allowed',
  },
  {
    id: 'ot-decker',
    name: 'Taylor Decker',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'OT',
    ovr: 86,
    salary: 20,
    archetype: 'Veteran Blindside Anchor',
    attributes: { passing: 0, rushing: 0, passBlocking: 88, runBlocking: 87, athleticism: 78, footballIQ: 91 },
    highlightStat: '90 Pass Set Stability & Veteran Leadership',
  },
  {
    id: 'og-zeitler',
    name: 'Kevin Zeitler',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'OG',
    ovr: 85,
    salary: 6,
    archetype: 'Pro Bowl Interior Pass Protector',
    attributes: { passing: 0, rushing: 0, passBlocking: 91, runBlocking: 85, athleticism: 75, footballIQ: 94 },
    highlightStat: '93 Interior Bull Rush Absorption',
  },
  {
    id: 'og-glasgow',
    name: 'Graham Glasgow',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'OG',
    ovr: 82,
    salary: 7,
    archetype: 'Versatile Power Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 83, runBlocking: 84, athleticism: 74, footballIQ: 88 },
    highlightStat: '87 Gap Scheme Combo Blocks',
  },
  {
    id: 'c-ragnow',
    name: 'Frank Ragnow',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'C',
    ovr: 93,
    salary: 13,
    archetype: 'Warrior Elite Center (Madden 93)',
    attributes: { passing: 0, rushing: 0, passBlocking: 93, runBlocking: 97, athleticism: 84, footballIQ: 97 },
    highlightStat: '98 Inside Zone Demolition & Playing Through Injuries',
  },
  {
    id: 'edge-hutchinson',
    name: 'Aidan Hutchinson',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'EDGE',
    ovr: 94,
    salary: 9,
    archetype: 'Relentless High-Motor Game Wrecker',
    attributes: { passRush: 96, runDefense: 92, coverage: 74, athleticism: 92, footballIQ: 96 },
    highlightStat: '98 Spin-Move Velocity & Highest Pressure Rate in Football',
  },
  {
    id: 'edge-smith-zadarius',
    name: 'Za\'Darius Smith',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'EDGE',
    ovr: 83,
    salary: 11,
    archetype: 'Inside-Out Hybrid Pass Rusher',
    attributes: { passRush: 87, runDefense: 81, coverage: 62, athleticism: 81, footballIQ: 87 },
    highlightStat: '89 3-Tech Alignment Stunts & Sacks',
  },
  {
    id: 'dt-mcneill',
    name: 'Alim McNeill',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'DT',
    ovr: 88,
    salary: 24,
    archetype: 'Dancing Bear Interior Disruptor',
    attributes: { passRush: 90, runDefense: 92, coverage: 50, athleticism: 85, footballIQ: 90 },
    highlightStat: '94 Quick-Twitch Interior Gap Explosion & Sacks',
  },
  {
    id: 'dt-reader',
    name: 'DJ Reader',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'DT',
    ovr: 87,
    salary: 13,
    archetype: 'Nose Tackle Run Wall',
    attributes: { passRush: 76, runDefense: 97, coverage: 35, athleticism: 68, footballIQ: 92 },
    highlightStat: '98 0-Tech Double Team Eradication',
  },
  {
    id: 'lb-campbell-jack',
    name: 'Jack Campbell',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'LB',
    ovr: 84,
    salary: 3,
    archetype: '6-Foot-5 Thumping Middle LB',
    attributes: { passRush: 79, runDefense: 90, coverage: 82, athleticism: 88, footballIQ: 89 },
    highlightStat: '93 Downhill Tackle For Loss & Run Fits',
  },
  {
    id: 'lb-anzalone',
    name: 'Alex Anzalone',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'LB',
    ovr: 83,
    salary: 6,
    archetype: 'Captain & Flow Tackler',
    attributes: { passRush: 78, runDefense: 85, coverage: 84, athleticism: 85, footballIQ: 92 },
    highlightStat: '90 Defensive Signal Calling & Blitz Sacks',
  },
  {
    id: 'cb-arnold-terrion',
    name: 'Terrion Arnold',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'CB',
    ovr: 79,
    salary: 3,
    archetype: 'Fiery Press-Man Boundary',
    attributes: { passRush: 0, runDefense: 79, coverage: 82, athleticism: 91, footballIQ: 81 },
    highlightStat: '88 Physical Press & Competitive Motor',
  },
  {
    id: 's-branch',
    name: 'Brian Branch',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'S',
    ovr: 92,
    salary: 2,
    archetype: 'All-Pro Star / Safety / Ballhawk Sensation',
    attributes: { passRush: 84, runDefense: 94, coverage: 95, athleticism: 91, footballIQ: 97 },
    highlightStat: '98 Instinctive Interceptions, PBU & Sure-Tackling in Space',
  },
  {
    id: 's-joseph-kerby',
    name: 'Kerby Joseph',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'S',
    ovr: 88,
    salary: 1,
    archetype: 'Centerfield Interception Thief',
    attributes: { passRush: 60, runDefense: 80, coverage: 93, athleticism: 90, footballIQ: 93 },
    highlightStat: '97 League-Leading Deep Interception Range',
  },

  // ===================== GREEN BAY PACKERS (GB) =====================
  {
    id: 'qb-love',
    name: 'Jordan Love',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'QB',
    ovr: 89,
    salary: 55,
    starter: true,
    archetype: 'Fearless Laser Gunslinger',
    attributes: { passing: 92, rushing: 78, passBlocking: 0, runBlocking: 0, athleticism: 84, footballIQ: 91 },
    highlightStat: '96 Arm Talent, Tight-Window Touchdowns & Off-Platform Poise',
  },
  {
    id: 'qb-willis',
    name: 'Malik Willis',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'QB',
    ovr: 78,
    salary: 3,
    starter: false,
    archetype: 'Explosive Dual-Threat Playmaker Backup',
    attributes: { passing: 79, rushing: 92, passBlocking: 0, runBlocking: 0, athleticism: 94, footballIQ: 79 },
    highlightStat: '94 Acceleration & Undefeated Spot-Start Execution',
  },
  {
    id: 'qb-clifford',
    name: 'Sean Clifford',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'QB',
    ovr: 69,
    salary: 1,
    starter: false,
    archetype: 'Scrappy Athletic Backup',
    attributes: { passing: 71, rushing: 76, passBlocking: 0, runBlocking: 0, athleticism: 78, footballIQ: 76 },
    highlightStat: '79 Scramble Mobility',
  },
  {
    id: 'rb-jacobs-josh',
    name: 'Josh Jacobs',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'RB',
    ovr: 90,
    salary: 12,
    archetype: 'Violent Cutback & Contact Engine',
    attributes: { passing: 0, rushing: 93, receiving: 83, passBlocking: 82, runBlocking: 0, athleticism: 88, footballIQ: 93 },
    highlightStat: '97 Broken Tackles, Trucking & 4th Quarter Closers',
  },
  {
    id: 'wr-reed-jayden',
    name: 'Jayden Reed',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'WR',
    ovr: 85,
    salary: 2,
    archetype: 'All-Purpose Electric Dynamic Weapon',
    attributes: { passing: 0, rushing: 85, receiving: 88, passBlocking: 0, runBlocking: 60, athleticism: 94, footballIQ: 88 },
    highlightStat: '96 Jet Sweep & Slot Crossing Explosions',
  },
  {
    id: 'wr-doubs',
    name: 'Romeo Doubs',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'WR',
    ovr: 81,
    salary: 1,
    archetype: 'Contested Catch Clutch Endzone Target',
    attributes: { passing: 0, rushing: 0, receiving: 84, passBlocking: 0, runBlocking: 68, athleticism: 85, footballIQ: 85 },
    highlightStat: '91 Red-Zone & Playoff Contested Catches',
  },
  {
    id: 'wr-watson-christian',
    name: 'Christian Watson',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'WR',
    ovr: 81,
    salary: 2,
    archetype: '6-Foot-4 4.36 Homerun Threat',
    attributes: { passing: 0, rushing: 76, receiving: 82, passBlocking: 0, runBlocking: 68, athleticism: 97, footballIQ: 79 },
    highlightStat: '98 Breakaway Vertical Speed & Stride',
  },
  {
    id: 'te-kraft',
    name: 'Tucker Kraft',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'TE',
    ovr: 84,
    salary: 1,
    archetype: 'Violent YAC Tight End',
    attributes: { passing: 0, rushing: 0, receiving: 85, passBlocking: 76, runBlocking: 86, athleticism: 87, footballIQ: 86 },
    highlightStat: '94 Yards After Catch & Stiff-Arm Bulldozer',
  },
  {
    id: 'ot-walker-rasheed',
    name: 'Rasheed Walker',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'OT',
    ovr: 80,
    salary: 1,
    archetype: 'Pass Pro Left Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 83, runBlocking: 79, athleticism: 81, footballIQ: 81 },
    highlightStat: '85 Pass Set Punch Timing',
  },
  {
    id: 'ot-tom-zach',
    name: 'Zach Tom',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'OT',
    ovr: 86,
    salary: 1,
    archetype: 'Elite Pass Protecting Right Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 92, runBlocking: 83, athleticism: 85, footballIQ: 91 },
    highlightStat: '95 Mirroring Elite Edge Rushers & Zero Sacks',
  },
  {
    id: 'og-jenkins-elgton',
    name: 'Elgton Jenkins',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'OG',
    ovr: 88,
    salary: 17,
    archetype: 'Versatile Wall Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 92, runBlocking: 87, athleticism: 81, footballIQ: 93 },
    highlightStat: '94 Zero-Sack Pass Protection Consistency',
  },
  {
    id: 'og-rhyan-sean',
    name: 'Sean Rhyan',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'OG',
    ovr: 77,
    salary: 1,
    archetype: 'Power Gap Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 77, runBlocking: 82, athleticism: 78, footballIQ: 78 },
    highlightStat: '85 Inside Zone Drive Power',
  },
  {
    id: 'c-myers-josh',
    name: 'Josh Myers',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'C',
    ovr: 79,
    salary: 2,
    archetype: 'Reliable Line Caller Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 80, athleticism: 77, footballIQ: 84 },
    highlightStat: '85 Pre-Snap Blitz Callouts & Snaps',
  },
  {
    id: 'edge-gary',
    name: 'Rashan Gary',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'EDGE',
    ovr: 88,
    salary: 24,
    archetype: 'Pure Power-Speed Bull Rusher',
    attributes: { passRush: 91, runDefense: 89, coverage: 65, athleticism: 94, footballIQ: 88 },
    highlightStat: '95 Bull Rush Velocity & Relentless Closing Speed',
  },
  {
    id: 'dt-clark-kenny',
    name: 'Kenny Clark',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'DT',
    ovr: 88,
    salary: 21,
    archetype: 'Nose/3-Tech Dual Threat',
    attributes: { passRush: 88, runDefense: 91, coverage: 50, athleticism: 80, footballIQ: 92 },
    highlightStat: '93 Interior Bull Rush & 2-Gap Run Defense',
  },
  {
    id: 'dt-wyatt',
    name: 'Devonte Wyatt',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'DT',
    ovr: 82,
    salary: 3,
    archetype: 'First-Step Gap Penetrator',
    attributes: { passRush: 86, runDefense: 80, coverage: 50, athleticism: 88, footballIQ: 81 },
    highlightStat: '90 Interior Quick-Twitch Sacks',
  },
  {
    id: 'lb-cooper-edgerrin',
    name: 'Edgerrin Cooper',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'LB',
    ovr: 83,
    salary: 2,
    archetype: '4.51 Heat-Seeking Missile LB',
    attributes: { passRush: 86, runDefense: 85, coverage: 84, athleticism: 95, footballIQ: 84 },
    highlightStat: '95 Blitz Closing Speed & Strip Sacks',
  },
  {
    id: 'lb-walker-quay',
    name: 'Quay Walker',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'LB',
    ovr: 82,
    salary: 3,
    archetype: 'Sideline-to-Sideline Athlete',
    attributes: { passRush: 78, runDefense: 85, coverage: 82, athleticism: 92, footballIQ: 83 },
    highlightStat: '90 Open Field Scraping & Tackling',
  },
  {
    id: 'cb-alexander-jaire',
    name: 'Jaire Alexander',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'CB',
    ovr: 92,
    salary: 21,
    archetype: 'Pro Bowl Shutdown Man Corner',
    attributes: { passRush: 0, runDefense: 79, coverage: 95, athleticism: 93, footballIQ: 95 },
    highlightStat: '96 Hip Fluidity, Mirror Technique & Playoff Picks',
  },
  {
    id: 's-mckinney',
    name: 'Xavier McKinney',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'S',
    ovr: 93,
    salary: 17,
    archetype: 'All-Pro Centerfield Ballhawk God',
    attributes: { passRush: 72, runDefense: 89, coverage: 97, athleticism: 91, footballIQ: 98 },
    highlightStat: '99 NFL-Leading Interception Run & Deep Halves Perfection',
  },
  {
    id: 's-bullard',
    name: 'Javon Bullard',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'S',
    ovr: 80,
    salary: 2,
    archetype: 'Ferocious Nickel / Split Safety',
    attributes: { passRush: 75, runDefense: 85, coverage: 82, athleticism: 89, footballIQ: 84 },
    highlightStat: '90 Enforcer Hits & Versatile Coverage',
  },

  // ===================== MINNESOTA VIKINGS (MIN) =====================
  {
    id: 'qb-darnold',
    name: 'Sam Darnold',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'QB',
    ovr: 83,
    salary: 10,
    starter: true,
    archetype: 'Aggressive Downfield Gunslinger',
    attributes: { passing: 86, rushing: 75, passBlocking: 0, runBlocking: 0, athleticism: 80, footballIQ: 82 },
    highlightStat: '91 Big-Time Throw Rate & Pocket Toughness',
  },
  {
    id: 'qb-mccarthy',
    name: 'J.J. McCarthy',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'QB',
    ovr: 81,
    salary: 5,
    starter: false,
    archetype: 'High-Velocity Off-Platform Leader',
    attributes: { passing: 85, rushing: 84, passBlocking: 0, runBlocking: 0, athleticism: 88, footballIQ: 84 },
    highlightStat: '92 Intermediate Middle-Field Velocity & 3rd-Down Conversions',
  },
  {
    id: 'rb-jones-aaron',
    name: 'Aaron Jones',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'RB',
    ovr: 88,
    salary: 7,
    archetype: 'Silky Zone Runner & Receiving Weapon',
    attributes: { passing: 0, rushing: 90, receiving: 89, passBlocking: 78, runBlocking: 0, athleticism: 91, footballIQ: 93 },
    highlightStat: '95 Zone Vision, Jump Cuts & 5.0+ YPC',
  },
  {
    id: 'wr-jefferson',
    name: 'Justin Jefferson',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'WR',
    ovr: 98,
    salary: 35,
    archetype: 'Premier Route Craftsman & Elite Weapon',
    attributes: { passing: 0, rushing: 72, receiving: 98, passBlocking: 0, runBlocking: 65, athleticism: 96, footballIQ: 98 },
    highlightStat: '99 Unstoppable Route Running, Contested Catches & Separation',
  },
  {
    id: 'wr-addison',
    name: 'Jordan Addison',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'WR',
    ovr: 84,
    salary: 3,
    archetype: 'Fluid Route Craftsman & Deep Threat',
    attributes: { passing: 0, rushing: 0, receiving: 87, passBlocking: 0, runBlocking: 52, athleticism: 91, footballIQ: 87 },
    highlightStat: '93 Separation at Top of Route & Deep Tracking',
  },
  {
    id: 'te-hockenson',
    name: 'T.J. Hockenson',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'TE',
    ovr: 90,
    salary: 16,
    archetype: 'Elite Target Funnel Tight End',
    attributes: { passing: 0, rushing: 0, receiving: 93, passBlocking: 75, runBlocking: 80, athleticism: 86, footballIQ: 93 },
    highlightStat: '96 Intermediate Dig & Seam Reliability',
  },
  {
    id: 'ot-darrisaw',
    name: 'Christian Darrisaw',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'OT',
    ovr: 93,
    salary: 26,
    archetype: 'Elite All-Pro Left Tackle Fortress',
    attributes: { passing: 0, rushing: 0, passBlocking: 96, runBlocking: 94, athleticism: 87, footballIQ: 94 },
    highlightStat: '98 Pass Protection Purity & Run Displacement',
  },
  {
    id: 'ot-oneill-brian',
    name: 'Brian O\'Neill',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'OT',
    ovr: 87,
    salary: 18,
    archetype: 'Elite Athletic Right Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 90, runBlocking: 88, athleticism: 86, footballIQ: 91 },
    highlightStat: '92 Mirror Footwork in True Pass Sets',
  },
  {
    id: 'og-brandel',
    name: 'Blake Brandel',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'OG',
    ovr: 79,
    salary: 3,
    archetype: 'Zone Scheme Left Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 81, athleticism: 78, footballIQ: 83 },
    highlightStat: '84 Flow Blocking on Outside Zone',
  },
  {
    id: 'og-risner',
    name: 'Dalton Risner',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'OG',
    ovr: 78,
    salary: 2,
    archetype: 'Pass Pro Specialist Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 84, runBlocking: 76, athleticism: 74, footballIQ: 84 },
    highlightStat: '87 Pass Pro Anchor Against Bull Rush',
  },
  {
    id: 'c-bradbury',
    name: 'Garrett Bradbury',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'C',
    ovr: 80,
    salary: 5,
    archetype: 'Athletic Reach-Block Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 79, runBlocking: 83, athleticism: 85, footballIQ: 86 },
    highlightStat: '89 Reach-Blocks on Outside Zone Runs',
  },
  {
    id: 'edge-greenard',
    name: 'Jonathan Greenard',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'EDGE',
    ovr: 88,
    salary: 19,
    archetype: 'Speed-to-Power Strip Sack Artist',
    attributes: { passRush: 92, runDefense: 87, coverage: 65, athleticism: 88, footballIQ: 90 },
    highlightStat: '95 Pressure Rate & Dip-and-Rip Cornering',
  },
  {
    id: 'edge-van-ginkel',
    name: 'Andrew Van Ginkel',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'EDGE',
    ovr: 86,
    salary: 10,
    archetype: 'Flores Scheme Defensive Swiss Knife',
    attributes: { passRush: 88, runDefense: 85, coverage: 86, athleticism: 87, footballIQ: 96 },
    highlightStat: '97 Pick-Six Returns on Zone Drops & Blitz Sacks',
  },
  {
    id: 'dt-phillips-harrison',
    name: 'Harrison Phillips',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'DT',
    ovr: 82,
    salary: 6,
    archetype: 'Nose Tackle Run Plugger',
    attributes: { passRush: 74, runDefense: 91, coverage: 40, athleticism: 70, footballIQ: 87 },
    highlightStat: '93 2-Gap Run Absorption',
  },
  {
    id: 'dt-tillery',
    name: 'Jerry Tillery',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'DT',
    ovr: 78,
    salary: 2,
    archetype: 'Length Interior Pass Rusher',
    attributes: { passRush: 81, runDefense: 76, coverage: 45, athleticism: 82, footballIQ: 79 },
    highlightStat: '85 Long-Arm Interior QB Disruption',
  },
  {
    id: 'lb-pace',
    name: 'Ivan Pace Jr.',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'LB',
    ovr: 83,
    salary: 1,
    archetype: 'Unblockable A-Gap Blitz Missile',
    attributes: { passRush: 88, runDefense: 86, coverage: 79, athleticism: 88, footballIQ: 88 },
    highlightStat: '96 A-Gap Blitz Pressure & Sacks',
  },
  {
    id: 'lb-cashman',
    name: 'Blake Cashman',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'LB',
    ovr: 84,
    salary: 7,
    archetype: 'Complete Coverage & Flow LB',
    attributes: { passRush: 80, runDefense: 86, coverage: 88, athleticism: 89, footballIQ: 91 },
    highlightStat: '92 Zone Pass Deflections & Signal Calling',
  },
  {
    id: 'cb-murphy-byron',
    name: 'Byron Murphy Jr.',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'CB',
    ovr: 85,
    salary: 11,
    archetype: 'Versatile Turnover Cornerback',
    attributes: { passRush: 70, runDefense: 79, coverage: 88, athleticism: 88, footballIQ: 91 },
    highlightStat: '93 Break on Ball & Interception Numbers',
  },
  {
    id: 'cb-gilmore-stephon',
    name: 'Stephon Gilmore',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'CB',
    ovr: 83,
    salary: 7,
    archetype: 'Veteran DPOY Lockdown Master',
    attributes: { passRush: 0, runDefense: 75, coverage: 87, athleticism: 82, footballIQ: 97 },
    highlightStat: '95 Route Anticipation & Sideline Contested PBUs',
  },
  {
    id: 's-smith-harrison',
    name: 'Harrison Smith',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'S',
    ovr: 87,
    salary: 9,
    archetype: 'The Hitman / Hall of Fame Disguise Master',
    attributes: { passRush: 82, runDefense: 88, coverage: 90, athleticism: 82, footballIQ: 99 },
    highlightStat: '99 Pre-Snap Blitz/Drop Disguises & Interceptions',
  },
  {
    id: 's-bynum',
    name: 'Camryn Bynum',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'S',
    ovr: 84,
    salary: 1,
    archetype: 'Complete Deep Free Safety',
    attributes: { passRush: 65, runDefense: 84, coverage: 87, athleticism: 86, footballIQ: 91 },
    highlightStat: '91 Open Field Tackling & Deep Coverage',
  },
  // --- NFC North Kickers & Special Teams ---
  {
    id: 'k-santos-cairo',
    name: 'Cairo Santos',
    team: 'CHI',
    teamCity: 'Chicago',
    position: 'K',
    ovr: 83,
    salary: 4,
    starter: true,
    archetype: 'Soldier Field Wind Tamer',
    attributes: { passing: 0, rushing: 0, kicking: 87, athleticism: 73, footballIQ: 88 },
    highlightStat: '91% Career Accuracy in Hostile Soldier Field Winds',
  },
  {
    id: 'k-bates-jake',
    name: 'Jake Bates',
    team: 'DET',
    teamCity: 'Detroit',
    position: 'K',
    ovr: 82,
    salary: 2,
    starter: true,
    archetype: '64-Yard Spring League Monster Leg',
    attributes: { passing: 0, rushing: 0, kicking: 86, athleticism: 77, footballIQ: 81 },
    highlightStat: '64-Yard Field Goal Game Winners in Ford Field',
  },
  {
    id: 'k-mcmanus-brandon',
    name: 'Brandon McManus',
    team: 'GB',
    teamCity: 'Green Bay',
    position: 'K',
    ovr: 81,
    salary: 3,
    starter: true,
    archetype: 'Super Bowl Veteran Cannon',
    attributes: { passing: 0, rushing: 0, kicking: 85, athleticism: 74, footballIQ: 90 },
    highlightStat: 'Lambeau Field Freezing Cold Game-Winning Executions',
  },
  {
    id: 'k-reichard-will',
    name: 'Will Reichard',
    team: 'MIN',
    teamCity: 'Minnesota',
    position: 'K',
    ovr: 83,
    salary: 2,
    starter: true,
    archetype: 'NCAA Scoring Leader / Ice-Cold Rookie Sniper',
    attributes: { passing: 0, rushing: 0, kicking: 88, athleticism: 77, footballIQ: 87 },
    highlightStat: 'Perfect 50+ Yard Streak in Rookie Season',
  },
];
