import { Player } from '../../types';

export const NFC_SOUTH_PLAYERS: Player[] = [
  // ===================== ATLANTA FALCONS (ATL) =====================
  {
    id: 'qb-cousins',
    name: 'Kirk Cousins',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'QB',
    ovr: 84,
    salary: 45,
    starter: true,
    archetype: 'Pocket Commander',
    attributes: { passing: 89, rushing: 62, passBlocking: 0, runBlocking: 0, athleticism: 68, footballIQ: 91 },
    highlightStat: '91 Play-Action Accuracy & Read Progression',
  },
  {
    id: 'qb-penix',
    name: 'Michael Penix Jr.',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'QB',
    ovr: 80,
    salary: 5,
    starter: false,
    archetype: 'Deep Ball Cannon',
    attributes: { passing: 86, rushing: 72, passBlocking: 0, runBlocking: 0, athleticism: 82, footballIQ: 80 },
    highlightStat: '94 Deep Throw Power & Tight Window Velocity',
  },
  {
    id: 'qb-heinicke',
    name: 'Taylor Heinicke',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'QB',
    ovr: 72,
    salary: 3,
    starter: false,
    archetype: 'Scrappy Improviser Backup',
    attributes: { passing: 74, rushing: 76, passBlocking: 0, runBlocking: 0, athleticism: 78, footballIQ: 80 },
    highlightStat: '82 Scramble Off-Schedule Playmaking',
  },
  {
    id: 'rb-bijan',
    name: 'Bijan Robinson',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'RB',
    ovr: 89,
    salary: 6,
    archetype: 'Elusive Receiving Weapon',
    attributes: { passing: 0, rushing: 91, receiving: 89, passBlocking: 76, runBlocking: 0, athleticism: 93, footballIQ: 89 },
    highlightStat: '95 Juke Move & Contact Balance in Space',
  },
  {
    id: 'rb-allgeier',
    name: 'Tyler Allgeier',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'RB',
    ovr: 81,
    salary: 1,
    archetype: 'Short-Yardage Hammer',
    attributes: { passing: 0, rushing: 84, receiving: 71, passBlocking: 79, runBlocking: 0, athleticism: 79, footballIQ: 82 },
    highlightStat: '86 Inside Zone Power & Stiff Arm',
  },
  {
    id: 'wr-london',
    name: 'Drake London',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'WR',
    ovr: 87,
    salary: 6,
    archetype: 'Physical Red-Zone Dominator',
    attributes: { passing: 0, rushing: 0, receiving: 90, passBlocking: 0, runBlocking: 74, athleticism: 85, footballIQ: 87 },
    highlightStat: '94 Contested Catch & High Point Mastery',
  },
  {
    id: 'wr-mooney',
    name: 'Darnell Mooney',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'WR',
    ovr: 80,
    salary: 13,
    archetype: 'Deep Threat Burner',
    attributes: { passing: 0, rushing: 0, receiving: 82, passBlocking: 0, runBlocking: 55, athleticism: 91, footballIQ: 80 },
    highlightStat: '92 Acceleration & Post-Corner Separation',
  },
  {
    id: 'te-pitts',
    name: 'Kyle Pitts',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'TE',
    ovr: 83,
    salary: 8,
    archetype: 'Slot Flex Weapon',
    attributes: { passing: 0, rushing: 0, receiving: 86, passBlocking: 62, runBlocking: 66, athleticism: 92, footballIQ: 80 },
    highlightStat: '92 Seam Route Speed & Catch Radius',
  },
  {
    id: 'ot-matthews-jake',
    name: 'Jake Matthews',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'OT',
    ovr: 82,
    salary: 18,
    archetype: 'Veteran Pass Protector',
    attributes: { passing: 0, rushing: 0, passBlocking: 86, runBlocking: 78, athleticism: 77, footballIQ: 89 },
    highlightStat: '88 Pass Protection Anchor Consistency',
  },
  {
    id: 'ot-mcgary',
    name: 'Kaleb McGary',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'OT',
    ovr: 81,
    salary: 11,
    archetype: 'Downhill Power Run RT',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 88, athleticism: 76, footballIQ: 82 },
    highlightStat: '91 Outside Zone Drive Block Displacement',
  },
  {
    id: 'og-lindstrom',
    name: 'Chris Lindstrom',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'OG',
    ovr: 93,
    salary: 20,
    archetype: 'Premier All-Pro Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 92, runBlocking: 96, athleticism: 85, footballIQ: 94 },
    highlightStat: '96 Run Block Impact & Zone Reach Perfection',
  },
  {
    id: 'og-bergeron',
    name: 'Matthew Bergeron',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'OG',
    ovr: 79,
    salary: 2,
    archetype: 'Athletic Left Guard Puller',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 82, athleticism: 84, footballIQ: 80 },
    highlightStat: '86 Second-Level Angle Cutoffs',
  },
  {
    id: 'c-dalman',
    name: 'Drew Dalman',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'C',
    ovr: 83,
    salary: 3,
    archetype: 'Zone Scheme Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 88, athleticism: 84, footballIQ: 85 },
    highlightStat: '89 Reach-Block Prowess in Outside Zone',
  },
  {
    id: 'edge-judon',
    name: 'Matthew Judon',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'EDGE',
    ovr: 86,
    salary: 13,
    archetype: 'Bending Speed-to-Power Rusher',
    attributes: { passRush: 88, runDefense: 81, coverage: 68, athleticism: 83, footballIQ: 88 },
    highlightStat: '90 Signature Cross-Chop & Strip-Sack Instincts',
  },
  {
    id: 'dt-jarrett',
    name: 'Grady Jarrett',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'DT',
    ovr: 88,
    salary: 16,
    archetype: 'Penetrating 3-Tech',
    attributes: { passRush: 87, runDefense: 89, coverage: 50, athleticism: 81, footballIQ: 91 },
    highlightStat: '91 Interior First-Step Burst & Leveraged Pad Level',
  },
  {
    id: 'dt-onyemata',
    name: 'David Onyemata',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'DT',
    ovr: 82,
    salary: 11,
    archetype: 'Heavy 3-Tech Power Rusher',
    attributes: { passRush: 83, runDefense: 86, coverage: 45, athleticism: 77, footballIQ: 84 },
    highlightStat: '88 Pocket Collapse & Inside Push',
  },
  {
    id: 'lb-elliss',
    name: 'Kaden Elliss',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'LB',
    ovr: 83,
    salary: 7,
    archetype: 'Blitzer / Gap Shooter',
    attributes: { passRush: 83, runDefense: 84, coverage: 78, athleticism: 83, footballIQ: 84 },
    highlightStat: '87 A-Gap Blitz Execution & Tackle for Loss',
  },
  {
    id: 'cb-terrell',
    name: 'A.J. Terrell',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'CB',
    ovr: 89,
    salary: 20,
    archetype: 'Lockdown Shadow Corner',
    attributes: { passRush: 0, runDefense: 76, coverage: 91, athleticism: 91, footballIQ: 89 },
    highlightStat: '92 Press-Man Mirror & Shadow Capability',
  },
  {
    id: 's-bates',
    name: 'Jessie Bates III',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'S',
    ovr: 96,
    salary: 16,
    archetype: 'Centerfield Ballhawk (Madden 96)',
    attributes: { passRush: 65, runDefense: 88, coverage: 97, athleticism: 90, footballIQ: 98 },
    highlightStat: '98 Single-High Range & Interception Instincts',
  },

  // ===================== CAROLINA PANTHERS (CAR) =====================
  {
    id: 'qb-young-bryce',
    name: 'Bryce Young',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'QB',
    ovr: 79,
    salary: 9,
    starter: true,
    archetype: 'Point Guard Distributor Scrambler',
    attributes: { passing: 83, rushing: 81, passBlocking: 0, runBlocking: 0, athleticism: 85, footballIQ: 88 },
    highlightStat: '90 Off-Platform Vision & Intermediate Touch',
  },
  {
    id: 'qb-dalton',
    name: 'Andy Dalton',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'QB',
    ovr: 74,
    salary: 4,
    starter: false,
    archetype: 'Experienced Veteran Pocket Passer',
    attributes: { passing: 77, rushing: 60, passBlocking: 0, runBlocking: 0, athleticism: 65, footballIQ: 88 },
    highlightStat: '85 Quick Diagnostic Ball Placement',
  },
  {
    id: 'rb-hubbard',
    name: 'Chuba Hubbard',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'RB',
    ovr: 83,
    salary: 8,
    archetype: 'Decisive Zone Workhorse',
    attributes: { passing: 0, rushing: 86, receiving: 78, passBlocking: 80, runBlocking: 0, athleticism: 87, footballIQ: 86 },
    highlightStat: '91 Inside Zone Vision & Tough Yards After Contact',
  },
  {
    id: 'rb-brooks-jonathon',
    name: 'Jonathon Brooks',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'RB',
    ovr: 78,
    salary: 2,
    archetype: 'Complete Three-Down Weapon',
    attributes: { passing: 0, rushing: 82, receiving: 80, passBlocking: 74, runBlocking: 0, athleticism: 88, footballIQ: 81 },
    highlightStat: '90 Contact Balance & Open-Field Cut',
  },
  {
    id: 'wr-legette',
    name: 'Xavier Legette',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'WR',
    ovr: 79,
    salary: 3,
    archetype: '4.39 Physical Freak / DK Metcalf Clone',
    attributes: { passing: 0, rushing: 75, receiving: 81, passBlocking: 0, runBlocking: 70, athleticism: 95, footballIQ: 78 },
    highlightStat: '94 Physical High-Point & Speed on Slants',
  },
  {
    id: 'wr-thielen',
    name: 'Adam Thielen',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'WR',
    ovr: 82,
    salary: 8,
    archetype: 'Veteran Chain-Moving Slot',
    attributes: { passing: 0, rushing: 0, receiving: 85, passBlocking: 0, runBlocking: 62, athleticism: 77, footballIQ: 95 },
    highlightStat: '94 3rd Down Catch Percentage & Hands',
  },
  {
    id: 'te-tremble',
    name: 'Tommy Tremble',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'TE',
    ovr: 77,
    salary: 1,
    archetype: 'Physical Blocker / H-Back',
    attributes: { passing: 0, rushing: 0, receiving: 76, passBlocking: 78, runBlocking: 86, athleticism: 84, footballIQ: 80 },
    highlightStat: '88 Lead Blocker Pop & Flats Separation',
  },
  {
    id: 'ot-ekwonu',
    name: 'Ikem Ekwonu',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'OT',
    ovr: 82,
    salary: 7,
    archetype: 'Mauling Power Blindside LT',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 89, athleticism: 87, footballIQ: 81 },
    highlightStat: '93 Pancake Finishing Force on Gap Runs',
  },
  {
    id: 'ot-motty',
    name: 'Taylor Moton',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'OT',
    ovr: 85,
    salary: 17,
    archetype: 'Iron Man Right Tackle Anchor',
    attributes: { passing: 0, rushing: 0, passBlocking: 88, runBlocking: 85, athleticism: 78, footballIQ: 91 },
    highlightStat: '92 Pass Protection Strike & Streak of Snaps',
  },
  {
    id: 'og-hunt',
    name: 'Robert Hunt',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'OG',
    ovr: 86,
    salary: 20,
    archetype: 'Dominant Power Guard Wall',
    attributes: { passing: 0, rushing: 0, passBlocking: 88, runBlocking: 90, athleticism: 81, footballIQ: 88 },
    highlightStat: '94 Interior Pass Pro & Gap Scheme Cleaving',
  },
  {
    id: 'og-lewis-damien',
    name: 'Damien Lewis',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'OG',
    ovr: 82,
    salary: 13,
    archetype: 'Heavy Road-Grader',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 88, athleticism: 77, footballIQ: 83 },
    highlightStat: '90 Drive-Block Movement on Inside Zone',
  },
  {
    id: 'c-corbett',
    name: 'Austin Corbett',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'C',
    ovr: 80,
    salary: 8,
    archetype: 'Veteran Transitioned Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 82, athleticism: 78, footballIQ: 86 },
    highlightStat: '86 Inside Zone Flow & Combo Reach',
  },
  {
    id: 'edge-clowney',
    name: 'Jadeveon Clowney',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'EDGE',
    ovr: 83,
    salary: 10,
    archetype: 'Run-Stopping Power Edge Crusher',
    attributes: { passRush: 83, runDefense: 94, coverage: 65, athleticism: 85, footballIQ: 90 },
    highlightStat: '96 Edge Contain, TFLs & Disruption',
  },
  {
    id: 'dt-brown-derrick',
    name: 'Derrick Brown',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'DT',
    ovr: 92,
    salary: 24,
    archetype: 'Historic NFL Record Run-Stopping Monster',
    attributes: { passRush: 86, runDefense: 99, coverage: 45, athleticism: 83, footballIQ: 95 },
    highlightStat: '99 NFL Record Tackles by a DT & 2-Gap Eradication',
  },
  {
    id: 'dt-robinson-ashawn',
    name: 'A\'Shawn Robinson',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'DT',
    ovr: 81,
    salary: 7,
    archetype: 'Heavy Run-Stuffing DT',
    attributes: { passRush: 72, runDefense: 89, coverage: 35, athleticism: 70, footballIQ: 86 },
    highlightStat: '92 Double-Team Stalemate & Inside Clogs',
  },
  {
    id: 'lb-thompson-shaq',
    name: 'Shaq Thompson',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'LB',
    ovr: 81,
    salary: 6,
    archetype: 'Veteran Flow LB',
    attributes: { passRush: 74, runDefense: 84, coverage: 82, athleticism: 80, footballIQ: 90 },
    highlightStat: '88 Sideline Pursuit & Sure Tackling',
  },
  {
    id: 'cb-horn',
    name: 'Jaycee Horn',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'CB',
    ovr: 88,
    salary: 5,
    archetype: 'Elite Physical Shadow Corner',
    attributes: { passRush: 0, runDefense: 84, coverage: 93, athleticism: 94, footballIQ: 90 },
    highlightStat: '96 Press-Man Erasure & Sub-40.0 QBR Allowed',
  },
  {
    id: 's-woods-xavier',
    name: 'Xavier Woods',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'S',
    ovr: 81,
    salary: 5,
    archetype: 'Reliable Free Safety',
    attributes: { passRush: 60, runDefense: 80, coverage: 84, athleticism: 83, footballIQ: 88 },
    highlightStat: '87 Deep Half Positioning & Open Field Stops',
  },

  // ===================== NEW ORLEANS SAINTS (NO) =====================
  {
    id: 'qb-carr',
    name: 'Derek Carr',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'QB',
    ovr: 82,
    salary: 37,
    starter: true,
    archetype: 'Veteran Rhythm Pocket Passer',
    attributes: { passing: 86, rushing: 68, passBlocking: 0, runBlocking: 0, athleticism: 74, footballIQ: 89 },
    highlightStat: '90 Deep Touch & Play-Action Seam Accuracy',
  },
  {
    id: 'qb-rattler',
    name: 'Spencer Rattler',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'QB',
    ovr: 74,
    salary: 2,
    starter: false,
    archetype: 'Arm-Talent Off-Platform Backup',
    attributes: { passing: 77, rushing: 76, passBlocking: 0, runBlocking: 0, athleticism: 82, footballIQ: 76 },
    highlightStat: '87 Off-Platform Velocity & Mobility',
  },
  {
    id: 'qb-haener',
    name: 'Jake Haener',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'QB',
    ovr: 71,
    salary: 1,
    starter: false,
    archetype: 'Accurate Rhythm Backup',
    attributes: { passing: 74, rushing: 64, passBlocking: 0, runBlocking: 0, athleticism: 68, footballIQ: 79 },
    highlightStat: '82 Quick Ball Delivery',
  },
  {
    id: 'rb-kamara',
    name: 'Alvin Kamara',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'RB',
    ovr: 89,
    salary: 12,
    archetype: 'Balance God / Greatest Dual-Threat Receiver',
    attributes: { passing: 0, rushing: 88, receiving: 94, passBlocking: 79, runBlocking: 0, athleticism: 91, footballIQ: 95 },
    highlightStat: '98 Contact Balance, Angle Breaking & Screen Vision',
  },
  {
    id: 'wr-olave',
    name: 'Chris Olave',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'WR',
    ovr: 86,
    salary: 4,
    archetype: 'Silky Smooth Route Wizard',
    attributes: { passing: 0, rushing: 0, receiving: 90, passBlocking: 0, runBlocking: 52, athleticism: 93, footballIQ: 90 },
    highlightStat: '95 Separation on Out & Post Routes',
  },
  {
    id: 'wr-shaheed',
    name: 'Rashid Shaheed',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'WR',
    ovr: 83,
    salary: 5,
    archetype: 'All-Pro Returner / 4.30 Deep Burner',
    attributes: { passing: 0, rushing: 78, receiving: 84, passBlocking: 0, runBlocking: 48, athleticism: 98, footballIQ: 82 },
    highlightStat: '98 Return Touchdowns & Over-the-Top Deep Bomb Touchdowns',
  },
  {
    id: 'te-hill-taysom',
    name: 'Taysom Hill',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'TE',
    ovr: 83,
    salary: 10,
    archetype: 'Swiss Army Human Bulldozer',
    attributes: { passing: 78, rushing: 88, receiving: 80, passBlocking: 78, runBlocking: 86, athleticism: 90, footballIQ: 88 },
    highlightStat: '95 Trucking on Direct QB Power Runs & Red Zone TDs',
  },
  {
    id: 'ot-fuaga',
    name: 'Taliese Fuaga',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'OT',
    ovr: 82,
    salary: 4,
    archetype: 'Mauling Rookie Left Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 83, runBlocking: 88, athleticism: 83, footballIQ: 81 },
    highlightStat: '91 Gap Scheme Drive Block Power',
  },
  {
    id: 'ot-penning',
    name: 'Trevor Penning',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'OT',
    ovr: 78,
    salary: 3,
    archetype: 'Nasty Power Right Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 77, runBlocking: 86, athleticism: 84, footballIQ: 77 },
    highlightStat: '89 Down-Block Strike & Finishing Grit',
  },
  {
    id: 'og-ruiz-cesar',
    name: 'Cesar Ruiz',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'OG',
    ovr: 80,
    salary: 11,
    archetype: 'Mobile Pulling Right Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 82, athleticism: 82, footballIQ: 84 },
    highlightStat: '85 Space Pulling Blocks & Screen Lead',
  },
  {
    id: 'c-mccoy-erik',
    name: 'Erik McCoy',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'C',
    ovr: 87,
    salary: 12,
    archetype: 'Pro Bowl Anchor Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 89, runBlocking: 91, athleticism: 82, footballIQ: 92 },
    highlightStat: '93 A-Gap Wall & Reach Block Leverage',
  },
  {
    id: 'edge-jordan-cam',
    name: 'Cameron Jordan',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'EDGE',
    ovr: 84,
    salary: 13,
    archetype: 'Hall of Fame Iron Power Edge',
    attributes: { passRush: 85, runDefense: 93, coverage: 60, athleticism: 75, footballIQ: 97 },
    highlightStat: '95 Power Bull Rush & Run Contain',
  },
  {
    id: 'edge-granderson',
    name: 'Carl Granderson',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'EDGE',
    ovr: 82,
    salary: 13,
    archetype: 'High-Motor Pursuer',
    attributes: { passRush: 84, runDefense: 85, coverage: 62, athleticism: 84, footballIQ: 83 },
    highlightStat: '88 Speed-to-Power Pressure',
  },
  {
    id: 'dt-bresee',
    name: 'Bryan Bresee',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'DT',
    ovr: 81,
    salary: 3,
    archetype: 'Interior Pass Rush Specialist',
    attributes: { passRush: 86, runDefense: 79, coverage: 50, athleticism: 85, footballIQ: 80 },
    highlightStat: '89 Interior Sacks & Club-Swim Move',
  },
  {
    id: 'lb-davis-demario',
    name: 'Demario Davis',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'LB',
    ovr: 90,
    salary: 8,
    archetype: 'All-Pro Field General & Blitzer (Madden 90)',
    attributes: { passRush: 88, runDefense: 94, coverage: 87, athleticism: 84, footballIQ: 98 },
    highlightStat: '97 A-Gap Green Dog Blitzes & Sure-Fire Tackling',
  },
  {
    id: 'lb-werner',
    name: 'Pete Werner',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'LB',
    ovr: 82,
    salary: 8,
    archetype: 'Gap-Fill Run Stopping LB',
    attributes: { passRush: 73, runDefense: 89, coverage: 80, athleticism: 81, footballIQ: 87 },
    highlightStat: '90 Inside Tackle for Loss Stops',
  },
  {
    id: 'cb-adebo',
    name: 'Paulson Adebo',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'CB',
    ovr: 85,
    salary: 1,
    archetype: 'Physical Ballhawk Boundary Corner',
    attributes: { passRush: 0, runDefense: 81, coverage: 88, athleticism: 90, footballIQ: 88 },
    highlightStat: '94 Interceptions, PBUs & Run Support Jamming',
  },
  {
    id: 'cb-taylor-alontae',
    name: 'Alontae Taylor',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'CB',
    ovr: 82,
    salary: 1,
    archetype: 'Blitzing Slot Weapon Corner',
    attributes: { passRush: 87, runDefense: 84, coverage: 82, athleticism: 93, footballIQ: 84 },
    highlightStat: '95 Multi-Sack Games off the Slot Blitz',
  },
  {
    id: 's-mathieu',
    name: 'Tyrann Mathieu',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'S',
    ovr: 86,
    salary: 6,
    archetype: 'The Honey Badger / Legendary Turnover Creator',
    attributes: { passRush: 76, runDefense: 83, coverage: 90, athleticism: 84, footballIQ: 98 },
    highlightStat: '97 Baiting Quarterbacks into Deep Interceptions',
  },

  // ===================== TAMPA BAY BUCCANEERS (TB) =====================
  {
    id: 'qb-mayfield',
    name: 'Baker Mayfield',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'QB',
    ovr: 85,
    salary: 33,
    starter: true,
    archetype: 'Gunslinger / Fiery Competitor',
    attributes: { passing: 88, rushing: 79, passBlocking: 0, runBlocking: 0, athleticism: 80, footballIQ: 89 },
    highlightStat: '94 3rd Down Passing Touchdowns & Off-Platform Grit',
  },
  {
    id: 'qb-trask',
    name: 'Kyle Trask',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'QB',
    ovr: 70,
    salary: 2,
    starter: false,
    archetype: 'Towering Pocket Backup',
    attributes: { passing: 73, rushing: 58, passBlocking: 0, runBlocking: 0, athleticism: 62, footballIQ: 78 },
    highlightStat: '80 Intermediate Seam Pass',
  },
  {
    id: 'rb-white-rachaad',
    name: 'Rachaad White',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'RB',
    ovr: 83,
    salary: 1,
    archetype: 'Elite Pass-Catching Satellite Back',
    attributes: { passing: 0, rushing: 81, receiving: 90, passBlocking: 79, runBlocking: 0, athleticism: 88, footballIQ: 87 },
    highlightStat: '94 Checkdown YAC & Flawless Hands',
  },
  {
    id: 'rb-irving-bucky',
    name: 'Bucky Irving',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'RB',
    ovr: 82,
    salary: 1,
    archetype: 'Human Joystick Contact Balancer',
    attributes: { passing: 0, rushing: 86, receiving: 83, passBlocking: 70, runBlocking: 0, athleticism: 91, footballIQ: 84 },
    highlightStat: '96 Broken Tackle Rate & Slippery Zone Cuts',
  },
  {
    id: 'wr-evans-mike',
    name: 'Mike Evans',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'WR',
    ovr: 92,
    salary: 20,
    archetype: '10 Straight 1,000-Yard Seasons / Red Zone God (Madden 92)',
    attributes: { passing: 0, rushing: 0, receiving: 95, passBlocking: 0, runBlocking: 78, athleticism: 89, footballIQ: 97 },
    highlightStat: '99 High-Point Contested Catches & Touchdown Inevitability',
  },
  {
    id: 'wr-godwin',
    name: 'Chris Godwin',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'WR',
    ovr: 88,
    salary: 20,
    archetype: 'Fearless Middle-Field Dominator',
    attributes: { passing: 0, rushing: 0, receiving: 92, passBlocking: 0, runBlocking: 80, athleticism: 88, footballIQ: 93 },
    highlightStat: '96 Catch Rate on Crossing Routes & Physical YAC',
  },
  {
    id: 'te-otton',
    name: 'Cade Otton',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'TE',
    ovr: 81,
    salary: 1,
    archetype: 'High-Volume In-Line Chain Mover',
    attributes: { passing: 0, rushing: 0, receiving: 83, passBlocking: 75, runBlocking: 80, athleticism: 81, footballIQ: 85 },
    highlightStat: '88 4th Quarter Clutch Catches Over Middle',
  },
  {
    id: 'ot-wirfs',
    name: 'Tristan Wirfs',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'OT',
    ovr: 95,
    salary: 28,
    archetype: 'Freakish All-Pro Blindside Titan (Madden 95)',
    attributes: { passing: 0, rushing: 0, passBlocking: 98, runBlocking: 93, athleticism: 91, footballIQ: 96 },
    highlightStat: '99 Pass Protection Set Quickness & Anchor Power',
  },
  {
    id: 'ot-goedeke',
    name: 'Luke Goedeke',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'OT',
    ovr: 83,
    salary: 1,
    archetype: 'Physical Mauling Right Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 84, runBlocking: 87, athleticism: 81, footballIQ: 84 },
    highlightStat: '90 Pass Set Physical Punch & Run Finish',
  },
  {
    id: 'og-mauch-cody',
    name: 'Cody Mauch',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'OG',
    ovr: 78,
    salary: 2,
    archetype: 'Athletic Pulling Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 77, runBlocking: 83, athleticism: 85, footballIQ: 79 },
    highlightStat: '88 Space Screen Mobility & Second-Level Blocks',
  },
  {
    id: 'og-bredeson',
    name: 'Ben Bredeson',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'OG',
    ovr: 77,
    salary: 3,
    archetype: 'Stout Power Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 79, runBlocking: 78, athleticism: 74, footballIQ: 81 },
    highlightStat: '83 A-Gap Double Team Anchor',
  },
  {
    id: 'c-barton-graham',
    name: 'Graham Barton',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'C',
    ovr: 80,
    salary: 3,
    archetype: 'Athletic Rookie Pivot',
    attributes: { passing: 0, rushing: 0, passBlocking: 81, runBlocking: 85, athleticism: 86, footballIQ: 82 },
    highlightStat: '88 Level 2 Reach Blocking on Outside Stretch',
  },
  {
    id: 'edge-diaby',
    name: 'Yaya Diaby',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'EDGE',
    ovr: 82,
    salary: 1,
    archetype: 'Heavy Bull-Rush Power Edge',
    attributes: { passRush: 85, runDefense: 86, coverage: 60, athleticism: 90, footballIQ: 82 },
    highlightStat: '91 Speed-to-Power Pocket Compression',
  },
  {
    id: 'dt-vea',
    name: 'Vita Vea',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'DT',
    ovr: 91,
    salary: 17,
    archetype: '350-Pound Tevita Tuliʻakiʻono Tuipulotu Mosese Vaʻinga Vea',
    attributes: { passRush: 88, runDefense: 98, coverage: 35, athleticism: 81, footballIQ: 92 },
    highlightStat: '99 Immovable 2-Gap Anchor & Shockwave Bull Rush Sacks',
  },
  {
    id: 'dt-kancey',
    name: 'Calijah Kancey',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'DT',
    ovr: 84,
    salary: 3,
    archetype: '4.67 Speed Interior Disruptor',
    attributes: { passRush: 90, runDefense: 79, coverage: 50, athleticism: 93, footballIQ: 83 },
    highlightStat: '95 Fastest 3-Tech Get-Off & Backfield Explosion',
  },
  {
    id: 'lb-david',
    name: 'Lavonte David',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'LB',
    ovr: 90,
    salary: 9,
    archetype: 'Hall of Fame All-Field Maestro (Madden 90)',
    attributes: { passRush: 82, runDefense: 94, coverage: 93, athleticism: 83, footballIQ: 99 },
    highlightStat: '98 TFLs, Forced Fumbles & Pass Coverage Masterclass',
  },
  {
    id: 'cb-dean-jamel',
    name: 'Jamel Dean',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'CB',
    ovr: 83,
    salary: 13,
    archetype: '4.30 Speed Boundary Corner',
    attributes: { passRush: 0, runDefense: 78, coverage: 86, athleticism: 94, footballIQ: 85 },
    highlightStat: '92 Straight-Line Recovery Speed on Go Routes',
  },
  {
    id: 's-winfield',
    name: 'Antoine Winfield Jr.',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'S',
    ovr: 95,
    salary: 21,
    archetype: 'All-Pro Game-Wrecking Weapon (Madden 95)',
    attributes: { passRush: 88, runDefense: 94, coverage: 95, athleticism: 92, footballIQ: 98 },
    highlightStat: '99 Goal-Line Strip Fumbles, Sacks & Interceptions',
  },
  // --- NFC South Kickers & Special Teams ---
  {
    id: 'k-koo-younghoe',
    name: 'Younghoe Koo',
    team: 'ATL',
    teamCity: 'Atlanta',
    position: 'K',
    ovr: 85,
    salary: 4,
    starter: true,
    archetype: 'Onside Kick Wizard & Clutch Sniper',
    attributes: { passing: 0, rushing: 0, kicking: 90, athleticism: 74, footballIQ: 92 },
    highlightStat: 'NFL Record Onside Recovery Touch & 90% Career Accuracy',
  },
  {
    id: 'k-pineiro-eddy',
    name: 'Eddy Piñeiro',
    team: 'CAR',
    teamCity: 'Carolina',
    position: 'K',
    ovr: 81,
    salary: 3,
    starter: true,
    archetype: 'High-Percentage Steady Placekicker',
    attributes: { passing: 0, rushing: 0, kicking: 85, athleticism: 75, footballIQ: 83 },
    highlightStat: '90%+ Field Goal Percentage & Dependable Cold Snap Executions',
  },
  {
    id: 'k-grupe-blake',
    name: 'Blake Grupe',
    team: 'NO',
    teamCity: 'New Orleans',
    position: 'K',
    ovr: 80,
    salary: 2,
    starter: true,
    archetype: 'Superdome High-Arc Specialist',
    attributes: { passing: 0, rushing: 0, kicking: 84, athleticism: 76, footballIQ: 82 },
    highlightStat: 'Superdome 55-Yard Range & High Altitude Flight',
  },
  {
    id: 'k-mclaughlin-chase',
    name: 'Chase McLaughlin',
    team: 'TB',
    teamCity: 'Tampa Bay',
    position: 'K',
    ovr: 85,
    salary: 4,
    starter: true,
    archetype: '50+ Yard Laser Cannon Sniper',
    attributes: { passing: 0, rushing: 0, kicking: 90, athleticism: 75, footballIQ: 87 },
    highlightStat: '94% from 50+ Yards in Tampa Bay Franchise Record',
  },
];
