import { Player } from '../../types';

export const NFC_WEST_PLAYERS: Player[] = [
  // ===================== ARIZONA CARDINALS (ARI) =====================
  {
    id: 'qb-murray',
    name: 'Kyler Murray',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'QB',
    ovr: 86,
    salary: 46,
    starter: true,
    archetype: 'Dual-Threat Scrambler / Off-Platform Dynamo',
    attributes: { passing: 87, rushing: 92, passBlocking: 0, runBlocking: 0, athleticism: 93, footballIQ: 85 },
    highlightStat: '94 Acceleration & Off-Platform Arm Velocity',
  },
  {
    id: 'qb-tune',
    name: 'Clayton Tune',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'QB',
    ovr: 70,
    salary: 1,
    starter: false,
    archetype: 'Athletic Scramble Backup',
    attributes: { passing: 72, rushing: 78, passBlocking: 0, runBlocking: 0, athleticism: 82, footballIQ: 74 },
    highlightStat: '79 Scramble Mobility',
  },
  {
    id: 'rb-conner',
    name: 'James Conner',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'RB',
    ovr: 85,
    salary: 7,
    archetype: 'Power Bruiser',
    attributes: { passing: 0, rushing: 88, receiving: 76, passBlocking: 78, runBlocking: 0, athleticism: 82, footballIQ: 86 },
    highlightStat: '91 Yards After Contact & Stiff Arm',
  },
  {
    id: 'rb-benson',
    name: 'Trey Benson',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'RB',
    ovr: 77,
    salary: 2,
    archetype: 'Breakaway Speed',
    attributes: { passing: 0, rushing: 80, receiving: 70, passBlocking: 68, runBlocking: 0, athleticism: 90, footballIQ: 76 },
    highlightStat: '92 Speed Burst on Perimeter Outside Zone',
  },
  {
    id: 'wr-mrv',
    name: 'Marvin Harrison Jr.',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'WR',
    ovr: 85,
    salary: 8,
    archetype: 'Generational Route Technician',
    attributes: { passing: 0, rushing: 0, receiving: 89, passBlocking: 0, runBlocking: 62, athleticism: 91, footballIQ: 88 },
    highlightStat: '93 Catch Radius & Pure Release Technique',
  },
  {
    id: 'wr-wilson-michael',
    name: 'Michael Wilson',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'WR',
    ovr: 78,
    salary: 2,
    archetype: 'Possession Boundary Receiver',
    attributes: { passing: 0, rushing: 0, receiving: 80, passBlocking: 0, runBlocking: 68, athleticism: 82, footballIQ: 80 },
    highlightStat: '82 Contested Catch Along Sideline',
  },
  {
    id: 'te-mcbride',
    name: 'Trey McBride',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'TE',
    ovr: 89,
    salary: 2,
    archetype: 'Elite Move Tight End',
    attributes: { passing: 0, rushing: 0, receiving: 91, passBlocking: 74, runBlocking: 80, athleticism: 86, footballIQ: 88 },
    highlightStat: '92 Intermediate Separation & High YAC',
  },
  {
    id: 'ot-johnson-paris',
    name: 'Paris Johnson Jr.',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'OT',
    ovr: 82,
    salary: 7,
    archetype: 'Agile Blindside Protector',
    attributes: { passing: 0, rushing: 0, passBlocking: 84, runBlocking: 82, athleticism: 86, footballIQ: 82 },
    highlightStat: '86 Lateral Recovery & Mirroring Footwork',
  },
  {
    id: 'ot-beachum',
    name: 'Kelvin Beachum',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'OT',
    ovr: 77,
    salary: 2,
    archetype: 'Veteran Pass Pro Specialist',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 75, athleticism: 72, footballIQ: 86 },
    highlightStat: '83 Experienced Pass Sets & Punch Placement',
  },
  {
    id: 'og-hernandez',
    name: 'Will Hernandez',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'OG',
    ovr: 80,
    salary: 4,
    archetype: 'Mauling Power Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 85, athleticism: 75, footballIQ: 81 },
    highlightStat: '88 Raw Torque in Gap Scheme Pulls',
  },
  {
    id: 'og-brown-evan',
    name: 'Evan Brown',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'OG',
    ovr: 78,
    salary: 3,
    archetype: 'Solid Interior Combo Blocker',
    attributes: { passing: 0, rushing: 0, passBlocking: 79, runBlocking: 80, athleticism: 77, footballIQ: 82 },
    highlightStat: '84 Zone Reach & Combo Displacement',
  },
  {
    id: 'c-froholdt',
    name: 'Hjalte Froholdt',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'C',
    ovr: 81,
    salary: 4,
    archetype: 'Physical Viking Pivot',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 86, athleticism: 78, footballIQ: 84 },
    highlightStat: '88 Gap Scheme Drive Power & Anchor',
  },
  {
    id: 'edge-collins-zaven',
    name: 'Zaven Collins',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'EDGE',
    ovr: 79,
    salary: 14,
    archetype: 'Edge Setter / Power Rusher',
    attributes: { passRush: 78, runDefense: 83, coverage: 71, athleticism: 84, footballIQ: 81 },
    highlightStat: '84 Edge Contain & Tackling Range',
  },
  {
    id: 'edge-gardeck',
    name: 'Dennis Gardeck',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'EDGE',
    ovr: 78,
    salary: 5,
    archetype: 'Speed Rush Specialist',
    attributes: { passRush: 82, runDefense: 72, coverage: 65, athleticism: 86, footballIQ: 80 },
    highlightStat: '86 First-Step Get-Off on Passing Downs',
  },
  {
    id: 'dt-nichols',
    name: 'Bilal Nichols',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'DT',
    ovr: 79,
    salary: 7,
    archetype: 'Heavy Gap-Plugger',
    attributes: { passRush: 77, runDefense: 83, coverage: 40, athleticism: 76, footballIQ: 82 },
    highlightStat: '85 2-Gap Hold on Inside Runs',
  },
  {
    id: 'lb-white-kyzir',
    name: 'Kyzir White',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'LB',
    ovr: 82,
    salary: 5,
    archetype: 'Sideline-to-Sideline Chase LB',
    attributes: { passRush: 73, runDefense: 84, coverage: 80, athleticism: 83, footballIQ: 84 },
    highlightStat: '85 Read-and-React Pursuit Angle',
  },
  {
    id: 'cb-murphy-bunting',
    name: 'Sean Murphy-Bunting',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'CB',
    ovr: 79,
    salary: 6,
    archetype: 'Press-Man Cornerback',
    attributes: { passRush: 0, runDefense: 72, coverage: 82, athleticism: 88, footballIQ: 80 },
    highlightStat: '84 Break on Football & Press Jam',
  },
  {
    id: 's-baker',
    name: 'Budda Baker',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'S',
    ovr: 90,
    salary: 14,
    archetype: 'Heat-Seeking Box Enforcer',
    attributes: { passRush: 76, runDefense: 94, coverage: 86, athleticism: 89, footballIQ: 93 },
    highlightStat: '95 Run Alley Fills & Unrivaled High Motor',
  },
  {
    id: 's-thompson-jalen',
    name: 'Jalen Thompson',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'S',
    ovr: 83,
    salary: 8,
    archetype: 'Versatile Split-Safety',
    attributes: { passRush: 65, runDefense: 82, coverage: 85, athleticism: 84, footballIQ: 85 },
    highlightStat: '86 Open-Field Tackling in Space',
  },

  // ===================== LOS ANGELES RAMS (LAR) =====================
  {
    id: 'qb-stafford',
    name: 'Matthew Stafford',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'QB',
    ovr: 87,
    salary: 40,
    starter: true,
    archetype: 'Super Bowl Champion / Sidearm Gunslinger',
    attributes: { passing: 93, rushing: 58, passBlocking: 0, runBlocking: 0, athleticism: 62, footballIQ: 96 },
    highlightStat: '98 No-Look Passes, Arm Angles & Pocket Toughness',
  },
  {
    id: 'qb-garoppolo',
    name: 'Jimmy Garoppolo',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'QB',
    ovr: 75,
    salary: 3,
    starter: false,
    archetype: 'Experienced Quick-Release Veteran',
    attributes: { passing: 78, rushing: 58, passBlocking: 0, runBlocking: 0, athleticism: 62, footballIQ: 84 },
    highlightStat: '85 Quick Slant Release',
  },
  {
    id: 'rb-kyren',
    name: 'Kyren Williams',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'RB',
    ovr: 89,
    salary: 1,
    archetype: 'Elite Vision & Touchdown Engine',
    attributes: { passing: 0, rushing: 92, receiving: 84, passBlocking: 88, runBlocking: 0, athleticism: 86, footballIQ: 95 },
    highlightStat: '97 Zone Cutback Vision & Blitz Protection Mastery',
  },
  {
    id: 'wr-nacua',
    name: 'Puka Nacua',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'WR',
    ovr: 92,
    salary: 1,
    archetype: 'Historic NFL Rookie Record Holder / YAC Alpha (Madden 92)',
    attributes: { passing: 0, rushing: 82, receiving: 95, passBlocking: 0, runBlocking: 80, athleticism: 90, footballIQ: 95 },
    highlightStat: '98 Broken Tackles on Crossing Routes & Physical Dominance',
  },
  {
    id: 'wr-kupp',
    name: 'Cooper Kupp',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'WR',
    ovr: 90,
    salary: 27,
    archetype: 'Triple Crown / Master Route Technician',
    attributes: { passing: 0, rushing: 72, receiving: 96, passBlocking: 0, runBlocking: 74, athleticism: 86, footballIQ: 99 },
    highlightStat: '99 Pre-Snap Option Routes & Surgical Separation',
  },
  {
    id: 'wr-robinson-demarcus',
    name: 'Demarcus Robinson',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'WR',
    ovr: 80,
    salary: 4,
    archetype: 'Clutch One-Handed Touchdown Target',
    attributes: { passing: 0, rushing: 0, receiving: 82, passBlocking: 0, runBlocking: 66, athleticism: 86, footballIQ: 83 },
    highlightStat: '91 Spectacular One-Handed Over-the-Shoulder Catches',
  },
  {
    id: 'te-parkinson',
    name: 'Colby Parkinson',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'TE',
    ovr: 79,
    salary: 7,
    archetype: '6-Foot-7 Red-Zone In-Line',
    attributes: { passing: 0, rushing: 0, receiving: 80, passBlocking: 74, runBlocking: 80, athleticism: 81, footballIQ: 82 },
    highlightStat: '87 High-Point Catch Radius in End-Zone',
  },
  {
    id: 'ot-jackson-alaric',
    name: 'Alaric Jackson',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'OT',
    ovr: 82,
    salary: 5,
    archetype: 'Athletic Blindside Protector',
    attributes: { passing: 0, rushing: 0, passBlocking: 84, runBlocking: 83, athleticism: 81, footballIQ: 83 },
    highlightStat: '87 Pass Pro Anchor Against Bull Rush',
  },
  {
    id: 'ot-havenstein',
    name: 'Rob Havenstein',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'OT',
    ovr: 85,
    salary: 11,
    archetype: 'Veteran Wall Right Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 88, runBlocking: 87, athleticism: 74, footballIQ: 91 },
    highlightStat: '90 Wide Zone Reach & Pass Protection Anchor',
  },
  {
    id: 'og-dotson',
    name: 'Kevin Dotson',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'OG',
    ovr: 88,
    salary: 16,
    archetype: 'Dominant Power Guard Wall',
    attributes: { passing: 0, rushing: 0, passBlocking: 89, runBlocking: 94, athleticism: 80, footballIQ: 88 },
    highlightStat: '96 Gap Scheme Cleaving & Zero-Sack Pass Pro',
  },
  {
    id: 'og-avila',
    name: 'Steve Avila',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'OG',
    ovr: 81,
    salary: 2,
    archetype: 'Mauling 330-Pound Anchor',
    attributes: { passing: 0, rushing: 0, passBlocking: 82, runBlocking: 86, athleticism: 77, footballIQ: 83 },
    highlightStat: '89 Inside Gap Double Team Push',
  },
  {
    id: 'c-limmer',
    name: 'Beaux Limmer',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'C',
    ovr: 78,
    salary: 1,
    archetype: 'Power Weight-Room Monster Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 84, athleticism: 82, footballIQ: 79 },
    highlightStat: '88 Raw Grip Strength & Combos',
  },
  {
    id: 'edge-young-byron',
    name: 'Byron Young',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'EDGE',
    ovr: 84,
    salary: 1,
    archetype: '4.43 Explosive Speed Edge',
    attributes: { passRush: 87, runDefense: 83, coverage: 65, athleticism: 93, footballIQ: 83 },
    highlightStat: '93 First-Step Get-Off & QB Pursuits',
  },
  {
    id: 'edge-verse',
    name: 'Jared Verse',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'EDGE',
    ovr: 86,
    salary: 4,
    archetype: 'Defensive Rookie of the Year Frontrunner / Power Smasher',
    attributes: { passRush: 90, runDefense: 89, coverage: 60, athleticism: 92, footballIQ: 86 },
    highlightStat: '97 Bull Rush Shockwave & League-Leading Rookie Pressures',
  },
  {
    id: 'dt-turner-kobie',
    name: 'Kobie Turner',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'DT',
    ovr: 86,
    salary: 1,
    archetype: 'The Conductor / 3-Tech Sack Artist',
    attributes: { passRush: 90, runDefense: 86, coverage: 50, athleticism: 85, footballIQ: 88 },
    highlightStat: '94 Club-Swim Interior Moves & Double-Digit Sacks',
  },
  {
    id: 'dt-fiske',
    name: 'Braden Fiske',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'DT',
    ovr: 81,
    salary: 2,
    archetype: 'High-Motor Defensive Tackle Penetrator',
    attributes: { passRush: 84, runDefense: 82, coverage: 50, athleticism: 91, footballIQ: 81 },
    highlightStat: '91 4.78 40-Yard Dash Interior Chase Sacks',
  },
  {
    id: 'lb-rozeboom',
    name: 'Christian Rozeboom',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'LB',
    ovr: 78,
    salary: 1,
    archetype: 'Inside Flow Linebacker',
    attributes: { passRush: 72, runDefense: 81, coverage: 79, athleticism: 82, footballIQ: 81 },
    highlightStat: '84 Tackle Angles in Middle Zones',
  },
  {
    id: 'cb-williams-darious',
    name: 'Darious Williams',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'CB',
    ovr: 83,
    salary: 7,
    archetype: 'Zone Click-and-Close Master',
    attributes: { passRush: 0, runDefense: 76, coverage: 87, athleticism: 88, footballIQ: 90 },
    highlightStat: '92 PBU Timing on Out-Breaking Routes',
  },
  {
    id: 's-curl',
    name: 'Kamren Curl',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'S',
    ovr: 84,
    salary: 5,
    archetype: 'Surgical Box/Split Safety',
    attributes: { passRush: 75, runDefense: 88, coverage: 86, athleticism: 84, footballIQ: 91 },
    highlightStat: '90 Tackle Consistency & Pass Deflections in Seam',
  },

  // ===================== SAN FRANCISCO 49ERS (SF) =====================
  {
    id: 'qb-purdy',
    name: 'Brock Purdy',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'QB',
    ovr: 89,
    salary: 1,
    starter: true,
    archetype: 'Super Bowl Mastermind / Anticipation Sniper',
    attributes: { passing: 93, rushing: 82, passBlocking: 0, runBlocking: 0, athleticism: 82, footballIQ: 96 },
    highlightStat: '97 Anticipatory Middle-Field Darts & Playoff Comebacks',
  },
  {
    id: 'qb-dobbs',
    name: 'Joshua Dobbs',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'QB',
    ovr: 74,
    salary: 2,
    starter: false,
    archetype: 'Mobile Improviser Backup',
    attributes: { passing: 75, rushing: 82, passBlocking: 0, runBlocking: 0, athleticism: 85, footballIQ: 81 },
    highlightStat: '86 Off-Schedule Scramble Runs',
  },
  {
    id: 'rb-mccaffrey',
    name: 'Christian McCaffrey',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'RB',
    ovr: 99,
    salary: 19,
    archetype: 'OPOY / Greatest All-Purpose Weapon (Madden 99 Club)',
    attributes: { passing: 75, rushing: 99, receiving: 99, passBlocking: 86, runBlocking: 0, athleticism: 96, footballIQ: 99 },
    highlightStat: '99 Route Running, Vision, Hands & Red Zone Scoring Machine',
  },
  {
    id: 'rb-mason-jordan',
    name: 'Jordan Mason',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'RB',
    ovr: 82,
    salary: 1,
    archetype: 'One-Cut Physical Hammer',
    attributes: { passing: 0, rushing: 86, receiving: 74, passBlocking: 80, runBlocking: 0, athleticism: 86, footballIQ: 83 },
    highlightStat: '92 Yards After Contact on Outside Zone Stretches',
  },
  {
    id: 'wr-samuel-deebo',
    name: 'Deebo Samuel',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'WR',
    ovr: 90,
    salary: 24,
    archetype: 'Wide Back / Pure Physical Terror',
    attributes: { passing: 70, rushing: 89, receiving: 91, passBlocking: 0, runBlocking: 82, athleticism: 93, footballIQ: 92 },
    highlightStat: '98 Yards After Catch, Broken Tackles & Jet Sweeps',
  },
  {
    id: 'wr-aiyuk',
    name: 'Brandon Aiyuk',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'WR',
    ovr: 91,
    salary: 30,
    archetype: 'All-Pro Separation & Blocking Master',
    attributes: { passing: 0, rushing: 0, receiving: 94, passBlocking: 0, runBlocking: 85, athleticism: 92, footballIQ: 94 },
    highlightStat: '97 Route Precision, Dig Route Mastery & Downfield Blocks',
  },
  {
    id: 'wr-jauan-jennings',
    name: 'Jauan Jennings',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'WR',
    ovr: 84,
    salary: 8,
    archetype: '3rd-and-Jauan / Physical Dominator',
    attributes: { passing: 75, rushing: 0, receiving: 86, passBlocking: 0, runBlocking: 88, athleticism: 83, footballIQ: 91 },
    highlightStat: '96 3rd Down Broken Tackles & Super Bowl Touchdowns',
  },
  {
    id: 'te-kittle',
    name: 'George Kittle',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'TE',
    ovr: 97,
    salary: 15,
    archetype: 'The People\'s Tight End / Dominant Force (Madden 97)',
    attributes: { passing: 0, rushing: 74, receiving: 96, passBlocking: 88, runBlocking: 99, athleticism: 91, footballIQ: 97 },
    highlightStat: '99 Run-Blocking Pancakes & Freight-Train YAC Stiff Arms',
  },
  {
    id: 'ot-williams-trent',
    name: 'Trent Williams',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'OT',
    ovr: 99,
    salary: 27,
    archetype: 'Silverback / Greatest Lineman in History (Madden 99 Club)',
    attributes: { passing: 0, rushing: 0, passBlocking: 99, runBlocking: 99, athleticism: 94, footballIQ: 99 },
    highlightStat: '99 Space Pulling Decapitations & Impenetrable Blindside',
  },
  {
    id: 'ot-mckivitz',
    name: 'Colton McKivitz',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'OT',
    ovr: 79,
    salary: 5,
    archetype: 'Zone Scheme Right Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 79, runBlocking: 83, athleticism: 78, footballIQ: 81 },
    highlightStat: '85 Outside Zone Stretch Reach Blocks',
  },
  {
    id: 'og-banks-aaron',
    name: 'Aaron Banks',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'OG',
    ovr: 81,
    salary: 2,
    archetype: 'Heavy Gap Scheme Left Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 83, runBlocking: 84, athleticism: 76, footballIQ: 82 },
    highlightStat: '88 Pass Protection Solid Anchor',
  },
  {
    id: 'og-puni',
    name: 'Dominick Puni',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'OG',
    ovr: 83,
    salary: 1,
    archetype: 'Elite Rookie Pass-Protecting Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 88, runBlocking: 84, athleticism: 85, footballIQ: 85 },
    highlightStat: '92 Zero QB Pressures Allowed Streak',
  },
  {
    id: 'c-brendel',
    name: 'Jake Brendel',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'C',
    ovr: 79,
    salary: 4,
    archetype: 'Shanahan Outside Zone Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 84, athleticism: 84, footballIQ: 85 },
    highlightStat: '88 Wide Zone Reach Blocking & Cadence Calling',
  },
  {
    id: 'edge-bosa-nick',
    name: 'Nick Bosa',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'EDGE',
    ovr: 97,
    salary: 34,
    archetype: 'DPOY / Master Technician Pass Rusher (Madden 97)',
    attributes: { passRush: 99, runDefense: 96, coverage: 65, athleticism: 93, footballIQ: 98 },
    highlightStat: '99 Quad-Drive Bull Rush, Edge Bend & Relentless Pressures',
  },
  {
    id: 'edge-floyd-leonard',
    name: 'Leonard Floyd',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'EDGE',
    ovr: 83,
    salary: 10,
    archetype: 'Long-Limbed Bend Rusher',
    attributes: { passRush: 86, runDefense: 80, coverage: 72, athleticism: 85, footballIQ: 86 },
    highlightStat: '90 Double-Digit Sack Consistency',
  },
  {
    id: 'dt-collins-maliek',
    name: 'Maliek Collins',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'DT',
    ovr: 83,
    salary: 8,
    archetype: 'Quick-Twitch 3-Tech Disruptor',
    attributes: { passRush: 86, runDefense: 82, coverage: 50, athleticism: 84, footballIQ: 84 },
    highlightStat: '90 Interior Penetration in Wide-9 Scheme',
  },
  {
    id: 'lb-warner',
    name: 'Fred Warner',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'LB',
    ovr: 98,
    salary: 19,
    archetype: 'Best Linebacker in Football (Madden 98)',
    attributes: { passRush: 84, runDefense: 99, coverage: 99, athleticism: 93, footballIQ: 99 },
    highlightStat: '99 Middle-Field Eradication, Peanut Punches & Pick-Sixes',
  },
  {
    id: 'lb-greenlaw',
    name: 'Dre Greenlaw',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'LB',
    ovr: 87,
    salary: 8,
    archetype: 'Violent Enforcer Will LB',
    attributes: { passRush: 80, runDefense: 93, coverage: 87, athleticism: 91, footballIQ: 91 },
    highlightStat: '96 Goal-Line Bone-Crushing Hits & Playoff Picks',
  },
  {
    id: 'cb-ward-charvarius',
    name: 'Charvarius Ward',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'CB',
    ovr: 90,
    salary: 14,
    archetype: 'All-Pro Press-Man Island Corner',
    attributes: { passRush: 0, runDefense: 82, coverage: 93, athleticism: 92, footballIQ: 93 },
    highlightStat: '96 League-Leading PBUs & Boundary Shadowing',
  },
  {
    id: 'cb-lenoir',
    name: 'Deommodore Lenoir',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'CB',
    ovr: 86,
    salary: 15,
    archetype: 'The Hyena / Feisty Slot & Outside Eraser',
    attributes: { passRush: 76, runDefense: 87, coverage: 88, athleticism: 90, footballIQ: 91 },
    highlightStat: '93 Physical Tackles, PBU Feistiness & Interceptions',
  },
  {
    id: 's-hufanga',
    name: 'Talanoa Hufanga',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'S',
    ovr: 86,
    salary: 1,
    archetype: 'All-Pro Instinctive Polamalu Disciple',
    attributes: { passRush: 82, runDefense: 92, coverage: 86, athleticism: 88, footballIQ: 94 },
    highlightStat: '95 Triggering in the Flat, Pick-Sixes & Hard Hits',
  },
  {
    id: 's-mustapha',
    name: 'Malik Mustapha',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'S',
    ovr: 80,
    salary: 1,
    archetype: 'Human Heat-Seeking Missile',
    attributes: { passRush: 80, runDefense: 89, coverage: 81, athleticism: 92, footballIQ: 83 },
    highlightStat: '96 Goal-Line Collision Stops & Downhill Tackles',
  },

  // ===================== SEATTLE SEAHAWKS (SEA) =====================
  {
    id: 'qb-smith-geno',
    name: 'Geno Smith',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'QB',
    ovr: 85,
    salary: 25,
    starter: true,
    archetype: 'Pinpoint Deep Boundary Passer',
    attributes: { passing: 90, rushing: 76, passBlocking: 0, runBlocking: 0, athleticism: 81, footballIQ: 90 },
    highlightStat: '95 Game-Winning 4th Quarter Drives & Deep Touch',
  },
  {
    id: 'qb-howell',
    name: 'Sam Howell',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'QB',
    ovr: 75,
    salary: 2,
    starter: false,
    archetype: 'Gunslinger Backup Passer',
    attributes: { passing: 78, rushing: 77, passBlocking: 0, runBlocking: 0, athleticism: 80, footballIQ: 76 },
    highlightStat: '85 Deep Ball Throw Power',
  },
  {
    id: 'rb-walker',
    name: 'Kenneth Walker III',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'RB',
    ovr: 88,
    salary: 2,
    archetype: 'Human Highlight / Home Run Explosive Back',
    attributes: { passing: 0, rushing: 92, receiving: 83, passBlocking: 74, runBlocking: 0, athleticism: 95, footballIQ: 88 },
    highlightStat: '98 Ankle-Breaking Jump Cuts & 75-Yard House Calls',
  },
  {
    id: 'rb-charbonnet',
    name: 'Zach Charbonnet',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'RB',
    ovr: 80,
    salary: 2,
    archetype: 'Physical Contact Grinder',
    attributes: { passing: 0, rushing: 83, receiving: 80, passBlocking: 82, runBlocking: 0, athleticism: 84, footballIQ: 82 },
    highlightStat: '88 Short-Yardage Trucking & Pass Pro',
  },
  {
    id: 'wr-metcalf',
    name: 'DK Metcalf',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'WR',
    ovr: 90,
    salary: 24,
    archetype: '6-Foot-4 235 lb 4.33 Athletic God',
    attributes: { passing: 0, rushing: 70, receiving: 92, passBlocking: 0, runBlocking: 76, athleticism: 98, footballIQ: 90 },
    highlightStat: '99 Speed, Size, Slant Bullying & Chasedown Tackles',
  },
  {
    id: 'wr-lockett',
    name: 'Tyler Lockett',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'WR',
    ovr: 85,
    salary: 17,
    archetype: 'Toe-Tap Magician & Flawless Hands',
    attributes: { passing: 0, rushing: 0, receiving: 89, passBlocking: 0, runBlocking: 50, athleticism: 87, footballIQ: 96 },
    highlightStat: '97 Sideline Toe-Drag Mastery & Impeccable Route IQ',
  },
  {
    id: 'wr-smith-njigba',
    name: 'Jaxon Smith-Njigba',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'WR',
    ovr: 86,
    salary: 3,
    archetype: 'Historic 3-Cone Agility Slot Wizard',
    attributes: { passing: 0, rushing: 0, receiving: 90, passBlocking: 0, runBlocking: 62, athleticism: 91, footballIQ: 91 },
    highlightStat: '97 Short-Area Agility, Target Funnel & YAC',
  },
  {
    id: 'te-fant',
    name: 'Noah Fant',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'TE',
    ovr: 82,
    salary: 10,
    archetype: '4.50 Seam-Stretching Move TE',
    attributes: { passing: 0, rushing: 0, receiving: 84, passBlocking: 72, runBlocking: 76, athleticism: 91, footballIQ: 82 },
    highlightStat: '89 Seam Speed & YAC Burst',
  },
  {
    id: 'ot-cross-charles',
    name: 'Charles Cross',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'OT',
    ovr: 86,
    salary: 5,
    archetype: 'Elite Blindside Pass Protector',
    attributes: { passing: 0, rushing: 0, passBlocking: 91, runBlocking: 84, athleticism: 87, footballIQ: 88 },
    highlightStat: '93 Kick-Slide Mirror & Speed Rush Denial',
  },
  {
    id: 'ot-lucas-abraham',
    name: 'Abraham Lucas',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'OT',
    ovr: 82,
    salary: 2,
    archetype: 'Physical Road-Grading Right Tackle',
    attributes: { passing: 0, rushing: 0, passBlocking: 83, runBlocking: 86, athleticism: 83, footballIQ: 83 },
    highlightStat: '88 Down-Block Finishing & Punch Power',
  },
  {
    id: 'og-tomlinson-laken',
    name: 'Laken Tomlinson',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'OG',
    ovr: 79,
    salary: 4,
    archetype: 'Veteran Iron Man Left Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 80, runBlocking: 81, athleticism: 74, footballIQ: 88 },
    highlightStat: '85 Pass Protection Awareness & Anchor',
  },
  {
    id: 'og-bradford-anthony',
    name: 'Anthony Bradford',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'OG',
    ovr: 77,
    salary: 1,
    archetype: 'Massive 340-Pound Power Guard',
    attributes: { passing: 0, rushing: 0, passBlocking: 76, runBlocking: 84, athleticism: 73, footballIQ: 77 },
    highlightStat: '87 Gap Scheme Power Moving Defenders',
  },
  {
    id: 'c-oluwatimi',
    name: 'Olu Oluwatimi',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'C',
    ovr: 77,
    salary: 1,
    archetype: 'Stout Rimington Trophy Center',
    attributes: { passing: 0, rushing: 0, passBlocking: 78, runBlocking: 80, athleticism: 76, footballIQ: 84 },
    highlightStat: '84 Interior Double-Team Chemistry',
  },
  {
    id: 'edge-nwosu',
    name: 'Uchenna Nwosu',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'EDGE',
    ovr: 82,
    salary: 15,
    archetype: 'Disciplined Edge Setter & Rusher',
    attributes: { passRush: 84, runDefense: 86, coverage: 70, athleticism: 83, footballIQ: 85 },
    highlightStat: '88 Edge Contain & Strip Sacks',
  },
  {
    id: 'edge-hall-derick',
    name: 'Derick Hall',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'EDGE',
    ovr: 81,
    salary: 2,
    archetype: 'Speed-to-Power Bull Rusher',
    attributes: { passRush: 85, runDefense: 82, coverage: 60, athleticism: 89, footballIQ: 80 },
    highlightStat: '90 Power Stabs & QB Pressures',
  },
  {
    id: 'dt-williams-leonard',
    name: 'Leonard Williams',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'DT',
    ovr: 88,
    salary: 21,
    archetype: 'Big Cat / 5-Tech Versatile Monster',
    attributes: { passRush: 89, runDefense: 92, coverage: 55, athleticism: 85, footballIQ: 92 },
    highlightStat: '95 Multi-Position Disruption & Pocket Collapsing',
  },
  {
    id: 'dt-murphy-byron-ii',
    name: 'Byron Murphy II',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'DT',
    ovr: 81,
    salary: 4,
    archetype: 'Explosive Bowling Ball 3-Tech',
    attributes: { passRush: 85, runDefense: 84, coverage: 45, athleticism: 90, footballIQ: 80 },
    highlightStat: '92 First-Step Penetration & Pad Level Leverage',
  },
  {
    id: 'lb-dodson',
    name: 'Tyrel Dodson',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'LB',
    ovr: 82,
    salary: 4,
    archetype: 'Inside Run-Fitter',
    attributes: { passRush: 76, runDefense: 87, coverage: 80, athleticism: 82, footballIQ: 86 },
    highlightStat: '89 Gap Fill Tackles for Loss',
  },
  {
    id: 'cb-woolen',
    name: 'Riq Woolen',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'CB',
    ovr: 87,
    salary: 1,
    archetype: '6-Foot-4 4.26 Speed Anomaly',
    attributes: { passRush: 0, runDefense: 76, coverage: 90, athleticism: 99, footballIQ: 87 },
    highlightStat: '99 Pure Top Speed, Vertical Length & Over-the-Top Breakups',
  },
  {
    id: 'cb-witherspoon',
    name: 'Devon Witherspoon',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'CB',
    ovr: 90,
    salary: 8,
    archetype: 'All-Pro Heat-Seeking Missile Nickel/Outside (Madden 90)',
    attributes: { passRush: 86, runDefense: 93, coverage: 93, athleticism: 94, footballIQ: 95 },
    highlightStat: '98 Bone-Crushing Open-Field Hits, PBUs & Blitz Sacks',
  },
  {
    id: 's-love-julian',
    name: 'Julian Love',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'S',
    ovr: 86,
    salary: 11,
    archetype: 'Pro Bowl Swiss-Army Ballhawk',
    attributes: { passRush: 72, runDefense: 86, coverage: 90, athleticism: 87, footballIQ: 93 },
    highlightStat: '94 Clutch 4th Quarter Interceptions & Blocked Field Goals',
  },
  {
    id: 's-jenkins-rayshawn',
    name: 'Rayshawn Jenkins',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'S',
    ovr: 81,
    salary: 6,
    archetype: 'Physical Downhill Strong Safety',
    attributes: { passRush: 74, runDefense: 85, coverage: 81, athleticism: 84, footballIQ: 86 },
    highlightStat: '88 Box Run Fits & Forced Fumbles',
  },
  // --- NFC West Kickers & Special Teams ---
  {
    id: 'k-ryland-chad',
    name: 'Chad Ryland',
    team: 'ARI',
    teamCity: 'Arizona',
    position: 'K',
    ovr: 79,
    salary: 2,
    starter: true,
    archetype: 'Clutch Desert Game-Winner',
    attributes: { passing: 0, rushing: 0, kicking: 83, athleticism: 76, footballIQ: 81 },
    highlightStat: 'Multiple Walk-Off Game Winners in High-Scoring Thrillers',
  },
  {
    id: 'k-karty-joshua',
    name: 'Joshua Karty',
    team: 'LAR',
    teamCity: 'Los Angeles',
    position: 'K',
    ovr: 80,
    salary: 2,
    starter: true,
    archetype: 'Stanford Accuracy & SoFi Stadium Sniper',
    attributes: { passing: 0, rushing: 0, kicking: 85, athleticism: 77, footballIQ: 83 },
    highlightStat: 'Pinpoint Ball Flight & SoFi Stadium Reliability',
  },
  {
    id: 'k-moody-jake',
    name: 'Jake Moody',
    team: 'SF',
    teamCity: 'San Francisco',
    position: 'K',
    ovr: 81,
    salary: 2,
    starter: true,
    archetype: 'Super Bowl 55-Yard Record Setter',
    attributes: { passing: 0, rushing: 0, kicking: 86, athleticism: 76, footballIQ: 84 },
    highlightStat: '55-Yard Super Bowl Record Maker & Strong Leg',
  },
  {
    id: 'k-myers-jason',
    name: 'Jason Myers',
    team: 'SEA',
    teamCity: 'Seattle',
    position: 'K',
    ovr: 84,
    salary: 4,
    starter: true,
    archetype: 'Lumen Field Rain & Wind Clutch Veteran',
    attributes: { passing: 0, rushing: 0, kicking: 88, athleticism: 75, footballIQ: 89 },
    highlightStat: '60+ Yard Franchise Long & Lumen Field Walk-Off Clutch Record',
  },
];
