import React, { useMemo, useState } from 'react';
import { ArrowLeft, Building2, CalendarDays, ChevronRight, Crown, DollarSign, Gavel, Landmark, Shield, Trophy, Users } from 'lucide-react';

const SAVE_KEY = 'ballknower_owner_career_v3';
export type OwnerTeamBaseline = { abbr:string;team:string;stadium:string;capacity:number;valuationB:number;valuationSource:'Forbes 2025 estimate';stadiumSource:'public stadium capacity';homeGames2026:number;scheduleSource:'NFL.com 2026 opponents' };
type StaffChoice={id:string;name:string;archetype:string;football:number;culture:number;costM:number};
type OwnerState={ownerName:string;abbr:string;week:number;season:number;cashM:number;approval:number;staffMorale:number;leagueInfluence:number;legacy:number;wins:number;losses:number;stadium:number;fanTrust:number;gm?:StaffChoice;coach?:StaffChoice;currentDecision:number;history:string[]};
type Effect=Partial<Record<'cashM'|'approval'|'staffMorale'|'leagueInfluence'|'legacy'|'stadium'|'fanTrust',number>>;
type DecisionChoice={label:string;detail:string;effect:Effect};
type Decision={eyebrow:string;title:string;scene:string;pressure:string;choices:DecisionChoice[]};

const AFC=new Set(['BAL','BUF','CIN','CLE','DEN','HOU','IND','JAX','KC','LV','LAC','MIA','NE','NYJ','PIT','TEN']);
const TEAMS:OwnerTeamBaseline[]=[
['ARI','Arizona Cardinals','State Farm Stadium',63400,5.5],['ATL','Atlanta Falcons','Mercedes-Benz Stadium',71000,6.2],['BAL','Baltimore Ravens','M&T Bank Stadium',71008,6.5],['BUF','Buffalo Bills','New Highmark Stadium',62000,6.1],
['CAR','Carolina Panthers','Bank of America Stadium',74867,5.7],['CHI','Chicago Bears','Soldier Field',61500,8.8],['CIN','Cincinnati Bengals','Paycor Stadium',65515,5.25],['CLE','Cleveland Browns','Huntington Bank Field',67431,6.4],
['DAL','Dallas Cowboys','AT&T Stadium',80000,13],['DEN','Denver Broncos','Empower Field at Mile High',76125,7.3],['DET','Detroit Lions','Ford Field',65000,6.7],['GB','Green Bay Packers','Lambeau Field',81441,6.5],
['HOU','Houston Texans','NRG Stadium',72220,6.6],['IND','Indianapolis Colts','Lucas Oil Stadium',67000,5.9],['JAX','Jacksonville Jaguars','EverBank Stadium',67814,5.4],['KC','Kansas City Chiefs','GEHA Field at Arrowhead Stadium',76416,7],
['LV','Las Vegas Raiders','Allegiant Stadium',65000,7.7],['LAC','Los Angeles Chargers','SoFi Stadium',70240,6.9],['LAR','Los Angeles Rams','SoFi Stadium',70240,10.5],['MIA','Miami Dolphins','Hard Rock Stadium',64767,7.5],
['MIN','Minnesota Vikings','U.S. Bank Stadium',66860,6.6],['NE','New England Patriots','Gillette Stadium',64628,9],['NO','New Orleans Saints','Caesars Superdome',73208,5.3],['NYG','New York Giants','MetLife Stadium',82500,10.1],
['NYJ','New York Jets','MetLife Stadium',82500,8.8],['PHI','Philadelphia Eagles','Lincoln Financial Field',67594,8.3],['PIT','Pittsburgh Steelers','Acrisure Stadium',68400,7],['SF','San Francisco 49ers','Levi’s Stadium',68500,8.6],
['SEA','Seattle Seahawks','Lumen Field',68740,6.8],['TB','Tampa Bay Buccaneers','Raymond James Stadium',65618,6.6],['TEN','Tennessee Titans','Nissan Stadium',69143,5.7],['WAS','Washington Commanders','Northwest Stadium',62000,7.4],
].map(([abbr,team,stadium,capacity,valuationB])=>({abbr:String(abbr),team:String(team),stadium:String(stadium),capacity:Number(capacity),valuationB:Number(valuationB),valuationSource:'Forbes 2025 estimate' as const,stadiumSource:'public stadium capacity' as const,homeGames2026:AFC.has(String(abbr))?8:9,scheduleSource:'NFL.com 2026 opponents' as const}));

const GMS:StaffChoice[]=[{id:'cap',name:'Marcus Grant',archetype:'Cap Architect',football:78,culture:70,costM:7.5},{id:'scout',name:'Darius King',archetype:'Elite Scout',football:86,culture:61,costM:9.2},{id:'players',name:'Andre Collins',archetype:'Players’ Executive',football:74,culture:88,costM:8.4}];
const COACHES:StaffChoice[]=[{id:'teacher',name:'Malik Hayes',archetype:'Culture Builder',football:78,culture:91,costM:10},{id:'offense',name:'Cole Bennett',archetype:'Offensive Visionary',football:91,culture:66,costM:13},{id:'defense',name:'Raymond Stone',archetype:'Defensive Enforcer',football:88,culture:72,costM:12}];
const DECISIONS:Decision[]=[
{eyebrow:'THE FIRST PRESSURE TEST',title:'YOUR STAR WANTS OUT',scene:'Your best player’s agent calls before sunrise. He wants a new deal or a trade—and the story is already leaking.',pressure:'Players, fans and the locker room are watching what kind of owner you will be.',choices:[{label:'PAY THE STAR',detail:'Protect the locker room; absorb the business hit.',effect:{cashM:-38,approval:5,staffMorale:6,fanTrust:7,legacy:2}},{label:'LET THE GM HANDLE IT',detail:'Back football operations and accept uncertainty.',effect:{staffMorale:8,leagueInfluence:2,approval:-2,legacy:1}},{label:'ORDER A TRADE',detail:'Take control, gain flexibility and risk the fanbase.',effect:{cashM:16,approval:-10,fanTrust:-12,staffMorale:-5,legacy:-2}}]},
{eyebrow:'CITY HALL · CLOSED DOOR',title:'THE STADIUM BILLION',scene:'The mayor offers infrastructure support, but only if the franchise commits private money and twenty more years to the city.',pressure:'This changes cash, stadium quality, fan trust and political capital.',choices:[{label:'BUILD TOGETHER',detail:'Share the cost and make a public commitment.',effect:{cashM:-120,stadium:18,approval:8,fanTrust:10,leagueInfluence:4,legacy:6}},{label:'PRIVATELY FINANCE',detail:'Keep control and take the largest financial risk.',effect:{cashM:-210,stadium:24,approval:5,fanTrust:5,legacy:9}},{label:'WALK AWAY',detail:'Protect cash and study other markets.',effect:{cashM:15,approval:-7,fanTrust:-15,leagueInfluence:-4,legacy:-3}}]},
{eyebrow:'OWNERS MEETING',title:'THE VOTE IS 23–8',scene:'A controversial rule change needs one more vote. Two powerful owners want your support—and both expect a favor later.',pressure:'League politics can unlock influence, but fans may hate the deal.',choices:[{label:'VOTE WITH THE OLD GUARD',detail:'Gain influence with powerful owners.',effect:{leagueInfluence:12,approval:-5,fanTrust:-4,legacy:2}},{label:'SIDE WITH THE PLAYERS',detail:'Protect trust and challenge leadership.',effect:{leagueInfluence:-6,approval:8,fanTrust:9,staffMorale:4,legacy:4}},{label:'ABSTAIN',detail:'Avoid the fight; lose respect in both rooms.',effect:{leagueInfluence:-4,approval:-2,legacy:-1}}]},
{eyebrow:'MONDAY MORNING',title:'THE COACH LOST THE ROOM',scene:'Three veterans complained publicly after another ugly loss. Your coach wants you to stay out of football business.',pressure:'A firing can excite fans and destroy stability. Patience can look weak.',choices:[{label:'BACK THE COACH',detail:'Choose stability and demand a turnaround.',effect:{staffMorale:9,approval:-4,fanTrust:-2,legacy:2}},{label:'FIRE HIM NOW',detail:'Reset the building and own the consequences.',effect:{cashM:-18,approval:7,staffMorale:-12,fanTrust:4,legacy:-1}},{label:'LET THE GM DECIDE',detail:'Honor the chain of command.',effect:{staffMorale:6,leagueInfluence:2,approval:-1,legacy:2}}]},
{eyebrow:'FAN COUNCIL',title:'WINNING GOT EXPENSIVE',scene:'Demand is surging. Your business team recommends a major ticket increase before the home schedule begins.',pressure:'Revenue builds the franchise. Affordability builds generations of fans.',choices:[{label:'RAISE PRICES 18%',detail:'Maximize demand while it is hot.',effect:{cashM:44,approval:-9,fanTrust:-11,legacy:-2}},{label:'SMALL INCREASE',detail:'Balance revenue with loyalty.',effect:{cashM:19,approval:1,fanTrust:1,legacy:2}},{label:'FREEZE PRICES',detail:'Turn fan loyalty into your identity.',effect:{cashM:-8,approval:10,fanTrust:13,legacy:6}}]},
];

const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,n));
const defaults:OwnerState={ownerName:'',abbr:'PHI',week:0,season:2026,cashM:350,approval:54,staffMorale:60,leagueInfluence:20,legacy:0,wins:0,losses:0,stadium:72,fanTrust:55,currentDecision:0,history:[]};
const restore=():OwnerState=>{try{const raw=localStorage.getItem(SAVE_KEY);return raw?{...defaults,...JSON.parse(raw)}:defaults;}catch{return defaults;}};
const persist=(state:OwnerState)=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch{}};
const moneyM=(n:number)=>`${n<0?'-':''}$${Math.abs(n).toFixed(0)}M`;

export const OwnerBusinessMode:React.FC<{onBack:()=>void}>=({onBack})=>{
 const initial=useMemo(restore,[]);const [state,setState]=useState<OwnerState>(initial);const [intro,setIntro]=useState(initial.ownerName?3:0);const [draftName,setDraftName]=useState(initial.ownerName);const [draftTeam,setDraftTeam]=useState(initial.abbr);
 const team=TEAMS.find(t=>t.abbr===state.abbr)||TEAMS[0];const decision=DECISIONS[state.currentDecision%DECISIONS.length];
 const projectedValue=team.valuationB*(1+state.legacy*.0025+(state.stadium-70)*.002+(state.fanTrust-50)*.0015);const ownerGrade=Math.round(clamp((state.approval+state.staffMorale+state.fanTrust+state.leagueInfluence)/4+state.legacy*.2));
 const save=(patch:Partial<OwnerState>)=>{const next={...state,...patch};setState(next);persist(next);};
 const begin=()=>{if(!draftName.trim())return;const next={...state,ownerName:draftName.trim(),abbr:draftTeam};setState(next);persist(next);setIntro(3);};
 const hire=(role:'gm'|'coach',person:StaffChoice)=>save({[role]:person,cashM:state.cashM-person.costM,staffMorale:clamp(state.staffMorale+person.culture/18),history:[`Hired ${person.name} as ${role==='gm'?'general manager':'head coach'}.`,...state.history].slice(0,20)} as Partial<OwnerState>);
 const choose=(choice:DecisionChoice)=>{const patch:any={};Object.entries(choice.effect).forEach(([key,value])=>{patch[key]=key==='cashM'?state.cashM+(value||0):clamp((state as any)[key]+(value||0));});const won=Math.random()<clamp(42+(state.gm?.football||70)/8+(state.coach?.football||70)/7+state.staffMorale/10,35,78)/100;const rollover=state.week>=17;patch.week=rollover?0:state.week+1;patch.season=rollover?state.season+1:state.season;patch.wins=rollover?0:state.wins+(won?1:0);patch.losses=rollover?0:state.losses+(won?0:1);patch.currentDecision=state.currentDecision+1;patch.history=[`${choice.label}: ${rollover?'A new league year begins.':won?'The team won this week.':'The team lost this week.'}`,...state.history].slice(0,20);save(patch);try{navigator.vibrate?.(won?[35,45,70]:[80]);}catch{}};

 if(intro<3)return <div className="min-h-[100dvh] bg-[#05070b] px-5 py-6 text-white sm:px-8"><div className="mx-auto flex min-h-[calc(100dvh-3rem)] max-w-4xl flex-col"><button onClick={onBack} className="flex min-h-11 w-fit items-center gap-2 rounded-full border border-white/10 bg-black/30 px-4 text-xs font-black"><ArrowLeft size={16}/> BACK</button><div className="flex flex-1 items-center py-8"><div className="w-full rounded-[2rem] border border-amber-300/25 bg-[#0c1018] p-6 shadow-2xl sm:p-9">
  {intro===0&&<><div className="text-[10px] font-black tracking-[.25em] text-amber-300">OWNER CAREER · THE CALL</div><h1 className="mt-3 text-4xl font-black leading-none sm:text-6xl">YOU DIDN’T BUY A TEAM.<br/>YOU BOUGHT EVERY PROBLEM.</h1><p className="mt-5 max-w-2xl text-sm font-semibold leading-7 text-zinc-400">Money gets you inside the building. Your decisions determine whether the franchise, city, locker room and league ever respect you.</p><button onClick={()=>setIntro(1)} className="mt-7 flex min-h-12 w-full items-center justify-between rounded-2xl bg-amber-300 px-5 font-black text-black">ENTER THE OWNER’S SUITE <ChevronRight/></button></>}
  {intro===1&&<><div className="text-[10px] font-black tracking-[.25em] text-amber-300">POWER HAS A PRICE</div><h1 className="mt-3 text-4xl font-black leading-none sm:text-6xl">EVERY ROOM<br/>REMEMBERS YOUR CHOICE.</h1><div className="mt-6 grid gap-3 sm:grid-cols-3">{[['THE CITY','Stadium money and relocation pressure.'],['THE BUILDING','Staff, players and culture.'],['THE LEAGUE','Politics, favors and legacy.']].map(([a,b])=><div key={a} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="font-black text-amber-300">{a}</div><p className="mt-2 text-xs leading-5 text-zinc-400">{b}</p></div>)}</div><button onClick={()=>setIntro(2)} className="mt-7 flex min-h-12 w-full items-center justify-between rounded-2xl bg-amber-300 px-5 font-black text-black">TAKE CONTROL <ChevronRight/></button></>}
  {intro===2&&<><div className="text-[10px] font-black tracking-[.25em] text-amber-300">CREATE YOUR OWNER</div><h1 className="mt-2 text-4xl font-black">WHO OWNS THE ROOM?</h1><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-black text-zinc-400">OWNER NAME<input value={draftName} onChange={e=>setDraftName(e.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-white/10 bg-black/40 px-4 text-base text-white"/></label><label className="text-xs font-black text-zinc-400">FRANCHISE<select value={draftTeam} onChange={e=>setDraftTeam(e.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-white/10 bg-black px-4 text-base text-white">{TEAMS.map(t=><option key={t.abbr} value={t.abbr}>{t.team}</option>)}</select></label></div><button disabled={!draftName.trim()} onClick={begin} className="mt-7 flex min-h-12 w-full items-center justify-between rounded-2xl bg-amber-300 px-5 font-black text-black disabled:opacity-30">BEGIN MY LEGACY <ChevronRight/></button></>}
 </div></div></div></div>;

 return <div className="min-h-[100dvh] bg-[#06080d] px-4 py-5 text-white sm:px-8"><div className="mx-auto max-w-6xl">
  <div className="mb-5 flex items-center justify-between gap-4"><button onClick={onBack} className="flex min-h-11 items-center gap-2 rounded-full border border-white/10 bg-black/30 px-4 text-xs font-black"><ArrowLeft size={16}/> SOLO</button><div className="text-right"><div className="text-[10px] font-black tracking-[.25em] text-amber-300">OWNER CAREER · {state.season}</div><div className="text-lg font-black">{state.ownerName}</div></div></div>
  <section className="overflow-hidden rounded-[2rem] border border-amber-300/25 bg-[radial-gradient(circle_at_85%_20%,rgba(252,211,77,.17),transparent_30%),#0c1018] p-5 sm:p-7"><div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div><div className="flex items-center gap-2 text-amber-300"><Crown size={18}/><span className="text-xs font-black tracking-[.22em]">THE OWNER’S SUITE</span></div><h1 className="mt-2 text-4xl font-black sm:text-6xl">{team.team}</h1><p className="mt-2 text-sm font-semibold text-zinc-400">{team.stadium} · {team.capacity.toLocaleString()} seats · Week {state.week||'Preseason'}</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-white/5 px-3 py-2 text-xs font-black"><Trophy size={13} className="mr-1 inline text-amber-300"/>{state.wins}-{state.losses}</span><span className="rounded-full bg-white/5 px-3 py-2 text-xs font-black"><DollarSign size={13} className="mr-1 inline text-emerald-300"/>{moneyM(state.cashM)} CASH</span><span className="rounded-full bg-white/5 px-3 py-2 text-xs font-black"><Landmark size={13} className="mr-1 inline text-sky-300"/>${projectedValue.toFixed(2)}B VALUE</span></div></div><div className="rounded-3xl border border-white/10 bg-black/30 p-5"><div className="text-[10px] font-black tracking-widest text-amber-300">OWNER RATING</div><div className="mt-1 text-6xl font-black">{ownerGrade}</div><div className="mt-4 grid grid-cols-2 gap-2 text-[10px]">{[['Approval',state.approval],['Fan Trust',state.fanTrust],['Staff',state.staffMorale],['Influence',state.leagueInfluence]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-white/5 p-3"><div className="text-zinc-500">{l}</div><div className="mt-1 text-lg font-black">{v}</div></div>)}</div></div></div></section>
  {(!state.gm||!state.coach)&&<section className="mt-5 rounded-[2rem] border border-white/10 bg-[#0d121b] p-5 sm:p-6"><div className="flex items-center gap-2"><Users className="text-amber-300"/><h2 className="text-2xl font-black">BUILD YOUR FRONT OFFICE</h2></div><p className="mt-2 text-sm text-zinc-400">Football skill affects results. Culture affects stability and pressure.</p>{!state.gm&&<StaffBoard title="HIRE A GENERAL MANAGER" people={GMS} onHire={p=>hire('gm',p)}/>} {!state.coach&&<StaffBoard title="HIRE A HEAD COACH" people={COACHES} onHire={p=>hire('coach',p)}/>}</section>}
  {state.gm&&state.coach&&<section className="mt-5 rounded-[2rem] border border-amber-300/20 bg-[#0d121b] p-5 sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black tracking-[.22em] text-amber-300"><CalendarDays size={16}/> WEEK {state.week||1} PRESSURE MOMENT</div><h2 className="mt-2 text-3xl font-black sm:text-5xl">{decision.title}</h2></div><div className="rounded-xl bg-white/5 px-3 py-2 text-[10px] font-black text-zinc-400">LEGACY {state.legacy}</div></div><div className="mt-5 grid gap-4 lg:grid-cols-[.85fr_1.15fr]"><div className="rounded-2xl border border-white/10 bg-black/30 p-5"><div className="text-[10px] font-black tracking-widest text-amber-300">{decision.eyebrow}</div><p className="mt-3 text-xl font-black leading-8">“{decision.scene}”</p><p className="mt-4 text-xs font-semibold leading-6 text-zinc-500">{decision.pressure}</p></div><div className="grid gap-3">{decision.choices.map(choice=><button key={choice.label} onClick={()=>choose(choice)} className="min-h-20 touch-manipulation rounded-2xl border border-white/10 bg-white/[.035] p-4 text-left transition active:scale-[.99] hover:border-amber-300/30"><div className="flex items-center justify-between gap-3"><div><div className="font-black">{choice.label}</div><div className="mt-1 text-xs leading-5 text-zinc-500">{choice.detail}</div></div><ChevronRight className="shrink-0 text-amber-300"/></div></button>)}</div></div></section>}
  <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-[2rem] border border-white/10 bg-[#0d121b] p-5"><div className="flex items-center gap-2"><Building2 className="text-amber-300"/><h3 className="text-xl font-black">FRANCHISE ASSETS</h3></div><div className="mt-4 grid grid-cols-2 gap-3">{[['Stadium',state.stadium],['Fan Trust',state.fanTrust],['League Power',state.leagueInfluence],['Legacy',state.legacy]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-black/25 p-3"><div className="text-[9px] font-black text-zinc-500">{l}</div><div className="mt-1 text-2xl font-black">{v}</div></div>)}</div><div className="mt-4 rounded-xl border border-white/5 bg-black/20 p-3 text-[10px] leading-5 text-zinc-600">Real-world baseline: {team.valuationSource}; {team.stadiumSource}; {team.scheduleSource}. Career outcomes are Ball Knower simulation results.</div></section><section className="rounded-[2rem] border border-white/10 bg-[#0d121b] p-5"><div className="flex items-center gap-2"><Gavel className="text-amber-300"/><h3 className="text-xl font-black">LEGACY LEDGER</h3></div><div className="mt-4 space-y-2">{state.history.length?state.history.slice(0,5).map((item,i)=><div key={`${item}-${i}`} className="rounded-xl bg-black/25 p-3 text-xs font-semibold text-zinc-300">{item}</div>):<div className="rounded-xl border border-dashed border-white/10 p-6 text-center text-xs text-zinc-600">Your first decision will define the franchise.</div>}</div></section></div>
 </div></div>;
};

const StaffBoard=({title,people,onHire}:{title:string;people:StaffChoice[];onHire:(person:StaffChoice)=>void})=><div className="mt-5"><div className="text-[10px] font-black tracking-[.2em] text-zinc-500">{title}</div><div className="mt-2 grid gap-3 sm:grid-cols-3">{people.map(person=><button key={person.id} onClick={()=>onHire(person)} className="min-h-32 rounded-2xl border border-white/10 bg-black/25 p-4 text-left hover:border-amber-300/30"><div className="flex items-center justify-between"><Shield className="text-amber-300"/><span className="text-[10px] font-black text-emerald-300">{moneyM(person.costM)}/YR</span></div><div className="mt-3 font-black">{person.name}</div><div className="text-xs text-zinc-500">{person.archetype}</div><div className="mt-3 flex gap-2 text-[9px] font-black"><span className="rounded bg-white/5 px-2 py-1">FB {person.football}</span><span className="rounded bg-white/5 px-2 py-1">CULT {person.culture}</span></div></button>)}</div></div>;
export default OwnerBusinessMode;
