import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,CalendarDays,ChevronRight,Crown,DollarSign,Gavel,Landmark,Trophy,Users}from'lucide-react';
import{nextOwnerDecision,OWNER_DECISIONS,unseenOwnerStoryCount,type OwnerChoice,type OwnerDecision}from'./ownerStoryEngine';
import{loadUserState,saveUserState}from'./userStateCloud';
const SAVE_KEY='ballknower_owner_career_v3';
const CLOUD_SAVE_KEY='owner_business_career_v1';
type Staff={id:string;name:string;role:string;football:number;culture:number;costM:number;tone:string};
type State={ownerName:string;abbr:string;week:number;season:number;cashM:number;approval:number;staffMorale:number;leagueInfluence:number;legacy:number;wins:number;losses:number;careerWins:number;careerLosses:number;seasonsCompleted:number;stadium:number;fanTrust:number;gm?:Staff;coach?:Staff;currentDecision?:number;usedDecisionIds:string[];lastOutcome?:string;history:string[];updatedAt:number};
const TEAMS=[['ARI','Arizona Cardinals','State Farm Stadium',63400,5.5],['ATL','Atlanta Falcons','Mercedes-Benz Stadium',71000,6.2],['BAL','Baltimore Ravens','M&T Bank Stadium',71008,6.5],['BUF','Buffalo Bills','New Highmark Stadium',62000,6.1],['CAR','Carolina Panthers','Bank of America Stadium',74867,5.7],['CHI','Chicago Bears','Soldier Field',61500,8.8],['CIN','Cincinnati Bengals','Paycor Stadium',65515,5.25],['CLE','Cleveland Browns','Huntington Bank Field',67431,6.4],['DAL','Dallas Cowboys','AT&T Stadium',80000,13],['DEN','Denver Broncos','Empower Field at Mile High',76125,7.3],['DET','Detroit Lions','Ford Field',65000,6.7],['GB','Green Bay Packers','Lambeau Field',81441,6.5],['HOU','Houston Texans','NRG Stadium',72220,6.6],['IND','Indianapolis Colts','Lucas Oil Stadium',67000,5.9],['JAX','Jacksonville Jaguars','EverBank Stadium',67814,5.4],['KC','Kansas City Chiefs','Arrowhead Stadium',76416,7],['LV','Las Vegas Raiders','Allegiant Stadium',65000,7.7],['LAC','Los Angeles Chargers','SoFi Stadium',70240,6.9],['LAR','Los Angeles Rams','SoFi Stadium',70240,10.5],['MIA','Miami Dolphins','Hard Rock Stadium',64767,7.5],['MIN','Minnesota Vikings','U.S. Bank Stadium',66860,6.6],['NE','New England Patriots','Gillette Stadium',64628,9],['NO','New Orleans Saints','Caesars Superdome',73208,5.3],['NYG','New York Giants','MetLife Stadium',82500,10.1],['NYJ','New York Jets','MetLife Stadium',82500,8.8],['PHI','Philadelphia Eagles','Lincoln Financial Field',67594,8.3],['PIT','Pittsburgh Steelers','Acrisure Stadium',68400,7],['SF','San Francisco 49ers','Levi’s Stadium',68500,8.6],['SEA','Seattle Seahawks','Lumen Field',68740,6.8],['TB','Tampa Bay Buccaneers','Raymond James Stadium',65618,6.6],['TEN','Tennessee Titans','Nissan Stadium',69143,5.7],['WAS','Washington Commanders','Northwest Stadium',62000,7.4]] as const;
const GMS:Staff[]=[{id:'cap',name:'Marcus Grant',role:'Cap Architect',football:78,culture:70,costM:7.5,tone:'from-sky-500 to-indigo-950'},{id:'scout',name:'Darius King',role:'Elite Scout',football:86,culture:61,costM:9.2,tone:'from-amber-500 to-red-950'},{id:'players',name:'Andre Collins',role:'Players’ Executive',football:74,culture:88,costM:8.4,tone:'from-emerald-500 to-slate-950'}];
const COACHES:Staff[]=[{id:'teacher',name:'Malik Hayes',role:'Culture Builder',football:78,culture:91,costM:10,tone:'from-violet-500 to-slate-950'},{id:'offense',name:'Cole Bennett',role:'Offensive Visionary',football:91,culture:66,costM:13,tone:'from-orange-500 to-red-950'},{id:'defense',name:'Raymond Stone',role:'Defensive Enforcer',football:88,culture:72,costM:12,tone:'from-cyan-500 to-blue-950'}];
const clamp=(n:number)=>Math.max(0,Math.min(100,n));const defaults:State={ownerName:'',abbr:'PHI',week:0,season:2026,cashM:350,approval:54,staffMorale:60,leagueInfluence:20,legacy:0,wins:0,losses:0,careerWins:0,careerLosses:0,seasonsCompleted:0,stadium:72,fanTrust:55,usedDecisionIds:[],history:[],updatedAt:0};
const normalize=(v:any):State=>{const legacyProgress=Math.max(0,Math.min(5,Number(v?.currentDecision)||0));const migratedIds=OWNER_DECISIONS.slice(0,legacyProgress).map(decision=>decision.id);return{...defaults,...v,staffMorale:clamp(Math.round(Number(v?.staffMorale)||60)),usedDecisionIds:Array.isArray(v?.usedDecisionIds)?v.usedDecisionIds:migratedIds,history:Array.isArray(v?.history)?v.history:[],updatedAt:Number(v?.updatedAt)||0};};
const restore=():State=>{try{const raw=localStorage.getItem(SAVE_KEY);return raw?normalize(JSON.parse(raw)):defaults;}catch{return defaults;}};const persist=(s:State)=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(s));}catch{}};const money=(n:number)=>`${n<0?'-':''}$${Math.abs(n).toFixed(0)}M`;
const Face=({p}:{p:Staff})=><div className={`relative h-14 w-14 shrink-0 overflow-hidden rounded-2xl bg-gradient-to-br ${p.tone}`}><div className="absolute left-1/2 top-2 h-7 w-7 -translate-x-1/2 rounded-full bg-amber-100/80"/><div className="absolute left-1/2 top-8 h-9 w-11 -translate-x-1/2 rounded-t-[45%] bg-white/80"/><div className="absolute left-1/2 top-2 h-3 w-8 -translate-x-1/2 rounded-full bg-black/70"/></div>;
const Scene=({d}:{d:OwnerDecision})=>d.visual==='trade'?<div className="relative aspect-[16/9] overflow-hidden rounded-3xl border border-white/10"><img src="/scenes/owner-trade-request.png" alt="Stylized football player addressing reporters" className="h-full w-full object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black to-transparent p-4 pt-12 text-xl font-black">BREAKING: THE LEAGUE IS WATCHING</div></div>:null;
export const OwnerBusinessMode:React.FC<{onBack:()=>void}>=({onBack})=>{
 const initial=useMemo(restore,[]);
 const[state,setState]=useState(initial);
 const[intro,setIntro]=useState(initial.ownerName?3:0);
 const[name,setName]=useState(initial.ownerName);
 const[teamPick,setTeamPick]=useState(initial.abbr);
 const[tab,setTab]=useState<'decision'|'franchise'|'staff'|'history'>('decision');

 useEffect(()=>{
  let cancelled=false;
  void loadUserState<State>(CLOUD_SAVE_KEY).then(cloudValue=>{
   if(cancelled||!cloudValue)return;
   const cloud=normalize(cloudValue);
   setState(local=>{
    const newest=cloud.updatedAt>local.updatedAt?cloud:local;
    const older=newest===cloud?local:cloud;
    const merged:State={
     ...newest,
     usedDecisionIds:[...new Set([...newest.usedDecisionIds,...older.usedDecisionIds])],
     history:[...new Set([...newest.history,...older.history])].slice(0,500),
    };
    persist(merged);
    setName(merged.ownerName);
    setTeamPick(merged.abbr);
    if(merged.ownerName)setIntro(3);
    return merged;
   });
  }).catch(error=>console.warn('Owner career cloud load failed',error));
  return()=>{cancelled=true;};
 },[]);

 const team=TEAMS.find(t=>t[0]===state.abbr)||TEAMS[0];
 const d=nextOwnerDecision(state);
 const unseenStories=unseenOwnerStoryCount(state.usedDecisionIds);
 const save=(p:Partial<State>)=>{
  const n:State={...state,...p,updatedAt:Date.now()};
  setState(n);
  persist(n);
  void saveUserState(CLOUD_SAVE_KEY,n).catch(error=>console.warn('Owner career cloud save failed',error));
 };
 const hire=(role:'gm'|'coach',p:Staff)=>save({[role]:p,cashM:state.cashM-p.costM,staffMorale:clamp(Math.round(state.staffMorale+p.culture/18)),history:[`Hired ${p.name}.`,...state.history]});
 const choose=(c:OwnerChoice)=>{
  const p:any={};
  Object.entries(c.effect).forEach(([k,v])=>p[k]=k==='cashM'?state.cashM+(v||0):clamp(Math.round((state as any)[k]+(v||0))));
  const footballStrength=((state.gm?.football||75)+(state.coach?.football||75))/2;
  const winChance=Math.max(.32,Math.min(.72,.47+(footballStrength-75)/220+(state.staffMorale-50)/500));
  const isPreseason=state.week===0;
  const won=!isPreseason&&Math.random()<winChance;
  const completedWins=isPreseason?state.wins:state.wins+(won?1:0);
  const completedLosses=isPreseason?state.losses:state.losses+(won?0:1);
  const seasonEnded=!isPreseason&&state.week>=17;
  const moment=state.week===0?'PRESEASON':`WEEK ${state.week}`;
  const decisionEntry=`${state.season} · ${moment} · ${d.title} — ${c.label}. ${isPreseason?'No regular-season game was played.':won?'The team won its next game.':'The team lost its next game.'}`;
  const seasonEntry=seasonEnded?`SEASON ${state.season} COMPLETE · ${completedWins}-${completedLosses}. Your choices carry into ${state.season+1}.`:null;
  Object.assign(p,{week:seasonEnded?0:state.week+1,season:seasonEnded?state.season+1:state.season,wins:seasonEnded?0:completedWins,losses:seasonEnded?0:completedLosses,careerWins:state.careerWins+(isPreseason?0:won?1:0),careerLosses:state.careerLosses+(isPreseason?0:won?0:1),seasonsCompleted:state.seasonsCompleted+(seasonEnded?1:0),usedDecisionIds:state.usedDecisionIds.includes(d.id)?state.usedDecisionIds:[...state.usedDecisionIds,d.id],lastOutcome:seasonEnded?`${c.label}. Final record: ${completedWins}-${completedLosses}. A new season begins, but your ownership history does not reset.`:isPreseason?`${c.label}. The regular season is ready for Week 1.`:`${c.label}. ${won?'The team answered with a win.':'The team took a loss, and the pressure moves forward.'}`,history:[...(seasonEntry?[seasonEntry]:[]),decisionEntry,...state.history]});
  save(p);
  window.scrollTo({top:0,behavior:'smooth'});
  try{navigator.vibrate?.(won?[35,45,70]:[80]);}catch{}
 };
if(intro<3)return <div className="min-h-[100dvh] bg-[#05070b] p-5 text-white"><button onClick={onBack} className="min-h-11 rounded-full border border-white/10 px-4 text-xs font-black"><ArrowLeft className="mr-2 inline" size={16}/>BACK</button><div className="mx-auto mt-10 max-w-3xl rounded-3xl border border-amber-300/25 bg-[#0c1018] p-6">{intro<2?<><div className="text-xs font-black tracking-widest text-amber-300">OWNER CAREER · {OWNER_DECISIONS.length} AUTHORED STORYLINES</div><h1 className="mt-3 text-4xl font-black">{intro===0?'YOU BOUGHT EVERY PROBLEM.':'EVERY CHOICE COMES BACK.'}</h1><p className="mt-4 text-sm leading-7 text-zinc-400">Handle stars, staff, stadium money, angry fans, league politics and years of consequences. Completed situations stay completed across every season.</p><button onClick={()=>setIntro(intro+1)} className="mt-6 min-h-12 w-full rounded-2xl bg-amber-300 font-black text-black">CONTINUE</button></>:<><h1 className="text-3xl font-black">WHO OWNS THE ROOM?</h1><input value={name} onChange={e=>setName(e.target.value)} placeholder="Owner name" className="mt-5 min-h-12 w-full rounded-2xl bg-black/40 px-4"/><select value={teamPick} onChange={e=>setTeamPick(e.target.value)} className="mt-3 min-h-12 w-full rounded-2xl bg-black px-4">{TEAMS.map(t=><option key={t[0]} value={t[0]}>{t[1]}</option>)}</select><button disabled={!name.trim()} onClick={()=>{save({ownerName:name.trim(),abbr:teamPick});setIntro(3)}} className="mt-5 min-h-12 w-full rounded-2xl bg-amber-300 font-black text-black disabled:opacity-30">BEGIN MY LEGACY</button></>}</div></div>;
const grade=Math.round(clamp((state.approval+state.staffMorale+state.fanTrust+state.leagueInfluence)/4+state.legacy*.2));return <div className="min-h-[100dvh] bg-[#06080d] p-4 text-white"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><button onClick={onBack} className="min-h-11 rounded-full border border-white/10 px-4 text-xs font-black"><ArrowLeft className="mr-2 inline" size={16}/>SOLO</button><b className="text-xs text-amber-300">{state.season} · WEEK {state.week||'PRE'}</b></header><nav className="sticky top-0 z-20 -mx-4 mt-3 flex gap-1 overflow-x-auto border-y border-white/10 bg-[#06080d]/95 px-4 py-2">{(['decision','franchise','staff','history']as const).map(x=><button key={x} onClick={()=>setTab(x)} className={`min-h-10 shrink-0 rounded-xl px-4 text-xs font-black uppercase ${tab===x?'bg-amber-300 text-black':'bg-white/5 text-zinc-400'}`}>{x}</button>)}</nav>
{tab==='decision'&&<>{state.lastOutcome&&<div className="mt-4 rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-4"><div className="text-[10px] font-black tracking-widest text-emerald-300">LAST DECISION</div><p className="mt-1 text-xs font-bold leading-5 text-zinc-300">{state.lastOutcome}</p></div>}<div className="mt-4"><Scene d={d}/></div><section className="mt-3 rounded-3xl border border-amber-300/20 bg-[#0d121b] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2 text-[10px] font-black tracking-widest text-amber-300"><CalendarDays size={15}/>{d.eyebrow}</div><div className="rounded-full border border-white/10 bg-black/30 px-3 py-1 text-[9px] font-black text-zinc-400">{unseenStories>0?`${unseenStories} NEW STORIES LEFT`:'ADAPTIVE LEGACY STORY'}</div></div><h1 className="mt-2 text-3xl font-black">{d.title}</h1><p className="mt-3 text-sm font-bold leading-6 text-zinc-300">{d.scene}</p><p className="mt-2 text-xs leading-5 text-zinc-500">{d.pressure}</p>{state.gm&&state.coach?<div className="mt-4 grid gap-2">{d.choices.map(c=><button key={c.label} onClick={()=>choose(c)} className="flex min-h-16 items-center justify-between rounded-2xl border border-white/10 p-3 text-left active:border-amber-300/50 active:bg-amber-300/5"><span><b className="block">{c.label}</b><small className="text-zinc-500">{c.detail}</small></span><ChevronRight className="shrink-0 text-amber-300"/></button>)}</div>:<button onClick={()=>setTab('staff')} className="mt-4 min-h-12 w-full rounded-2xl bg-amber-300 font-black text-black">BUILD YOUR FRONT OFFICE FIRST</button>}</section></>}
{tab==='franchise'&&<section className="mt-4 rounded-3xl border border-white/10 bg-[#0d121b] p-5"><Crown className="text-amber-300"/><h2 className="mt-2 text-3xl font-black">{team[1]}</h2><p className="text-xs text-zinc-500">{team[2]} · {Number(team[3]).toLocaleString()} seats</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-black"><span className="rounded-full bg-white/5 p-2"><Trophy className="inline" size={13}/> SEASON {state.wins}-{state.losses}</span><span className="rounded-full bg-white/5 p-2"><Trophy className="inline" size={13}/> CAREER {state.careerWins}-{state.careerLosses}</span><span className="rounded-full bg-white/5 p-2"><DollarSign className="inline" size={13}/> {money(state.cashM)}</span><span className="rounded-full bg-white/5 p-2"><Landmark className="inline" size={13}/> ${team[4]}B</span></div><div className="mt-4 grid grid-cols-3 gap-2">{[['RATING',grade],['FANS',state.fanTrust],['STADIUM',state.stadium],['APPROVAL',state.approval],['STAFF',Math.round(state.staffMorale)],['POWER',state.leagueInfluence],['SEASONS',state.seasonsCompleted],['STORIES',state.usedDecisionIds.length],['LEGACY',state.legacy]].map(([l,v])=><div key={String(l)} className="min-w-0 rounded-xl bg-black/25 p-3"><small className="block truncate text-zinc-500">{l}</small><b className="text-xl">{v}</b></div>)}</div></section>}
{tab==='staff'&&<section className="mt-4 rounded-3xl border border-white/10 bg-[#0d121b] p-5"><Users className="text-amber-300"/><h2 className="mt-2 text-2xl font-black">FRONT OFFICE</h2>{!state.gm?<Board title="GENERAL MANAGER" people={GMS} hire={p=>hire('gm',p)}/>:<Card p={state.gm}/>} {!state.coach?<Board title="HEAD COACH" people={COACHES} hire={p=>hire('coach',p)}/>:<Card p={state.coach}/>}</section>}
{tab==='history'&&<section className="mt-4 rounded-3xl border border-white/10 bg-[#0d121b] p-5"><Gavel className="text-amber-300"/><h2 className="mt-2 text-2xl font-black">LEGACY LEDGER</h2><p className="mt-1 text-xs text-zinc-500">{state.usedDecisionIds.length} unique ownership situations completed. Nothing in this ledger returns to the story deck.</p><div className="mt-4 space-y-2">{state.history.length?state.history.map((h,i)=><div key={i} className="rounded-xl bg-black/25 p-3 text-xs leading-5">{h}</div>):<p className="text-zinc-500">Your first decision will define the franchise.</p>}</div></section>}</div></div>};
const Card=({p}:{p:Staff})=><div className="mt-3 flex items-center gap-3 rounded-2xl border border-emerald-400/20 p-3"><Face p={p}/><div><b>{p.name}</b><div className="text-xs text-zinc-500">{p.role}</div></div></div>;const Board=({title,people,hire}:{title:string;people:Staff[];hire:(p:Staff)=>void})=><div className="mt-5"><small className="font-black tracking-widest text-zinc-500">HIRE A {title}</small><div className="mt-2 grid gap-2">{people.map(p=><button key={p.id} onClick={()=>hire(p)} className="flex min-h-20 items-center gap-3 rounded-2xl border border-white/10 p-3 text-left"><Face p={p}/><div className="min-w-0 flex-1"><b>{p.name}</b><div className="text-xs text-zinc-500">{p.role}</div><small>FB {p.football} · CULT {p.culture}</small></div><b className="text-xs text-emerald-300">{money(p.costM)}/YR</b></button>)}</div></div>;
export default OwnerBusinessMode;
