create table if not exists ball_knower_private.trivia_questions (
  id bigint generated by default as identity primary key,
  question_key text not null unique,
  tier text not null check (tier in ('ROOKIE','PRO','ALL-PRO','HALL OF FAME')),
  question text not null,
  answers jsonb not null check (jsonb_typeof(answers)='array' and jsonb_array_length(answers)=4),
  correct_index smallint not null check (correct_index between 0 and 3),
  explanation text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table ball_knower_private.trivia_questions enable row level security;
revoke all on ball_knower_private.trivia_questions from public, anon, authenticated;

create table if not exists ball_knower_private.trivia_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references ball_knower_private.trivia_questions(id) on delete cascade,
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  selected_index smallint check (selected_index between 0 and 3),
  is_correct boolean
);
create index if not exists trivia_attempts_user_created_idx on ball_knower_private.trivia_attempts(user_id,created_at desc);
alter table ball_knower_private.trivia_attempts enable row level security;
revoke all on ball_knower_private.trivia_attempts from public, anon, authenticated;

insert into ball_knower_private.trivia_questions(question_key,tier,question,answers,correct_index,explanation)
values
('sb_lix_winner','ROOKIE','Which team won Super Bowl LIX?','["Philadelphia Eagles","Kansas City Chiefs","Buffalo Bills","Detroit Lions"]'::jsonb,0,'Philadelphia defeated Kansas City in Super Bowl LIX.'),
('rodgers_2005_pick','PRO','Which quarterback was selected 24th overall in the 2005 NFL Draft?','["Aaron Rodgers","Jason Campbell","Alex Smith","Kyle Orton"]'::jsonb,0,'Green Bay selected Aaron Rodgers 24th overall in 2005.'),
('single_game_receiving_336','ALL-PRO','Which player set the single-game receiving yardage record with 336 yards?','["Flipper Anderson","Calvin Johnson","Julio Jones","Jerry Rice"]'::jsonb,0,'Flipper Anderson recorded 336 receiving yards for the Rams in 1989.'),
('1990_rushing_leader','HALL OF FAME','Who led the NFL in rushing yards during the 1990 regular season?','["Barry Sanders","Thurman Thomas","Emmitt Smith","Christian Okoye"]'::jsonb,0,'Barry Sanders led the NFL with 1,304 rushing yards in 1990.')
on conflict(question_key) do update set tier=excluded.tier, question=excluded.question, answers=excluded.answers, correct_index=excluded.correct_index, explanation=excluded.explanation, active=true;

create or replace function public.get_ball_knower_trivia_question(p_tier text)
returns table(attempt_id bigint, question_id bigint, tier text, question text, answers jsonb)
language plpgsql
security definer
set search_path = public, ball_knower_private, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_question ball_knower_private.trivia_questions%rowtype;
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  if p_tier not in ('ROOKIE','PRO','ALL-PRO','HALL OF FAME') then raise exception 'Invalid trivia tier'; end if;
  select q.* into v_question from ball_knower_private.trivia_questions q where q.active and q.tier=p_tier order by random() limit 1;
  if v_question.id is null then raise exception 'No active question available'; end if;
  insert into ball_knower_private.trivia_attempts(user_id,question_id) values(v_user,v_question.id) returning id into attempt_id;
  question_id := v_question.id;
  tier := v_question.tier;
  question := v_question.question;
  answers := v_question.answers;
  return next;
end;
$$;
revoke all on function public.get_ball_knower_trivia_question(text) from public, anon;
grant execute on function public.get_ball_knower_trivia_question(text) to authenticated;

create or replace function public.submit_ball_knower_trivia_answer(p_attempt_id bigint, p_selected_index integer)
returns table(is_correct boolean, correct_index integer, explanation text, xp_awarded integer, progression_recorded boolean)
language plpgsql
security definer
set search_path = public, ball_knower_private, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_attempt ball_knower_private.trivia_attempts%rowtype;
  v_question ball_knower_private.trivia_questions%rowtype;
  v_correct boolean;
  v_xp integer;
  v_event_type text;
  v_recorded boolean;
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  if p_selected_index not between 0 and 3 then raise exception 'Invalid answer index'; end if;
  select * into v_attempt from ball_knower_private.trivia_attempts where id=p_attempt_id and user_id=v_user for update;
  if v_attempt.id is null then raise exception 'Trivia attempt not found'; end if;
  if v_attempt.answered_at is not null then raise exception 'Trivia attempt already answered'; end if;
  if v_attempt.created_at < now() - interval '5 minutes' then raise exception 'Trivia attempt expired'; end if;
  select * into v_question from ball_knower_private.trivia_questions where id=v_attempt.question_id and active;
  if v_question.id is null then raise exception 'Trivia question unavailable'; end if;
  v_correct := p_selected_index=v_question.correct_index;
  v_xp := case v_question.tier when 'ROOKIE' then 15 when 'PRO' then 25 when 'ALL-PRO' then 40 else 60 end;
  if not v_correct then v_xp := 2; end if;
  v_event_type := case when v_correct and v_question.tier='HALL OF FAME' then 'trivia_hof_correct' when v_correct then 'trivia_correct' else 'trivia_wrong' end;
  update ball_knower_private.trivia_attempts set answered_at=now(),selected_index=p_selected_index,is_correct=v_correct where id=v_attempt.id;
  v_recorded := ball_knower_private.apply_progress_event(v_user,'trivia_attempt:'||v_attempt.id,v_event_type,'trivia',v_xp,case when v_correct then 1 else 0 end,jsonb_build_object('tier',v_question.tier,'question_key',v_question.question_key,'question_id',v_question.id));
  is_correct := v_correct;
  correct_index := v_question.correct_index;
  explanation := v_question.explanation;
  xp_awarded := case when v_recorded then v_xp else 0 end;
  progression_recorded := v_recorded;
  return next;
end;
$$;
revoke all on function public.submit_ball_knower_trivia_answer(bigint,integer) from public, anon;
grant execute on function public.submit_ball_knower_trivia_answer(bigint,integer) to authenticated;
