-- Final Phase 4B: server-authoritative Owner progression, authenticated Agent
-- transition verification, and server-verified Prediction picks.
-- Clients never choose progression event types, XP awards, rating deltas, or
-- idempotency keys.

create schema if not exists ball_knower_private;

-- Remove the abandoned counter-snapshot prototype if this migration is replayed
-- on a development database that saw an earlier draft.
drop function if exists public.record_ball_knower_verified_mode_snapshot(uuid,text,jsonb);
drop table if exists ball_knower_private.verified_mode_state;

create table if not exists ball_knower_private.verified_mode_milestones (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('owner','agent','prediction')),
  milestone_type text not null check (milestone_type in (
    'owner_season_complete','owner_playoff_appearance','owner_conference_title','owner_championship',
    'agent_client_signed','agent_trade_resolved','agent_contract_signed','agent_promise_fulfilled',
    'prediction_correct','prediction_wrong','prediction_push'
  )),
  source_key text not null,
  payload jsonb not null default '{}'::jsonb,
  verified_at timestamptz not null default now(),
  verified_by text not null default 'server',
  claimed_at timestamptz,
  unique(user_id,mode,source_key)
);
create index if not exists verified_mode_milestones_unclaimed_idx
  on ball_knower_private.verified_mode_milestones(user_id,verified_at)
  where claimed_at is null;
alter table ball_knower_private.verified_mode_milestones enable row level security;
revoke all on table ball_knower_private.verified_mode_milestones from public,anon,authenticated;

-- Owner mode uses a private, versioned server run. The browser can ask to
-- advance a matching run, but it cannot choose the result or postseason path.
create table if not exists ball_knower_private.verified_owner_runs (
  user_id uuid primary key references auth.users(id) on delete cascade,
  abbr text not null,
  season integer not null check (season between 2026 and 2200),
  week integer not null check (week between 0 and 21),
  stage text not null check (stage in ('preseason','regular','wild-card','divisional','conference','super-bowl')),
  wins integer not null default 0 check (wins between 0 and 20),
  losses integer not null default 0 check (losses between 0 and 20),
  playoff_seed integer check (playoff_seed is null or playoff_seed between 1 and 7),
  version integer not null default 1 check (version > 0),
  updated_at timestamptz not null default now()
);
alter table ball_knower_private.verified_owner_runs enable row level security;
revoke all on table ball_knower_private.verified_owner_runs from public,anon,authenticated;

-- Agent mode is still a local solo career, but rewards are derived from exact
-- authenticated OLD -> NEW cloud-state transitions rather than browser counters.
-- This lifecycle table makes client replays/removals idempotent.
create table if not exists ball_knower_private.verified_agent_clients (
  user_id uuid not null references auth.users(id) on delete cascade,
  player_id text not null,
  legacy_baseline boolean not null default true,
  signed_at timestamptz not null default now(),
  last_contract_season integer,
  last_trade_season integer,
  fulfilled_promises text[] not null default '{}'::text[],
  primary key(user_id,player_id)
);
alter table ball_knower_private.verified_agent_clients enable row level security;
revoke all on table ball_knower_private.verified_agent_clients from public,anon,authenticated;

create table if not exists ball_knower_private.verified_prediction_picks (
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  pick_id text not null,
  market text not null check (market in ('spread','total')),
  selection text not null,
  locked_line numeric not null,
  label text not null,
  kickoff_at timestamptz not null,
  away_team text not null,
  home_team text not null,
  locked_at timestamptz not null default now(),
  result text check (result is null or result in ('win','loss','push')),
  graded_at timestamptz,
  primary key(user_id,game_id)
);
alter table ball_knower_private.verified_prediction_picks enable row level security;
revoke all on table ball_knower_private.verified_prediction_picks from public,anon,authenticated;

create or replace function ball_knower_private.insert_verified_mode_milestone(
  p_user_id uuid,
  p_mode text,
  p_type text,
  p_source_key text,
  p_payload jsonb default '{}'::jsonb,
  p_verified_by text default 'server'
) returns bigint
language plpgsql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare v_id bigint;
begin
  insert into ball_knower_private.verified_mode_milestones(
    user_id,mode,milestone_type,source_key,payload,verified_by
  ) values(
    p_user_id,p_mode,p_type,left(p_source_key,180),coalesce(p_payload,'{}'::jsonb),left(p_verified_by,80)
  )
  on conflict(user_id,mode,source_key) do nothing
  returning id into v_id;
  if v_id is null then
    select id into v_id
    from ball_knower_private.verified_mode_milestones
    where user_id=p_user_id and mode=p_mode and source_key=left(p_source_key,180);
  end if;
  return v_id;
end;
$$;
revoke all on function ball_knower_private.insert_verified_mode_milestone(uuid,text,text,text,jsonb,text) from public,anon,authenticated;

create or replace function public.list_ball_knower_unclaimed_mode_milestones()
returns table(id bigint,mode text,milestone_type text,verified_at timestamptz)
language sql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
  select m.id,m.mode,m.milestone_type,m.verified_at
  from ball_knower_private.verified_mode_milestones m
  where m.user_id=auth.uid() and m.verified_at is not null and m.claimed_at is null
  order by m.id asc
  limit 100;
$$;
revoke all on function public.list_ball_knower_unclaimed_mode_milestones() from public,anon;
grant execute on function public.list_ball_knower_unclaimed_mode_milestones() to authenticated;

create or replace function public.claim_ball_knower_verified_mode_milestone(p_milestone_id bigint)
returns table(applied boolean,milestone_id bigint,event_key text)
language plpgsql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare
  v_user uuid:=auth.uid();
  v_milestone ball_knower_private.verified_mode_milestones%rowtype;
  v_xp integer;
  v_delta integer;
  v_event_key text;
  v_applied boolean;
begin
  if v_user is null then raise exception 'Sign in required'; end if;
  select * into v_milestone
  from ball_knower_private.verified_mode_milestones
  where id=p_milestone_id and user_id=v_user and verified_at is not null
  for update;
  if not found then raise exception 'Verified milestone not found'; end if;

  select x.xp,x.delta into v_xp,v_delta from (values
    ('owner_season_complete',30,1),('owner_playoff_appearance',60,1),('owner_conference_title',100,2),('owner_championship',180,3),
    ('agent_client_signed',25,1),('agent_trade_resolved',40,1),('agent_contract_signed',55,1),('agent_promise_fulfilled',45,1),
    ('prediction_correct',20,1),('prediction_wrong',2,-1),('prediction_push',5,0)
  ) as x(kind,xp,delta)
  where x.kind=v_milestone.milestone_type;
  if v_xp is null then raise exception 'Unsupported verified milestone'; end if;

  v_event_key:='mode_milestone:'||v_milestone.id;
  v_applied:=ball_knower_private.apply_progress_event(
    v_user,v_event_key,v_milestone.milestone_type,v_milestone.mode,v_xp,v_delta,
    coalesce(v_milestone.payload,'{}'::jsonb)||jsonb_build_object(
      'verified_milestone_id',v_milestone.id,'verified_by',v_milestone.verified_by
    )
  );
  update ball_knower_private.verified_mode_milestones
  set claimed_at=coalesce(claimed_at,now()) where id=v_milestone.id;
  return query select v_applied,v_milestone.id,v_event_key;
end;
$$;
revoke all on function public.claim_ball_knower_verified_mode_milestone(bigint) from public,anon;
grant execute on function public.claim_ball_knower_verified_mode_milestone(bigint) to authenticated;

-- Service-only Owner run access. A new run may only be initialized from a clean
-- preseason boundary. Re-baselining a later clean season awards nothing.
create or replace function public.get_ball_knower_verified_owner_run(p_user_id uuid)
returns jsonb
language sql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
  select case when auth.role()='service_role' then (
    select to_jsonb(r) from ball_knower_private.verified_owner_runs r where r.user_id=p_user_id
  ) else null end;
$$;
revoke all on function public.get_ball_knower_verified_owner_run(uuid) from public,anon,authenticated;
grant execute on function public.get_ball_knower_verified_owner_run(uuid) to service_role;

create or replace function public.begin_ball_knower_verified_owner_run(
  p_user_id uuid,p_abbr text,p_season integer
) returns jsonb
language plpgsql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare v_run ball_knower_private.verified_owner_runs%rowtype;
begin
  if auth.role()<>'service_role' then raise exception 'Service role required'; end if;
  if p_user_id is null or p_abbr !~ '^[A-Z]{2,3}$' or p_season<2026 or p_season>2200 then
    raise exception 'Invalid Owner run';
  end if;
  select * into v_run from ball_knower_private.verified_owner_runs where user_id=p_user_id for update;
  if not found then
    insert into ball_knower_private.verified_owner_runs(user_id,abbr,season,week,stage,wins,losses,playoff_seed,version)
    values(p_user_id,p_abbr,p_season,0,'preseason',0,0,null,1)
    returning * into v_run;
  elsif p_season>v_run.season then
    update ball_knower_private.verified_owner_runs
    set abbr=p_abbr,season=p_season,week=0,stage='preseason',wins=0,losses=0,playoff_seed=null,version=version+1,updated_at=now()
    where user_id=p_user_id returning * into v_run;
  end if;
  return to_jsonb(v_run);
end;
$$;
revoke all on function public.begin_ball_knower_verified_owner_run(uuid,text,integer) from public,anon,authenticated;
grant execute on function public.begin_ball_knower_verified_owner_run(uuid,text,integer) to service_role;

create or replace function public.commit_ball_knower_verified_owner_step(
  p_user_id uuid,
  p_expected_version integer,
  p_next_season integer,
  p_next_week integer,
  p_next_stage text,
  p_next_wins integer,
  p_next_losses integer,
  p_next_playoff_seed integer,
  p_won boolean
) returns jsonb
language plpgsql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare
  v_old ball_knower_private.verified_owner_runs%rowtype;
  v_new ball_knower_private.verified_owner_runs%rowtype;
  v_ids jsonb:='[]'::jsonb;
  v_id bigint;
begin
  if auth.role()<>'service_role' then raise exception 'Service role required'; end if;
  select * into v_old from ball_knower_private.verified_owner_runs
  where user_id=p_user_id for update;
  if not found then raise exception 'Verified Owner run not found'; end if;
  if v_old.version<>p_expected_version then raise exception 'Verified Owner run changed'; end if;
  if p_next_stage not in ('preseason','regular','wild-card','divisional','conference','super-bowl')
     or p_next_season<v_old.season or p_next_season>v_old.season+1
     or p_next_week<0 or p_next_week>21
     or p_next_wins<0 or p_next_wins>20 or p_next_losses<0 or p_next_losses>20
     or (p_next_playoff_seed is not null and (p_next_playoff_seed<1 or p_next_playoff_seed>7)) then
    raise exception 'Invalid verified Owner transition';
  end if;

  if v_old.stage='regular' and v_old.week=18 and p_next_stage in ('wild-card','divisional') then
    v_id:=ball_knower_private.insert_verified_mode_milestone(
      p_user_id,'owner','owner_playoff_appearance','owner:'||v_old.season||':playoffs',
      jsonb_build_object('season',v_old.season),'owner_server_run_v1'
    );
    v_ids:=v_ids||jsonb_build_array(v_id);
  end if;
  if v_old.stage='conference' and p_next_stage='super-bowl' and p_won then
    v_id:=ball_knower_private.insert_verified_mode_milestone(
      p_user_id,'owner','owner_conference_title','owner:'||v_old.season||':conference',
      jsonb_build_object('season',v_old.season),'owner_server_run_v1'
    );
    v_ids:=v_ids||jsonb_build_array(v_id);
  end if;
  if v_old.stage='super-bowl' and p_next_stage='preseason' and p_next_season=v_old.season+1 and p_won then
    v_id:=ball_knower_private.insert_verified_mode_milestone(
      p_user_id,'owner','owner_championship','owner:'||v_old.season||':championship',
      jsonb_build_object('season',v_old.season),'owner_server_run_v1'
    );
    v_ids:=v_ids||jsonb_build_array(v_id);
  end if;
  if p_next_stage='preseason' and p_next_season=v_old.season+1 then
    v_id:=ball_knower_private.insert_verified_mode_milestone(
      p_user_id,'owner','owner_season_complete','owner:'||v_old.season||':complete',
      jsonb_build_object('season',v_old.season,'champion',v_old.stage='super-bowl' and p_won),'owner_server_run_v1'
    );
    v_ids:=v_ids||jsonb_build_array(v_id);
  end if;

  update ball_knower_private.verified_owner_runs
  set season=p_next_season,week=p_next_week,stage=p_next_stage,wins=p_next_wins,losses=p_next_losses,
      playoff_seed=p_next_playoff_seed,version=version+1,updated_at=now()
  where user_id=p_user_id
  returning * into v_new;
  return jsonb_build_object('run',to_jsonb(v_new),'milestoneIds',v_ids);
end;
$$;
revoke all on function public.commit_ball_knower_verified_owner_step(uuid,integer,integer,integer,text,integer,integer,integer,boolean) from public,anon,authenticated;
grant execute on function public.commit_ball_knower_verified_owner_step(uuid,integer,integer,integer,text,integer,integer,integer,boolean) to service_role;

-- Safely decode the Agent cloud envelope. Bad JSON never blocks cloud sync.
create or replace function ball_knower_private.agent_state_doc(p_value jsonb)
returns jsonb
language plpgsql
immutable
set search_path=pg_catalog,pg_temp
as $$
declare v_doc jsonb;
begin
  if p_value is null or jsonb_typeof(p_value)<>'object' or not (p_value ? 'raw') then return null; end if;
  begin v_doc:=(p_value->>'raw')::jsonb; exception when others then return null; end;
  if jsonb_typeof(v_doc)<>'object' then return null; end if;
  return v_doc;
end;
$$;
revoke all on function ball_knower_private.agent_state_doc(jsonb) from public,anon,authenticated;

create or replace function ball_knower_private.agent_state_int(p_doc jsonb,p_key text,p_max integer)
returns integer
language plpgsql
immutable
set search_path=pg_catalog,pg_temp
as $$
declare v text; n integer;
begin
  if p_doc is null then return -1; end if;
  v:=p_doc->>p_key;
  if v is null or v!~'^\d+$' then return -1; end if;
  n:=v::integer;
  if n<0 or n>p_max then return -1; end if;
  return n;
end;
$$;
revoke all on function ball_knower_private.agent_state_int(jsonb,text,integer) from public,anon,authenticated;

create or replace function ball_knower_private.verify_agent_state_transition()
returns trigger
language plpgsql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare
  v_old jsonb;
  v_new jsonb;
  v_old_clients jsonb;
  v_new_clients jsonb;
  v_old_client jsonb;
  v_new_client jsonb;
  v_pid text;
  v_season integer;
  v_old_week integer;
  v_new_week integer;
  v_old_actions integer;
  v_new_actions integer;
  v_old_signed integer;
  v_new_signed integer;
  v_added integer:=0;
  v_inserted text;
  v_promise text;
  v_promises text[];
  v_lifecycle ball_knower_private.verified_agent_clients%rowtype;
  v_deal jsonb;
  v_old_deals integer;
  v_new_deals integer;
  v_id bigint;
begin
  if new.state_key<>'player_agent_career' then return new; end if;
  v_new:=ball_knower_private.agent_state_doc(new.value);
  if v_new is null then return new; end if;
  v_new_clients:=case when jsonb_typeof(v_new->'clients')='array' then v_new->'clients' else '[]'::jsonb end;

  if tg_op='INSERT' then
    v_season:=ball_knower_private.agent_state_int(v_new,'seasonYear',2200);
    for v_new_client in select value from jsonb_array_elements(v_new_clients) loop
      v_pid:=nullif(btrim(v_new_client->>'playerId'),'');
      if v_pid is null then continue; end if;
      v_promises:=array(select jsonb_array_elements_text(
        case when jsonb_typeof(v_new_client#>'{career,fulfilledPromises}')='array' then v_new_client#>'{career,fulfilledPromises}' else '[]'::jsonb end
      ));
      insert into ball_knower_private.verified_agent_clients(
        user_id,player_id,legacy_baseline,last_contract_season,last_trade_season,fulfilled_promises
      ) values(
        new.user_id,v_pid,true,
        case when jsonb_typeof(v_new_client->'futureDeal')='object' then nullif(v_season,-1) else null end,
        case when v_new_client#>>'{tradeRequest,status}'='resolved' then nullif(v_season,-1) else null end,
        coalesce(v_promises,'{}'::text[])
      ) on conflict(user_id,player_id) do nothing;
    end loop;
    return new;
  end if;

  v_old:=ball_knower_private.agent_state_doc(old.value);
  if v_old is null then return new; end if;
  v_old_clients:=case when jsonb_typeof(v_old->'clients')='array' then v_old->'clients' else '[]'::jsonb end;
  v_season:=ball_knower_private.agent_state_int(v_new,'seasonYear',2200);

  -- Everything present before this authenticated transition is baseline history.
  for v_old_client in select value from jsonb_array_elements(v_old_clients) loop
    v_pid:=nullif(btrim(v_old_client->>'playerId'),'');
    if v_pid is null then continue; end if;
    v_promises:=array(select jsonb_array_elements_text(
      case when jsonb_typeof(v_old_client#>'{career,fulfilledPromises}')='array' then v_old_client#>'{career,fulfilledPromises}' else '[]'::jsonb end
    ));
    insert into ball_knower_private.verified_agent_clients(
      user_id,player_id,legacy_baseline,last_contract_season,last_trade_season,fulfilled_promises
    ) values(
      new.user_id,v_pid,true,
      case when jsonb_typeof(v_old_client->'futureDeal')='object' then nullif(ball_knower_private.agent_state_int(v_old,'seasonYear',2200),-1) else null end,
      case when v_old_client#>>'{tradeRequest,status}'='resolved' then nullif(ball_knower_private.agent_state_int(v_old,'seasonYear',2200),-1) else null end,
      coalesce(v_promises,'{}'::text[])
    ) on conflict(user_id,player_id) do nothing;
  end loop;

  -- A signing must add exactly one detailed client in the same Agent week,
  -- consume exactly one of the two weekly actions, and increment signedClients.
  select count(*) into v_added
  from jsonb_array_elements(v_new_clients) n
  where nullif(btrim(n->>'playerId'),'') is not null
    and not exists (
      select 1 from jsonb_array_elements(v_old_clients) o where o->>'playerId'=n->>'playerId'
    );
  v_old_actions:=ball_knower_private.agent_state_int(v_old,'weeklyActionsUsed',2);
  v_new_actions:=ball_knower_private.agent_state_int(v_new,'weeklyActionsUsed',2);
  v_old_signed:=ball_knower_private.agent_state_int(v_old,'signedClients',10000);
  v_new_signed:=ball_knower_private.agent_state_int(v_new,'signedClients',10000);
  v_old_week:=ball_knower_private.agent_state_int(v_old,'seasonWeek',30);
  v_new_week:=ball_knower_private.agent_state_int(v_new,'seasonWeek',30);

  if v_added=1
     and v_old_signed>=0 and v_new_signed=v_old_signed+1
     and v_old_actions>=0 and v_new_actions=v_old_actions+1
     and v_old->>'seasonYear'=v_new->>'seasonYear'
     and v_old->>'phase'=v_new->>'phase'
     and v_old_week=v_new_week
     and jsonb_array_length(v_new_clients)=jsonb_array_length(v_old_clients)+1
     and jsonb_array_length(v_new_clients)<=5 then
    select value into v_new_client
    from jsonb_array_elements(v_new_clients) n
    where not exists(select 1 from jsonb_array_elements(v_old_clients) o where o->>'playerId'=n->>'playerId')
    limit 1;
    v_pid:=nullif(btrim(v_new_client->>'playerId'),'');
    if v_pid is not null
       and jsonb_typeof(v_new_client#>'{career,promises}')='array'
       and jsonb_array_length(v_new_client#>'{career,promises}')=2
       and nullif(btrim(v_new_client->>'signedAt'),'') is not null then
      insert into ball_knower_private.verified_agent_clients(user_id,player_id,legacy_baseline)
      values(new.user_id,v_pid,false)
      on conflict(user_id,player_id) do nothing
      returning player_id into v_inserted;
      if v_inserted is not null then
        perform ball_knower_private.insert_verified_mode_milestone(
          new.user_id,'agent','agent_client_signed','agent:client:'||v_pid,
          jsonb_build_object('playerId',v_pid,'season',v_season),'agent_cloud_transition_v1'
        );
      end if;
    end if;
  end if;

  v_old_deals:=case when jsonb_typeof(v_old->'dealHistory')='array' then jsonb_array_length(v_old->'dealHistory') else 0 end;
  v_new_deals:=case when jsonb_typeof(v_new->'dealHistory')='array' then jsonb_array_length(v_new->'dealHistory') else 0 end;
  v_deal:=case when v_new_deals=v_old_deals+1 then v_new->'dealHistory'->(v_new_deals-1) else null end;

  -- Compare each persistent client for concrete contract/trade/promise transitions.
  for v_new_client in select value from jsonb_array_elements(v_new_clients) loop
    v_pid:=nullif(btrim(v_new_client->>'playerId'),'');
    if v_pid is null then continue; end if;
    select value into v_old_client from jsonb_array_elements(v_old_clients)
    where value->>'playerId'=v_pid limit 1;
    if v_old_client is null then continue; end if;
    select * into v_lifecycle from ball_knower_private.verified_agent_clients
    where user_id=new.user_id and player_id=v_pid for update;
    if not found then continue; end if;

    if v_season>=2026 and v_new_deals=v_old_deals+1
       and jsonb_typeof(v_deal)='object'
       and jsonb_typeof(v_new_client->'futureDeal')='object'
       and v_new_client->'futureDeal'=v_deal
       and v_old_client->'futureDeal' is distinct from v_new_client->'futureDeal'
       and jsonb_typeof(v_deal->'totalM')='number'
       and jsonb_typeof(v_deal->'annualM')='number'
       and jsonb_typeof(v_deal->'guaranteedM')='number'
       and jsonb_typeof(v_deal->'years')='number'
       and (v_deal->>'totalM')::numeric between 1 and 1000
       and (v_deal->>'annualM')::numeric between 0.1 and 150
       and (v_deal->>'guaranteedM')::numeric between 0 and 1000
       and (v_deal->>'years')::numeric between 1 and 10
       and v_lifecycle.last_contract_season is distinct from v_season then
      update ball_knower_private.verified_agent_clients
      set last_contract_season=v_season where user_id=new.user_id and player_id=v_pid;
      perform ball_knower_private.insert_verified_mode_milestone(
        new.user_id,'agent','agent_contract_signed','agent:contract:'||v_pid||':'||v_season,
        jsonb_build_object('playerId',v_pid,'season',v_season),'agent_cloud_transition_v1'
      );
    end if;

    if v_season>=2026
       and v_new->>'phase'='regular'
       and v_new_week between 1 and 9
       and v_old_client#>>'{tradeRequest,status}'='open'
       and v_new_client#>>'{tradeRequest,status}'='resolved'
       and nullif(btrim(v_new_client#>>'{tradeRequest,destination}'),'') is not null
       and v_lifecycle.last_trade_season is distinct from v_season then
      update ball_knower_private.verified_agent_clients
      set last_trade_season=v_season where user_id=new.user_id and player_id=v_pid;
      perform ball_knower_private.insert_verified_mode_milestone(
        new.user_id,'agent','agent_trade_resolved','agent:trade:'||v_pid||':'||v_season,
        jsonb_build_object('playerId',v_pid,'season',v_season),'agent_cloud_transition_v1'
      );
    end if;

    if jsonb_typeof(v_new_client#>'{career,fulfilledPromises}')='array' then
      for v_promise in
        select jsonb_array_elements_text(v_new_client#>'{career,fulfilledPromises}')
        except
        select jsonb_array_elements_text(
          case when jsonb_typeof(v_old_client#>'{career,fulfilledPromises}')='array'
               then v_old_client#>'{career,fulfilledPromises}' else '[]'::jsonb end
        )
      loop
        if v_promise in ('money','guarantees','loyalty','winning','playing_time','family','brand','long_term')
           and not (v_promise=any(v_lifecycle.fulfilled_promises)) then
          update ball_knower_private.verified_agent_clients
          set fulfilled_promises=array_append(fulfilled_promises,v_promise)
          where user_id=new.user_id and player_id=v_pid;
          perform ball_knower_private.insert_verified_mode_milestone(
            new.user_id,'agent','agent_promise_fulfilled','agent:promise:'||v_pid||':'||v_promise,
            jsonb_build_object('playerId',v_pid,'promise',v_promise),'agent_cloud_transition_v1'
          );
        end if;
      end loop;
    end if;
  end loop;

  return new;
exception when others then
  -- Progression verification must never make the user's cloud save unavailable.
  raise warning 'Agent progression verification skipped: %',sqlerrm;
  return new;
end;
$$;
revoke all on function ball_knower_private.verify_agent_state_transition() from public,anon,authenticated;

drop trigger if exists verify_ball_knower_agent_progression on public.ball_knower_user_state;
create trigger verify_ball_knower_agent_progression
after insert or update of value on public.ball_knower_user_state
for each row
when (new.state_key='player_agent_career')
execute function ball_knower_private.verify_agent_state_transition();

-- Prediction storage and grading remain service-only. Final-score verification
-- occurs in the Vercel handler before this grading RPC is called.
create or replace function public.save_ball_knower_verified_prediction_pick(
  p_user_id uuid,p_game_id text,p_pick_id text,p_market text,p_selection text,p_locked_line numeric,p_label text,
  p_kickoff_at timestamptz,p_away_team text,p_home_team text
) returns boolean
language plpgsql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare v_count integer;
begin
  if auth.role()<>'service_role' then raise exception 'Service role required'; end if;
  if p_user_id is null or nullif(btrim(p_game_id),'') is null or p_market not in ('spread','total') then raise exception 'Invalid prediction pick'; end if;
  if p_kickoff_at<=now() then raise exception 'Game is already locked'; end if;
  if p_locked_line is null or abs(p_locked_line)>200 then raise exception 'Invalid locked line'; end if;
  insert into ball_knower_private.verified_prediction_picks(
    user_id,game_id,pick_id,market,selection,locked_line,label,kickoff_at,away_team,home_team,locked_at,result,graded_at
  ) values(
    p_user_id,left(p_game_id,120),left(p_pick_id,200),p_market,left(p_selection,120),p_locked_line,left(p_label,160),p_kickoff_at,left(p_away_team,120),left(p_home_team,120),now(),null,null
  )
  on conflict(user_id,game_id) do update set
    pick_id=excluded.pick_id,market=excluded.market,selection=excluded.selection,locked_line=excluded.locked_line,
    label=excluded.label,kickoff_at=excluded.kickoff_at,away_team=excluded.away_team,home_team=excluded.home_team,
    locked_at=now(),result=null,graded_at=null
  where ball_knower_private.verified_prediction_picks.kickoff_at>now();
  get diagnostics v_count=row_count;
  return v_count=1;
end;
$$;
revoke all on function public.save_ball_knower_verified_prediction_pick(uuid,text,text,text,text,numeric,text,timestamptz,text,text) from public,anon,authenticated;
grant execute on function public.save_ball_knower_verified_prediction_pick(uuid,text,text,text,text,numeric,text,timestamptz,text,text) to service_role;

create or replace function public.delete_ball_knower_verified_prediction_pick(p_user_id uuid,p_game_id text)
returns boolean
language plpgsql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare v_count integer;
begin
  if auth.role()<>'service_role' then raise exception 'Service role required'; end if;
  delete from ball_knower_private.verified_prediction_picks
  where user_id=p_user_id and game_id=p_game_id and kickoff_at>now();
  get diagnostics v_count=row_count;
  return v_count=1;
end;
$$;
revoke all on function public.delete_ball_knower_verified_prediction_pick(uuid,text) from public,anon,authenticated;
grant execute on function public.delete_ball_knower_verified_prediction_pick(uuid,text) to service_role;

create or replace function public.get_ball_knower_verified_prediction_picks(p_user_id uuid)
returns table(
  game_id text,pick_id text,market text,selection text,locked_line numeric,label text,kickoff_at timestamptz,
  away_team text,home_team text,locked_at timestamptz,result text,graded_at timestamptz
)
language sql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
  select p.game_id,p.pick_id,p.market,p.selection,p.locked_line,p.label,p.kickoff_at,p.away_team,p.home_team,p.locked_at,p.result,p.graded_at
  from ball_knower_private.verified_prediction_picks p
  where p.user_id=p_user_id order by p.locked_at desc limit 500;
$$;
revoke all on function public.get_ball_knower_verified_prediction_picks(uuid) from public,anon,authenticated;
grant execute on function public.get_ball_knower_verified_prediction_picks(uuid) to service_role;

create or replace function public.grade_ball_knower_verified_prediction_pick(
  p_user_id uuid,p_game_id text,p_result text,p_away_score integer,p_home_score integer
) returns bigint
language plpgsql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare
  v_pick ball_knower_private.verified_prediction_picks%rowtype;
  v_id bigint;
  v_type text;
begin
  if auth.role()<>'service_role' then raise exception 'Service role required'; end if;
  if p_result not in ('win','loss','push') then raise exception 'Invalid prediction result'; end if;
  select * into v_pick from ball_knower_private.verified_prediction_picks
  where user_id=p_user_id and game_id=p_game_id for update;
  if not found then raise exception 'Prediction pick not found'; end if;
  if v_pick.kickoff_at>now() then raise exception 'Game has not locked yet'; end if;
  v_type:=case p_result when 'win' then 'prediction_correct' when 'loss' then 'prediction_wrong' else 'prediction_push' end;
  if v_pick.result is not null and v_pick.result<>p_result then raise exception 'Prediction result is already finalized'; end if;
  update ball_knower_private.verified_prediction_picks
  set result=coalesce(result,p_result),graded_at=coalesce(graded_at,now())
  where user_id=p_user_id and game_id=p_game_id;
  v_id:=ball_knower_private.insert_verified_mode_milestone(
    p_user_id,'prediction',v_type,'prediction:'||p_game_id,
    jsonb_build_object(
      'game_id',p_game_id,'market',v_pick.market,'selection',v_pick.selection,'locked_line',v_pick.locked_line,
      'away_score',p_away_score,'home_score',p_home_score
    ),'nfl_final_score_v1'
  );
  return v_id;
end;
$$;
revoke all on function public.grade_ball_knower_verified_prediction_pick(uuid,text,text,integer,integer) from public,anon,authenticated;
grant execute on function public.grade_ball_knower_verified_prediction_pick(uuid,text,text,integer,integer) to service_role;

-- Extend the permanent-account claim without rewriting the large existing merge
-- RPC. When that RPC marks a claim complete, this trigger transfers all private
-- Phase 4B evidence to the permanent UUID in the same transaction.
create or replace function ball_knower_private.transfer_verified_mode_state_on_guest_claim()
returns trigger
language plpgsql
security definer
set search_path=public,ball_knower_private,pg_temp
as $$
begin
  if new.claimed_at is null or new.claimed_by is null
     or old.claimed_at is not null or new.guest_user_id=new.claimed_by then
    return new;
  end if;

  insert into ball_knower_private.verified_mode_milestones(
    user_id,mode,milestone_type,source_key,payload,verified_at,verified_by,claimed_at
  )
  select new.claimed_by,mode,milestone_type,source_key,payload,verified_at,verified_by,claimed_at
  from ball_knower_private.verified_mode_milestones where user_id=new.guest_user_id
  on conflict(user_id,mode,source_key) do nothing;
  delete from ball_knower_private.verified_mode_milestones where user_id=new.guest_user_id;

  insert into ball_knower_private.verified_prediction_picks(
    user_id,game_id,pick_id,market,selection,locked_line,label,kickoff_at,away_team,home_team,locked_at,result,graded_at
  )
  select new.claimed_by,game_id,pick_id,market,selection,locked_line,label,kickoff_at,away_team,home_team,locked_at,result,graded_at
  from ball_knower_private.verified_prediction_picks where user_id=new.guest_user_id
  on conflict(user_id,game_id) do nothing;
  delete from ball_knower_private.verified_prediction_picks where user_id=new.guest_user_id;

  insert into ball_knower_private.verified_owner_runs(
    user_id,abbr,season,week,stage,wins,losses,playoff_seed,version,updated_at
  )
  select new.claimed_by,abbr,season,week,stage,wins,losses,playoff_seed,version,updated_at
  from ball_knower_private.verified_owner_runs where user_id=new.guest_user_id
  on conflict(user_id) do nothing;
  delete from ball_knower_private.verified_owner_runs where user_id=new.guest_user_id;

  insert into ball_knower_private.verified_agent_clients(
    user_id,player_id,legacy_baseline,signed_at,last_contract_season,last_trade_season,fulfilled_promises
  )
  select new.claimed_by,player_id,legacy_baseline,signed_at,last_contract_season,last_trade_season,fulfilled_promises
  from ball_knower_private.verified_agent_clients where user_id=new.guest_user_id
  on conflict(user_id,player_id) do nothing;
  delete from ball_knower_private.verified_agent_clients where user_id=new.guest_user_id;

  return new;
end;
$$;
revoke all on function ball_knower_private.transfer_verified_mode_state_on_guest_claim() from public,anon,authenticated;

drop trigger if exists transfer_verified_mode_state_on_guest_claim on public.ball_knower_guest_account_claims;
create trigger transfer_verified_mode_state_on_guest_claim
after update of claimed_at,claimed_by on public.ball_knower_guest_account_claims
for each row
execute function ball_knower_private.transfer_verified_mode_state_on_guest_claim();
