-- Final Phase 4B: server-gated Owner/Agent milestones and server-verified Prediction picks.
-- Clients never choose progression event types, XP awards, rating deltas, or idempotency keys.

create schema if not exists ball_knower_private;

create table if not exists ball_knower_private.verified_mode_milestones (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('owner','agent','prediction')),
  milestone_type text not null check (milestone_type in (
    'owner_season_complete','owner_playoff_appearance','owner_conference_title','owner_championship',
    'agent_client_signed','agent_trade_resolved','agent_contract_signed','agent_promise_fulfilled',
    'prediction_correct','prediction_wrong','prediction_push'
  )),
  source_key text not null,
  payload jsonb not null default '{}'::jsonb,
  verified_at timestamptz not null default now(),
  verified_by text not null default 'server',
  claimed_at timestamptz,
  unique(user_id,mode,source_key)
);
create index if not exists verified_mode_milestones_unclaimed_idx
  on ball_knower_private.verified_mode_milestones(user_id,verified_at) where claimed_at is null;
alter table ball_knower_private.verified_mode_milestones enable row level security;
revoke all on table ball_knower_private.verified_mode_milestones from public,anon,authenticated;

create table if not exists ball_knower_private.verified_mode_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('owner','agent')),
  snapshot jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key(user_id,mode)
);
alter table ball_knower_private.verified_mode_state enable row level security;
revoke all on table ball_knower_private.verified_mode_state from public,anon,authenticated;

create table if not exists ball_knower_private.verified_prediction_picks (
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  pick_id text not null,
  market text not null check (market in ('spread','total')),
  selection text not null,
  locked_line numeric not null,
  label text not null,
  kickoff_at timestamptz not null,
  away_team text not null,
  home_team text not null,
  locked_at timestamptz not null default now(),
  result text check (result is null or result in ('win','loss','push')),
  graded_at timestamptz,
  primary key(user_id,game_id)
);
alter table ball_knower_private.verified_prediction_picks enable row level security;
revoke all on table ball_knower_private.verified_prediction_picks from public,anon,authenticated;

create or replace function ball_knower_private.mode_counter(p_snapshot jsonb,p_key text,p_max integer)
returns integer
language plpgsql immutable
set search_path=pg_catalog,pg_temp
as $$
declare v text; n integer;
begin
  if jsonb_typeof(p_snapshot)<>'object' then return -1; end if;
  v:=p_snapshot->>p_key;
  if v is null or v!~'^\d+$' then return -1; end if;
  n:=v::integer;
  if n<0 or n>p_max then return -1; end if;
  return n;
end;
$$;
revoke all on function ball_knower_private.mode_counter(jsonb,text,integer) from public,anon,authenticated;

create or replace function ball_knower_private.insert_verified_mode_milestone(
  p_user_id uuid,p_mode text,p_type text,p_source_key text,p_payload jsonb default '{}'::jsonb,p_verified_by text default 'server'
) returns bigint
language plpgsql security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare v_id bigint;
begin
  insert into ball_knower_private.verified_mode_milestones(user_id,mode,milestone_type,source_key,payload,verified_by)
  values(p_user_id,p_mode,p_type,left(p_source_key,160),coalesce(p_payload,'{}'::jsonb),left(p_verified_by,80))
  on conflict(user_id,mode,source_key) do nothing returning id into v_id;
  if v_id is null then
    select id into v_id from ball_knower_private.verified_mode_milestones
    where user_id=p_user_id and mode=p_mode and source_key=left(p_source_key,160);
  end if;
  return v_id;
end;
$$;
revoke all on function ball_knower_private.insert_verified_mode_milestone(uuid,text,text,text,jsonb,text) from public,anon,authenticated;

create or replace function public.list_ball_knower_unclaimed_mode_milestones()
returns table(id bigint,mode text,milestone_type text,verified_at timestamptz)
language sql security definer
set search_path=public,ball_knower_private,pg_temp
as $$
  select m.id,m.mode,m.milestone_type,m.verified_at
  from ball_knower_private.verified_mode_milestones m
  where m.user_id=auth.uid() and m.verified_at is not null and m.claimed_at is null
  order by m.id asc limit 100;
$$;
revoke all on function public.list_ball_knower_unclaimed_mode_milestones() from public,anon;
grant execute on function public.list_ball_knower_unclaimed_mode_milestones() to authenticated;

create or replace function public.claim_ball_knower_verified_mode_milestone(p_milestone_id bigint)
returns table(applied boolean,milestone_id bigint,event_key text)
language plpgsql security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare
  v_user uuid:=auth.uid();
  v_milestone ball_knower_private.verified_mode_milestones%rowtype;
  v_xp integer; v_delta integer; v_event_key text; v_applied boolean;
begin
  if v_user is null then raise exception 'Sign in required'; end if;
  select * into v_milestone from ball_knower_private.verified_mode_milestones
  where id=p_milestone_id and user_id=v_user and verified_at is not null for update;
  if not found then raise exception 'Verified milestone not found'; end if;
  select x.xp,x.delta into v_xp,v_delta from (values
    ('owner_season_complete',30,1),('owner_playoff_appearance',60,1),('owner_conference_title',100,2),('owner_championship',180,3),
    ('agent_client_signed',25,1),('agent_trade_resolved',40,1),('agent_contract_signed',55,1),('agent_promise_fulfilled',45,1),
    ('prediction_correct',20,1),('prediction_wrong',2,-1),('prediction_push',5,0)
  ) as x(kind,xp,delta) where x.kind=v_milestone.milestone_type;
  if v_xp is null then raise exception 'Unsupported verified milestone'; end if;
  v_event_key:='mode_milestone:'||v_milestone.id;
  v_applied:=ball_knower_private.apply_progress_event(
    v_user,v_event_key,v_milestone.milestone_type,v_milestone.mode,v_xp,v_delta,
    coalesce(v_milestone.payload,'{}'::jsonb)||jsonb_build_object('verified_milestone_id',v_milestone.id,'verified_by',v_milestone.verified_by)
  );
  update ball_knower_private.verified_mode_milestones set claimed_at=coalesce(claimed_at,now()) where id=v_milestone.id;
  return query select v_applied,v_milestone.id,v_event_key;
end;
$$;
revoke all on function public.claim_ball_knower_verified_mode_milestone(bigint) from public,anon;
grant execute on function public.claim_ball_knower_verified_mode_milestone(bigint) to authenticated;

-- Service-only transition verifier. First valid snapshot is a no-reward baseline.
-- Stale snapshots are ignored and jumps larger than two are baselined without rewards.
create or replace function public.record_ball_knower_verified_mode_snapshot(p_user_id uuid,p_mode text,p_snapshot jsonb)
returns table(milestone_id bigint)
language plpgsql security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare
  v_old jsonb; v_id bigint;
  a integer; b integer; c integer; d integer;
  oa integer; ob integer; oc integer; od integer;
  i integer;
begin
  if auth.role() <> 'service_role' then raise exception 'Service role required'; end if;
  if p_user_id is null or p_mode not in ('owner','agent') or jsonb_typeof(p_snapshot)<>'object' then raise exception 'Invalid mode snapshot'; end if;
  if octet_length(p_snapshot::text)>8192 then raise exception 'Mode snapshot too large'; end if;

  if p_mode='owner' then
    a:=ball_knower_private.mode_counter(p_snapshot,'seasonsCompleted',500);
    b:=ball_knower_private.mode_counter(p_snapshot,'playoffAppearances',500);
    c:=ball_knower_private.mode_counter(p_snapshot,'conferenceTitles',500);
    d:=ball_knower_private.mode_counter(p_snapshot,'championships',500);
    if least(a,b,c,d)<0 or b>a or c>b or d>c then return; end if;
  else
    a:=ball_knower_private.mode_counter(p_snapshot,'signedClients',10000);
    b:=ball_knower_private.mode_counter(p_snapshot,'resolvedTrades',10000);
    c:=ball_knower_private.mode_counter(p_snapshot,'dealCount',10000);
    d:=ball_knower_private.mode_counter(p_snapshot,'promisesKept',10000);
    if least(a,b,c,d)<0 then return; end if;
  end if;

  select snapshot into v_old from ball_knower_private.verified_mode_state
  where user_id=p_user_id and mode=p_mode for update;
  if not found then
    insert into ball_knower_private.verified_mode_state(user_id,mode,snapshot) values(p_user_id,p_mode,p_snapshot)
    on conflict(user_id,mode) do nothing;
    return;
  end if;

  if p_mode='owner' then
    oa:=ball_knower_private.mode_counter(v_old,'seasonsCompleted',500);
    ob:=ball_knower_private.mode_counter(v_old,'playoffAppearances',500);
    oc:=ball_knower_private.mode_counter(v_old,'conferenceTitles',500);
    od:=ball_knower_private.mode_counter(v_old,'championships',500);
  else
    oa:=ball_knower_private.mode_counter(v_old,'signedClients',10000);
    ob:=ball_knower_private.mode_counter(v_old,'resolvedTrades',10000);
    oc:=ball_knower_private.mode_counter(v_old,'dealCount',10000);
    od:=ball_knower_private.mode_counter(v_old,'promisesKept',10000);
  end if;
  if least(oa,ob,oc,od)<0 then
    update ball_knower_private.verified_mode_state set snapshot=p_snapshot,updated_at=now() where user_id=p_user_id and mode=p_mode;
    return;
  end if;
  if a<oa or b<ob or c<oc or d<od then return; end if;
  if greatest(a-oa,b-ob,c-oc,d-od)>2 then
    update ball_knower_private.verified_mode_state set snapshot=p_snapshot,updated_at=now() where user_id=p_user_id and mode=p_mode;
    return;
  end if;

  if p_mode='owner' then
    for i in (oa+1)..a loop v_id:=ball_knower_private.insert_verified_mode_milestone(p_user_id,'owner','owner_season_complete','owner:season:'||i,jsonb_build_object('count',i),'mode_transition_v1'); milestone_id:=v_id; return next; end loop;
    for i in (ob+1)..b loop v_id:=ball_knower_private.insert_verified_mode_milestone(p_user_id,'owner','owner_playoff_appearance','owner:playoff:'||i,jsonb_build_object('count',i),'mode_transition_v1'); milestone_id:=v_id; return next; end loop;
    for i in (oc+1)..c loop v_id:=ball_knower_private.insert_verified_mode_milestone(p_user_id,'owner','owner_conference_title','owner:conference:'||i,jsonb_build_object('count',i),'mode_transition_v1'); milestone_id:=v_id; return next; end loop;
    for i in (od+1)..d loop v_id:=ball_knower_private.insert_verified_mode_milestone(p_user_id,'owner','owner_championship','owner:championship:'||i,jsonb_build_object('count',i),'mode_transition_v1'); milestone_id:=v_id; return next; end loop;
  else
    for i in (oa+1)..a loop v_id:=ball_knower_private.insert_verified_mode_milestone(p_user_id,'agent','agent_client_signed','agent:client:'||i,jsonb_build_object('count',i),'mode_transition_v1'); milestone_id:=v_id; return next; end loop;
    for i in (ob+1)..b loop v_id:=ball_knower_private.insert_verified_mode_milestone(p_user_id,'agent','agent_trade_resolved','agent:trade:'||i,jsonb_build_object('count',i),'mode_transition_v1'); milestone_id:=v_id; return next; end loop;
    for i in (oc+1)..c loop v_id:=ball_knower_private.insert_verified_mode_milestone(p_user_id,'agent','agent_contract_signed','agent:contract:'||i,jsonb_build_object('count',i),'mode_transition_v1'); milestone_id:=v_id; return next; end loop;
    for i in (od+1)..d loop v_id:=ball_knower_private.insert_verified_mode_milestone(p_user_id,'agent','agent_promise_fulfilled','agent:promise:'||i,jsonb_build_object('count',i),'mode_transition_v1'); milestone_id:=v_id; return next; end loop;
  end if;
  update ball_knower_private.verified_mode_state set snapshot=p_snapshot,updated_at=now() where user_id=p_user_id and mode=p_mode;
end;
$$;
revoke all on function public.record_ball_knower_verified_mode_snapshot(uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.record_ball_knower_verified_mode_snapshot(uuid,text,jsonb) to service_role;

create or replace function public.save_ball_knower_verified_prediction_pick(
  p_user_id uuid,p_game_id text,p_pick_id text,p_market text,p_selection text,p_locked_line numeric,p_label text,
  p_kickoff_at timestamptz,p_away_team text,p_home_team text
) returns boolean
language plpgsql security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare v_count integer;
begin
  if auth.role()<>'service_role' then raise exception 'Service role required'; end if;
  if p_user_id is null or nullif(btrim(p_game_id),'') is null or p_market not in ('spread','total') then raise exception 'Invalid prediction pick'; end if;
  if p_kickoff_at<=now() then raise exception 'Game is already locked'; end if;
  if p_locked_line is null or abs(p_locked_line)>200 then raise exception 'Invalid locked line'; end if;
  insert into ball_knower_private.verified_prediction_picks(user_id,game_id,pick_id,market,selection,locked_line,label,kickoff_at,away_team,home_team,locked_at,result,graded_at)
  values(p_user_id,left(p_game_id,120),left(p_pick_id,200),p_market,left(p_selection,120),p_locked_line,left(p_label,160),p_kickoff_at,left(p_away_team,120),left(p_home_team,120),now(),null,null)
  on conflict(user_id,game_id) do update set pick_id=excluded.pick_id,market=excluded.market,selection=excluded.selection,locked_line=excluded.locked_line,label=excluded.label,kickoff_at=excluded.kickoff_at,away_team=excluded.away_team,home_team=excluded.home_team,locked_at=now(),result=null,graded_at=null
  where ball_knower_private.verified_prediction_picks.kickoff_at>now();
  get diagnostics v_count=row_count;
  return v_count=1;
end;
$$;
revoke all on function public.save_ball_knower_verified_prediction_pick(uuid,text,text,text,text,numeric,text,timestamptz,text,text) from public,anon,authenticated;
grant execute on function public.save_ball_knower_verified_prediction_pick(uuid,text,text,text,text,numeric,text,timestamptz,text,text) to service_role;

create or replace function public.delete_ball_knower_verified_prediction_pick(p_user_id uuid,p_game_id text)
returns boolean
language plpgsql security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare v_count integer;
begin
  if auth.role()<>'service_role' then raise exception 'Service role required'; end if;
  delete from ball_knower_private.verified_prediction_picks where user_id=p_user_id and game_id=p_game_id and kickoff_at>now();
  get diagnostics v_count=row_count;
  return v_count=1;
end;
$$;
revoke all on function public.delete_ball_knower_verified_prediction_pick(uuid,text) from public,anon,authenticated;
grant execute on function public.delete_ball_knower_verified_prediction_pick(uuid,text) to service_role;

create or replace function public.get_ball_knower_verified_prediction_picks(p_user_id uuid)
returns table(game_id text,pick_id text,market text,selection text,locked_line numeric,label text,kickoff_at timestamptz,away_team text,home_team text,locked_at timestamptz,result text,graded_at timestamptz)
language sql security definer
set search_path=public,ball_knower_private,pg_temp
as $$
  select p.game_id,p.pick_id,p.market,p.selection,p.locked_line,p.label,p.kickoff_at,p.away_team,p.home_team,p.locked_at,p.result,p.graded_at
  from ball_knower_private.verified_prediction_picks p where p.user_id=p_user_id order by p.locked_at desc limit 500;
$$;
revoke all on function public.get_ball_knower_verified_prediction_picks(uuid) from public,anon,authenticated;
grant execute on function public.get_ball_knower_verified_prediction_picks(uuid) to service_role;

create or replace function public.grade_ball_knower_verified_prediction_pick(p_user_id uuid,p_game_id text,p_result text,p_away_score integer,p_home_score integer)
returns bigint
language plpgsql security definer
set search_path=public,ball_knower_private,pg_temp
as $$
declare v_pick ball_knower_private.verified_prediction_picks%rowtype; v_id bigint; v_type text;
begin
  if auth.role()<>'service_role' then raise exception 'Service role required'; end if;
  if p_result not in ('win','loss','push') then raise exception 'Invalid prediction result'; end if;
  select * into v_pick from ball_knower_private.verified_prediction_picks where user_id=p_user_id and game_id=p_game_id for update;
  if not found then raise exception 'Prediction pick not found'; end if;
  if v_pick.kickoff_at>now() then raise exception 'Game has not locked yet'; end if;
  v_type:=case p_result when 'win' then 'prediction_correct' when 'loss' then 'prediction_wrong' else 'prediction_push' end;
  update ball_knower_private.verified_prediction_picks set result=coalesce(result,p_result),graded_at=coalesce(graded_at,now()) where user_id=p_user_id and game_id=p_game_id;
  v_id:=ball_knower_private.insert_verified_mode_milestone(p_user_id,'prediction',v_type,'prediction:'||p_game_id,
    jsonb_build_object('game_id',p_game_id,'market',v_pick.market,'selection',v_pick.selection,'locked_line',v_pick.locked_line,'away_score',p_away_score,'home_score',p_home_score),'nfl_final_score_v1');
  return v_id;
end;
$$;
revoke all on function public.grade_ball_knower_verified_prediction_pick(uuid,text,text,integer,integer) from public,anon,authenticated;
grant execute on function public.grade_ball_knower_verified_prediction_pick(uuid,text,text,integer,integer) to service_role;
