-- Phase 4B starts with a strict trust boundary: browser clients may claim a
-- server-verified milestone by id, but cannot choose its type, key, or reward.
create table if not exists ball_knower_private.verified_mode_milestones (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('owner','agent','prediction')),
  milestone_type text not null check (milestone_type in (
    'owner_season_complete','owner_playoff_appearance','owner_conference_title','owner_championship',
    'agent_client_signed','agent_trade_resolved','agent_contract_signed','agent_promise_fulfilled',
    'prediction_correct','prediction_wrong','prediction_push'
  )),
  source_key text not null check (char_length(source_key) between 8 and 160),
  source_payload jsonb not null default '{}'::jsonb check (jsonb_typeof(source_payload)='object' and octet_length(source_payload::text)<=8192),
  verified_at timestamptz not null,
  verified_by text not null check (char_length(verified_by) between 3 and 80),
  claimed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id,mode,source_key),
  constraint verified_mode_milestone_matches_mode check (
    (mode='owner' and milestone_type like 'owner_%')
    or (mode='agent' and milestone_type like 'agent_%')
    or (mode='prediction' and milestone_type like 'prediction_%')
  )
);

alter table ball_knower_private.verified_mode_milestones enable row level security;
revoke all on table ball_knower_private.verified_mode_milestones from public,anon,authenticated;

create index if not exists verified_mode_milestones_user_claim_idx
on ball_knower_private.verified_mode_milestones(user_id,claimed_at,id);

create or replace function public.claim_ball_knower_verified_mode_milestone(p_milestone_id bigint)
returns table(applied boolean,event_key text)
language plpgsql
security definer
set search_path=public,ball_knower_private,pg_temp
as $function$
declare
  v_user uuid:=auth.uid();
  v_milestone ball_knower_private.verified_mode_milestones%rowtype;
  v_xp integer;
  v_rating integer;
  v_applied boolean;
  v_event_key text;
begin
  if v_user is null then raise exception 'Authentication required'; end if;

  select * into v_milestone
  from ball_knower_private.verified_mode_milestones
  where id=p_milestone_id and user_id=v_user and verified_at is not null
  for update;

  if v_milestone.id is null then raise exception 'Verified mode milestone not found'; end if;

  select reward.xp,reward.rating into v_xp,v_rating
  from (values
    ('owner_season_complete',30,1),('owner_playoff_appearance',60,1),
    ('owner_conference_title',100,2),('owner_championship',180,3),
    ('agent_client_signed',25,1),('agent_trade_resolved',40,1),
    ('agent_contract_signed',55,1),('agent_promise_fulfilled',45,1),
    ('prediction_correct',20,1),('prediction_wrong',2,-1),('prediction_push',5,0)
  ) as reward(kind,xp,rating)
  where reward.kind=v_milestone.milestone_type;

  if v_xp is null then raise exception 'Unsupported verified milestone'; end if;

  v_event_key:='mode_milestone:'||v_milestone.id;
  v_applied:=ball_knower_private.apply_progress_event(
    v_user,v_event_key,v_milestone.milestone_type,v_milestone.mode,v_xp,v_rating,
    v_milestone.source_payload||jsonb_build_object('milestone_id',v_milestone.id,'verified_at',v_milestone.verified_at)
  );

  update ball_knower_private.verified_mode_milestones
  set claimed_at=coalesce(claimed_at,now())
  where id=v_milestone.id;

  return query select v_applied,v_event_key;
end;
$function$;

revoke all on function public.claim_ball_knower_verified_mode_milestone(bigint) from public,anon;
grant execute on function public.claim_ball_knower_verified_mode_milestone(bigint) to authenticated;
