import {existsSync,writeFileSync} from 'node:fs';
import {MINI_TEAMS} from '../public/play-moment-3d/mini-teams.js';
import {SOLO_PLAYERS_DATABASE} from '../soloUniverse';
const art=Object.fromEntries(MINI_TEAMS.map(team=>{
 const rank=(id:string)=>{const index=team.lineup.findIndex(p=>p.id===id);return index<0?99:index;};
 const players=SOLO_PLAYERS_DATABASE.filter(p=>p.team===team.abbr).sort((a,b)=>(b.overall??0)-(a.overall??0)||rank(a.id)-rank(b.id)).slice(0,3).map(player=>({id:player.id,name:player.name,rating:player.overall??0,position:player.position,portrait:`/mini-team-selection/${player.id}.webp`}));
 const logo=`/mini-team-selection/${team.abbr.toLowerCase()}-logo.webp`;
 for(const path of [logo,...players.map(p=>p.portrait)])if(!existsSync('public'+path))throw Error('Create artwork for '+path+' before updating the selector.');
 const specialists=SOLO_PLAYERS_DATABASE.filter(p=>p.team===team.abbr && (p.position==='K'||p.position==='P'));
 if(specialists.length!==2)throw Error('Expected kicker and punter for '+team.abbr);
 const specialTeams=Math.round(specialists.reduce((sum,p)=>sum+(p.overall??0),0)/specialists.length);
 return [team.abbr,{logo,players,specialTeams}];
}));
writeFileSync('miniSelectorArt.ts','// Generated by scripts/build-mini-selector.ts. Stable portrait files are keyed by player ID.\nexport const MINI_SELECTOR_ART: Record<string, {logo: string; specialTeams: number; players: {id: string; name: string; rating: number; position: string; portrait: string}[]}> = '+JSON.stringify(art)+';\n');
console.log('Generated top-three artwork metadata for',MINI_TEAMS.length,'Solo teams.');
