import assert from 'node:assert/strict';
import {newDash,pressDash,tapStride,speedPercent,accuracy,positionRanking,stepDash,combineAthlete,FINISH,RESULT_KEY,RULESET,readResults,saveResult,bestResult} from '../combine/dash.js';
const athlete=combineAthlete({id:'wr-test',name:'Test Receiver',position:'WR',speed:94,attributes:{athleticism:90}});
function start(speed=94){const s=newDash({...athlete,speed,acceleration:speed});pressDash(s);stepDash(s,2);stepDash(s,.1);pressDash(s);return s;}
function run(speed=94,dt=1/120,pace=.25,wrong=false){const s=start(speed);let next=.15,side='left';for(let i=0;i<20000&&s.phase==='running';i++){if(s.clock+1e-8>=next){tapStride(s,side);if(!wrong)side=side==='left'?'right':'left';next+=pace;}else stepDash(s,Math.min(dt,next-s.clock));}assert.equal(s.phase,'finished');assert.equal(s.distance,FINISH);assert(s.splits[0]<s.splits[1]&&s.splits[1]<s.splits[2]);return s;}
const clean=run(),slow=run(94,1/120,.85),idle=run(94,1/120,100),repeated=run(94,1/120,.25,true),spam=run(94,1/120,.025);
assert(clean.clock<slow.clock&&clean.clock<idle.clock);assert(repeated.clock>clean.clock+1);assert(spam.clock>clean.clock+1);assert(spam.clock<20,'Repeated mistakes must not trap the runner or prevent saving');assert(accuracy(clean).flow===100);assert(clean.peakVelocity/(7.2+44*.066)>.90);assert(run(95).clock<run(70).clock);
const natural=run(94,1/120,.4);assert(natural.clock<idle.clock-.5,'Natural slower alternation must still work without a beat window');
const s=start();for(let i=0;i<12;i++){tapStride(s,s.nextSide);stepDash(s,.25);}assert(speedPercent(s)>=90);const before=speedPercent(s),expected=s.nextSide;tapStride(s,expected==='left'?'right':'left');assert(speedPercent(s)<before-5);assert.equal(s.nextSide,expected);for(let i=0;i<5;i++){stepDash(s,.25);tapStride(s,s.nextSide);}assert(speedPercent(s)>=90,'Flow must recover');const gap=start();for(let i=0;i<8;i++){tapStride(gap,gap.nextSide);stepDash(gap,.25);}const moving=gap.velocity;stepDash(gap,1.2);assert(gap.velocity<moving-1,'Stopping loses speed');
const times=[30,60,90,120,144].map(hz=>run(94,1/hz).clock);assert(Math.max(...times)-Math.min(...times)<.005);
const early=newDash(athlete);pressDash(early);pressDash(early);stepDash(early,10);assert.equal(early.phase,'false-start');assert.equal(early.distance,0);
const held=newDash(athlete);pressDash(held);stepDash(held,2);stepDash(held,3);assert.equal(held.phase,'ready');assert.equal(held.distance,0);pressDash(held);assert.equal(held.phase,'running');
assert.deepEqual(positionRanking([athlete,{...athlete,id:'slow',speed:50},{...athlete,id:'qb',position:'QB'}],athlete,clean.clock),{rank:1,total:2});
let value='broken';const storage={getItem:()=>value,setItem:(key,v)=>{assert.equal(key,RESULT_KEY);value=v}};assert.deepEqual(readResults(storage),[]);
const a={ruleset:RULESET,context:'solo-a',playerId:'wr',name:'Receiver',position:'WR',date:1,splits:[1.6,2.6,4.6]};assert(saveResult(a,storage));assert(saveResult({...a,context:'standalone',splits:[1.5,2.5,4.5]},storage));assert(saveResult({...a,splits:[1.5,2.5,4.55]},storage));assert(saveResult({...a,ruleset:undefined,splits:[1.4,2.4,4.2]},storage));assert.equal(bestResult(readResults(storage),'solo-a','wr').splits[2],4.55);assert.equal(bestResult(readResults(storage),'solo-b','wr'),null);assert(!saveResult({...a,splits:[3,2,1]},storage));assert(!saveResult(a,{getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}}));
const input={id:'prospect-1',name:'Prospect',position:'LT',grade:90};assert.deepEqual(combineAthlete(input),combineAthlete(input));assert(combineAthlete(input).speed<70);
console.log('PASS natural alternation, max-speed range, visible speed loss/recovery, stopped-flow decay, repeated-side/spam penalties, tap launch, automatic exact finish/splits, refresh stability, ratings, rankings and legacy storage isolation.',{clean:clean.clock,natural:natural.clock,slow:slow.clock,idle:idle.clock,repeated:repeated.clock,spam:spam.clock,times});
