import { writeFileSync } from 'node:fs';
import { PLAYERS_DATABASE } from '../players';
import { getDraftPositionGroup } from '../rosterRules';

const output = process.argv[2] || '/tmp/20260825_secure_draft_order_game_catalog.sql';
const sql = (value: string) => `'${value.replaceAll("'", "''")}'`;
const rows = PLAYERS_DATABASE
  .map(player => ({ player, group: getDraftPositionGroup(player) }))
  .filter((entry): entry is typeof entry & { group: NonNullable<typeof entry.group> } => Boolean(entry.group))
  .filter(({ player }) => Boolean(player.id) && Number.isFinite(player.salary) && Number.isFinite(player.ovr));

const ids = new Set<string>();
for (const { player } of rows) {
  if (ids.has(player.id)) throw new Error(`Duplicate canonical player id: ${player.id}`);
  ids.add(player.id);
}
if (rows.length < 1500) throw new Error(`Canonical Draft Order Game pool unexpectedly small: ${rows.length}`);

const values = rows.map(({ player, group }) => {
  const canonical = {
    id: player.id,
    name: player.name,
    team: player.team,
    teamCity: player.teamCity || 'NFL',
    position: player.position,
    ovr: player.ovr,
    overallRating: player.overallRating ?? player.ovr,
    salary: Number(player.salary.toFixed(2)),
  };
  return `(${sql(player.id)},${sql(group)},${Number(player.salary.toFixed(2))},${Number(player.ovr)},${sql(JSON.stringify(canonical))}::jsonb,true)`;
});

const migration = `-- GENERATED by scripts/generate-draft-order-game-catalog.ts. Do not hand edit.
-- Authoritative private catalog for the explicit Draft Order Game only.

create table if not exists ball_knower_private.draft_order_game_players (
  player_id text primary key,
  position_group text not null check (position_group in ('QB','RB','WR','TE','OL','DL_EDGE','LB','CB','S','K','P')),
  salary numeric(8,2) not null check (salary >= 0),
  ovr integer not null check (ovr between 0 and 100),
  player_json jsonb not null,
  active boolean not null default true
);
alter table ball_knower_private.draft_order_game_players enable row level security;
revoke all on ball_knower_private.draft_order_game_players from public, anon, authenticated;

insert into ball_knower_private.draft_order_game_players(player_id,position_group,salary,ovr,player_json,active) values
${values.join(',\n')}
on conflict(player_id) do update set
 position_group=excluded.position_group, salary=excluded.salary, ovr=excluded.ovr, player_json=excluded.player_json, active=true;

-- Anything removed from the current client catalog becomes non-selectable without deleting history.
update ball_knower_private.draft_order_game_players p set active=false
where not (p.player_id = any(array[${rows.map(({player}) => sql(player.id)).join(',')}]::text[]));
`;

writeFileSync(output, migration);
console.log(`Generated ${rows.length} canonical Draft Order Game players at ${output}`);
