import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validTickerStories} from '../HomeNewsTicker';
const valid={headline:'A real feed headline',url:'https://publisher.example/news'};
assert.deepEqual(validTickerStories({available:false,articles:[valid]}),[]);
assert.deepEqual(validTickerStories({available:true,articles:null}),[]);
assert.equal(validTickerStories({available:true,articles:[valid,valid,null,{...valid,url:'javascript:alert(1)'},{...valid,url:'https://user:pass@publisher.example/'},{...valid,headline:''}]}).length,1);
assert.equal(validTickerStories({available:true,articles:[{...valid,headline:'X'.repeat(500)}]})[0].headline.length,240);
assert.equal(validTickerStories({available:true,articles:Array.from({length:25},(_,i)=>({...valid,url:`https://publisher.example/${i}`}))}).length,20);
const ticker=fs.readFileSync('HomeNewsTicker.tsx','utf8');
const hero=fs.readFileSync('HomeStadiumHero.tsx','utf8');
const nav=fs.readFileSync('Navbar.tsx','utf8');
const css=fs.readFileSync('homeBroadcast.css','utf8');
assert.ok(ticker.includes('120_000')&&ticker.includes('10_000'));
assert.ok(ticker.includes('AbortController')&&ticker.includes("'visibilitychange'")&&ticker.includes('clearTimeout(timer)'));
assert.ok(ticker.includes('aria-live="off"')&&ticker.includes('onFocusCapture')&&ticker.includes('aria-expanded={!hidden}'));
assert.ok(hero.includes('IntersectionObserver')&&hero.includes('prefers-reduced-motion: reduce'));
assert.ok(!hero.includes('bk-home-motion')&&!hero.includes('Motion ')&&!hero.includes('localStorage'));
assert.ok(hero.includes('bk-home-floodlights')&&css.includes('bk-home-stadium-flicker')&&css.includes('bk-home-stadium-halo'));
assert.ok(css.includes('[data-motion="off"] :is(.bk-home-light,.bk-home-haze,.bk-home-floodlight)'));
assert.ok(!hero.includes('<video')&&!hero.includes('<canvas')&&!hero.includes('setInterval'));
assert.ok(nav.includes("showNews&&<Suspense")&&nav.includes("lazy(()=>import('./HomeNewsTicker')"));
assert.ok(css.includes('animation-play-state: paused')&&css.includes('@media (prefers-reduced-motion: reduce)'));
assert.ok(fs.statSync('public/atmosphere/home-stadium.webp').size<50_000);
console.log('Home broadcast checks passed: safe news normalization, realistic floodlight flicker, automatic accessible motion, lazy ticker, bounded payload and headline controls.');
