import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import{advanceOwnerSeason,migrateOwnerLegacyWeek,normalizeOwnerAbbr,OWNER_TEAM_ABBRS,owner2026Calendar,ownerGameRevenue,ownerPlayoffHomeGame,ownerPlayoffSeed,ownerSeasonCalendar,ownerStageLabel,qualifiesForOwnerPlayoffs,type OwnerSeasonSnapshot}from'../ownerSeasonEngine';

const base:OwnerSeasonSnapshot={abbr:'PHI',season:2026,week:18,stage:'regular',wins:9,losses:7,cashM:350,ticketPrice:125,parkingPrice:35,fanTrust:70,stadium:75,gmCostM:9,coachCostM:12};
assert.equal(qualifiesForOwnerPlayoffs(9,8),true);
assert.equal(qualifiesForOwnerPlayoffs(7,10),false);
assert.equal(advanceOwnerSeason({...base,week:17},false).nextStage,'regular','Week 17 must not end the 18-week calendar');
assert.equal(advanceOwnerSeason(base,false).nextStage,'wild-card','a qualified owner season must continue after Week 18');
assert.equal(advanceOwnerSeason({...base,wins:6,losses:10},false).seasonEnded,true,'a non-playoff season must roll over');
assert.equal(advanceOwnerSeason({...base,stage:'wild-card',week:18},true).nextStage,'divisional');
assert.equal(advanceOwnerSeason({...base,stage:'divisional',week:19},true).nextStage,'conference');
assert.equal(advanceOwnerSeason({...base,stage:'conference',week:20},true).nextStage,'super-bowl');
const champion=advanceOwnerSeason({...base,stage:'super-bowl',week:21},true);
assert.equal(champion.seasonEnded,true);
assert.equal(champion.wonChampionship,true);
assert.equal(champion.expensesM,21,'annual executive salaries must hit the P&L once');
assert.ok(champion.revenueM>=85,'a championship must include the title revenue bump');
assert.ok(ownerGameRevenue(base,true,false)>0);
assert.equal(ownerGameRevenue(base,false,false),0);
assert.equal(ownerStageLabel('wild-card',18),'WILD CARD');
const weeklyRevenue=[1,3,5,7,9,11,13,15,17].reduce((total,week)=>total+ownerGameRevenue({...base,week},true,false),0);
assert.ok(weeklyRevenue>ownerGameRevenue(base,true,false),'a season receipt must be able to accumulate every home gate');
for(const abbr of OWNER_TEAM_ABBRS){const calendar=owner2026Calendar(abbr);assert.equal(calendar.length,18);assert.equal(calendar.filter(week=>week.isBye).length,1);assert.equal(calendar.filter(week=>!week.isBye).length,17);assert.ok([8,9].includes(calendar.filter(week=>week.isHome).length),`${abbr} must retain eight or nine home games`);}
const calendars=OWNER_TEAM_ABBRS.map(abbr=>owner2026Calendar(abbr));
assert.equal(calendars.flat().filter(week=>week.isHome).length,272,'the 272-game regular season must have exactly 272 designated home teams');
for(let week=1;week<=18;week++){const entries=calendars.map(calendar=>calendar[week-1]);assert.equal(entries.filter(entry=>entry.isHome).length,entries.filter(entry=>!entry.isBye).length/2,`Week ${week} must have one home team per game`);}
assert.equal(normalizeOwnerAbbr('NOPE'),'PHI','unsupported persisted team codes must fall back safely');
assert.notDeepEqual(ownerSeasonCalendar('PHI',2027),ownerSeasonCalendar('PHI',2026),'later careers must not reuse the same venue slate');
assert.equal(ownerSeasonCalendar('PHI',2026).filter(entry=>entry.isHome).length,9);
assert.equal(ownerSeasonCalendar('PHI',2027).filter(entry=>entry.isHome).length,8,'future-year hosting must alternate conference revenue equity');
assert.equal(ownerPlayoffHomeGame({...base,stage:'wild-card',wins:9}),false,'a low-seeded Wild Card team must not receive a home gate');
assert.equal(ownerPlayoffHomeGame({...base,stage:'wild-card',playoffSeed:4}),true,'seed 4 must host a Wild Card game');
assert.equal(ownerPlayoffHomeGame({...base,stage:'super-bowl',wins:14}),false,'the Super Bowl must remain neutral');
assert.deepEqual(new Set(Array.from({length:20},(_,index)=>ownerPlayoffSeed(8+(index%6),OWNER_TEAM_ABBRS[index%OWNER_TEAM_ABBRS.length],2026+index))),new Set([1,2,3,4,5,6,7]),'the model must represent every conference seed');
const topSeed=advanceOwnerSeason({...base,wins:12,losses:4},true);
assert.equal(topSeed.playoffSeed,1);
assert.equal(topSeed.nextStage,'divisional','seed 1 must receive a Wild Card bye');
assert.equal(owner2026Calendar('WAS')[0].isHome,false,'Washington opens Week 1 away at Philadelphia');
assert.equal(owner2026Calendar('PHI')[0].isHome,true,'Philadelphia opens Week 1 at home against Washington');
assert.equal(owner2026Calendar('ARI')[3].isHome,false,'Arizona plays Week 4 away at the Giants');
assert.equal(migrateOwnerLegacyWeek('WAS',7),8,'a legacy game counter must skip Washington’s Week 7 bye');
assert.equal(migrateOwnerLegacyWeek('PHI',17),18,'a legacy Week 17 save must have one regular-season game left');
const ownerMode=readFileSync(new URL('../OwnerBusinessMode.tsx',import.meta.url),'utf8');
assert.ok(!ownerMode.includes('cashM:state.cashM-p.costM'),'annual staff salary must not also be charged up front');
assert.ok(ownerMode.includes('seasonStaffCommitmentsM:state.seasonStaffCommitmentsM+p.costM'),'hired staff salary must remain obligated after a later firing');
assert.ok(ownerMode.includes('Math.max(0,-choiceCash)'),'decision spending must be included in season expenses');
assert.ok(ownerMode.includes('careerExpensesM:trackCash&&cashDelta<0'),'buyouts and investments must reach the career expense ledger');
assert.ok(ownerMode.includes('seasonStaffCommitmentsM))?Number(v.seasonStaffCommitmentsM):0'),'legacy saves must not repay salaries charged before migration');
assert.ok(ownerMode.includes('careerWins:baseline.careerWins+(isRegularGame&&won?1:0)'),'postseason wins must not inflate the regular-season career record');
console.log('Phase 4 Owner postseason checks passed.');
