import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const detail = readFileSync(new URL('../FantasyPlayerDetail.tsx', import.meta.url), 'utf8');
const cloud = readFileSync(new URL('../fantasyPlayerDetailsCloud.ts', import.meta.url), 'utf8');
const postDraft = readFileSync(new URL('../FantasyLeaguePostDraft.tsx', import.meta.url), 'utf8');
const hub = readFileSync(new URL('../FantasyHub.tsx', import.meta.url), 'utf8');
const communications = readFileSync(new URL('../FantasyLeagueCommunications.tsx', import.meta.url), 'utf8');

assert.ok(detail.includes('loadFantasyPlayerWeeks({ id: player.id'), 'Player detail must load authoritative weekly history using the selected player identity.');
const fallbackQueryStart = cloud.indexOf('// Older weekly rows can retain a superseded Ball Knower id.');
const fallbackQueryEnd = cloud.indexOf('  ]);', fallbackQueryStart);
assert.ok(fallbackQueryStart >= 0 && fallbackQueryEnd > fallbackQueryStart, 'Exactly one scoped name/position discovery query must exist.');
const fallbackQuery = cloud.slice(fallbackQueryStart, fallbackQueryEnd);
assert.match(fallbackQuery, /\.eq\('player_name', player\.name\)[\s\S]*?\.eq\('position', player\.position\)/, 'The identity discovery query must require exact name and exact position.');
assert.ok(!fallbackQuery.includes(".eq('team', player.team)"), 'Identity discovery must retain history across NFL team changes.');
assert.ok(cloud.includes(".eq('ball_knower_player_id', player.id)"), 'Weekly history must query the permanent Ball Knower player identity first.');
assert.ok(cloud.includes('identityProviderIds.size === 1'), 'Current-id rows must resolve to exactly one provider identity before historical fallback is trusted.');
assert.ok(cloud.includes('fallbackProviderIds.size === 1'), 'Discovered historical rows must resolve to exactly one provider identity before merging.');
assert.ok(cloud.includes('soleFallbackProviderId === soleIdentityProviderId'), 'Historical fallback rows must match the provider identity anchored by the selected permanent player id.');
assert.ok(cloud.includes('No current-id rows means there is no trustworthy provider identity anchor.'), 'An empty current identity must fail closed instead of guessing a player from name and position.');
assert.ok(detail.includes("player?.name, player?.team, player?.position"), 'History must reload whenever a fallback identity field changes.');
assert.ok(detail.includes("type DetailTab = 'overview' | 'gameLog' | 'stats'"), 'Player details must expose Overview, Game Log, and Stats destinations.');
assert.ok(detail.includes('2026 Projection'), 'The player header must prioritize useful season projection data.');
assert.ok(detail.includes('Game Log') && detail.includes('<table'), 'Game Log must render a real weekly comparison table.');
assert.ok(detail.includes('overflow-x-auto'), 'The Game Log table must remain usable on narrow mobile screens.');
assert.ok(detail.includes('max-h-[92dvh]') && detail.includes('overflow-y-auto'), 'The full player sheet must remain scrollable in short mobile viewports.');
assert.ok(detail.includes('env(safe-area-inset-bottom)'), 'The player sheet must always preserve the iPhone bottom safe area.');
assert.ok(detail.includes('role="tablist"') && detail.includes('role="tab"'), 'Player detail tab semantics must expose the selected tab accessibly.');
assert.ok(detail.includes("ranking.actual_points_2025 !== null"), 'Unavailable 2025 totals must remain unavailable instead of coercing null to zero.');
assert.ok(detail.includes("return 'Opponent unavailable'"), 'Missing legacy opponent metadata must not be mislabeled as a bye.');
assert.ok(!detail.includes('Stored final points'), 'Dead stored-history summary boxes must not dominate the player header.');
assert.ok(!detail.includes('Ball Knower will not invent missing stats'), 'Missing history must use a helpful product empty state instead of defensive copy.');
assert.ok(detail.includes('weekly game log is not available yet'), 'Missing weekly history must still be disclosed honestly.');
assert.ok(detail.includes('projection_source_url'), 'Shared ranking details must preserve source provenance.');
assert.ok(detail.includes("event.key === 'Escape'"), 'Player details must close from the keyboard.');
assert.ok(detail.includes("useState<2026 | 2025>"), 'Player detail must expose 2026 and 2025 season views.');
assert.ok(cloud.includes("from('ball_knower_player_week_scores')"), 'Weekly detail must use the existing score source of truth.');
assert.ok(postDraft.includes('<FantasyPlayerDetail'), 'Online fantasy must render the reusable player detail surface.');
assert.ok(postDraft.includes('onOpenPlayer={(playerId)'), 'Matchup players must open the shared player detail surface.');
assert.ok(postDraft.includes('onOpenPlayer={(player) => openPlayerDetail(player, selectedTeam)}'), 'Other managers’ roster players must open the same detail surface.');
assert.ok(postDraft.includes('onClick={() => openPlayerDetail(player)}'), 'Free agents and waiver players must be inspectable without selecting a claim.');
assert.ok(postDraft.includes('const player = findPlayer(playerId);'), 'Historical matchup players must resolve outside current rosters.');
assert.ok(hub.includes('watchAction={{ watched: watchlist.includes'), 'Cheat Sheet details must preserve the My Guys action.');
assert.ok(hub.includes('<FantasyPlayerDetail'), 'Cheat Sheet rankings must open the shared detail surface.');
assert.ok(communications.includes('<FantasyPlayerDetail'), 'Trading Block entries must open the shared detail surface.');
assert.ok(communications.includes('onOpen={setDetailPlayer}'), 'Trading Block player buttons must wire into shared details.');

console.log('Phase 2 player detail checks passed: decision-first modal, safe game log, anchored history, and shared entry points.');
