import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { ProfileLockerView } from '../ProfileLockerView';
import { profileDate, profileNumber, profileXpProgress, signedProfileDelta } from '../profileLockerState';
import type { Achievement, ProgressEvent, ProgressProfile } from '../progressionCloud';

const profile: ProgressProfile = { userId: 'fixture', displayName: 'Fixture GM', bkRating: 50, xp: 550, level: 1, footballIq: 50, gmRating: 51, predictionRating: 48, triviaRating: 49, agentRating: 52, ownerRating: 50, championships: 0, currentStreak: 0, longestStreak: 0, updatedAt: '2026-09-08T12:00:00Z' };
const achievements: Achievement[] = Array.from({ length: 7 }, (_, index) => ({ key: `fixture-${index}`, title: `Fixture trophy ${index}`, description: `Verified milestone ${index}`, category: 'gm', tier: index % 2 ? 'silver' : 'gold', xpReward: 100, ...(index === 1 ? { unlockedAt: '2026-09-08T12:00:00Z' } : {}) }));
const events: ProgressEvent[] = [{ id: 1, eventType: 'prediction_wrong', category: 'prediction', xpAwarded: 2, ratingDelta: -1, occurredAt: '2026-09-08T12:00:00Z', metadata: {} }];
const render = (overrides = {}) => renderToStaticMarkup(React.createElement(ProfileLockerView, { profile, achievements, events, loading: false, error: '', onRefresh: () => {}, ...overrides }));

assert.equal(profileXpProgress(0, 1)?.percent, 0);
assert.equal(profileXpProgress(550, 1)?.percent, 55.00000000000001);
assert.equal(profileXpProgress(1000, 2)?.earned, 0);
assert.equal(profileXpProgress(1450, 2)?.nextTotal, 2000);
assert.equal(profileXpProgress(999, 1)?.earned, 999);
assert.equal(profileXpProgress(1000, 1), null, 'Do not display fabricated progress for inconsistent server data');
for (const invalid of [-1, NaN, Infinity]) assert.equal(profileXpProgress(invalid, 1), null);
assert.equal(profileXpProgress(0, 0), null);
assert.equal(profileNumber(undefined), '—');
assert.equal(profileNumber(0), '0');
assert.equal(signedProfileDelta(-2), '-2');
assert.equal(signedProfileDelta(3), '+3');
assert.equal(profileDate('bad date'), '');

const html = render();
assert.equal((html.match(/class="bk-locker-hex"/g) || []).length, 6);
assert.equal((html.match(/class="bk-locker-trophy"/g) || []).length, 7, 'Do not truncate the trophy catalog to six items');
assert.match(html, /1\/7 unlocked/);
assert.match(html, /aria-valuenow="550"/);
assert.match(html, /Level 2 at 1,000 XP/);
assert.match(html, /-1 RTG/);
assert.doesNotMatch(html, /\+-1/);
assert.match(html, /Fixture trophy 6/);
assert.match(html, /Server controlled/);
const zero = render({ profile: { ...profile, xp: 0, championships: 0 }, events: [], achievements: [] });
assert.match(zero, /aria-valuenow="0"/);
assert.match(zero, /No verified progression receipts yet/);
const unavailable = render({ profile: null, events: [], achievements: [], error: 'Offline' });
assert.doesNotMatch(unavailable, /role="progressbar"|No verified progression receipts yet/);
assert.match(unavailable, /temporarily unavailable/);
assert.match(unavailable, /role="alert"/);
assert.match(render({ loading: true, profile: null, events: [], achievements: [] }), /Loading verified progression receipts/);
assert.doesNotMatch(html, /0\.1 DAILY|1,245|Connect platforms/i, 'Never copy invented mockup rewards or counts');
const source = (file: string) => readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');
assert.match(source('LockerHub.tsx'), /<ProfilePhotoEditor\s*\//);
assert.match(source('LockerHub.tsx'), /equipLockerItem/);
assert.match(source('LockerHub.tsx'), /ownedCollectibles/);
assert.match(source('ProgressionProfileCard.tsx'), /version !== requestVersion\.current/);
assert.match(source('ProgressionProfileCard.tsx'), /key=\{currentUser\?\.id/);
assert.match(source('profileLocker.css'), /prefers-reduced-motion:reduce/);
assert.match(source('profileLocker.css'), /scroll-snap-type:x proximity/);
console.log('Profile locker contracts passed: true XP thresholds, 6 ratings, full trophy catalog, signed receipts, loading/errors, unchanged photo entrypoint and account-scoped reads.');
